### ISSUE TITLE
No GUI

### ISSUE THREAD

**Issue by DeviousD4n** [evilsocket/opensnitch#1000]
Running Pop!_OS 22.04 LTS.

Installed the debs for the daemon and GUI. Also installed the Appindicator extension. Still nothing (not even in the tray) but ps shows both the daemon and UI running.

[dan@void:~] $ ps aux | grep snit
root        1050  5.8  0.2 2726444 68992 ?       SNsl 20:03   0:01 /usr/bin/opensnitchd -rules-path /etc/opensnitchd/rules
dan         2856 86.8  0.6 1937220 223244 ?      RNl  20:03   0:04 /usr/bin/python3 /usr/bin/opensnitch-ui

Then to add insult to injury after running apt remove the UI still tries to run after startup.

Nothing works not even the uninstall.

Willing to try it again if there are any suggestions, also why can it only be run from the systray?

Edit: found the extra remove: sudo apt remove python3-opensnitch-ui

**Comment by gustavo-iniguez-goya** [comment]
Hi @DeviousD4n ,

it looks like you're experiencing this bug: https://github.com/evilsocket/opensnitch/issues/647#issuecomment-1383956333

> dan 2856 **86.8** 0.6 1937220 223244 ? RNl 20:03 0:04 /usr/bin/python3 /usr/bin/opensnitch-ui

Could you verify if the solution of that issue fixes the problem?

**Comment by DeviousD4n** [comment]
That did it! Though i did have another issue at first when running opensnitch-ui:

dan@void:~] $ opensnitch-ui     
Traceback (most recent call last):
  File "/usr/bin/opensnitch-ui", line 23, in <module>
    from opensnitch.service import UIService
  File "/usr/lib/python3/dist-packages/opensnitch/service.py", line 13, in <module>
    from opensnitch import ui_pb2
  File "/usr/lib/python3/dist-packages/opensnitch/ui_pb2.py", line 32, in <module>
    _descriptor.EnumValueDescriptor(
  File "/usr/local/lib/python3.10/dist-packages/google/protobuf/descriptor.py", line 796, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

but a pip install protobuf==3.20 seems to have fixed it... though there seem to be other issues now... like no options being remembered once i click allow, which leads to me constantly having to allow


So..... about 5 minutes has passed now and i've had to close it, absolutely no rules are being followed or enforced. They seem to get added to the rules but upon restarting the app there were zero rules and the allow deny dialog shows up every second. So, while there is a window now (yay!) there are other issues. I can only assume they are related?

**Comment by gustavo-iniguez-goya** [comment]
It's really bad luck that you've had these 2 errors with python3-grpcio and protobuf at the same time during the first installation :( 

Probably you'll have 2 versions of protobuf, the one installed by apt and another one installed from pip.

Anyway, we fixed that problem by uninstalling protobuf from pip:  `~ $ pip3 uninstall protobuf` (worth checking also uninstalling it as root, just in case you installed it system-wide).

https://github.com/evilsocket/opensnitch/issues/741#issuecomment-1523369154
https://github.com/evilsocket/opensnitch/issues/860#issuecomment-1471565761
