### ISSUE TITLE
[BUG] Usage of netlists is bugged

### ISSUE THREAD

**Issue by TriMoon** [evilsocket/opensnitch#1020]
**Describe the bug**
It seems that when you use ipnet lists via a file that the wrong rule is applied. :thinking: 
Maybe the bug happens with all list files, but im not sure because i use a few, but this one catched my attention in particular.

Include the following information:
 - OpenSnitch version:
**v1.6.2 (deb from the releases page)**
```
$ inxi -zSG

System:
  Kernel: 6.2.0-27-generic arch: x86_64 bits: 64 Desktop: KDE Plasma v: 5.27.4
    Distro: Ubuntu 23.04 (Lunar Lobster)
Graphics:
  Device-1: NVIDIA GP102 [GeForce GTX 1080 Ti] driver: nvidia v: 535.86.05
  Display: x11 server: X.Org v: 1.21.1.7 with: Xwayland v: 22.1.8 driver: X:
    loaded: nvidia unloaded: fbdev,modesetting,nouveau,vesa
    gpu: nvidia,nvidia-nvswitch resolution: 2560x1080~60Hz
  API: OpenGL v: 4.6.0 NVIDIA 535.86.05 renderer: NVIDIA GeForce GTX 1080
    Ti/PCIe/SSE2
```

**To Reproduce**
Use files in these `tar`'s as config:
- [rules.tar.gz](https://github.com/evilsocket/opensnitch/files/12361854/rules.tar.gz)
- [lists.tar.gz](https://github.com/evilsocket/opensnitch/files/12361856/lists.tar.gz)

1. Disable the `opensnitchd` firewall.
1. Install [WGC](https://lutris.net/games/wargaming-game-center/) using Lutris.
1. Login to your account in the WGC. (Or create a fresh new one)
1. Install WoT-Blitz using the WGC.
1. Test that you can successfully run WoT-Blitz.
1. Use the config files attached above as rules and lists.
Note that you need to change the paths used inside the `1003-01` / `1003-02` / `1003-03` rules to point to the correct dirs you placed them in because they will most likely be different for you :wink:
1. Enable the `opensnitchd` firewall with the new configs, and don't forget to set `DEBUG` as log level...
1. Monitor the logs. _(I prefer real-time using `tail` and a log in `/tmp`)_
1. Start WoT-Blitz again and try to play.

**Post error logs:** 
- The netlist is matched in a different rule, but the action is performed from a different rule...
```
[2023-08-16 18:32:48]  DBG  [eBPF exit event] -> 76684
[2023-08-16 18:32:49]  DBG  new connection udp => 45295:192.168.0.254 -> 80.240.112.35 ():32860 uid: 1000, mark: 0
[2023-08-16 18:32:49]  DBG  [ebpf conn] not in cache, but in execEvents: udp45295192.168.0.25480.240.112.3532860, 79276 -> /home/mainuser/.local/share/lutris/runners/wine/lutris-GE-Proton8-13-x86_64/bin/wine-preloader
[2023-08-16 18:32:49]  DBG  [ebpf conn] adding item to cache: udp45295192.168.0.25480.240.112.3532860
[2023-08-16 18:32:49]  DBG  Net list match: 80.240.112.35, 80.240.112.0/24
[2023-08-16 18:32:49]  DBG  ✘ /home/mainuser/.local/share/lutris/runners/wine/lutris-GE-Proton8-13-x86_64/bin/wine-preloader -> 45295:192.168.0.254 => 80.240.112.35:32860, mark: 0 (1003-99-Lutris-Lockdown)
[2023-08-16 18:32:50]  DBG  [eBPF exit event] -> 47217
```

**Expected behavior (optional)**
Correct rule being applied ofcourse.

**Screenshots**
<s>If applicable, add screenshots or videos to help explain your problem. It may help to understand the issue much better.</s>

**Additional context**
<s>Add any other context about the problem here.</s>

**Comment by gustavo-iniguez-goya** [comment]
Hi @TriMoon ,

The expected action in this case would be to allow the connection to the network 80.240.112.0/24?

I see that the ipnet list is defined in the rule 1003-02*, but that rule has the action Allow, but `[ ] Priority rule` is not checked ("precedence": false). Therefore the daemon will continue evaluating rules until a deny/reject is found, or until there're no more rules to evaluate.

Could check `[x] Priority rule` ("precedence": true) and see if it works as expected?

**Comment by TriMoon** [comment]
> I see that the ipnet list is defined in the rule 1003-02*, but that rule has the action Allow, but `[ ] Priority rule` is not checked ("precedence": false).

Rule `1003-99` doesn't have priority set either, which means it should be processed after it in "alphabetical order"..

> Could you check `[x] Priority rule` ("precedence": true) and see if it works as expected?

Will check first thing tomorrow :+1:

**Comment by TriMoon** [comment]
Seems it worked, but i don't understand WHY...it's illogical.

- I'll now try without priority in _ANY_ of the `1003` rules and see.
Nope didn't work, the lockdown rules is applied without any priority rules in `1003` :weary:

**Comment by gustavo-iniguez-goya** [comment]
1. The rules are evaluated in alphabetical order
2. When we find an Allow rule that matches the connection, we save it, and continue evaluating rules.
3. If we find a Deny/Reject rule, then we don't need to continue evaluating rules, so we stop evaluating rules.
4. At the end of all the rules, if there were no Deny/Reject rules:
   - If an Allow rule matched -> allow the connection.
   - If no rules matched -> Ask the user to allow/deny it.

If you mark `[x] Priority rule` for an Allow rule, then the connection is allowed at point 2.

**Comment by TriMoon** [comment]
And EXACTLY this part is what makes it all illogical:
> 2. When we find an Allow rule that matches the connection, we save it, **and continue evaluating rules.**

Why continue at all???
If the user creates any rules, an Allow in this case, it expects the parsing to act at that point and STOP...
An Allow does not mean "Pass" or "Ignore"...

So your logic should be changed into:
1. The rules are evaluated in alphabetical order
1. When we find any Allow/Deny/Reject rule that matches the connection, then we don't need to continue evaluating rules, so we stop evaluating rules.
We act accordingly to Allow/Deny/Reject the connection.
1. At the end of all the rules, if there were no matching Allow/Deny/Reject rules:
   1. If the GUI is connected, ask the user what to do.
   2. If the GUI is NOT connected, or the timeout is reached in the GUI, perform the configured Default action.

The `[x] Priority rule` concept should place the rule in a list that gets evaluated before the 
"normal" rules, but with same alphabetical ordering in that list.
