### ISSUE TITLE
Edit option does not work on newly cloned rule in opensnitch UI

### ISSUE THREAD

**Issue by brbar** [evilsocket/opensnitch#1027]
If you clone the rule and try to edit it - nothing will happen.
I'm using the recent version of opensnitch 1.6.3.

Steps to reproduce:
1. Clone an existing rule
2. Click edit on newly cloned rule. Edit rule window will not open.

**Comment by lainedfles** [comment]
@brbar You may need to provide more information about your environment, i.e. OS version, display environment, etc. Additionally, UI & daemon debug logging may shed some light on your problem; I'm unable to re-produce it per your description via master build of 1.6.3. Does this occur with a specific rule or any?

**Comment by gustavo-iniguez-goya** [comment]
hey @brbar ,

I think this issue has been partially fixed on v1.6.4. At least it opens the rules editor dialog.

The reason that could have caused this error might have been a typo, fixed here: 72756c85b86d198e0bb915dad7ca61b59694c5c1

But I realize, that the fields of the rules are not displayed in the dialog, if the type is "list". I'll investigate it.
