### ISSUE TITLE
Ethtool/wol blocked even with rule

### ISSUE THREAD

**Issue by Skincanvas** [evilsocket/opensnitch#1052]
wol only works when opensnitch is completely disabled. It is the only program I have discovered that does not get an interactive prompt when used.

 - OpenSnitch 1.6.3-1, installed through aur
 - Arch Linux
 - Linux 6.5.5.arch1-1
 - xfce4

**To Reproduce**
1. [have a suspended server with wol enabled](https://wiki.archlinux.org/title/Wake-on-LAN#Enable_WoL_on_the_network_adapter)
2. enable opensnitch
3. wol -i $ipaddress $macaddress
4. no interactive prompt from opensnitch to create a rule, wol just finishes without error
5. create manual rule pointing to 'whereis wol'
6. try wol again, wont work
7. disable opensnitch
8. try wol again, works
there is no mention of wol in 'tail /var/log/opensnitchd.log'

**What I Have Tried**
1. manual rule pointing to 'whereis wol'
2. using wol -p flag, trying an alternate port from wol's default of 40000 to 1034, for example
3. enabling all my rules in case wol was using something random
4. updating to opensnitch-git

**Comment by gustavo-iniguez-goya** [comment]
Hi @Skincanvas ,

I've finally tried to reproduce this issue. As far as I can tell, on Manjaro + kernel 5.19/6.1/6.5.5 opensnitch prompts you to allow/deny the outbound connection.


Could you set the LogLevel to DEBUG in Preferences->Nodes->LogLevel and reproduce it again?

You should see log entries like this one:
```bash
 DBG  [eBPF exec event] ppid: 0, pid: 2450, /usr/bin/wol -> [wol  -i 1.2.3.4 00:11:22:33:44:55]
```

also execute as root: `opensnitchd -check-requirements` to verify that all the requirements are met.

**Comment by luzpaz** [comment]
@Skincanvas ping

**Comment by gustavo-iniguez-goya** [comment]
@Skincanvas , closing for now. Please, if you reproduce it again, post the log file as suggested in my last comment.
