### ISSUE TITLE
Over 6GB of memory being used by UI

### ISSUE THREAD

**Issue by Calcolan-Was-Somehow-Taken** [evilsocket/opensnitch#1053]
**Describe the bug**
The UI for OpenSnitch is using up 6+GB of memory after having my computer running overnight

Include the following information:
 - OpenSnitch version: 1.6.3
 - OS: Ubuntu
 - Version: 22.04.3 LTS
 - Window Manager: GNOME
 - Kernel version: `Linux Gourmet-Gaming-Box 6.2.0-34-generic #34~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Sep 7 13:12:03 UTC 2 x86_64 x86_64 x86_64 GNU/Linux`

**To Reproduce**
I left my computer running overnight probably meaning around 36 hours and is now using up 6.3GB of memory. I'm not sure what else I have done differently.

**Screenshots**
If applicable, add screenshots or videos to help explain your problem. It may help to understand the issue much better.
![Screenshot from 2023-10-07 19-43-43](https://github.com/evilsocket/opensnitch/assets/120821337/068a6d02-a45e-4386-ad28-3048e99da30c)
![Screenshot from 2023-10-07 18-55-25](https://github.com/evilsocket/opensnitch/assets/120821337/62f28ec1-468b-4862-9de0-203f1efa608a)

**Comment by gustavo-iniguez-goya** [comment]
Hi @Calcolan-Was-Somehow-Taken ,

You need to save events to disk, under Preferences -> DB -> Database type [File]

see https://github.com/evilsocket/opensnitch/issues/1030#issuecomment-1729326176

This has been already reported here #1030, so I close this issue as duplicated.

Thank you for reporting this problem!
