### ISSUE TITLE
[Bug] Missing Rule Still Displayed In UI

### ISSUE THREAD

**Issue by hbednar** [evilsocket/opensnitch#1056]
**Describe the bug**
After doing a review of rules and deleting the ones that are no longer needed, i got the below error when trying to delete one.
As this is an old rule it may have been deleted and for some reason is still showing in the UI.

Include the following information:
 - OpenSnitch version: 1.6.2
 -  - OpenSnitch UI version: 1.6.3
 - OS: Debian
 - Version sid
 - Window Manager: i3wm
 - Kernel version: echo $(uname -a)

**To Reproduce**
I found this out by accident when trying to delete a rule but, it may also happen when editing a rule that's missing.

**Post error logs:** 
![2023-55](https://github.com/evilsocket/opensnitch/assets/71215137/ecd6fbb5-ee59-4373-805a-ab2124dfb4a1)

**Comment by gustavo-iniguez-goya** [comment]
Hi @hbednar ,

Thank you for reporting this problem. I've managed to reproduce an (old) issue that was preventing rules from being refreshed.
As the list of rules was not refreshed, when you clicked on an already deleted rule, the error you posted was usually displayed to the user.

With this fix this error should happen anymore. But if you apply the fix, or reproduce it again with the next release, please, reopen this issue.

Thank you!
