### ISSUE TITLE
Links to download the v1.6.3 files show the v1.6.2 files

### ISSUE THREAD

**Issue by pardub** [evilsocket/opensnitch#1058]
**Describe the bug**
The links to download the v1.6.3 seems to be similar as the v1.6.2

v1.6.3 shows https://github.com/evilsocket/opensnitch/releases/download/v1.6.2/opensnitch_1.6.2-1_amd64.deb
v1.6.2 shows https://github.com/evilsocket/opensnitch/releases/download/v1.6.2/opensnitch_1.6.2-1_amd64.deb

**Comment by pizzadude** [comment]
Because only the GUI was updated.

**Comment by pardub** [comment]
Got it.
Thank you!
