### ISSUE TITLE
unknown pid wants to connect...

### ISSUE THREAD

**Issue by saitam1** [evilsocket/opensnitch#106]
I had the gui popping up several times and telling that **unknown** pids want to connect:
```
Unknown
(pid=unknown) wants to connect to 224.0.0.251 on UDP port 5353 (mdns)
```
How can I find out what app this actually is?

Also the terminal returned similar messages:

`(WARNING) Could not find process for udp connection 192.168.178.65:48301 -> 239.255.255.250:1900`

**Comment by JayBk** [comment]
Seems like something is trying to do multicast DNS (mDNS).

https://stackoverflow.com/questions/12483717/what-is-the-multicast-doing-on-224-0-0-251
https://www.ietf.org/rfc/rfc6762.txt

Wikipedia -- The multicast Domain Name System (mDNS) resolves host names to IP addresses within small networks that do not include a local name server. It is a zero-configuration service, using essentially the same programming interfaces, packet formats and operating semantics as the unicast Domain Name System (DNS). Although Stuart Cheshire designed mDNS to be stand-alone capable, it can work in concert with unicast DNS servers.

As to how you can find out what is using it, sorry I don't really know. Maybe try searching for what uses mdns on the operating system you have? Good luck!

**Comment by Pulsar33** [comment]
I had the same popup about ten times in  ten minutes with unicast addresses. I think it could be a process created by firefox, like plugin container.
Hope this can help
