### ISSUE TITLE
Error applying configuration /etc/opensnitchd/opensnitch.o no such file or directory

### ISSUE THREAD

**Issue by sha-265** [evilsocket/opensnitch#1060]
**Describe the bug**
I'm trying to edit change OpenSnitch configuration via GUI (specifically trying to enable `Debug invalid connections`), and I get this error:
> Error applying configuration /etc/opensnitchd/opensnitch.o no such file or directory

The changes are not saved.

 - OpenSnitch version: 1.5.8
 - OS: Ubuntu
 - Version: 23.04
 - Window Manager: GNOME Shell
 - Kernel version: `Linux 6.2.0-35-generic #35-Ubuntu SMP PREEMPT_DYNAMIC Tue Oct 3 13:14:56 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

**To Reproduce**
1. Open OpenSnitch GUI
2. Open the preferences window 
3. Go to `Nodes` tab
4. Check `Debug invalid connections`
5. Click `Apply` button
6. Look at the bottom of the window for the error

**Post error logs:** 
Nothing in logs

**Screenshots**
![image](https://github.com/evilsocket/opensnitch/assets/4103710/1045cc40-dd6e-4c58-9e5f-1b167654a579)

**Comment by gustavo-iniguez-goya** [comment]
hi @sha-265 ,

This error was fixed on v1.5.9, but I think it never entered into Debian. So right now your options are: 1) install latest release v1.6.3 from github, or 2) install latest ebpf modules from the v1.5.2 release page.

You can download the modules from here: https://github.com/evilsocket/opensnitch/releases/download/v1.5.2/ebpf-modules-v1.5.x.tar.gz

Could you copy the file `x86_64/opensnitch.o` from the tgz to /etc/opensnitchd/ and let me know if it works?

The modules are the same than the ones packaged with the v1.5.2 .deb packages .

**Comment by sha-265** [comment]
> Could you copy the file `x86_64/opensnitch.o` from the tgz to /etc/opensnitchd/ and let me know if it works?

Yep, it did work. Thank you.

**Comment by gustavo-iniguez-goya** [comment]
Thank you @sha-265 ! We had some problems compiling the ebpf modules on the Debian's infra, that's why they're not present.

**Comment by xvjs** [comment]
ubuntu 20.04
it was a long story. 

```
error: expected '(' after 'asm'
llc: error: opensnitch.bc: error: Could not open input file: No such file or directory
llc: error: llc: opensnitch.bc: error: Invalid record
```

stupid version error. somehow it started like this: 

```
make HOSTCC=clang-12 CC=clang-12 LLC=llc-12 KERNEL_DIR=/usr/src/linux-headers-5.15.0-131-generic KERNEL_HEADERS=/usr/src/linux-hwe-5.15-headers-5.15.0-131 ARCH=x86

sudo cp *.o /etc/opensnitchd/
sudo systemctl restart opensnitchd
```
