### ISSUE TITLE
Manajro kernel 6.1.69-1 wont work

### ISSUE THREAD

**Issue by horvjoe9** [evilsocket/opensnitch#1077]
Manajro kernel 6.1.69-1 opensnitch wont work.

I have installed Opensnitch 1.6.4 from the repo. The non-git version. I have changed done:

Edit build file to point to your headers:

Change:

KDIR="/usr/src/linux"

To:

KDIR="/usr/lib/modules/$(uname -r)/build"

After the app installed, but the cloud is white and I am not able to turn on the firewall.
Thank you :)

**Comment by horvjoe9** [comment]
The icon on the tint2 is white and the firewall wont start. I am unable to start it. The status icon is a green triangle. And there is no version number.
Any idea? Or suggestion to solve this?

**Comment by gustavo-iniguez-goya** [comment]
Hey @horvjoe9 ,

Could you launch the daemon manually? : `opensnitchd -rules /etc/opensnitchd/rules/` it'll give us an idea on why it's not working.

Be sure that it's not already running before launching it: `pgrep opensnitchd`

Also execute and post the output of: `opensnitchd -check-requirements`

**Comment by gustavo-iniguez-goya** [comment]
oops, sorry, I meant: `# opensnitchd -rules-path /etc/opensnitchd/rules/` (as root)

**Comment by horvjoe9** [comment]
> oops, sorry, I meant: `# opensnitchd -rules-path /etc/opensnitchd/rules/` (as root)

joe@Lenovo ~ $ pgrep opensnitchd
joe@Lenovo ~ $ sudo opensnitchd -rules-path /etc/opensnitchd/rules/

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

For security reasons, the password you type will not be visible.

[sudo] password for joe: 
[2024-01-08 09:47:12]  IMP  Starting opensnitch-daemon v1.6.2
[2024-01-08 09:47:12]  INF  Loading rules from /etc/opensnitchd/rules ...
OK: libnetfiler_queue supports nfq_get_uid
OK: libnetfiler_queue supports nfq_get_uid
found /usr/lib/libc.so.6

**Comment by gustavo-iniguez-goya** [comment]
ok!! try enabling the service: `$ sudo systemctl enable opensnitchd` then restart and see if it works

**Comment by horvjoe9** [comment]
> ok!! try enabling the service: `$ sudo systemctl enable opensnitchd` then restart and see if it works

joe@Lenovo ~ $ sudo systemctl enable opensnitchd
[sudo] password for joe: 
Created symlink /etc/systemd/system/multi-user.target.wants/opensnitchd.service → /usr/lib/systemd/system/opensnitchd.service.

Still nothing. :(

**Comment by gustavo-iniguez-goya** [comment]
you're welcome @horvjoe9 !
