### ISSUE TITLE
[Bug] Logrotate Brakes GUI Loging

### ISSUE THREAD

**Issue by zero77** [evilsocket/opensnitch#1092]
**Describe the bug**
After i enable logrotate to rotate opensnitch logs it breaks the gui each time it runs.
I am left with a completely blank gui with no data under any of the tabs (Events, Nodes, RULES, HOSTS, etc)
But, after i restart the gui it works again and starts to show new logs but does not include old logs.

This is the logrotate config i am using: [config](https://github.com/evilsocket/opensnitch/blob/dddfdc924e18de471afbe74b4fe82b824db42473/utils/packaging/daemon/deb/debian/opensnitch.logrotate#L4)

Include the following information:
 - OpenSnitch version: 1.6.4
 - OS: Debian
 - Version: sid
 - Window Manager: i3wm
 - Kernel version: 6.6.13-amd64

**To Reproduce**

1. enable logrotate
2. whate for logs to be rotated
3. open gui and see missing data -  `I am not sure how quickly this happens as i only see the effects when i open the gui`

4 restart gui and it all works as normal again with out old logs

**Post error logs:** 
I am not sure how to provide the logs as restarting the gui is the workaround i am using and won't show any errors

**Expected behavior (optional)**

**Screenshots**

**Additional context**

**Comment by gustavo-iniguez-goya** [comment]
thank you @zero77 ! do you remember what GUI version did you have installed before upgrading to v1.6.4?

**Comment by gustavo-iniguez-goya** [comment]
Mmh, where's the db file located? is it maybe being deleted by some background cleanup process?

**Comment by gustavo-iniguez-goya** [comment]
thank you @zero77 , the log file should be a regular plain text file. It's configured in /etc/opensnitchd/default-config.json (https://github.com/evilsocket/opensnitch/blob/master/daemon/default-config.json) and by default it points to /var/log/opensnitchd.log

On the other hand, the .db path is configured by the GUI and saved under $HOME/.config/opensnitchd/settings.conf (the user's home who opened the GUI). The GUI must have write access to the DB, so if you save it under /etc/opensnitchd/ be sure that your user can write to the .db
