### ISSUE TITLE
[Feature Request] Add Zoom option to the UI Preferences

### ISSUE THREAD

**Issue by liwodg** [evilsocket/opensnitch#1102]
I have a hidpi monitor and experienced problems with correct icons size. I managed to do it with QT_SCREEN_SCALE_FACTORS option as suggested in wiki, but I think it would be more convenient to have this option in the GUI (along with QT_AUTO_SCREEN_SCALE_FACTOR).

It may also be helpful for other users to mention in the wiki (https://github.com/evilsocket/opensnitch/wiki/GUI-known-problems#gui-size-problems-on-4k-monitors) that it may be worth to try to install qt-material and change default theme (in my case on Linux Mint the icons were positioned incorrectly until I installed this lib and changed the "System" theme).

Thanks again for the program!

**Comment by gustavo-iniguez-goya** [comment]
added @liwodg ! this feature has been something that I've wanted to add for so long ... finally it's done.
