### ISSUE TITLE
Cannot Load Deamon - opensnitchd.service does not exist

### ISSUE THREAD

**Issue by jodinetheron** [evilsocket/opensnitch#1106]
**Describe the bug**
When I open program I just get a blank screen. It is not loading any data.

Include the following information:
 - OpenSnitch version: 1.6.5.1
 - OS: Nobara (Fedora)
 - Version: 39
 - Window Manager: using Wayland but also have  X11
 - Kernel version: Linux username 6.7.6-201.fsync.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC TKG Wed Feb 28 02:20:59 UTC 2024 x86_64 GNU/Linux

**To Reproduce**
Just installed OpenSnitch via .noarch.rpm on Nobara (Fedora) via terminal.

As per your FAQ, 
I ran `pgrep opensnitchd` 

then ran `sudo systemctl enable opensnitchd` and get the following error:
Failed to enable unit: Unit file opensnitchd.service does not exist.

I also ran `opensnitchd -check-requirements` and get the following error:
bash: opensnitchd: command not found...

![Screenshot from 2024-03-15 10-01-02](https://github.com/evilsocket/opensnitch/assets/147303564/96025b31-8e17-4bc1-9578-c4fade26cd99)

**Comment by marbew** [comment]
I have exactly the same issue on my Ubunut 5.15.0-100-generic #110~20.04.1-Ubuntu SMP Tue Feb 13 14:25:03 UTC 2024 x86_64 after installing "sudo dpkg -i python3-opensnitch-ui_1.6.5.1-1_all.deb" there is no service to enable.
Also opensnitch does not show any status. Like only the UI is running but nothing else.

**Comment by cipitaua** [comment]
confirmed debian sid

**Comment by cipitaua** [comment]
I did not realize that the daemon and ui are in separate packages! sorry.

**Comment by marbew** [comment]
Excuse me, could you help me to understand better how to install opensnitch on Ubuntu, I am sure you can provide at this point a better howto install that the official one. Thank you

**Comment by marbew** [comment]
I finally understood, and installed it. Thank you so much. I can close my call about daemon.
Reading properly the main page you have to download 2 .deb file and install it all together. 
Apologies again. Happy opensnitch to everybody
