### ISSUE TITLE
Fedora Silverblue -- opensnitchd -check-requirements --> ERR  /proc/config.gz not found

### ISSUE THREAD

**Issue by frigeky00** [evilsocket/opensnitch#1117]
**Describe the bug**
Daemon doesn't start and `opensnitchd -check-requirements` produces an error.

Include the following information:
 - 1.6.5.1 for the gui and 1.6.5 for the daemon.
 - OS: Fedora Silverblue
 - Version 40
 - Window Manager: GNOME
 - Kernel version: Linux fedora 6.8.4-300.fc40.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Apr 4 20:41:39 UTC 2024 x86_64 GNU/Linux

**To Reproduce**

I installed both the daemon and the GUI on Silverblue. However, the daemon does not seem to start.
When I try `sudo systemctl enable opensnitchd`, I get `Failed to enable unit: Unit file opensnitchd.service does not exist.`
But when I try `opensnitchd -check-requirements`, I get:

> Checking system requirements for kernel version 6.8.4-300.fc40.x86_64
> ------------------------------------------------------------------------------
> 
> [2024-04-09 12:19:02]  ERR  /proc/config.gz not found

**Additional context**
Running Fedora Silverblue -- but it seems that others do too and it works.

**Comment by gustavo-iniguez-goya** [comment]
Hi @frigeky00 !

Thank you for reporting this problem. Could you verify if this file exists /usr/lib/modules/6.8.4-300.fc40.x86_64/config?
It seems that on Silverblue it's placed there. I don't know if it'll also apply for others distros.

**Comment by gustavo-iniguez-goya** [comment]
added support for kernel config paths located under /usr/lib/modules/$KERNEL/
