### ISSUE TITLE
opensnitch.io does not host project site any more

### ISSUE THREAD

**Issue by kam193** [evilsocket/opensnitch#1128]
The domain `opensnitch.io`, mentioned in some test code (although I don't think really called) as well as on the @evilsocket's website https://www.evilsocket.net/ doesn't look to be controlled by the project any more and presents a website with several suspicious links / ads.

I'd suggest removing any references to the domain.

**Comment by evilsocket** [comment]
where exactly are these references to remove other than an old post on my personal blog?

**Comment by kam193** [comment]
I've seen it on your blog in the "Projects" section on the main page and in a few test/example data in the repository. All you can find here: https://github.com/search?q=org%3Aevilsocket+opensnitch.io&type=code

**Comment by evilsocket** [comment]
i'd say this is the wrong repo then.
