### ISSUE TITLE
Upgraded from Ubuntu 20 to 22.04.4, Opensnitch UI not opening

### ISSUE THREAD

**Issue by deadbroker** [evilsocket/opensnitch#1129]
Hi there

I migrated from Ubuntu 20 to Ubuntu 22.04.4 LTS and Opensnitch doesn't work (version 1.6.5).

I tried opening it from the application launcher in Ubuntu but nothing happens when I click the icon.

I ran `$ opensnitch-ui` and got the following error:

`Traceback (most recent call last):
  File "/usr/bin/opensnitch-ui", line 41, in <module>
    from opensnitch.service import UIService
  File "/usr/lib/python3/dist-packages/opensnitch/service.py", line 15, in <module>
    from opensnitch import ui_pb2
  File "/usr/lib/python3/dist-packages/opensnitch/ui_pb2.py", line 32, in <module>
    _descriptor.EnumValueDescriptor(
  File "/usr/local/lib/python3.10/dist-packages/google/protobuf/descriptor.py", line 914, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates`

Any clue what's happening here?

**Comment by deadbroker** [comment]
I have solved it with the following command:

`$ pip install protobuf==3.20.*`

I had to downgrade protobuf

https://stackoverflow.com/questions/72899948/how-to-downgrade-protobuf

**Comment by gustavo-iniguez-goya** [comment]
Hi @deadbroker ,

great you were able to fix it, thank you for letting us know!

I've updated the wiki with this info.

**Comment by gustavo-iniguez-goya** [comment]
Hi @deadbroker ,

great you were able to fix it, thank you for letting us know!

I've updated the wiki with this info.

https://github.com/evilsocket/opensnitch/wiki/GUI-known-problems
