### ISSUE TITLE
Uninitialized firewall and logger causing SIGSEGV on master branch (c3bbb92)

### ISSUE THREAD

**Issue by 1fishe2fishe** [evilsocket/opensnitch#1131]
**Describe the bug**
I was getting SIGSEGV while running opensnitchd built from the master branch. I've submitted a PR (#1130) to fix it and described the issue in detail, so this serves as a placeholder issue for the PR. Please close this after the PR is merged.

**Comment by UffeJakobsen** [comment]
I see the same issue

**Comment by gustavo-iniguez-goya** [comment]
working on it, will be fixed asap.

**Comment by 1fishe2fishe** [comment]
https://github.com/evilsocket/opensnitch/issues/1130#issuecomment-2109638326 fixes the issue more efficiently than my PR, I guess the issue can be considered resolved when it's pushed.
