### ISSUE TITLE
GUI Not opening on Fedora 40

### ISSUE THREAD

**Issue by FusionStreak** [evilsocket/opensnitch#1137]
## Open Snitch GUI

- Version: 1.6.5-1
- Installed from: `opensnitch-ui-1.6.5-1.noarch.rpm`

## System Info

- OS: Fedora Linux 40 (Workstation Edition) x86_64
- Kernel: 6.8.10-300.fc40.x86_64
- DE: KDE Plasma 6.0.5
- WM: KWin (Wayland)
- Python: 3.12.3

## Steps to Re-create

- Launching through GUI icon does not launch the program, nor show an icon in the system tray
- Launching through console
```sh
$ opensnitch-ui 
Traceback (most recent call last):
  File "/usr/bin/opensnitch-ui", line 41, in <module>
    from opensnitch.service import UIService
  File "/usr/lib/python3/dist-packages/opensnitch/service.py", line 15, in <module>
    from opensnitch import ui_pb2
  File "/usr/lib/python3/dist-packages/opensnitch/ui_pb2.py", line 32, in <module>
    _descriptor.EnumValueDescriptor(
  File "/home/<USER>/.local/lib/python3.12/site-packages/google/protobuf/descriptor.py", line 917, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```

**Comment by gustavo-iniguez-goya** [comment]
hi @FusionStreak ,

This is a known issue. There're a couple of workarounds, the one that seems to work fine is: https://github.com/evilsocket/opensnitch/issues/1129#issuecomment-2105823389 ,  https://stackoverflow.com/a/73383927(for example: `~ $ pip install protobuf==3.20.6`)

Let me know if it fixes the error.
