### ISSUE TITLE
[Feature Request] Have the ability to choose and kill live connection.

### ISSUE THREAD

**Issue by mmaatuq** [evilsocket/opensnitch#1143]
### Summary: In some cases I don't want to add a rule but i want to choose one of the live connections from the events tab and be able to terminate it -

**Comment by gustavo-iniguez-goya** [comment]
hi @mmaatuq ,

This will be possible once we implement this other feature: #1112

**Comment by mmaatuq** [comment]
> hi @mmaatuq ,
> 
> This will be possible once we implement this other feature: #1112
i'll close this ticket then.
thanks.
