### ISSUE TITLE
opensnitch runs on startup even when service is disabled

### ISSUE THREAD

**Issue by lufinkey** [evilsocket/opensnitch#1150]
I installed opensnitch and rebooted my system. After noticing it ran on startup, I closed it, checked `~/.config/autostart` for a file (there was none), and disabled the service by running `systemctl disable opensnitch`, then rebooted my machine again. On startup, the application was still showing up in my tray on startup. Checking the status of the service, it says it's disabled.

I'm on Debian 12

**Comment by gustavo-iniguez-goya** [comment]
Hi @lufinkey ,

There should be a symbolic link pointing to /usr/share/applications/opensnitch_ui.desktop under `/etc/xdg/autostart/` .
Remove it and it should not be launched on startup.

We need to review/rethink the Autostart GUI option, but for now it's like this. I'll try to improve this behaviour.
