### ISSUE TITLE
Generates large number of error logs: `Error parsing rule Created date (it should be in RFC3339 format)`

### ISSUE THREAD

**Issue by thenbe** [evilsocket/opensnitch#1153]
**Describe the bug**
v1.6.6 of opensnitch spams the journal. Here is the output of `journalctl --follow --lines=1000 --all -u opensnitchd.service`

https://github.com/evilsocket/opensnitch/assets/33713262/d1afff1e-85a5-4942-88bf-d6aa527357aa

The issue only started happening after upgrading from v1.6.5.1 to v1.6.6. 

Include the following information:
 - OpenSnitch version: v1.6.6
 - OS: [e.g. Debian GNU/Linux, ArchLinux, Slackware, ...]:
   - system: `"x86_64-linux"`
   - host os: `Linux 6.6.37, NixOS, 24.11 (Vicuna), 24.11.20240709.feb2849`
 - Kernel version: echo $(uname -a): `Linux 6.6.37 #1-NixOS SMP PREEMPT_DYNAMIC Fri Jul  5 07:34:07 UTC 2024 x86_64 GNU/Linux`

**To Reproduce**

1. Run `journalctl --follow --lines=1000 --all -u opensnitchd.service`
2. Observe the large number of logs.

**Comment by thenbe** [comment]
systemd service package definition: https://github.com/NixOS/nixpkgs/blob/870dee25191906192cba64a031da23dd035568fd/nixos/modules/services/security/opensnitch.nix#L168-L204

opensnitch package definition: https://github.com/NixOS/nixpkgs/blob/870dee25191906192cba64a031da23dd035568fd/pkgs/by-name/op/opensnitch/package.nix

**Comment by gustavo-iniguez-goya** [comment]
Hi @thenbe ,

Sorry for the late reply. That warning means that the rule has an invalid date. The Created field should be something like: `"created": "2023-02-11T23:48:49.990680711+01:00",`

If you select from the GUI the rules, and make a change (right click -> Disable/Enable, or Apply to -> ...), it'll add the correct date to the rules.

**Comment by thenbe** [comment]
Not 100% sure, but I this may have been caused because some custom rules I had written by hand did not have a `created` and `updated` fields. This may have also been exacerbated by the fact that those rules lived in a read-only directory (`/nix/store`).

Regardless, the issue is resolved once I added the `created` and `updated` fields to my hand-written json rules.
