### ISSUE TITLE
SyntaxWarning: invalid escape sequence '\.'

### ISSUE THREAD

**Issue by antonsoroko** [evilsocket/opensnitch#1154]
**Describe the bug**

Not a "real" bug, but I noticed SyntaxWarning during upgrade to 1.6.6 on ubuntu 24.04 with python 3.12.
iirc python 3.12 does not like when raw strings are used as normal strings (i guess you wanted to use raw string r'\.', but i might be wrong.)

Include the following information:
 - OpenSnitch version: 1.6.6
 - OS: Ubuntu
 - Version: 24.04
 - Window Manager: KDE5
 - Kernel version: 6.8.0-36-generic

**To Reproduce**
`sudo apt install ./opensnitch_1.6.6-1_amd64.deb ./python3-opensnitch-ui_1.6.6-1_all.deb`

**Post error logs:** 
```
/usr/lib/python3/dist-packages/opensnitch/dialogs/prompt.py:608: SyntaxWarning: invalid escape sequence '\.'
  appimage_path = os.path.dirname(con.process_path).replace(".", "\.")
```

**Expected behavior (optional)**

**Screenshots**

**Additional context**

**Comment by akhepcat** [comment]
Apparently in newer pythons, the regular expressions should be written as  raw strings:  r"..."    or have the backslashes quoted in the string

raw strings should be backward compatible.

(this is according to bug reports to hplip for the same thing)

**Comment by gustavo-iniguez-goya** [comment]
fixed in https://github.com/evilsocket/opensnitch/commit/9e660e1d4813612d412bec6c631ebce7dbfed149

thank you!
