### ISSUE TITLE
[Feature Request] Reject by default instead of Drop

### ISSUE THREAD

**Issue by vbooka1** [evilsocket/opensnitch#1159]
Hello, please consider adding a configudation option to Reject connections by default instead of Drop-ping them.
Reason: many programs hang or behave in other strange ways when their call-home connections are dropped, and work well if the connections are rejected.

**Comment by gustavo-iniguez-goya** [comment]
Hi @vbooka1 ,

That option was added on v1.6.6. You can change the DefaultAction from the Preferences dialog, Nodes and Popups tabs:

Nodes tab, default action when the GUI is closed:

![Captura de pantalla de 2024-08-03 18-04-36](https://github.com/user-attachments/assets/d547128f-051d-40af-9d88-5047e6274494)

Pop-ups tab, default option preselected:
![Captura de pantalla de 2024-08-03 18-04-22](https://github.com/user-attachments/assets/e94c8086-fa14-4f7c-9fff-1de7165912b3)
