### ISSUE TITLE
Setting List of domains/IPs doesn't work with remote GUI

### ISSUE THREAD

**Issue by ciandonovan** [evilsocket/opensnitch#1174]
When `opensnitch-ui` is connected to `opensnitchd` on another host or in another mount namespace, setting `List of domains/IPs` doesn't work with the file/directory picker.

This is because it is setting a path local to the `opensnitch-ui` instance, which obviously doesn't exist on the `opensnitchd` remote host.

Even if the absolute path is set in `opensnitch-ui` for a path that does exist on the `opensnitchd` host, the `opensnitch-ui` checks if that path exists on its own host, and rejects the setting since it doesn't exist. This should be easy to fix by removing the check if the node isn't local, the interactive picker should probably be disabled in this case.

**Comment by gustavo-iniguez-goya** [comment]
hmm, I'll review this issue. Thank you @ciandonovan for reporting it.
