### ISSUE TITLE
opensnitch-ui default options not being saved

### ISSUE THREAD

**Issue by odomingao** [evilsocket/opensnitch#1176]
**Describe the bug**
I tried to change the default duration of the action to "once" rather than "until reboot", however the setting does not save

Include the following information:
 - OpenSnitch version: 1.6.5.1-1
 - OS: Arch
 - Version: rolling
 - Window Manager: Hyprland
 - Kernel version: 6.10.4 (custom build, w/linux-hardened patches)

**To Reproduce**
Describe in detail as much as you can what happened.

1. Change the default option from "until reboot" to "once"
2. Save/apply
3. Close opensnitch-ui
4. Open opensnitch-ui
5. Verify that the change was not saved

**Expected behavior (optional)**
The settings to be saved and retained after the application is closed

**Comment by gustavo-iniguez-goya** [comment]
hi @odomingao ,

Where did you change this option? on the Preferences->Nodes tab, or from a popup?

**Comment by odomingao** [comment]
From the preferences menu, yes.

**Comment by gustavo-iniguez-goya** [comment]
Ok, thank you.

That daemon option is not used right now. I removed the hability to configure it from the GUI on v1.7.0 (master branch). The one that can be configured from Preferences -> Nodes tab, the option from Preferences -> Pop-ups tab is valid.

The DefaultAction configured is used when there's no GUI connected, or when the user takes no action on a pop-up, or when we're already asking the user to take an action.

But the DefaultDuration is not used.
