### ISSUE TITLE
what could this be?

### ISSUE THREAD

**Issue by slynobody** [evilsocket/opensnitch#1177]
**Describe the bug**

Snitch is working while jouralctl throws out this: (btw: after plasma6.1 update, the icons are rather huge now, maybe a migration to qt6 is planned?)

: ERROR:dbus.connection:Exception in handler for D-Bus signal:
Aug 20 10:49:59 opensnitch-ui[7539]: Traceback (most recent call last):
Aug 20 10:49:59 lopensnitch-ui[7539]:   File "/usr/lib/python3/dist-packages/dbus/connection.py", line 218, in maybe_handle_message
Aug 20 10:49:59 opensnitch-ui[7539]:     self._handler(*args, **kwargs)
Aug 20 10:49:59 opensnitch-ui[7539]:   File "/usr/lib/python3/dist-packages/notify2.py", line 154, in _closed_callback
Aug 20 10:49:59 opensnitch-ui[7539]:     n = notifications_registry[nid]
Aug 20 10:49:59 opensnitch-ui[7539]:         ~~~~~~~~~~~~~~~~~~~~~~^^^^^
Aug 20 10:49:59 opensnitch-ui[7539]: KeyError: 2
Aug 20 10:49:59 opensnitch-ui[7539]: ERROR:dbus.connection:Exception in handler for D-Bus signal:
Aug 20 10:49:59 opensnitch-ui[7539]: Traceback (most recent call last):
Aug 20 10:49:59  opensnitch-ui[7539]:   File "/usr/lib/python3/dist-packages/dbus/connection.py", line 218, in maybe_handle_message
Aug 20 10:49:59  opensnitch-ui[7539]:     self._handler(*args, **kwargs)
Aug 20 10:49:59 opensnitch-ui[7539]:   File "/usr/lib/python3/dist-packages/notify2.py", line 154, in _closed_callback
Aug 20 10:49:59 opensnitch-ui[7539]:     n = notifications_registry[nid]
Aug 20 10:49:59  opensnitch-ui[7539]:         ~~~~~~~~~~~~~~~~~~~~~~^^^^^
Aug 20 10:49:59 opensnitch-ui[7539]: KeyError: 2

Include the following information:
 - OpenSnitch 1.6.6
 - OS: Debian
 - Version: Sid
 - Window Manager: plasma  6.1
 - Kernel version: 6.10.6
 - python:  3.12

**Comment by gustavo-iniguez-goya** [comment]
Hi @slynobody !

This is an error caused by python3-notify2, it's not handling the exception, see: https://github.com/evilsocket/opensnitch/issues/906#issuecomment-1510262834
