### ISSUE TITLE
debian: do *not* install python3-grpcio 1.59.5-1

### ISSUE THREAD

**Issue by slynobody** [evilsocket/opensnitch#1178]
**Describe the bug**
Just a short heads-up for debian-users: do *not* install python3-grpcio 1.59.5-1, stay on 1.51.1-4.1+b6.

if you update to python3-grpcio 1.59.5-1, you will encounter the following error:

  File "/usr/bin/opensnitch-ui", line 35, in <module>
    import grpc
  File "/usr/lib/python3/dist-packages/grpc/__init__.py", line 22, in <module>
    from grpc import _compression
  File "/usr/lib/python3/dist-packages/grpc/_compression.py", line 20, in <module>
    from grpc._cython import cygrpc
ImportError: /usr/lib/python3/dist-packages/grpc/_cython/cygrpc.cpython-312-x86_64-linux-gnu.so: undefined symbol: _ZTVN4absl7debian514flags_internal8FlagImplE

    OpenSnitch 1.6.6
    OS: Debian
    Version: Sid
    Window Manager: plasma 6.1
    Kernel version: 6.10.6
    python: 3.12

**Comment by gustavo-iniguez-goya** [comment]
hey @slynobody , thank you for the heads-up!

I guess you installed that version via pip, because latest on the repos on Sid is 1.51.1-4.1+b6 as you pointed out.

Is this issue still relevant?

**Comment by slynobody** [comment]
this is / was on experimental. but i simply dont upgrade.
