### ISSUE TITLE
eBPF modules makefile fails if ccache package is installed

### ISSUE THREAD

**Issue by pizzadude** [evilsocket/opensnitch#1206]
Hi, I was building opensnitch from latest sources and I noticed that building the EBPF modules is broken. I use Fedora 40.

The current makefile in the ebpf_prog folder fails with:

```
llc -march=bpf -mcpu=generic -filetype=obj -o opensnitch.o opensnitch.bc
llc: llc: error: llc: opensnitch-procs.bcllc: : error: Could not open input file: No such file or directory
error: llc: opensnitch-dns.bc: error: Could not open input file: No such file or directory
error: llc: opensnitch.bc: error: Could not open input file: No such file or directory
make: *** [Makefile:61: opensnitch-procs.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [Makefile:61: opensnitch-dns.o] Error 1
make: *** [Makefile:61: opensnitch.o] Error 1

```

The resulting opensnitch*.o modules are corrupt.

Downgrading the makefile to the version here fixes the issue:
https://github.com/evilsocket/opensnitch/blob/51779e8b8d30ee45785891ca5b0ad455ea45f685/ebpf_prog/Makefile

**Comment by gustavo-iniguez-goya** [comment]
Hey @pizzadude ,

I've just compiled the modules on Fedora 40 with latest Makefile, and compiled fine.
I've just executed 'make' .. so no idea why it failed for you.

I've had to install make, bison, clang, kernel-devel and llvm.

**Comment by pizzadude** [comment]
@gustavo-iniguez-goya 

I removed "ccache" and now it compiles fine.

**Comment by gustavo-iniguez-goya** [comment]
installed ccache , recompiled and it worked O:)

I have no idea how ccache works, maybe you need to clean the cached files.

**Comment by gustavo-iniguez-goya** [comment]
closing as I think this issue is not related with our modules. But anyway, if you were using ccache to compile the modules reopen it/drop a comment so we can investigate the problem.
