### ISSUE TITLE
Service not working after log out and log in

### ISSUE THREAD

**Issue by YukiXXL** [evilsocket/opensnitch#1217]
**Describe the bug**
After logging out and logging back in, the service is running in the background but GUI is not. When opening any app that needs network, the request box is never shown and the app is automaticaly given permission to access the network like the service is disabled. Trying to start the GUI process with 'opensnitch-ui' sas "GUI already running, opening its window and exiting." but nothing happens. Only by killing the process and starting it again works.

Info:
 - OpenSnitch version: 1.6.6.
 - OS: Linux Mint
 - Version: 22 Cinnamon
 - Window Manager: Cinnamon
 - Kernel version: 6.8.0-47-generic

**To Reproduce**
Log out and log back in.

**Post error logs:** 
[2m[2024-11-04 17:32:27][0m [97m[43m WAR [0m Error while pinging UI service: rpc error: code = DeadlineExceeded desc = context deadline exceeded, state: READY
[2m[2024-11-04 17:32:29][0m [97m[43m WAR [0m Error while pinging UI service: rpc error: code = DeadlineExceeded desc = context deadline exceeded, state: READY
[2m[2024-11-04 17:32:31][0m [97m[43m WAR [0m Error while pinging UI service: rpc error: code = DeadlineExceeded desc = context deadline exceeded, state: READY
[2m[2024-11-04 17:32:33][0m [97m[43m WAR [0m Error while pinging UI service: rpc error: code = DeadlineExceeded desc = context deadline exceeded, state: READY
[2m[2024-11-04 17:32:35][0m [97m[43m WAR [0m Error while pinging UI service: rpc error: code = DeadlineExceeded desc = context deadline exceeded, state: READY
[2m[2024-11-04 17:32:37][0m [97m[43m WAR [0m Error while pinging UI service: rpc error: code = DeadlineExceeded desc = context deadline exceeded, state: READY
[2m[2024-11-04 17:32:39][0m [97m[43m WAR [0m Error while pinging UI service: rpc error: code = DeadlineExceeded desc = context deadline exceeded, state: READY
[2m[2024-11-04 17:32:41][0m [97m[43m WAR [0m Error while pinging UI service: rpc error: code = DeadlineExceeded desc = context deadline exceeded, state: READY
[2m[2024-11-04 17:32:43][0m [97m[43m WAR [0m Error while pinging UI service: rpc error: code = DeadlineExceeded desc = context deadline exceeded, state: READY
[2m[2024-11-04 17:32:45][0m [97m[43m WAR [0m Error while pinging UI service: rpc error: code = DeadlineExceeded desc = context deadline exceeded, state: READY
[2m[2024-11-04 17:32:47][0m [97m[43m WAR [0m Error while pinging UI service: rpc error: code = DeadlineExceeded desc = context deadline exceeded, state: READY
[2m[2024-11-04 17:32:48][0m [97m[41m ERR [0m getting notifications: rpc error: code = Unavailable desc = keepalive watchdog timeout <nil>
[2m[2024-11-04 17:32:48][0m [97m[43m WAR [0m Error while asking for rule: rpc error: code = Unavailable desc = transport is closing - /usr/bin/xbrlapi (8299) -> 127.0.0.1:4101 (proto:tcp uid:1001)
[2m[2024-11-04 17:32:48][0m [97m[41m ERR [0m Invalid rule received, applying default action
[2m[2024-11-04 17:32:48][0m [97m[41m ERR [0m Connection to the UI service lost.

**(`# /usr/bin/opensnitchd -rules-path /etc/opensnitchd/rules`)**
ERROR: nfq_create_queue() queue not created

**Additional context**
`opensnitchd -check-requirements` returns all passed.

**Comment by gustavo-iniguez-goya** [comment]
Hi @YukiXXL ,

Issue reproduced. When exiting the Cinnamon session our GUI is closed, but when entering again the GUI is launched, but for some reason the icon is not added to the systray.

I'll investigate what is causing this behaviour.

**Comment by gustavo-iniguez-goya** [comment]
@YukiXXL , could you add this line at the bottom of `/usr/bin/opensnitch-ui` and let me know if the issue is fixed?


    except KeyboardInterrupt:
        on_exit()
    except Exception as e:
        print(e)

    # this line   
    on_exit()

**Comment by YukiXXL** [comment]
> @YukiXXL , could you add this line at the bottom of `/usr/bin/opensnitch-ui` and let me know if the issue is fixed?
> 
> ```
> except KeyboardInterrupt:
>     on_exit()
> except Exception as e:
>     print(e)
> 
> # this line   
> on_exit()
> ```

Sorry for very late reply. I tested it and it worked. Thank you.
