### ISSUE TITLE
Opensnitch starts maximized in Hyprland / Wiki needs Hyprland startup instructions

### ISSUE THREAD

**Issue by guttermonk** [evilsocket/opensnitch#1218]
Opensnitch starts maximized in Hyprland on startup even with the `--background` flag set. My Hyprland config file has the following:
```
exec-once = [
  "QT_STYLE_OVERRIDE=kvantum opensnitch-ui --background"
];
```
If I kill opensnitch and reopen it in the CLI using the above command, it starts minimized (as expected) with the following output in terminal:
```
	 ~ OpenSnitch GUI - 1.6.5.1 ~
	protobuf: 4.24.4 - grpc: 1.62.2
--------------------------------------------------

gRPC Max Message Length: 8MiB
                  Bytes: 8388608
is new file, or IN MEMORY, setting initial schema version
setting schema version to: 3
setting schema version to: 3
Setting journal_mode:  OFF
Setting DB memory optimizations
schema version: 3
db schema is up to date
Loading translations: /nix/store/xbqhchpqcr7lvhc6z0a0jpfhzkshwq3d-opensnitch-ui-1.6.5.1/lib/python3.11/site-packages/opensnitch/utils/../i18n locale: en_US
using IPASN DB: /nix/store/znpyq3gj64pn9hsjq57p2ksbm31cmypb-python3.11-pyasn-1.6.2/lib/python3.11/site-packages/pyasn/data/ipasn_20140513_v12.dat.gz
Using server address: unix:///tmp/osui.sock auth type: simple
```

Include the following information:
 - OpenSnitch version: 1.6.5.1
 - OS: NixOS
 - Version: 24.05
 - Window Manager: hyprland
 - Kernel version: Linux hyprnix 6.6.59 #1-NixOS SMP PREEMPT_DYNAMIC Fri Nov 1 00:58:34 UTC 2024 x86_64 GNU/Linux

**Comment by guttermonk** [comment]
The solution is to set `services.opensnitch.enable = true;` in configuration.nix, which will launch the program on it's own during startup. There's no need to include it in the hyprland config.

My issue was that I had the service enabled and, apparently, launching opensnitch-ui from the hyprland config causes it to open maximized.

It would be good to include these instructions in the wiki. Hope this helps!

**Comment by gustavo-iniguez-goya** [comment]
thank you for posting the solution @guttermonk !
