### ISSUE TITLE
[Feature Request] Add option to display DNS-server destination IPs in event-view

### ISSUE THREAD

**Issue by seniordevel** [evilsocket/opensnitch#1223]
I am really irritated by the way of logging DNS requests: The DNS servers destination IP is missing, while the queried domain is shown. 
Nobody needs to see the DNS query, since the query string is obvious anyway (if a request target would be 'google.com/etc', the prior DNS query would be 'google.com') So I don't see the purpose of showing this at all, well except you are running a corrupted DNS-client or you need to learn the very basics of networking; but then I suggest to use a packet viewer, not a firewall.
In almost 40 years of work I've never seen a software firewall which misses to log such important destination IP's.

I know, I can see the destination IP in details view, where the DNS request is shown correctly:
`UDP 57575:192.168.0.15 -> 5.1.66.255 (github.com):53`
But I would like to see this for DNS requests in event-view, e.g. **8.8.8.8 _(github.com)_:53** (with, or better without the queried domain string).

I am aware that in the past several issues -related to my request- have been posted here. But, I wonder, no one requested to really log the DNS destination IP's in event-overview. 

Just to name -only one- of the scenarios, where this feature would be helpful (not to mention the security issues provided by possible malware namespace servers):
I have configured a list of several private DNS servers. I would like to evaluate, which server performs best in terms of providing answers to most DNS queries. For statistical reasons I need to observe this over a longer time. Currently almost impossible, as I would need to open detail view for every single DNS-server request.

**Comment by gustavo-iniguez-goya** [comment]
Hi @seniordevel ,

I couldn't agree with you more. We used to display it as you request: https://github.com/gustavo-iniguez-goya/opensnitch/issues/50

I removed it from the daemon here d6cf18ef279643cba12a484d74193683797c8990

but it seems that I never add it back to the GUI.

**Comment by seniordevel** [comment]
Hello @gustavo,
thanks for your attention.

Not sure what audience or user group you might want to address with your frontend. 
But those who want to use a firewall to debug DNS-related network problems or to survey related security issues doubtlessly need the target IP's visible.

This issue you mentioned  [gustavo-iniguez-goya#50](https://github.com/gustavo-iniguez-goya/opensnitch/issues/50) is a good example to underline my own request. Showing the 'host to resolve' is not useful at all, even disturbing, no matter if shown alone or together with target IP.
May I ask why you consider this as helpful (showing the host to resolve) ?

With the modifications you made with [d6cf18e](https://github.com/evilsocket/opensnitch/commit/d6cf18ef279643cba12a484d74193683797c8990) any serious DNS-related debugging, DNS-configuration, and much more has become impossible. Sad, Opensnitch looked nice at first glance, but this way unusable for me - and probably many others.

Possibly you agree to another suggestion:
Make the few modifications  [d6cf18e](https://github.com/evilsocket/opensnitch/commit/d6cf18ef279643cba12a484d74193683797c8990) conditional, and add a preference to default-config.json.

**Comment by gustavo-iniguez-goya** [comment]
I think that all this is for historical reasons. Originally only a few fields of the connection were displayed on the GUI, and I didn't want to change it at the time. Then I realized that it was useful to display what domain an app was trying to resolve, so I added it to the Destination column. Users complained, so I removed it :)

But this change should have never been added to the daemon, but to the GUI, and let the users configure the columns to display.

> May I ask why you consider this as helpful (showing the host to resolve) ?

Showing the IP + the domain is useful to know what DNS server is being used to resolve a domain, for many reasons (debugging, curiosity, ...).

Now users can configure what columns to show, so maybe we could add all the fields of a connection to the Events tab, and let the users configure what columns to show. Similar to the Node tab view (when double clicking on a Node).

So you as an advanced user, what would you like to see in the Events tab, all the fields in each column?

OpenSnitch should be simple enough to use for beginners, but also powerful enough to debug network, system or security issues.

**Comment by seniordevel** [comment]
> Now users can configure what columns to show, so maybe we could add all the fields of a connection to the Events tab, and let the users configure what columns to show. 

I think this is the way to go.


> ... what would you like to see in the Events tab, all the fields in each column?

I suggest to have the following very basic columns:
-Direction (In or Out)
-Source IP/Port
-Destination IP/Port (but always with the correct IP/port, also for DNS, never show the 'host to resolve' here)

To make it simple enough for beginners, you might wish to add a column named description or similar (e.g. with some additional information as 'DNS request via ....', or just a link pointing to a FAQ page)


> Showing the IP + the domain is useful to know what DNS server is being used to resolve a domain, for many reasons (debugging, curiosity, ...).

As for DNS requests, showing the the domain for the DNS server (if available) would be acceptable, but not showing the domain of the 'host to resolve'. I have never seen a case where this had been wrong, so it makes no sense in terms of debugging. Hiding important information while replacing it with declarative content (just because of misunderstandings - or out of curiosity) should never be done in my opinion.

**Comment by gustavo-iniguez-goya** [comment]
> -Destination IP/Port (but always with the correct IP/port, also for DNS, never show the 'host to resolve' here)

Without showing the domain in DNS queries, you'd see logs like this one:

`reject, 47807,172.17.0.1, 9.9.9.9,  53, udp, /usr/lib/firefox-esr/firefox-esr,/usr/bin/firefox-esr, 000-block-domains`

Instead showing the domain:
`reject, 47807,172.17.0.1, s.gravatar.com,  53, udp, /usr/lib/firefox-esr/firefox-esr,/usr/bin/firefox-esr, 000-block-domains`

I think it really helps to know what has been rejected, because there's no more connections after that one.

Of course if we allow to show all the fields it'd be:
`reject, 47807,172.17.0.1, 9.9.9.9, s.gravatar.com,  53, udp, /usr/lib/firefox-esr/firefox-esr,/usr/bin/firefox-esr, 000-block-domains`

**Comment by seniordevel** [comment]
> Without showing the domain in DNS queries, you'd see logs like this one:
> 
> `reject, 47807,172.17.0.1, 9.9.9.9, 53, udp, /usr/lib/firefox-esr/firefox-esr, 000-block-domains`
> 
Sorry in case I wasn't being clear enough. For the destination column this would be the only correct implementation in my opinion, safe and telling users everything necessary. Any other stuff should be unavailable, at least been shown in another column.

I wonder, in your example above, you reject a DNS request!
Reject DNS queries, seriously?ㅤㅤㅤㅤㅤㅤ 
You might wish to block an IP, a subnet or a network range.  But why should someone want to block a DNS request? Blocking a domain by blocking DNS resolving is highly unsafe, since it can be bypassed easily by using the IP directly. 
Therefore this should never be supported nor suggested - particularly with regard to beginners who understandably expect a firewall to work safely and strictly. Implementation of DNS-query blocking makes a firewall (-frontend) unreliable for beginners and kind of silly for experienced users.


> Instead showing the domain: `reject, 47807,172.17.0.1, s.gravatar.com, 53, udp, /usr/lib/firefox-esr/firefox-esr, 000-block-domains`
> 
> I think it really helps to know what has been rejected, because there's no more connections after that one.
> 
Pretty useless, if we want to talk about safety, security and reliability. And therefore even dangerous for beginners. Dns blocking might be part of adblockers; adblockers are known to be unreliable anyway. 

I strongly recommend to forget about any DNS blocking stuff, there definitely is no place for it in a serious firewall environment.

**Comment by gustavo-iniguez-goya** [comment]
ah, I see. I don't see it that way.

We support DNS block lists, like /etc/hosts but configurable from the GUI that allows you to review what was denied or not.
And frankly it works quite well: https://github.com/evilsocket/opensnitch/wiki/block-lists

So showing the domain in DNS queries will continue.

I'll add the rest of the fields.

**Comment by seniordevel** [comment]
> We support DNS block lists, ....

Thanks for clarification. I was not aware of that. So your project is dedicated to be something like a general content blocker, not just a frontend for iptables/nftables what makes a big difference. 

> I'll add the rest of the fields.

So many thanks, I am happy to see the DNS server IP's soon.
