### ISSUE TITLE
[Feature Request] Reduce vertical row size for data tables

### ISSUE THREAD

**Issue by e3dio** [evilsocket/opensnitch#1234]
### Summary:
There is excessive padding for lines of text in the data tables (Events, Rules, etc), half the screen is empty space, not ideal for viewing data. Add UI setting for reducing vertical padding between lines of text

**Comment by gustavo-iniguez-goya** [comment]
hi @e3dio !

Are you using the `qt-material` themes? this is, the themes from Preferences -> UI

could you post a screenshot on how it's displayed on your system? 

We're using Qt's default row height, but we could let the users configure it.

**Comment by e3dio** [comment]
Is this normal? Too much empty white space. I'd reduce row height as much as possible. I tried playing with the settings but couldn't find where to change it, any idea how?

![opensnitch_spacing](https://github.com/user-attachments/assets/99800aa2-66b1-4118-bdeb-b13c58211e73)

**Comment by e3dio** [comment]
Ok got it, much better in my opinion:

![os_space](https://github.com/user-attachments/assets/ccb7adb7-280e-4193-a093-ad82fba2630e)

**Comment by gustavo-iniguez-goya** [comment]
Setting a fixed size will break the look&feel for other users.

This is how it looks in KDE with a global 14px font:

![Captura de pantalla de 2024-12-10 12-17-56](https://github.com/user-attachments/assets/dd1721b1-7f17-4f89-9443-6909638bc865)

vs default section size:

![Captura de pantalla de 2024-12-10 12-20-43](https://github.com/user-attachments/assets/8aa537ee-a5cb-47a0-8a2e-da9f9c079567)

Examples of other apps:

Vlc:
![Captura de pantalla de 2024-12-10 12-40-45](https://github.com/user-attachments/assets/0c780e57-e4fd-4c2f-aad6-d6b2cfde25c4)

![Captura de pantalla de 2024-12-10 12-41-47](https://github.com/user-attachments/assets/9aa52db4-1f71-4c58-bc1b-c872cb284e7f)

KDE Keyboard layout options:

![Captura de pantalla de 2024-12-10 12-47-09](https://github.com/user-attachments/assets/5d675bc6-2713-4d9f-a81e-47ca6372d553)


Wireshark on the other hand let the users configure the size of the font, but the space between rows is the same:

14pt font:
![Captura de pantalla de 2024-12-10 13-04-35](https://github.com/user-attachments/assets/a25ea8d7-08a2-48e0-8849-f5aed82f2b3f)

8pt font:
![Captura de pantalla de 2024-12-10 13-05-32](https://github.com/user-attachments/assets/85a7d7aa-1931-4582-98e5-19c5c92d3721)

**Comment by e3dio** [comment]
Someone familiar with QT could add a fix: reduce the default height and optionally add a UI setting to adjust it. I created a PR just to document the quick fix for people who need it: https://github.com/evilsocket/opensnitch/pull/1235

**Comment by gustavo-iniguez-goya** [comment]
Thank you @e3dio ,

Better document it here, as people tend to search the issues more than the PRs:
```
        self.verticalHeader().setMinimumSectionSize(16)
        self.verticalHeader().setDefaultSectionSize(16)
```
