### ISSUE TITLE
UI: Filter does seem to work anymore

### ISSUE THREAD

**Issue by UffeJakobsen** [evilsocket/opensnitch#1243]
When updating to latest version built from master - UI (log) filter function does not seem to work anymore

BTW: thanks for the fixes to the DNS - logging both the queried server and the lookup value itself :+1:  :-)

**Comment by gustavo-iniguez-goya** [comment]
aah, ok. I'll update it ASAP.

Thank you for the heads-up.

**Comment by gustavo-iniguez-goya** [comment]
fixed. Thank you @UffeJakobsen !
