### ISSUE TITLE
Import Error: No module PyQt5 found

### ISSUE THREAD

**Issue by johnjohnsp1** [evilsocket/opensnitch#134]
Hello Simone,

i report this error:

root@VMKALI20173:~# service opensnitchd start
root@VMKALI20173:~# opensnitch-ui 
Traceback (most recent call last):
  File "/usr/local/bin/opensnitch-ui", line 3, in <module>
    from PyQt5 import QtWidgets, QtGui
ImportError: No module named PyQt5
root@VMKALI20173:~# uname -a
Linux VMKALI20173 4.15.0-kali2-amd64 #1 SMP Debian 4.15.11-1kali1 (2018-03-21) x86_64 GNU/Linux
root@VMKALI20173:~# cat /etc/lsb-release 
DISTRIB_ID=Kali
DISTRIB_RELEASE=kali-rolling
DISTRIB_CODENAME=kali-rolling
DISTRIB_DESCRIPTION="Kali GNU/Linux Rolling"

as you can see I'm trying to run the tool from a VMware with kali linux up to date but having issue as object to the module PyQT5 that is missing.

all the command I found on the code page about building I had no problems.
Here what I did:

root@VMKALI20173:~/opensnitch/ui# pip install -r requirements.txt 
Requirement already satisfied: grpc in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 1))
Collecting grpcio-tools (from -r requirements.txt (line 2))
  Downloading grpcio_tools-1.10.1-cp27-cp27mu-manylinux1_x86_64.whl (22.2MB)
    100% |████████████████████████████████| 22.2MB 18kB/s 
Requirement already satisfied: pyinotify==0.9.6 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 3))
Requirement already satisfied: futures==3.2.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 4))
Requirement already satisfied: unicode_slugify==0.1.3 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 5))
Requirement already satisfied: configparser==3.5.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 6))
Requirement already satisfied: msgpack-python in /usr/local/lib/python2.7/dist-packages (from grpc->-r requirements.txt (line 1))
Collecting grpcio>=1.10.1 (from grpcio-tools->-r requirements.txt (line 2))
  Downloading grpcio-1.10.1-cp27-cp27mu-manylinux1_x86_64.whl (7.6MB)
    100% |████████████████████████████████| 7.6MB 180kB/s 
Requirement already satisfied: protobuf>=3.5.0.post1 in /usr/local/lib/python2.7/dist-packages (from grpcio-tools->-r requirements.txt (line 2))
Requirement already satisfied: six in /usr/local/lib/python2.7/dist-packages (from unicode_slugify==0.1.3->-r requirements.txt (line 5))
Requirement already satisfied: unidecode in /usr/local/lib/python2.7/dist-packages (from unicode_slugify==0.1.3->-r requirements.txt (line 5))
Requirement already satisfied: enum34>=1.0.4 in /usr/local/lib/python2.7/dist-packages (from grpcio>=1.10.1->grpcio-tools->-r requirements.txt (line 2))
Requirement already satisfied: setuptools in /usr/local/lib/python2.7/dist-packages (from protobuf>=3.5.0.post1->grpcio-tools->-r requirements.txt (line 2))
Installing collected packages: grpcio, grpcio-tools
  Found existing installation: grpcio 1.10.0
    Uninstalling grpcio-1.10.0:
      Successfully uninstalled grpcio-1.10.0
Successfully installed grpcio-1.10.1 grpcio-tools-1.10.1
root@VMKALI20173:~/opensnitch/ui# ls
bin  desktop_parser.py  dialogs  Makefile  requirements.txt  res  resources_rc.py  service.py  setup.py  ui_pb2_grpc.py  ui_pb2.py  version.py
root@VMKALI20173:~/opensnitch/ui# pip install .
Processing /root/opensnitch/ui
Installing collected packages: opensnitch-ui
  Running setup.py install for opensnitch-ui ... done
Successfully installed opensnitch-ui-1.0.0b0
root@VMKALI20173:~/opensnitch/ui# ls
bin  desktop_parser.py  dialogs  Makefile  requirements.txt  res  resources_rc.py  service.py  setup.py  ui_pb2_grpc.py  ui_pb2.py  version.py
root@VMKALI20173:~/opensnitch/ui# pip install python-pyqt5
Collecting python-pyqt5
  Could not find a version that satisfies the requirement python-pyqt5 (from versions: )
No matching distribution found for python-pyqt5
root@VMKALI20173:~/opensnitch/ui# apt-get install python-pyqt5
Lettura elenco dei pacchetti... Fatto
Generazione albero delle dipendenze       
Lettura informazioni sullo stato... Fatto
python-pyqt5 è già alla versione più recente (5.9.2+dfsg-1).
0 aggiornati, 0 installati, 0 da rimuovere e 0 non aggiornati.

anything else I can try ? 
thanks

**Comment by evilsocket** [comment]
please format this issue properly

**Comment by evilsocket** [comment]
pull, follow the readme and the latest commits should solve this

**Comment by johnjohnsp1** [comment]
Thanks,

It is now working

**Comment by evilsocket** [comment]
- victory dance -
