### ISSUE TITLE
ImportError: No module named ui-pb2

### ISSUE THREAD

**Issue by a9e78rauijasdf** [evilsocket/opensnitch#135]
On ubuntu 17.10 - tested on two machines with repo go version 1.8 installed. Used install instructions point by point, though adding three more steps:

 - moving opensnitch github repo into gopath
 - apt install golang-glide
 - running make deps within opensnitch folder

Compile + install runs without flaws. The daemon runs as well. Trying to run opensnitch-ui yields:

Traceback (most recent call last):
  File "/usr/local/bin/opensnitch-ui", line 17, in <module>
    import ui_pb2
ImportError: No module named ui_pb2

**Comment by evilsocket** [comment]
i think i know how to fix it, it's about what setup.py copies i think, will work on it as soon as i can

**Comment by evilsocket** [comment]
pull, follow the readme and the latest commits should solve this
