### ISSUE TITLE
make fails due to "ImportError: No module named 'grpc_tools'"

### ISSUE THREAD

**Issue by boramalper** [evilsocket/opensnitch#140]
## Problem

make fails due to missing Python 3 dependency

```
$ make 
make[1]: Entering directory '/home/bora/labs/opensnitch/proto'
python3 -m grpc_tools.protoc -I. --python_out=../ui/opensnitch/ --grpc_python_out=../ui/opensnitch/ ui.proto
/usr/bin/python3: Error while finding spec for 'grpc_tools.protoc' (ImportError: No module named 'grpc_tools')
Makefile:7: recipe for target '../ui/ui_pb2.py' failed
make[1]: *** [../ui/ui_pb2.py] Error 1
make[1]: Leaving directory '/home/bora/labs/opensnitch/proto'
Makefile:8: recipe for target 'protocol' failed
make: *** [protocol] Error 2
```

## Solution

Well, installing the dependency!

    python3 -m pip install --user grpcio-tools

**Comment by ansell** [comment]
The line added by this issue was removed in a later commit https://github.com/evilsocket/opensnitch/commit/0687203a20203ea1303033993cab74c3ab5d13cd I came across the same issue today while following the installation instructions.

**Comment by ansell** [comment]
Also need to add ``sudo apt-get install python3-pip`` for those who have not done python development on the machine they are installing on

**Comment by mossbyte** [comment]
This is happening again. The solution above requirements are satisfied, and the error occurs.

/usr/bin/python3: Error while finding module specification for `grcp_tools.protoc` (ModuleNotFoundError: No module named `grcp_tools`

Is the underscore versus a dash somehow conflicting, or is that normal?

**Comment by xinln** [comment]
@boramalper  You are the best

**Comment by evatiwari** [comment]
I have ```grpcio-tools``` installed but somehow I am still getting this exact same error 
```
/opt/homebrew/opt/python@3.9/bin/python3.9: Error while finding module specification for 'grpc_tools.protoc' (ModuleNotFoundError: No module named 'grpc_tools')
```

**Comment by liulixiang1988** [comment]
> I have `grpcio-tools` installed but somehow I am still getting this exact same error
> 
> ```
> /opt/homebrew/opt/python@3.9/bin/python3.9: Error while finding module specification for 'grpc_tools.protoc' (ModuleNotFoundError: No module named 'grpc_tools')
> ```

I also encountered the same issue in MacOS:

```
/Library/Frameworks/Python.framework/Versions/3.10/bin/python3: Error while finding module specification for 'grpcio_tools.protoc' (ModuleNotFoundError: No module named 'grpcio_tools')
```

**Comment by stevenjowens** [comment]
You need grpcio-tools, not grpc-tools.

I had a venv set up and code working, then had to move things around so I had to recreate the venv, slipped and types "pip install grpc-tools" instead of "pip install grpcio-tools" and it mysteriously broke.   Took a little poking about before I realized my mistake and fixed it.

**Comment by Jangab-water** [comment]
@boramalper it works for me.

i think, however, `grpcio` should contain `grpcio-tools`. if proto is not compiled, it isn't works. i cannot understand why they are seperated.

have you ever plan to integrate them?

sincerely,
