### ISSUE TITLE
Add support compile dep

### ISSUE THREAD

**Issue by specialworld83** [evilsocket/opensnitch#147]
Hello, you can have the support for dep, since the glide code has been made obsolete by the same programmer in a ticket.

**Comment by specialworld83** [comment]
Golang Dep
The Go community now has the dep project to manage dependencies. Please consider trying to migrate from Glide to dep. If there is an issue preventing you from migrating please file an issue with dep so the problem can be corrected. Glide will continue to be supported for some time but is considered to be in a state of support rather than active feature development.

**Comment by tianon** [comment]
With the discussion happening around "vgo" now, I'd recommend not rushing
out to use "dep" especially if you've already got a workflow that's working
for you.

**Comment by evilsocket** [comment]
since we're not in 1.0.0 yet i can just experiment, so far I'm not very happy with Glide so I'll just try dep and compare ...
