### ISSUE TITLE
OpenSnitch-UI freezing after running 5 min

### ISSUE THREAD

**Issue by intika** [evilsocket/opensnitch#150]
I am having an odd issue...

**Info :** 
the OpenSnitch-UI freeze and become very slow (only opensnitch-ui) ... no error is displayed on the command line browsing the connection list is very slow, sometime the core windows become black and and a lot of connections are displayed on the list without having a popup that ask for authorisation... the rule list is empty 

**Issue :**
- Gui very slow 
- The question pop-up is generated 1/10 

**Question :** 
Do you have any idea about it ? or any advice to debug ?

Thanks

**Comment by evilsocket** [comment]
not a screenshot, not a log, nothing, closing this as incomplete

**Comment by logix2** [comment]
I'm also noticing that the UI freezes frequently when the General tab is selected, and opensnitch-ui has a high CPU usage when this happens. But I'm not seeing anything, how can I debug it?

**Comment by intika** [comment]
we need to go back to school to learn debugging ;) ^^ otherwise its not worth posting here lol

**Comment by logix2** [comment]
This might be of some use:
```
Original exception was:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/opensnitch/dialogs/stats.py", line 204, in _on_update_triggered
KeyError: 'getpwuid(): uid not found: 102'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/opensnitch/dialogs/stats.py", line 204, in _on_update_triggered
KeyError: 'getpwuid(): uid not found: 102'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 780, in get_code
  File "<frozen importlib._bootstrap_external>", line 832, in get_data
OSError: [Errno 24] Too many open files: '/usr/lib/python3/dist-packages/apport/__init__.py'
```
I get this about... a few hundred times per minute when running opensnitch-ui :)

**Comment by evilsocket** [comment]
@intika you don't need to know debugging in order to take a screenshot or copy/paste some text, you just don't have to be lazy.

**Comment by intika** [comment]
:+1:

**Comment by hook-s3c** [comment]
also having this issue, UI seizes up for a few moments before refreshing, happens often when going through the tabs

can't really screenshot a freeze, looks the same as when it's running

**Comment by podkop** [comment]
Hi,

I installed _opensnitch-1.3.6-1.x86_64.rpm_ and _opensnitch-ui-1.3.6-1.f29.noarch.rpm_ in Fedora 33 (desktop). Qt version 5.12.9.

After a minute or so, opensnitch-ui crashes while opensnitch continues working in background. 
The log shows Qt errors of the following kind: 

> QObject: Cannot create children for a parent that is in a different thread.
> (Parent is Adwaita::WidgetStateEngine(0x55e44f19fa20), parent's thread is QThread(0x55e44e8ada20), current thread is QThread(0x7f560c003670)
> QObject::installEventFilter(): Cannot filter events for objects in a different thread.

Steps described in [Known-problems - GUI crash/exceptioneption-or-does-not-show-up](https://github.com/evilsocket/opensnitch/wiki/Known-problems#gui-crashexception-or-does-not-show-up) do not help.

**Comment by gustavo-iniguez-goya** [comment]
hey @podkop ,

Could you install and try it with this release? https://github.com/evilsocket/opensnitch/releases/tag/v1.4.0-rc.3
https://github.com/evilsocket/opensnitch/releases/download/v1.4.0-rc.3/opensnitch-1.4.0rc3-1.x86_64.rpm
https://github.com/evilsocket/opensnitch/releases/download/v1.4.0-rc.3/opensnitch-ui-1.4.0rc2-1.fc29.noarch.rpm

We've fixed a lot of bugs since 1.3.6.

**Comment by podkop** [comment]
Thanks, it works! I thought it is release candidate?

**Comment by gustavo-iniguez-goya** [comment]
yeah, it's a release candidate, but as far as I can tell fairly stable for daily use.

**Comment by podkop** [comment]
Thanks again. Great app.
