### ISSUE TITLE
No module named 'ui_pb2'

### ISSUE THREAD

**Issue by Mass1998** [evilsocket/opensnitch#156]
Installed but when I run: opensnitch-ui

Traceback (most recent call last):
  File "/usr/bin/opensnitch-ui", line 17, in <module>
    import ui_pb2
ModuleNotFoundError: No module named 'ui_pb2'

**Comment by evilsocket** [comment]
This bug was already fixed, you're probably using an old version.

**Comment by testuser369** [comment]
using latest version 

~/go/src/github.com/evilsocket/opensnitch$ sudo opensnitch-ui
Traceback (most recent call last):
  File "/usr/local/bin/opensnitch-ui", line 18, in <module>
    from opensnitch.service import UIService
  File "/usr/local/lib/python3.6/dist-packages/opensnitch/service.py", line 16, in <module>
    import ui_pb2
ModuleNotFoundError: No module named 'ui_pb2'

~/go/src/github.com/evilsocket/opensnitch$ sudo make install
make[1]: Entering directory '/home/pc/go/src/github.com/evilsocket/opensnitch/daemon'
make[1]: Leaving directory '/home/pc/go/src/github.com/evilsocket/opensnitch/daemon'
make[1]: Entering directory '/home/pc/go/src/github.com/evilsocket/opensnitch/ui'
The directory '/home/pc/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/pc/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Processing /home/pc/go/src/github.com/evilsocket/opensnitch/ui
  Requirement already satisfied (use --upgrade to upgrade): opensnitch-ui==1.0.0b0 from file:///home/pc/go/src/github.com/evilsocket/opensnitch/ui in /usr/local/lib/python3.6/dist-packages
make[1]: Leaving directory '/home/pc/go/src/github.com/evilsocket/opensnitch/ui'
:~/go/src/github.com/evilsocket/opensnitch$ sudo systemctl enable opensnitchd
Created symlink /etc/systemd/system/multi-user.target.wants/opensnitchd.service → /etc/systemd/system/opensnitchd.service.
c:~/go/src/github.com/evilsocket/opensnitch$ sudo service opensnitchd start^C
