### ISSUE TITLE
(naive issue) : 'unrecognized import path "context"...

### ISSUE THREAD

**Issue by Herve5** [evilsocket/opensnitch#158]
Trying to install, when I type
$ go get -u github.com/golang/dep/cmd/dep
I get :
package context: unrecognized import path "context" (import path does not begin with hostname)
What did I wrong?
TIA!

**Comment by evilsocket** [comment]
this is not related to opensnitch, make sure you're using a recent Go version and that you installed it correctly

**Comment by jpwhitney** [comment]
I realize this is closed, but I had the same error and after some searching found that it is related to the version of Go that is installed and the context package.
To fix this I ran these commands to install a more recent version of Go than my package manager (Ubuntu 16.04) had available.
```
sudo add-apt-repository ppa:longsleep/golang-backports
sudo apt-get update
sudo apt-get install golang-go
```
