### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by wiserweb** [evilsocket/opensnitch#161]
`go get github.com/evilsocket/opensnitch`

Gives

```
go get github.com/evilsocket/opensnitch
can't load package: package github.com/evilsocket/opensnitch: no buildable Go source files in /home/bigmint/go/src/github.com/evilsocket/opensnitch

```

Probably meant to be 

`go get github.com/evilsocket/opensnitch/daemon`

**Comment by evilsocket** [comment]
From the README:

> ignore the message about no Go files being found

You know ... **READ**ME ...

**Comment by wiserweb** [comment]
Ok.. it's not clear if that's for the line above or below good sir.
