### ISSUE TITLE
Slow ?

### ISSUE THREAD

**Issue by squalou** [evilsocket/opensnitch#164]
Hi,
with opensnitch up and running, I clearly noticed  less responsive network operations.
Seems 'logical' since there's somehting in between ... but I'm surprised its that much noticeable.

For instance, I'm running Arch, issuing 'yaourt -Syu' to synchronise packages databases:
- without opensnitch : 1,7s
- with opensnicth : 24s

Same thing when mounting smb shares etc.

I'm running this on a powerfull laptop (last year xps13 with core i7 and 16g ram) on a gigabyte fiber network. Also, opensnitchd is not consuming lot of cpu, rarely more than 1%, so .. I don't know.

Is this something to be expected or is there possily something wrong  / something I can do ?

thanks

**Comment by squalou** [comment]
I'm pleased to help if I can,

here are the files, after a few minutes and some slow operations (like above : smb mount, package db sync)

[cpu-and-mem-profiles.zip](https://github.com/evilsocket/opensnitch/files/1932744/cpu-and-mem-profiles.zip)

**Comment by Nadrieril** [comment]
Would it make sense to add ACCEPT/DROP rules to iptables whenever opensnitch marks a destination as accepted/refused ? That would solve the speed problem since only connections to new destinations would need to go through opensnitch, and iptables filtering is super fast.

**Comment by squalou** [comment]
maybe a good idea, provided opensnitch cleans up iptables rules when it's closed or killed, or restarted... which is probably not that easy to manage.
I'd hate having to manually deal with iptables rules the day I want to stop opensitch for whatever reason, or if it fails starting.

**Comment by Nadrieril** [comment]
I would set up a chain so that you only need to remove that chain in order to remove all the opensnitch-added rules. If you think it's a good idea and once I have managed to compile opensnitch, I may try to write a PR for that

**Comment by evilsocket** [comment]
What rule would you use to block a specific app instead of a specific destination?

**Comment by Nadrieril** [comment]
The `owner` iptable match seems to be able to do that: https://www.frozentux.net/iptables-tutorial/iptables-tutorial.html#OWNERMATCH

**Comment by evilsocket** [comment]
I don't know iptables enough, do you think it can cover [all of these cases](https://github.com/evilsocket/opensnitch/blob/master/daemon/rule/operator.go#L81) ?

**Comment by Nadrieril** [comment]
I am sure it can do all of those, except `process.cmd`, `process.path` and `process.env`.
`process.env` is definitely not an option; and I think `--owner-cmd` should work for either `process.path` or `process.cmd` but I'm not sure which.

**Comment by evilsocket** [comment]
thing is, there's already something -similar- to that implemented, basically [here i mark](https://github.com/evilsocket/opensnitch/blob/461e6b678e97d0f9235d6d1f320beef9dde3d4d4/daemon/main.go#L210) packets that a DENY rule matched and [here I tell iptables to just DROP such packets](https://github.com/evilsocket/opensnitch/blob/master/daemon/main.go#L263) ... but I keep getting those connections events anyway, I guess this NFQUEUE mark thingy is per-packet and not per-connection ... or there's a bug somewhere ... or I got it completely wrong ... need more time to debug :P

**Comment by Nadrieril** [comment]
When setting up complex firewalling/routing, I usually have a rule that says `-m state --state RELATED,ESTABLISHED -j ACCEPT`. This allows any packet from a connection that was previously accepted by the firewall. Maybe that would do what you need ? (cf. https://www.frozentux.net/iptables-tutorial/iptables-tutorial.html#STATEMATCH)

**Comment by evilsocket** [comment]
@Nadrieril would you be able to send a PR with this additional rule?

**Comment by Nadrieril** [comment]
I'm sorry, I've never gotten to using opensnitch on my system so I don't have time to contribute to it. I might try setting it up again in a few months but I'm not even sure.

**Comment by endorama** [comment]
Hello, I'm currently using opensnitch on a daily basis, and the performance penalty is really taxing. 

I would gladly contribute, but need a bit more information: if I got this right, the rule `-m state --state RELATED,ESTABLISHED -j ACCEPT` should be added to the `OUTPUT` chain, adding a new function to [daemon/firewall/rules.go](https://github.com/evilsocket/opensnitch/blob/c10e7a30c8f63c50a13770a3a1df73263a545bb7/daemon/firewall/rules.go) file, correct?

Then this function should be run before `firewall.QueueConnection` in [main.go#L261](https://github.com/evilsocket/opensnitch/blob/c10e7a30c8f63c50a13770a3a1df73263a545bb7/daemon/main.go#L261).

If this is it I should be able to provide a PR for the end of the week.

**Comment by gustavo-iniguez-goya** [comment]
This should be fixed with latest packages.
