### ISSUE TITLE
How essential is that UI for this firewall to work? 

### ISSUE THREAD

**Issue by thebunnyrules** [evilsocket/opensnitch#165]
Is it possible to run OpenSnitch in an open terminal window? If not, what happen if I don't compile the ui and just edit the rules in nano, would it still work?

I'm asking because I've not been able to get QT native apps to run native Wayland in gnome-shell-wayland (even with all the plasma-wayland packages installed). If no GTK alternatives exists for your UI, the QT UI will be run in an X11 layer, even if the user is running a wayland session. A X11 based UI for a firewall is far from ideal as all X11 apps are allowed  to send keystrokes to each other. This can be leveraged by a malicious app, so that it can theoretically answer for the user if they're not paying attention.

**Comment by evilsocket** [comment]
> Is it possible to run OpenSnitch in an open terminal window?

Yes, the daemon is just a native process with no UI.

>  If not, what happen if I don't compile the ui and just edit the rules in nano, would it still work?

Nothing, the daemon will keep working as it loads the JSON rules from the folder, however, if a new connection will not match any rule, by default it'd connect to the UI service and ask it what to do, if the service is not running, the only thing it can do is allowing the connection. So it works, but new connections won't be filtered (until you don't manually add a rule to cover those as well).

> If no GTK alternatives exists for your UI

It's not "my" UI, the project is open, if you need a GTK UI, pull requests are more than welcome, I just happen to like Qt more :)

> A X11 based UI for a firewall is far from ideal

Most of the things on Linux as a desktop system are far from ideal ...

> This can be leveraged by a malicious app

This is simply not the scenario OpenSnitch would protect you from, if your computer is already compromised with a malicious app running, that app can do a lot of different things to bypass the application firewall.
