### ISSUE TITLE
make error on kali rolling 64

### ISSUE THREAD

**Issue by steevespapillon** [evilsocket/opensnitch#167]
when i want to compile:make[1]: Entering directory '/root/go/src/github.com/evilsocket/opensnitch/proto'
python3 -m grpc_tools.protoc -I. --python_out=../ui/opensnitch/ --grpc_python_out=../ui/opensnitch/ ui.proto
make[1]: Leaving directory '/root/go/src/github.com/evilsocket/opensnitch/proto'
make[1]: Entering directory '/root/go/src/github.com/evilsocket/opensnitch/daemon'
make[1]: dep: Command not found
Makefile:10: recipe for target 'deps' failed
make[1]: *** [deps] Error 127
make[1]: Leaving directory '/root/go/src/github.com/evilsocket/opensnitch/daemon'
Makefile:11: recipe for target 'daemon/opensnitchd' failed
make: *** [daemon/opensnitchd] Error 2

**Comment by evilsocket** [comment]
"dep: Command not found"

you didn't

> go get -u github.com/golang/dep/cmd/dep

RTFM

**Comment by steevespapillon** [comment]
Hello,i followed step by step the installation procédure before having this
error

**Comment by evilsocket** [comment]
what's the output of:

    go get -u github.com/golang/dep/cmd/dep
    go env
    which dep
    echo $GOPATH
    echo $PATH

**Comment by steevespapillon** [comment]
Thank you i will do that and send you the issue later

**Comment by steevespapillon** [comment]
hi i had forgotten output of:
go get -u github.com/golang/dep/cmd/dep..ouput nothing

go env:
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/papillon/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/papillon/go"
GORACE=""
GOROOT="/usr/lib/go-1.10"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.10/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build758542969=/tmp/go-build -gno-reco

which dep:
/usr/local/bin/dep

echo /home/papillon/go:
/home/papillon/go
 
echo $PATH:
/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
