### ISSUE TITLE
[Errno 2] No such file or directory

### ISSUE THREAD

**Issue by gapry** [evilsocket/opensnitch#168]
I try to install opensnitch in Manjaro and it occurs `[Errno 2] No such file or directory`. The details as follows.

# Environment
* `Linux Y410P 4.14.34-1-MANJARO #1 SMP PREEMPT Thu Apr 12 17:26:43 UTC 2018 x86_64 GNU/Linux`
* `go version go1.10.1 linux/amd64`

# Setup
`$ sudo pacman -S protobuf libpcap libnetfilter_queue`
`$ yaourt --m-arg "--skippgpcheck" -S opensnitch-git`

# Result
```
==> WARNING: Skipping verification of source file PGP signatures.
==> Validating source files with sha256sums...
    opensnitch-git ... Skipped
==> Extracting sources...
  -> Creating working copy of opensnitch git repo...
Cloning into 'opensnitch-git'...
done.
==> Starting pkgver()...
==> Updated version: opensnitch-git r340.f71d8ce-1
==> Starting build()...
python: can't open file 'setup.py': [Errno 2] No such file or directory
==> ERROR: A failure occurred in build().
    Aborting...
==> ERROR: Makepkg was unable to build opensnitch-git.
==> Restart building opensnitch-git ? [y/N]
==> ---------------------------------------
==> 
```

**Comment by evilsocket** [comment]
this is a problem of how it's packaged for Arch, not of the software itself, I'm not the maintainer of that package.
