### ISSUE TITLE
Auto-accept countdown should stop when clicking in the dialog

### ISSUE THREAD

**Issue by ansell** [evilsocket/opensnitch#175]
The auto-accept countdown by default seems to be 15 seconds. However, clicking in the dialog to change the settings does not remove the auto-accept countdown. This makes it seem like you only have 15 seconds to decide whether you want to allow or not, including the time to change the settings, and otherwise the default action will be used with a rule created for it. If I need to research what the consequences of allowing or denying an action are, I need to be able to halt the countdown, and the easiest way of doing that is to click in the dialog somewhere. Extending the default timeout using the config file, or switching to deny by default and still having a countdown, are not useful with situations where more research is required.

**Comment by Khoramyar** [comment]
Yes. 15 seconds is way too short for many of these decisions.

I also would like to see config settings i.e. adjustment for default countdown in GUI, maybe a menu option for tray icon?

**Comment by gustavo-iniguez-goya** [comment]
✔️ config settings added.
✔️ countdown is stopped if you click on the [+] button.
✔️ countdown configurable.

**Comment by ad7718** [comment]
It's not obvious what you need to click on "+" to stop countdown. I think that clicking on any dropdown or even on window must stop it.
