### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by johnsilvermore** [evilsocket/opensnitch#179]
I totally dig that you're making a littlesnitch alternative for linux. I can't install it though. I'm on debian 9.
at the step where I enter the 'make' command, I get this :  

make[1]: Entering directory '/src/local/go/src/github.com/evilsocket/opensnitch/proto'
python3 -m grpc_tools.protoc -I. --python_out=../ui/opensnitch/ --grpc_python_out=../ui/opensnitch/ ui.proto
make[1]: Leaving directory '/src/local/go/src/github.com/evilsocket/opensnitch/proto'
make[1]: Entering directory '/src/local/go/src/github.com/evilsocket/opensnitch/daemon'
make[1]: dep: Command not found
Makefile:10: recipe for target 'deps' failed
make[1]: *** [deps] Error 127
make[1]: Leaving directory '/src/local/go/src/github.com/evilsocket/opensnitch/daemon'
Makefile:11: recipe for target 'daemon/opensnitchd' failed
make: *** [daemon/opensnitchd] Error 2

I played around with all possible gopaths (in root folder and in my user folder) and I keep ending up with the output from above.

thanks

**Comment by johnsilvermore** [comment]
New info: If I try to make as non-root I get this:
make[1]: Entering directory '/home/enterprise-touch/go2/src/github.com/evilsocket/opensnitch/proto'
python3 -m grpc_tools.protoc -I. --python_out=../ui/opensnitch/ --grpc_python_out=../ui/opensnitch/ ui.proto
/usr/bin/python3: Error while finding module specification for 'grpc_tools.protoc' (ImportError: No module named 'grpc_tools')
Makefile:7: recipe for target '../ui/ui_pb2.py' failed
make[1]: *** [../ui/ui_pb2.py] Error 1
make[1]: Leaving directory '/home/enterprise-touch/go2/src/github.com/evilsocket/opensnitch/proto'
Makefile:8: recipe for target 'protocol' failed
make: *** [protocol] Error 2

**Comment by ansell** [comment]
Did you follow the steps in the README.md file before running make?

https://github.com/evilsocket/opensnitch#tldr

Installing grpcio-tools and the other listed build dependencies worked for me to get past that error
