### ISSUE TITLE
Ability to change rules from the UI

### ISSUE THREAD

**Issue by grenzor** [evilsocket/opensnitch#186]
Thanks for this great application.

It would be useful to be able to able to change added rules from the UI for example if I already added a temporary session rule I could right-click, edit and the popup options are available again so I change it to temporary only once, permanent etc. allow/deny rules. 

Also it seems like temporary rules aren't stored anywhere that I can see including the rules JSON file so I'm unable to change it after allowing/denying from the popup.

**Comment by gustavo-iniguez-goya** [comment]
Fixed with latest version.
