### ISSUE TITLE
Compilation error in daemon/netfilter

### ISSUE THREAD

**Issue by dpramone** [evilsocket/opensnitch#189]
user@xxxxx:~/go/src/github.com/evilsocket/opensnitch/daemon> make
# github.com/evilsocket/opensnitch/daemon/netfilter
netfilter/queue.go:118: cannot use queueSize (type C.u_int32_t) as type C.uint32_t in argument to func literal
netfilter/queue.go:121: cannot use C.u_int8_t(2) (type C.u_int8_t) as type C.uint8_t in argument to func literal
make: *** [Makefile:13: opensnitchd] Error 2

System: Linux xxxxxxx@xxxxxxx.xxx 4.12.14-lp150.12.16-default #1 SMP Tue Aug 14 17:51:27 UTC 2018 (28574e6) x86_64 x86_64 x86_64 GNU/Linux
Dist: OpenSuSE Leap 15.0
Go: 1.9
GOARCH="amd64"
GOBIN="/home/dpraet/go/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/dpraet/go:/usr/lib64/go/contrib"
GORACE=""
GOROOT="/usr/lib64/go/1.9"
GOTOOLDIR="/usr/lib64/go/1.9/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build553318921=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"

Netfilter: libnetfilter_queue1/libnetfilter_queue1 1.0.3

**Comment by Luca1991** [comment]
Same problem here (openSUSE Leap 15.0). Have you found a way to fix this?

**Comment by lindroidux** [comment]
Any fix?

**Comment by gustavo-iniguez-goya** [comment]
I've just compiled the daemon on OpenSuse Leap 15 with no errors.

> ~ $ cat /etc/os-release
> NAME="openSUSE Leap"
> VERSION="15.0"

> ~ $ go version
> go version go1.12.6 linux/amd64

> ~ $ gcc -v
> (...)
> gcc version 7.3.1 20180323 (...)

> ~ $ zypper info libnetfilter_queue1
> (...)
> Version: 1.0.3-lp150.1.3

> ~ $ uname -r
> 4.12.14-lp150.12.67-default

```
linux-jzin:~/go/src/github.com/evilsocket/opensnitch/daemon $ make
linux-jzin:~/go/src/github.com/evilsocket/opensnitch/daemon $ ls -l opensnitchd
-rwxr-xr-x 1 root root 15345632 Aug 19 16:00 opensnitchd
linux-jzin:~/go/src/github.com/evilsocket/opensnitch/daemon # ./opensnitchd -rules-path /etc/opensnitch/
[2019-08-19 14:07:37]  IMP  Starting opensnitch-daemon v1.0.0b
[2019-08-19 14:07:37]  INF  Loading rules from /etc/opensnitch ...
[2019-08-19 14:07:37]  INF  Running on netfilter queue #0 ...
```
it looks like the only difference is the go version, which I just installed today.

**Comment by gustavo-iniguez-goya** [comment]
Fixed with latest version.
