### ISSUE TITLE
Missing git clone in install section?

### ISSUE THREAD

**Issue by picatz** [evilsocket/opensnitch#19]
## Problem
Current install instructions are:
```shell
sudo apt-get install build-essential python-dev python-setuptools libnetfilter-queue-dev python-qt4
cd opensnitch
sudo python setup.py install
```

The line
```shell
cd opensnitch
```
Makes me think I'm supposed to change into a directory. Cuz, that's what it's doing.

## Add Git Clone
So, I believe it's missing the following line to git clone the repo:
```shell
git clone https://github.com/evilsocket/opensnitch.git
```

Right?

**Comment by evilsocket** [comment]
Are you kidding me? It's pretty much like saying, in some installation instructions, the line "download from the download link" is missing O.o

**Comment by picatz** [comment]
## Thoughts
I understand your point. 

###### But I'ma Just Say Some Stuff, also I <3 u no worries.
Hopefully I can clarify a little bit of what I meant though.

## Clarity
I think that having the `git clone` line in the install instructions in the README would help clarify how to install opensnitch. 
###### But Why?
I think the `cd` instruction is just a tiny bit ambiguous -- mostly I think this would genuinely be a less friendly to people that _don't_ use git all the time. 
###### Download from the Download Link
To be fair, I think: you can download the code in a few ways: either by cloning, or by downloading the zip from the web interface. If you got the zip, the install instructions would be extra ambiguous I think.
###### Lazy Friendly
Plus, having the `git clone line` would make the install instructions extra copy+paste friendly. For the super lazy.

#### Totally Necessary?
I don't think it's totally necessary to be overly explicit with "_how-to_" instructions. But I think this line would be worth the extra line in the install instructions. At least that's my personal opinion that you can ignore; which I respect, in full, for the record.

I was sort of thinking about me before I knew how to use `git`; and I honestly think those install instructions would've tripped me up. Which is why I brought up the issue. 

Though I suppose I could've at least clarified my point better.

**Comment by evilsocket** [comment]
I totally get it, my point is that since the software is still in alpha, as specified in the README, I don't want to encourage non-developers to use it, Therefore, without having the `git clone ...` command, I'm trying to have only devs involved in the project right now.

Ideally, when there'll be a release candidate, the software will be packaged and pushed on pip, but right now I'd rather keep it the way it is ... makes sense?
