### ISSUE TITLE
Does not scale properly, can't resize windows. Buttons smashed together. Ubuntu 18.04 

### ISSUE THREAD

**Issue by 13xps** [evilsocket/opensnitch#191]
Installed on Ubuntu 18.04 4k screen scaled 200%

![screenshot from 2018-08-29 17-46-37](https://user-images.githubusercontent.com/42802126/44780169-e4beb800-abb3-11e8-9511-1fd3be7e3064.png)

**Comment by MiWCryptAnalytics** [comment]
PR #203 should fix this issue with the ui widgets being drawn too small and overlapping.
