### ISSUE TITLE
Installation blocked due to upstream python-netfilterqueue dependency install error

### ISSUE THREAD

**Issue by luzpaz** [evilsocket/opensnitch#195]
Upstream:
https://github.com/kti/python-netfilterqueue/issues/44
https://aur.archlinux.org/packages/python-netfilterqueue-git/#comment-661972

Specs:
Manjaro 17.1.12  
Python 3.7.0 (default, Jul 15 2018, 10:44:58) [GCC 8.1.1 20180531]

**Comment by gustavo-iniguez-goya** [comment]
opensnitch does not use python-netfilterqueue anymore
