### ISSUE TITLE
Please provide releases and binaries to ease up packaging

### ISSUE THREAD

**Issue by cookiengineer** [evilsocket/opensnitch#196]
Hey there,

I was adopting the AUR package for opensnitch-git today, and after around 3 hours trying to get stuff to work, I now officially give up. Currently, there's no feasible non-throwing-laptop-outta-window way to package opensnitch easily.

Please provide detailed instructions which binary is expected where, why the final binary keeps looking for a `./rules` file in the current working dir, and please provide instructions how to compile everything - without Makefiles loading stuff from the internet.

Hints on how to make opensnitch package-able for downstream Linux distributions:

- [ ] Remove all pip commands from Makefiles and move them into something like `./bin/install-dependencies.sh`
- [ ] Remove all `go get` instructions from the Makefiles as well, and move them to an external shell script, too.
- [ ] After the `make` command has run through, provide a clear `/build` folder where all things are in their expected locations. If it needs a given folder structure, make something like `/build/etc/what/ever/you/expect.conf` as well. If you expect your binary to be named `opensnitch-daemon`, move it into `/build/usr/bin/opensnitch-daemon` as well.
- [ ] Provide details on how the systemd integration should work, in the sense which services or unit files are expected to run as user and which are expected to run via systemd normally.
- [ ] Provide details how the UI integration works, which symlink has to be where and how to put it correctly in python's site-packages folder. What are the paths exactly, meaning is it `/usr/bin/opensnitch-ui` or what?

Thanks in advice,
~Cookie

**Comment by lsfxz** [comment]
I have to agree, properly separating build and install procedures would make packaging much easier.

In the meantime, you can have a look at https://github.com/lsfxz/opensnitch-arch. I've packaged it to provide it in a private Arch repository, but I guess if you'd like to pick it up to adopt the AUR package, it might be a starting point.

It's not the prettiest PKGBUILD, and with further modifications it could probably done more cleanly, but it works and builds properly in a chroot.

Most of the dependencies in the git repo are in the AUR (and actually grabbed from there), except for unicode-slugify if I recall correctly, so you probably want to grab that as well.

**Comment by lsfxz** [comment]
Just as a heads-up, I've just picked it up as a maintainer,for now. Still not entirely happy with the PKGBUILD, and there's some strangeness with the (-git-)dependencies left.

If you'd like to take it over I'd happily orphan it again – didn't intend to get in your way there :)

**Comment by cookiengineer** [comment]
@lsfxz No worries, everything okay :) Thanks for taking over the package!

**Comment by gustavo-iniguez-goya** [comment]
Nice work!! :)
