### ISSUE TITLE
opensnitchd does not start on Ubuntu 18.10 (kernel 4.18.0-10)

### ISSUE THREAD

**Issue by andreiple** [evilsocket/opensnitch#214]
Hello,

I was using opensnitch successfully on Ubuntu 18.04, but yesterday upgraded to Ubuntu 18.10 and opensnitchd fails to start with error:
[2018-10-19 00:53:52]  IMP  Starting opensnitch-daemon v1.0.0b
[2018-10-19 00:53:52]  !!!  Error while enabling probe descriptor for opensnitch_exec_probe: write /sys/kernel/debug/tracing/kprobe_events: operation not permitted

Tried rebuilding/reinstallind opensnitchd, but still getting the same error.

**Comment by andreiple** [comment]
I'll close it. It works fine on clean install of Ubuntu 18.10, but it's buggered somehow after upgrade 18.04 -> 18.10. Guess does not worth any time on sorting out what's wrong

**Comment by miguelconde91** [comment]
I have the same issue in a clean installation of ubuntu 18.10 For a compatibility issue of my hardware I was working with a non stable version of kernel 4.20 using this kernel I installed opensnitch and it worked fine, recently I deleted the non stable kernels and I kept the last one signed in Kubuntu repos 18.10 and now not the opensnitch works, I have that same error.
