### ISSUE TITLE
Can't run the UI

### ISSUE THREAD

**Issue by paulcarroty** [evilsocket/opensnitch#216]
Fedora 28, python 3.6, step-by-step followed README.

[osntch.log](https://github.com/evilsocket/opensnitch/files/2526539/osntch.log)

`opensnitchd.service` runs without any issue.

**Comment by davidhscope** [comment]
> Fedora 28, python 3.6, step-by-step followed README.
> 
> [osntch.log](https://github.com/evilsocket/opensnitch/files/2526539/osntch.log)
> 
> `opensnitchd.service` runs without any issue.

I have solution for this issue, Please add opensnitch. before config,

it worked for me.

**Comment by paulcarroty** [comment]
@davidhscope great, can you provide more info? You mean https://github.com/evilsocket/opensnitch/blob/master/ui/opensnitch/config.py?

**Comment by davidhscope** [comment]
@paulcarroty 

You need edit 2 files: 
- /usr/local/lib/python3.6/dist-packages/opensnitch/service.py 
- /usr/local/lib/python3.6/dist-packages/opensnitch/dialogs/prompt.py 
Replaces 
```python
from config import Config
from version import version
```
By
```python
from opensnitch.config import Config
from opensnitch.version import version
```

**Comment by paulcarroty** [comment]
@davidhscope got the same result - only notification when something want connect to internet, no main window.

**Comment by davidhscope** [comment]
> @davidhscope got the same result - only notification when something want connect to internet, no main window.

@paulcarroty you can use which cmd to find real path of opensnicht-ui stored. etc: ~/.opensnicht/ui/....

replace all config to opensnich.config

That worked for me!

**Comment by paulcarroty** [comment]
@davidhscope OK, I'll try. Which DE you use? GNOME just ripped of the tray, maybe it's the reason of this issue.

**Comment by davidhscope** [comment]
@paulcarroty I use Ubuntu 18.04 with default settings.

**Comment by paulcarroty** [comment]
![](https://i.imgur.com/xRcxzyB.png)

Got it working in Fedora 29 Xfce, didn't change anything.

@evilsocket can you fix it for environments without tray like GNOME and tons of window managers?

**Comment by Ashrael** [comment]
HI! 
I am having the same problem, somehow the UI does not start at all...  I am using Ubuntu MATE 18.04. Also I have not ray icon and no icon on opensnitch in the menu? Tried starting UI from cli, no joy, no error, no nothing...  I have to add that I am looking for an install that runs opensnitch for a non root user. Althought the UI doesn't run as admin user as well... 

Any help appreciated!

**Comment by paulcarroty** [comment]
This project seems abandoned, I switched to https://gitlab.com/douaneapp/Douane .

**Comment by Ashrael** [comment]
LOL, looking at douane, i think that is abandoned... There is another project, but it looks shady to me, website looks great, but no info whatsoever: https://fireprompt.com/ Anyone know more of this one, or tried it?

**Comment by Ashrael** [comment]
I got the UI to work in the admin account, but still no joy in user account. For user (in cli):

```
opensnitch-ui 
Traceback (most recent call last):
  File "/usr/local/bin/opensnitch-ui", line 18, in <module>
    from opensnitch.service import UIService
  File "/usr/local/lib/python3.6/dist-packages/opensnitch/service.py", line 16, in <module>
    import ui_pb2
  File "/usr/local/lib/python3.6/dist-packages/opensnitch/ui_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
ModuleNotFoundError: No module named 'google'
```
Any help appreciated!

**Comment by paulcarroty** [comment]
@evilsocket instead of deleting our comments please fix your shitty code.
And I just got all comments to email, so you just lost the time.

**Comment by evilsocket** [comment]
@paulcarroty instead of redirecting users to projects that are even more unstable than this one and confuse them, think twice. 

Also you should think twice about the fact that **you** decided to use my "shitty code" (that yes, it is shitty) that has not even been released in alpha, probably because you're just too dumb to realize yourself that there's a big difference between stable and prototype.

Now you can go f yourself elsewhere.
