### ISSUE TITLE
LMDE3 install failed at make

### ISSUE THREAD

**Issue by PeetsB** [evilsocket/opensnitch#218]
Clean system install - Go, Python all installed and environment variables set accordingly.
Looks like file stdlib-bsearch.h is missing.
Any workaround?

`make[1]: Entering directory '/home/peter/go/src/github.com/evilsocket/opensnitch/proto'
python3 -m grpc_tools.protoc -I. --python_out=../ui/opensnitch/ --grpc_python_out=../ui/opensnitch/ ui.proto
make[1]: Leaving directory '/home/peter/go/src/github.com/evilsocket/opensnitch/proto'
make[1]: Entering directory '/home/peter/go/src/github.com/evilsocket/opensnitch/daemon'
# github.com/evilsocket/opensnitch/daemon/netfilter
In file included from ./queue.h:5:0,
                 from netfilter/queue.go:8:
/usr/include/stdlib.h:720:11: fatal error: bits/stdlib-bsearch.h: No such file or directory
 # include <bits/stdlib-bsearch.h>
           ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:13: opensnitchd] Error 2
make[1]: Leaving directory '/home/peter/go/src/github.com/evilsocket/opensnitch/daemon'
make: *** [Makefile:11: daemon/opensnitchd] Error 2
`

**Comment by gustavo-iniguez-goya** [comment]
`stdlib-bsearch.h` is part of the `libc6-dev` package, on Debian based systems at least. Double check that you have it installed.

This problem could also arise if you were compiling the daemon for other architecture, arm for example. Reopen the issue if the problem still occurs please.
