### ISSUE TITLE
Other firewalls

### ISSUE THREAD

**Issue by BillDietrich** [evilsocket/opensnitch#220]
Sorry, I haven't installed yet, and I'm a n00b too, but I see no mention of other firewalls.  I assume opensnitch can't be used if the system is using an existing set of rules in iptables or the new nftables ?  Which might be managed through ufw of gufw or other apps.  Or are there cases where both opensnitch and one of the others can be used ?  Please discuss in the Readme file.  Thanks.

**Comment by erenseymen** [comment]
Using with ufw. No issues.

**Comment by gustavo-iniguez-goya** [comment]
Correct, it should play nice with other firewalls.

**Comment by BillDietrich** [comment]
Again, the issue mostly was about documenting this in the README, right up front.
