### ISSUE TITLE
minor Makefile trouble

### ISSUE THREAD

**Issue by Herve5** [evilsocket/opensnitch#221]
Hello,
On Ubuntu 18, Go version 1.10.4, when following the install script I get
(...)
go get -u github.com/golang/dep/cmd/dep
(...)
make
(...)
make[1] : entering « /home/herve5/go/src/github.com/evilsocket/opensnitch/daemon »
make[1]: dep: Command not found
Makefile:10: recipe for target 'deps' failed
make[1]: *** [deps] Error 127

As the go get command didn't return errors for dep, I don't know what to do?

TIA!
Hervé

**Comment by TheRealAgentK** [comment]
Pretty much been getting the same when running make:

`make[1]: Entering directory '/home/kai/development/go/src/github.com/evilsocket/opensnitch/proto'
python3 -m grpc_tools.protoc -I. --python_out=../ui/opensnitch/ --grpc_python_out=../ui/opensnitch/ ui.proto
make[1]: Leaving directory '/home/kai/development/go/src/github.com/evilsocket/opensnitch/proto'
make[1]: Entering directory '/home/kai/development/go/src/github.com/evilsocket/opensnitch/daemon'
make[1]: dep: Command not found
Makefile:10: recipe for target 'deps' failed
make[1]: *** [deps] Error 127
make[1]: Leaving directory '/home/kai/development/go/src/github.com/evilsocket/opensnitch/daemon'
Makefile:11: recipe for target 'daemon/opensnitchd' failed
make: *** [daemon/opensnitchd] Error 2
`

**Comment by TheRealAgentK** [comment]
Was able to get over this hurdle by actually making sure that GOPATH/bin is in the PATH.

**Comment by gustavo-iniguez-goya** [comment]
This issue is solved (and old). The compilation instructions have been updated here: https://github.com/gustavo-iniguez-goya/opensnitch/wiki/Compilation
