### ISSUE TITLE
BPF / eBPF support?

### ISSUE THREAD

**Issue by jkozera** [evilsocket/opensnitch#222]
As far as I understand the [eBPF firewall](http://www.brendangregg.com/ebpf.html), the [`bpf_get_current_pid_tgid`](https://github.com/iovisor/bcc/blob/master/docs/reference_guide.md#4-bpf_get_current_pid_tgid) function from there, would allow getting a process id for a connection, without resorting to the [inode resolving hacks](https://github.com/evilsocket/opensnitch/blob/d325c85f24934608a5c20ace67b2026aeac1baf1/daemon/procmon/parse.go#L12-L34).

Would you be interested in seeing support for this feature implemented, @evilsocket?

I realise it wouldn't work with Linux < 4.2, but it could be optional, and we could keep support for `iptables` for pre-4.2 kernels.

I think it'd help with the stability issues from #171 since I suspect those are caused by some race conditions causing the `pid` to be unavailable. (I've checked earlier today, and even after adding the IPv6 support at https://github.com/jkozera/opensnitch/commit/b5135bd5cdcd5db0d2a0fd161eca6ac2c695df6b, some UDP / IPv4 packages tend to be unnoticed by OpenSnitch.)

**Comment by jkozera** [comment]
FWIW, I've roughly implemented the idea at https://github.com/jkozera/opensnitch/commit/05fb1349332b86215653c87651cbc88fcd519f21 (+ some other changes related to #171, for instance allowing to drop unknown pids, at https://github.com/jkozera/opensnitch/commit/5f5a6f09ad99a5e75b1acdb7fe2d15281b0ee487)

**Comment by p-** [comment]
@jkozera 
I don't know if compatibility with that old kernels is necessary. Ubuntu 16.04 came with 4.4, and even Red Hat seem to have [backported eBPF to Red Hat 7.6](https://twitter.com/brendangregg/status/1033021706997297153?lang=de) (which uses a 3.10 something Kernel). I would guess that most users of OpenSnitch probably use a more recent kernel.

**Comment by p-** [comment]
@jkozera
What I actually want to like even more (than the list operator) are the eBPF commits in your repo.
Because I think going down the eBPF road seems like a great idea for better reliability.

**Comment by p-** [comment]
Hi @jkozera 
I tried your eBPF commits and on the first glimpse OpenSnitch seems snappier!

(It's just not that easy to build anymore. E.g. I had problems making the changes in the other commit surrounding`queue.h`).

But eBPF seems to be the way to go.

**Comment by p-** [comment]
If anyone is interested:
I created a small eBPF prototype in Go called [socket-connect-bpf](https://github.com/p-/socket-connect-bpf) with a kernel probe attached to `security_socket_connect,` so that no connection should be missed.

Maybe somebody wants to experiment with it as a new base for Opensnitch...

**Comment by gustavo-iniguez-goya** [comment]
that looks awesome @p- , thank you for sharing! would be nice if it would be merged, or if anyone would be willing to work on a common branch to keep fixing issues.

**Comment by gustavo-iniguez-goya** [comment]
done! https://github.com/evilsocket/opensnitch/commit/9497cf8394a6afb179fd0303a9b046d6259191d5
