### ISSUE TITLE
Size scale issue, really big buttons/windows

### ISSUE THREAD

**Issue by B4rabbas** [evilsocket/opensnitch#226]
Hello,
I've builded open snitch today but it's very unusable like this, see the attachement for better comprehension.

Cheers.

B
![screenshot openshot](https://user-images.githubusercontent.com/36156012/49332764-4461a080-f5b3-11e8-9fba-09aa4c39da72.png)
![statistics](https://user-images.githubusercontent.com/36156012/49332771-6eb35e00-f5b3-11e8-8106-99345fe97ee8.png)

**Comment by Duckseazon** [comment]
Hi,

Same issue here on Debian 9.6 with Cinnamon 3.2.7 installed. Opensnitch can be used but it is difficult and not straightforward.

Thanks

**Comment by Duckseazon** [comment]
Where are you changing this setting? I tried to add this to ~/.opensnitch/ui-config.json but nothing changed.
Thank you for your help

**Comment by MatteoManzoni** [comment]
I modify the python command that launch the UI. Mine was under /usr/bin/

**Comment by Duckseazon** [comment]
Thanks a lot, it worked! Mine was located here /usr/local/bin.

**Comment by alexschomb** [comment]
Thanks, this helped on Manjaro KDE as well. I modified the line to look like this:
```
os.environ["QT_AUTO_SCREEN_SCALE_FACTOR"] = "0"
```

Unfortunately this has to be redone after each update.

**Comment by gustavo-iniguez-goya** [comment]
I think this is fixed with latest version. Feel free to reopen it if it still occurs.
