### ISSUE TITLE
Daemon killed/restarts periodically

### ISSUE THREAD

**Issue by datio** [evilsocket/opensnitch#228]
It happens every few seconds/minutes on Ubuntu 16.04

![screenshot from 2018-12-10 15-10-56](https://user-images.githubusercontent.com/15472/49734742-fc670b80-fc8d-11e8-9c68-0736e68f07aa.png)

```Error while parsing address to int: strconv.ParseInt: parsing "other address": value out of range```

**Comment by Fmajor** [comment]
same error on Gentoo...

**Comment by Lockdis** [comment]
sorry but what's the tool used for logs? @datio 

thanks

**Comment by datio** [comment]
@Lockdis try ```tail -f /var/log/opensnitchd.log```
