### ISSUE TITLE
Python grpcio requirement is old

### ISSUE THREAD

**Issue by rjzak** [evilsocket/opensnitch#230]
Is this required: `grpcio==1.0.0`?
It conflicts with TensorFlow: `tensorflow 1.8.0 has requirement grpcio>=1.8.6, but you'll have grpcio 1.0.0 which is incompatible.` Why require old software?

**Comment by cwh1te** [comment]
Why require old software?
There are a whole lot of possible reasons, to the point that the question almost seems facetious.

Why not use virtualenv to manage different projects you want to use which feature different dependencies?
If you want to use 1.8.0, go for it! If you wanna be extra awesome, submit a PR when you've worked out all the bugs that may be introduced by doing that.

Please note that I'm not associated with this project, just a long time watcher offering my opinion. Sorry in advance if it isn't wanted. :)

**Comment by gustavo-iniguez-goya** [comment]
We should be compatible from 1.10.0 on. I think this is not a problem anymore, but feel free to reopen it is.
