### ISSUE TITLE
Protection dependant on opensnitchd?

### ISSUE THREAD

**Issue by Teuwu** [evilsocket/opensnitch#232]
Just a question.
I've noticed that the opensnitchd, restarts a lot or shutdowns for some time, and then starts back up again at a later time. In the times where it is not running, does the "wall" in firewall go down in those times as well? As in the rules are only enforced while the daemon is running?

**Comment by Teuwu** [comment]
I did some testing, and it does seem to be the case, when the daemon is down, its a free for all when it is up opensnitchd does its thing.

**Comment by cwh1te** [comment]
I hope policy persistence without the daemon will possible in/after alpha. Maybe this could be part of a future milestone?

**Comment by gustavo-iniguez-goya** [comment]
If the daemon exits unexpectedly for any reason, the firewall rules won't be deleted. Right now the default action in such case is to allow all (new) traffic. Otherwise you'd block all (new) traffic.
