### ISSUE TITLE
Anything other than General tab of the UI is empty

### ISSUE THREAD

**Issue by avin3sh** [evilsocket/opensnitch#233]
I am on `Ubuntu 18.04`  and have followed the installation instruction and everything works except that the UI doesn't list anything other than whats being shown in "General" tab.

This is what the General tab looks like,
![general_tab](https://user-images.githubusercontent.com/3116732/50434626-fca90d00-0903-11e9-8d1c-2d00d7d68195.png)

But at the same time all other tabs, including, for example, Processes is blank,
![process_tab](https://user-images.githubusercontent.com/3116732/50434666-26faca80-0904-11e9-897d-84f933ee3007.png)

Running the `opensnitch-ui` from CLI throws the following error repeatedly while the UI is still running,
```

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/opensnitch/dialogs/stats.py", line 205, in _on_update_triggered
    pw_name = pwd.getpwall(int(uid)).pw_name
TypeError: getpwall() takes no arguments (1 given)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/opensnitch/dialogs/stats.py", line 209, in _on_update_triggered
    by_users["%s (%s)" % (pw_name, uid)] = hits
UnboundLocalError: local variable 'pw_name' referenced before assignment

```

**Comment by gustavo-iniguez-goya** [comment]
This should be fixed with latest version.
