### ISSUE TITLE
[Feature Request] AppImage

### ISSUE THREAD

**Issue by zero77** [evilsocket/opensnitch#237]
Can you please provide an AppImage, this is basically just a standalone portable executable for linux, that doesn't require installation.
Thanks

There are different ways to create AppImages:

    Use Open Build Service (OBS)
    Convert existing binary packages (.deb, .rpm, …)
    Bundling your Travis CI builds as AppImages
    Run linuxdeployqt on your Qt application
    Using electron-builder for Electron-based apps
    Create an AppDir manually

Documentation:
https://docs.appimage.org/packaging-guide/ways.html
https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages

**Comment by Herve5** [comment]
I strongly second this, being myself unable to actually gather all the required details for compiling it on Linux (I don't have the right Go version and don't know Go, etc.)
I understand and appreciate Simone is a single person doing an enormous lot of work, so I presume if someone else could prepare the AppImage for him it'd be even better -but I am still uncompetent, for this too :(
Hervé

**Comment by rjzak** [comment]
The daemon process requires installation, since it runs in the background is controlled by `systemd.` I think only the control GUI could be made into an AppImage.

**Comment by zero77** [comment]
I think the best solution is.
> Bundling your Travis CI builds as AppImages

But i haven't had a look yet.

**Comment by Khoramyar** [comment]
Any plans for a .deb package? If we get that it would be great for adaptation and usage.

**Comment by jeremiah** [comment]
Personally I'd prefer flatpak or a deb. I'll look into providing one or the other.

**Comment by tuqueque** [comment]
Anything but the current cumbersome way of installing (building) Opensnitch today... I'd go for Flatpak instead of .deb or even Snap. Flatpak is the most distro-agnostic of them all and really easy to use.

**Comment by dCo3lh0** [comment]
some applications have 2 releases of AppImages exactly because of this, one for the daemon the CLI version and another for the GUI, a single example of that is Retroshare. They call the server version i think.. and the GUI, I think this could work... Of course Flatpaks and debs would be cool too...

**Comment by karam72** [comment]
Both Flatpak and appImage are great!

**Comment by jeremiah** [comment]
I think the best approach, for now at least, is to either build from source or use the provided debs. Once various distributions catch up to the version of libc being used then you'll be able to address packages for a large installed base, like Ubuntu and Debian users, as long as they're using up to date versions of the same. The lack of a newer libc in Debian and in Debian derived OSes is a block for me for building upstream debs. More info in this issue: https://github.com/evilsocket/opensnitch/issues/494

**Comment by gustavo-iniguez-goya** [comment]
do you mean libc 2.32/33 versions?

**Comment by jeremiah** [comment]
Yes. Currently Debian GNU/Linux 11 (bullseye) has version 2.31-13+deb11u2 of the GNU standard C library. While I haven't checked the symbols like `GLIBC_2.32 pthread_sigmask`, I assume that feature is not in the bullseye version of Debian.

The next stable version of Debian, Debian GNU/Linux bookworm/sid, or just "bookworm" or "testing" already has 2.33-7 for it's libc library. This should make it easier to push the source code of opensnitch upstream into Debian and maintain it there. This allows for opensnitch to flow downstream into Debian derivatives like Ubuntu.

**Comment by gustavo-iniguez-goya** [comment]
Try compiling with Go 1.15, it doesn't require 2.32/33 libs. Newer versions depends on  pthread_sigmask() which is only available on libc >= 2.32.

**Comment by jeremiah** [comment]
Oh, I didn't realize that. I will try with Go 1.15.

**Comment by RangerMauve** [comment]
This'd be great to have for immutable OSs like SteamOS on the SteamDeck (and similar)

**Comment by Twig6943** [comment]
Why was this closed all of a sudden? I don't know if this is possible but I think it should be looked into. A community I can recommend that knows a lot about packaging is [PkgForge](https://github.com/pkgforge-community)

**Comment by shuvashish76** [comment]
Duplicate open issue #1510

**Comment by dCo3lh0** [comment]
just sharing that pkgforge team has builded a unofficial version of OpenSnitch in the appimage package format, if someone wants, just be sure of one thing, its unofficial, therefore it can have (or not) bugs and issues not found on official version and you must know what to report to who...

https://github.com/pkgforge-dev/OpenSnitch-AppImage
