### ISSUE TITLE
rules and logs manpage

### ISSUE THREAD

**Issue by in1t3r** [evilsocket/opensnitch#24]
opensnitch by default do not use iptables to setup rules but only /root/opensnitch.db for storing the rules.
That makes it works fine with other firewall software but also make rules harder to be read its not to hard they can be read with sqlitebrowser but also there is no manpage so for example verdict is not defined is for every single app whitelisted or not allowed once or forever 0. 
Can you please provide at least simple manpage so that we know what we can tweak with which effect?
Also running X apps with root privileges is dangerous.

**Comment by ei8fdb** [comment]
I'm happy to help with manpage if someone can work with me to understand all of Opensnitch's functionality.
