### ISSUE TITLE
apt install go-dep needed for dependencies

### ISSUE THREAD

**Issue by hook-s3c** [evilsocket/opensnitch#246]
as titled, ubuntu 18.04

**Comment by yan-foto** [comment]
If you've already installed `dep` (as mentioned in [**tl;dr**](https://github.com/evilsocket/opensnitch/blob/master/README.md#tldr)), it's enough to have go's bin dir on your `$PATH`:

```
export PATH=$PATH:$GOPATH/bin
```

**Comment by gustavo-iniguez-goya** [comment]
closing, it was already answered
