### ISSUE TITLE
 opensnitch gui import error no module named xy

### ISSUE THREAD

**Issue by testuser369** [evilsocket/opensnitch#250]
huge thanks 4 this project, insane work so far... i will need time to get into the code
like more than months but i hope we can cooperate, im planing a few projects and would like to contribute code over time :)

looks like a half perfect tesla tower i really like what you provide

using apt install go-lang go-dep -y - // Add to Install guide if correct

tried by changing import to opensnitch.xy 
also  sudo apt-get install python-dev and sudo ln -s /usr/include/python2.7 /usr/local/include/python2.7
refering to https://github.com/evilsocket/opensnitch/issues/134

root@kali:~/go/src/github.com/evilsocket/opensnitch# opensnitch-ui
Traceback (most recent call last):
  File "/usr/local/bin/opensnitch-ui", line 3, in <module>
    from PyQt5 import QtWidgets, QtGui, QtCore
ModuleNotFoundError: No module named 'PyQt5'

user@mint:~/go/src/github.com/evilsocket/opensnitch/ui$ sudo opensnitch-ui
[sudo] password for user:               
Traceback (most recent call last):
  File "/usr/local/bin/opensnitch-ui", line 18, in <module>
    from opensnitch.service import UIService
  File "/usr/local/lib/python3.6/dist-packages/opensnitch/service.py", line 16, in <module>
    import ui_pb2
ModuleNotFoundError: No module named 'ui_pb2'

maybe its related to this impact:

~/go/src/github.com/evilsocket/opensnitch/ui sudo pip3 install -r requirements.txt
The directory '/home/user/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/user/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag

using no sudo result in:

Building wheels for collected packages: grpcio, pyinotify, unicode-slugify, configparser, futures
  Running setup.py bdist_wheel for grpcio ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-psr4qnwp/grpcio/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmp89op5zdapip-wheel- --python-tag cp36:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for grpcio
  Running setup.py clean for grpcio
  Running setup.py bdist_wheel for pyinotify ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-psr4qnwp/pyinotify/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmp8ruvdeywpip-wheel- --python-tag cp36:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for pyinotify
  Running setup.py clean for pyinotify
  Running setup.py bdist_wheel for unicode-slugify ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-psr4qnwp/unicode-slugify/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmptwln0_l2pip-wheel- --python-tag cp36:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for unicode-slugify
  Running setup.py clean for unicode-slugify
  Running setup.py bdist_wheel for configparser ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-psr4qnwp/configparser/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpk5mxgigtpip-wheel- --python-tag cp36:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for configparser
  Running setup.py clean for configparser
  Running setup.py bdist_wheel for futures ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-psr4qnwp/futures/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpwbjeiv4dpip-wheel- --python-tag cp36:
  /tmp/pip-build-psr4qnwp/futures/setup.py:6: UserWarning: This backport is meant only for Python 2.
  Python 3 users do not need it, as the concurrent.futures package is available in the standard library.
    warn('This backport is meant only for Python 2.\n'
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for futures
  Running setup.py clean for futures
Failed to build grpcio pyinotify unicode-slugify configparser futures
Installing collected packages: six, enum34, futures, setuptools, protobuf, grpcio, grpcio-tools, pyinotify, unidecode, unicode-slugify, sip, pyqt5, configparser
  Running setup.py install for futures ... done
  Running setup.py install for grpcio ... done
  Running setup.py install for pyinotify ... done
  Running setup.py install for unicode-slugify ... done
  Running setup.py install for configparser ... done
Successfully installed configparser-3.5.0 enum34-1.1.6 futures-3.1.1 grpcio-1.0.0 grpcio-tools-1.10.1 protobuf-3.7.1 pyinotify-0.9.6 pyqt5-5.10.1 setuptools-40.8.0 sip-4.19.8 six-1.12.0 unicode-slugify-0.1.3 unidecode-1.0.23

**Comment by gustavo-iniguez-goya** [comment]
closing as old and maybe not relevant anymore. I'm using the deb packages on kali and work perfect.
