### ISSUE TITLE
Cannot install opensnitch on PureOS

### ISSUE THREAD

**Issue by sorcer1122** [evilsocket/opensnitch#251]
Hello,

I am getting the following error while install on PureOS (debian based):

root@john:~/go/src/github.com/evilsocket/opensnitch# make
make[1]: Entering directory '/root/go/src/github.com/evilsocket/opensnitch/proto'
python3 -m grpc_tools.protoc -I. --python_out=../ui/opensnitch/ --grpc_python_out=../ui/opensnitch/ ui.proto
make[1]: Leaving directory '/root/go/src/github.com/evilsocket/opensnitch/proto'
make[1]: Entering directory '/root/go/src/github.com/evilsocket/opensnitch/daemon'
# crypto/rc4
/usr/local/go/src/crypto/rc4/rc4_asm.go:15:18: (*Cipher).XORKeyStream redeclared in this block
	previous declaration at /usr/local/go/src/crypto/rc4/rc4.go:61:6
# bytes
/usr/local/go/src/bytes/bytes_decl.go:10:6: IndexByte redeclared in this block
	previous declaration at /usr/local/go/src/bytes/bytes.go:101:34
/usr/local/go/src/bytes/bytes_decl.go:17:6: Equal redeclared in this block
	previous declaration at /usr/local/go/src/bytes/bytes.go:18:25
/usr/local/go/src/bytes/bytes_decl.go:24:6: Compare redeclared in this block
	previous declaration at /usr/local/go/src/bytes/bytes.go:37:27
# strings
/usr/local/go/src/strings/strings_decl.go:8:6: IndexByte redeclared in this block
	previous declaration at /usr/local/go/src/strings/strings.go:150:34
# crypto/cipher
/usr/local/go/src/crypto/cipher/xor_amd64.go:9:6: xorBytes redeclared in this block
	previous declaration at /usr/local/go/src/crypto/cipher/xor.go:58:33
/usr/local/go/src/crypto/cipher/xor_amd64.go:22:6: xorWords redeclared in this block
	previous declaration at /usr/local/go/src/crypto/cipher/xor.go:83:27
make[1]: *** [Makefile:13: opensnitchd] Error 2
make[1]: Leaving directory '/root/go/src/github.com/evilsocket/opensnitch/daemon'
make: *** [Makefile:11: daemon/opensnitchd] Error 2
root@john:~/go/src/github.com/evilsocket/opensnitch# 

Any idea how to fix it?

**Comment by jonathanvlan** [comment]
There is a theme about pure os / https://tracker.pureos.net/T327
The functional package, for x64 Architecture / https://sourceforge.net/projects/unknownos/files/opensnitch/

**Comment by sorcer1122** [comment]
Thanks, it kind of works, however opensnitch-ui does not start up, without giving any errors. Any ideas where to dig?

**Comment by jonathanvlan** [comment]
aahh
for the gnome-shell desktop it is necessary to create its shell extension icon,
I forgot it,

How to start
open terminal
sudo opensnitch-ui

I will be working on the gnome-shell extension and update the package for the 
apparmor and firejail profiles .

**Comment by sorcer1122** [comment]
> How to start
> open terminal
> sudo opensnitch-ui

As I wrote in my previous message, it does not work. It looks as if the command is being executed but nothing pops up. Patiently waiting for gnome-shell, thanks a lot for your work!

**Comment by sorcer1122** [comment]
Just wonder if anybody can help with this? When executing sudo opensnitch-ui I get:

QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
No protocol specified
qt.qpa.screen: QXcbConnection: Could not connect to display :0
Could not connect to any X display.

**Comment by gustavo-iniguez-goya** [comment]
Hi @sorcer1122 

You don't need to run the GUI as root. Launch it as regular user.

Regarding the gnome-shell icon, you need to install this extension:
https://github.com/gustavo-iniguez-goya/opensnitch/wiki/Known-problems#OpenSnitch-icon-does-not-show-up-on-gnome-shell

And use latest packages from the releases section, they should work Debian based distributions like PureOS:
https://github.com/evilsocket/opensnitch/releases

**Comment by gustavo-iniguez-goya** [comment]
Confirmed, latest deb packages work on PureOS.
