### ISSUE TITLE
The https://www.opensnitch.io/ website is unavailable

### ISSUE THREAD

**Issue by da2x** [evilsocket/opensnitch#253]
The https://www.opensnitch.io/ website is unavailable

**Comment by rradar** [comment]
That's true. I get a

> DNS_PROBE_FINISHED_NXDOMAIN

**Comment by j-degreef** [comment]
+1

**Comment by evilsocket** [comment]
yes, the domain expired and i did not renew it.

**Comment by armaanhammer** [comment]
Was the domain of any importance? Or was it just a front end for this repo?
