### ISSUE TITLE
default timeouts of 30 seconds or more are not respected 

### ISSUE THREAD

**Issue by p-** [evilsocket/opensnitch#255]
If a user specifies a `default_timeout` of 30 seconds or more it is not respected by the OpenSnitch daemon.

What happens instead:
The GRPC client reaches it's deadline of 30 seconds as defined [on this line](https://github.com/evilsocket/opensnitch/blob/61cf3d1e0852d41be08c9293bb0ae753471a91f5/daemon/ui/client.go#L151) and then uses its "allow once" [clientErrorRule](https://github.com/evilsocket/opensnitch/blob/61cf3d1e0852d41be08c9293bb0ae753471a91f5/daemon/ui/client.go#L24).
Additionally, following text is written to the log:

    Error while asking for rule: rpc error: code = DeadlineExceeded desc = context deadline exceeded

Meanwhile, [the UI is still counting down](https://www.youtube.com/watch?v=wXJueORvMAA).

Some questions:
- What would be the best solution to solve this?
- Should the daemon also load the client-config?
- What are the side-effects of setting a large number as GRPC deadline?
- Should the UI reject `default_timeout` values that are above a certain value?

**Comment by gustavo-iniguez-goya** [comment]
finally we've fixed this issue. Now the GUI doesn't block the daemon, it applies the default action while waiting for a user response.
