### ISSUE TITLE
[Feature Request] Easy way to see what connections a user has open in the UI

### ISSUE THREAD

**Issue by FruityWelsh** [evilsocket/opensnitch#258]
It would be sweet to be able to see what procs are open by a specific user in the user tab (IE a drop down or something). Love this utility so far though, just would make digging down easier! A tangental request would be to be able to see the user in the gerneral tab as well.

**Comment by gustavo-iniguez-goya** [comment]
With latest packages you can view the connections a user has opened. It's not exactly what you requested, but maybe it's out of the scope of this app.

Check it out, and close the issue if it's enough for you.
