### ISSUE TITLE
missing dep: python-gtk2

### ISSUE THREAD

**Issue by trqx** [evilsocket/opensnitch#26]
Hi,

Here is a missing dep (at least for latest ubuntu): python-gtk2.
I'm a bit surprised since python-qt4 is listed in the deps.

**Comment by ChlorideCull** [comment]
I'd argue the dependency for GTK2 could probably be removed, considering [this is the only place it's used](/evilsocket/opensnitch/blob/81429d0e8ab889927c600b0e486d0024185ecebd/opensnitch/ui.py#L85). It's kinda odd to pull in all of GTK2 for the sake of finding the path to an icon.
