### ISSUE TITLE
The prompt dialog countdown accelerates as connections are enqueued to be allowed/denied

### ISSUE THREAD

**Issue by gustavo-iniguez-goya** [evilsocket/opensnitch#273]
When a new connection goes out and opensnitch opens the dialog to allow or deny it, as new connections are enqueued the countdown of the displayed dialog accelerates.

Example:
https://imgur.com/a/WJWjdLX

As far as I can tell, the problem might be that thread which handles the (tick) countdown is still running when a new dialog is launched, so the new one starts counting down. It should wait to exit:
prompt.py:
```
         with self._lock:
             # reset state
             self._tick = self._cfg.default_timeout
+            if self._tick_thread != None:
+                self._tick_thread.join()
```

**Comment by Khoramyar** [comment]
Thank you! This was driving me crazy...
