### ISSUE TITLE
Error while enabling probe descriptor for opensnitch_exec_probe: write /sys/kernel/debug/tracing/kprobe_events: no such file or directory

### ISSUE THREAD

**Issue by squalou** [evilsocket/opensnitch#276]
Hi,

I've read similar issues #214 #235 for instances, but none of which breing any solution.

I'm running a 4.19 LTS kernel.

Compilation works fine, but I can't start the daemon.

```
[2019-08-08 11:51:14]  IMP  Starting opensnitch-daemon v1.0.0b
[2019-08-08 11:51:14]  !!!  Error while enabling probe descriptor for opensnitch_exec_probe: write /sys/kernel/debug/tracing/kprobe_events: no such file or directory
```

I'm runing Arch, these files *do* exist, debugs is mounted, Secure Boot is OFF in bios (was a suggestion in another issue)

Will gladly help track this down if I can,

regards

**Comment by squalou** [comment]
Hi, just to mention that the issue persists.

I've seen other arch users starting the daemon successfully so there's probably something missing on my system ... no idea what.

**Comment by gustavo-iniguez-goya** [comment]
In that scenario, we should probably fallback to parse /proc

Can you post the output of "mount | grep debugfs" command? I've checked it in Suse(>=11), Debian (>=8), Ubuntu (>=13), Fedora (>=21), RHEL (>=7) and CentOS (>=7.0) and debugfs is on in all of them.

**Comment by squalou** [comment]
hi

```$ mount | grep debugfs 
debugfs on /sys/kernel/debug type debugfs (rw,nosuid,nodev,noexec,relatime)
```

**Comment by gustavo-iniguez-goya** [comment]
compile this branch and see if it works on your system please:
https://github.com/gustavo-iniguez-goya/opensnitch/tree/main

**Comment by squalou** [comment]
I tried,
it's promising indeed : daemon starts, no errors !


I managed to run an old UI I still had installed, and had issues with unresponsive buttons.

... so I tried to build / instll clean this branch, 
(using a virtualenv and not sudo pip install, see other issue about this)

below step never ended :

.... Building wheels for collected packages: grpcio-tools
  Building wheel for grpcio-tools (setup.py) ...

**Comment by gustavo-iniguez-goya** [comment]
good news! :)

**Comment by gustavo-iniguez-goya** [comment]
Fixed with latest version.
