### ISSUE TITLE
How to uninstall ?

### ISSUE THREAD

**Issue by skaox** [evilsocket/opensnitch#278]
Hi,
simple question how to uninstall ?
Thank you in advance

**Comment by gustavo-iniguez-goya** [comment]
Hi skaox,

Reverse the installation steps https://github.com/evilsocket/opensnitch/blob/master/daemon/Makefile: 
```
        systemctl stop opensnitchd
	rm -rf /etc/opensnitchd/
	rm /usr/local/bin/opensnitchd
	rm /etc/systemd/system/opensnitchd.service
        pip3 uninstall opensnitch-ui
        rm -rf ~/.opensnitch/
```

**Comment by gustavo-iniguez-goya** [comment]
Following the above instructions should solve this issue.
