### ISSUE TITLE
Feature Request: Make new rules default to list operator including process.path

### ISSUE THREAD

**Issue by medains** [evilsocket/opensnitch#279]
If I'm reading the golang code correctly, it supports the use of an operator type "list" - but there is no example in the README of that.

I think that it would be something like
```json
{
  "created": "2019-08-29T08:08:04.998109722+01:00",
  "updated": "2019-08-29T08:08:04.998151386+01:00",
  "name": "allow-firefox-80",
  "enabled": true,
  "action": "allow",
  "duration": "always",
  "operator": {
    "type": "list",
    "operand": "ignored",
    "data": "ignored",
    "list": [
      { "type": "simple", "operand": "dest.port", "data": "80", "list": [] },
      { "type": "simple", "operand": "process.path", "data": "/usr/lib/firefox/firefox", "list": [] }
    ]
  }
}
```

This feels like it should be the default setting (process and port)

**Comment by p-** [comment]
Here is an example of the List Operator #231 

> This feels like it should be the default setting (process and port)

Agreed, I think most (if not all) rules should be in combination with a process.path.

**Comment by medains** [comment]
Updated to a feature request for the new rules defaulting to include process.path

**Comment by gustavo-iniguez-goya** [comment]
Latest version allows to personalize pop-ups options :+1:
