### ISSUE TITLE
Add instructions for priority of rules

### ISSUE THREAD

**Issue by medains** [evilsocket/opensnitch#280]
Each connection will be filtered by one rule - the first match - it seems that the order of rules is based off the name of the rule.

So for example, if I had the following rules
* Block some advertising domain
* Allow port 80

If the port 80 rule had a name that sorted earlier than the blocking rule, then it would still permit http requests to the domain.

I can't be sure whether its the rule name or the filename of the rule that controls that ordering.

**Comment by vyachkonovalov** [comment]
Looks like rules order is based on filename order. I had to rename deny-any-google-analytics.json to 001-deny-any-google-analytics.json for it to take presedence over allow-simple-usrlibfirefox-developer-editionfirefox.json

**Comment by gustavo-iniguez-goya** [comment]
Hi!

With latest version you can prioritize rules as follow:
- name the rule in alphabetical order.
- check [x] Priority in the rules editor.

**Comment by gustavo-iniguez-goya** [comment]
https://github.com/gustavo-iniguez-goya/opensnitch/wiki/Rules
