### ISSUE TITLE
iptables rules not deleted if the daemon dies/exits with error

### ISSUE THREAD

**Issue by gustavo-iniguez-goya** [evilsocket/opensnitch#281]
If the daemon exits due to an unexpected reason (segfault, etc), the iptables rules are not deleted. 
When it starts again, the iptables rules are added without deleting the existing ones:

> Chain OUTPUT (policy ACCEPT 0 packets, 0 bytes)
>  pkts bytes target     prot opt in     out     source               destination         
>  6621  439K NFQUEUE    all  --  *      *       0.0.0.0/0            0.0.0.0/0            ctstate NEW NFQUEUE num 0 bypass
>     0     0 NFQUEUE    all  --  *      *       0.0.0.0/0            0.0.0.0/0            ctstate NEW NFQUEUE num 0 bypass

> Chain OUTPUT (policy ACCEPT 0 packets, 0 bytes)
>  pkts bytes target     prot opt in     out     source               destination         
>     0     0 DROP       all  --  *      *       0.0.0.0/0            0.0.0.0/0            mark match 0x18ba5
>     0     0 DROP       all  --  *      *       0.0.0.0/0            0.0.0.0/0            mark match 0x18ba5

**Comment by Ph0rkoz** [comment]
Would be cool if we could pull all your requests from 1 repo somewhere. This hasn't been updated in months.

**Comment by gustavo-iniguez-goya** [comment]
I have a local "main" branch with all the PRs merged. I'll test it all again and publish it to github.

**Comment by Ph0rkoz** [comment]
Yes please because some of the edits didn't work. Also the go files have hardcoded pulls to this main branch inside which I had to manually edit before it was actually using your code and not original.
