### ISSUE TITLE
Does OpenSnitch manage only the outcoming connections ?

### ISSUE THREAD

**Issue by NRGLine4Sec** [evilsocket/opensnitch#283]
Does OpenSnitch manage only the outcoming connections?
I don't see any option to manage incoming connections too like GUFW does.

**Comment by p-** [comment]
Yes, OpenSnitch only handles outbound connections (as far it can catch them). See this Issue: #116

**Comment by NRGLine4Sec** [comment]
Good job @gustavo-iniguez-goya !
This will be a nice improvement !

**Comment by NRGLine4Sec** [comment]
Closed by #660
