### ISSUE TITLE
GUI is too big and can't be resized

### ISSUE THREAD

**Issue by Ph0rkoz** [evilsocket/opensnitch#285]
My gui has grown and there is no option to resize it.

see: https://imgur.com/a/5G1q8Vq

**Comment by onny** [comment]
Don't you think this might be a problem with your compositor/window manager? How did it get so big?

**Comment by heapwolf** [comment]
the dialogs take up about 50% of my screen, the main UI doesn't even fit on the screen.

**Comment by MarkoShiva** [comment]
Well I am pretty sure that gui can be reworked. @evilsocket 
Its not problem we can rewamp it better in pyside2.

**Comment by gustavo-iniguez-goya** [comment]
Fixed in latest packages. Open a new issue if it's still not displayed correctly.
