### ISSUE TITLE
GUI Fails to Launch

### ISSUE THREAD

**Issue by seonwoolee** [evilsocket/opensnitch#287]
I'm using Arch Linux and installed opensnitch through the AUR package. The `opensnitchd` daemon starts and runs just fine. Whenever an application tries to access the network, the notification window pops up

However, I cannot launch the ui that shows all the connections made. When I run `opensnitch-ui`, I get the following message
`Attribute Qt::AA_EnableHighDpiScaling must be set before QCoreApplication is created.`
and the terminal hangs there

**Comment by yochananmarqos** [comment]
@seonwoolee I've made a working [PKGBUILD](https://github.com/yochananmarqos/pkgbuilds/blob/master/opensnitch-git/PKGBUILD).

**Comment by seonwoolee** [comment]
I still get the same error with your PKGBUILD

**Comment by thomasmodeneis** [comment]
yep, having same issue after upgrading to ubuntu 19.10 (gcc 9.2.1, Python 3.7.5, pip 18.1)

**Comment by seonwoolee** [comment]
Don't know when it started working for me, but the AUR package is working for me now. Closing
