### ISSUE TITLE
high cpu usage while torrenting

### ISSUE THREAD

**Issue by erenseymen** [evilsocket/opensnitch#288]
opensnitch uses high cpu while qbittorrent running.

**Comment by gustavo-iniguez-goya** [comment]
Hi @erenseymen , try it out with latest packages (v1.2.0 or v1.3.0*) and let us know please.

**Comment by erenseymen** [comment]
Don't use it anymore. Sorry.

**Comment by gustavo-iniguez-goya** [comment]
ok, thank you!
