### ISSUE TITLE
GUI fails to launch on Debian 10

### ISSUE THREAD

**Issue by skjorrface** [evilsocket/opensnitch#293]
Hi, I installed both .deb packages opensnitch and python3-opensnitch-gui on debian 10 with python 3. During deb install pm also installed additional slugify-unicode and other packages, but when I try to launch opensnitch-ui via terminal this is what I get:

`Traceback (most recent call last):
  File "/usr/bin/opensnitch-ui", line 49, in <module>
    service = UIService(app, on_exit)
TypeError: __init__() missing 1 required positional argument: 'config'`

Any hint what I may be doing wrong here?

**Comment by gustavo-iniguez-goya** [comment]
Hello @skjorrface , if you installed the deb packages then you are using [this fork](https://github.com/gustavo-iniguez-goya/opensnitch). Report it there and close this one please.

**Comment by skjorrface** [comment]
Ok, thanks.
