### ISSUE TITLE
regex on process name?

### ISSUE THREAD

**Issue by picolens** [evilsocket/opensnitch#294]
Firstup. a hearty thank you to @evilsocket for building such a useful open sourcing tool. the linux community has needed this for a long time and you're a hero in my book

so...maybe this is obvious and it was missed reading the docs....but how does one make a rule for a process name that changes?

I'm having a big issue with `snapd`

```bash
:~$ ls -la /etc/opensnitchd/rules/
total 84
drwxr-xr-x 2 root root 4096 Feb 17 20:01 .
drwxr-xr-x 3 root root 4096 Sep 27 00:23 ..
-rw-r--r-- 1 root root  365 Oct 18 21:34 allow-simple-snapcore7917usrlibsnapdsnapd.json
-rw-r--r-- 1 root root  355 Nov  9 21:24 allow-simple-snapcore8039usrlibsnapdsnapd.json
-rw-r--r-- 1 root root  356 Oct 18 21:33 allow-simple-snapfirefox274firefox-bin.json
-rw-r--r-- 1 root root  329 Oct 28 21:09 allow-simple-usrbingnome-shell.json
-rw-r--r-- 1 root root  345 Oct 18 21:34 allow-simple-usrbingnome-software.json
-rw-r--r-- 1 root root  332 Oct 18 21:36 allow-simple-usrbinpython37.json
-rw-r--r-- 1 root root  329 Oct 26 15:44 allow-simple-usrbinruby25.json
```
notice how it's not called `snapd` but rather `snapcore7917usrlibsnapdsnapd` where 7917 is a random number that keeps changing.

As a result, the system continues to keep generating new pop-ups for api.snapcraft.io (or something like that), despite my efforts to say "accept this forever"

**Comment by gustavo-iniguez-goya** [comment]
It shouldn't be necessary a regex, just configure process.path to /usr/lib/snapd/snapd

In any case, try it with latest packages. I tested it several times and worked fine.
