### ISSUE TITLE
Loading filters into opensnitch

### ISSUE THREAD

**Issue by BullShark** [evilsocket/opensnitch#298]
How can I load these filters into opensnitch?

https://github.com/AdguardTeam/AdguardFilters

**Comment by gustavo-iniguez-goya** [comment]
I've been thinking lately in allow to load lists of suspicious IPs. 

I think we could use lists like these ones: https://iplists.firehol.org/

But instead of creating new opensnitch rules (which would penalize performance a lot), we would have a section in the Rules tab, and the lists would be loaded into the kernel directly. 

![Captura de pantalla de 2020-12-11 01-47-12](https://user-images.githubusercontent.com/2742953/101847149-d6152880-3b52-11eb-840a-295254170250.png)

**Comment by gustavo-iniguez-goya** [comment]
I'm testing this feature:

```
Loading blockfilter: /etc/opensnitchd/blocklists/domains/ads-and-tracking-extended.txt
domains loaded:  247650
Loading blockfilter: /etc/opensnitchd/blocklists/domains/adservers.txt
domains loaded:  341462
Loading blockfilter: /etc/opensnitchd/blocklists/domains/firstparty-trackers-hosts.txt
domains loaded:  397282
Loading blockfilter: /etc/opensnitchd/blocklists/domains/multiparty-trackers-hosts.txt
domains loaded:  408554
Loading blockfilter: /etc/opensnitchd/blocklists/domains/oisd.txt
domains loaded:  1351070
Loading blockfilter: /etc/opensnitchd/blocklists/domains/zzz-adaway-hosts.txt
domains loaded:  1351494

Total domains loaded:  1351494 Duplicated: 295552
```

some logs while running:
```
a.et.nytimes.com check took: 1.396µs
domain blocklisted:  a.et.nytimes.com 2
a.et.nytimes.com check took: 1.332µs
domain blocklisted:  a.et.nytimes.com 3
als-svc.nytimes.com check took: 1.44µs
domain blocklisted:  als-svc.nytimes.com 2
als-svc.nytimes.com check took: 1.296µs
domain blocklisted:  als-svc.nytimes.com 3
no: thumbor.forbes.com 1351494
no: thumbor.forbes.com 1351494
domain blocklisted:  geolocation.forbes.com 0
domain blocklisted:  geolocation.forbes.com 1
```

Pros: 
- It has almost no performance penalty in terms of speed
- checking a domain costs less than 2µs.

Cons:
- lists loaded on memory. 
- many applications are starting to use DoH, etc.

I think this approach is much better than creating app rules with [the ads script of the repository](https://github.com/evilsocket/opensnitch/blob/master/make_ads_rules.py).

Would be useful?

**Comment by NRGLine4Sec** [comment]
Yes it is useful, for example to block ads from Spotify.

Presently, I do it with some rules prefix by 000-deny-, but it could be definitively useful to do it with a list.

**Comment by gustavo-iniguez-goya** [comment]
Feature added, you can read more about it here: 
https://github.com/evilsocket/opensnitch/commit/26671ded24c80fbc4815a9e12e39ee8697a6b69a

basically create a new rule like described in the commit, create a directory where you want, and drop a list there:
```
$ mkdir ~/adslists/; cd ~/adslists/
$ wget https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt
```

You can combine these lists with other fields, for example to limit a program to connect only to a certain list of domains.

If you can build it from sources and test it would be useful. 

Also if you test it and have any extension to block ads using chrome/ium (uBlock origin or others), I'd interested to know if you see requests being blocked by opensnitch that in theory should be blocked by that extensions....

**Comment by gustavo-iniguez-goya** [comment]
All the instructions on how to use it have been added to the wiki: https://github.com/evilsocket/opensnitch/wiki/block-lists
