### ISSUE TITLE
default_timeout: null or default_timeout: 0 should disable the timeout

### ISSUE THREAD

**Issue by andykais** [evilsocket/opensnitch#299]
Hi there, I find that most of the time I dont ever want a timeout on opensnitch. Sometimes I want to do research on a process or ip before allowing it. For those times, I want the dialog to stay open until I feel confident in my rule selection. Could you pass through config so that setting default_timeout to `null` or `0` disables the timeout entirely? I could take a crack at this myself too if that is better.

Thank you for making this by the way! Fantastic program

**Comment by xenDE** [comment]
a way to stop the timer, if needed, would be great too.

**Comment by gustavo-iniguez-goya** [comment]
Done with latest packages. Also if you click on the + button, the timer is stopped.
