### ISSUE TITLE
Another init systems

### ISSUE THREAD

**Issue by LibreHacker** [evilsocket/opensnitch#300]
You can add support init systems like OpenRC and s6?

https://wiki.gentoo.org/wiki/OpenRC
https://www.skarnet.org/software/s6/

**Comment by dm17** [comment]
Is the only way I'd use it as well.

**Comment by xenDE** [comment]
better ask here: https://github.com/gustavo-iniguez-goya/opensnitch/

**Comment by gustavo-iniguez-goya** [comment]
It's being discussed here:
https://forum.artixlinux.org/index.php/topic,2011.0.html

Supporting s6 would allow us to run on OpenWRT and probably other systems.

**Comment by gustavo-iniguez-goya** [comment]
Some update on this request:
It seems that the AUR package should be splitted into several packages:
https://forum.artixlinux.org/index.php/topic,2011.msg13923.html

So  I guess we don't have to take any action from our side, and this issue can be closed, @LibreHacker ?

**Comment by gustavo-iniguez-goya** [comment]
@LibreHacker was this request finally added by artix devs?

**Comment by gustavo-iniguez-goya** [comment]
finally it was added.
