### ISSUE TITLE
add opensnitch to debian repo and create a ppa

### ISSUE THREAD

**Issue by freddii** [evilsocket/opensnitch#304]
It would be handy to have opensnitch in the default debian repo, so it can be installed with: apt install opensnitch

Are there any plans to bring opensnitch to debian?

Also a ppa at https://launchpad.net/ would be usefull.

**Comment by gustavo-iniguez-goya** [comment]
Hi @freddii !

There's an ITP ticket opened (_Intent To Package_), but there hasn' been activity since Feb 2019:
https://www.debian.org/devel/wnpp/being_packaged
`opensnitch: Port of the Little Snitch application firewall, 813 days in preparation, last activity 665 days ago.`

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=909567

Regarding the PPA, I created a repo at https://build.opensuse.org because you can create packages and repositories for RPM and DEB based distributions, for multiple architectures. I haven't worked on it since 4 months ago, but I'm planning to work on that direction.

**Comment by tianon** [comment]
@lamby an old ITP of yours is getting some attention :smile:

It looks like https://salsa.debian.org/lamby/pkg-opensnitch is where you left off, is that accurate?  Did you intend to continue (especially now that the project is active again :eyes: :heart: :exclamation:)?

**Comment by lamby** [comment]
That's probably where I left off, yes. I do not intend to continue, however. :+1:

**Comment by azispratama92** [comment]
https://www.cyberciti.biz/python-tutorials/opensnitch-the-little-snitch-application-like-firewall-tool-for-linux/ 

yep agreed, the PPA would be great, but thanks anyways =)

**Comment by cheako** [comment]
Just a note, projects should not contain a `debian` folder.  The only projects that should have this folder are Native Packages, opensnitch is not a good fit for this designation.

I don't have a usual recommendation for how to solve this, using a symlink(perhaps created/managed with a make target) and adding it to `.gitignore` seems like a good start.

**Comment by cheako** [comment]
Sorry, this needs an issue all it's own and it doesn't deserve one.  `.gitignore` for `rules` would exclude `debian/rules`, consider prefixing that with a `/` as I did in my example.  The ignore rules won't do anything for entries that already exist, they only prevent `git add` and `-a` flag of `git commit` from seeing things.

**Comment by petterreinholdtsen** [comment]
I had a look at this, and tried to build the latest version on Debian Bullseye.  If I understand the recipe on https://github.com/evilsocket/opensnitch/wiki/Compilation correctly, there are several build dependencies missing in Debian (indicated by the use of 'go install' and 'pip install'), and the fact that the ubuntu recipe do not involve calling 'debuild' to build packages.  These dependencies would have to be packaged first.

As I have stated in https://bugs.debian.org/909567 already, LI would be happy to assist if someone want to take on the task.

**Comment by petterreinholdtsen** [comment]
[Gustavo Iñiguez Goia]
> The missing Go dependencies for version 1.5.2 in Debian Bullseye are (as of today):
>
> github.com/google/nftables v0.0.0-20210514154851-a285acebcad3
> github.com/iovisor/gobpf v0.2.0
> github.com/evilsocket/ftrace v1.2.0

Aha.  I guess the best approach here is to get in touch with the golang
team in Debian to try to solicit help getting these into Debian.  Anyone
interested in doing this?  I expect them, as the rest of the free
software community, to be short on people and man-hours.

> `google.golang.org/grpc/cmd/protoc-gen-go-grpc` is also needed to
> compile the protobuffer.  It's packaged for Bookworm but not for
> Bullseye: https://packages.debian.org/bookworm/protoc-gen-go-grpc

Aha.  Good to know.  I can try again in my sid chroot with this package
in the dependencies.  I suspect it should be listed in debian/control.

> Latest stable version is v1.5.2. Could you try building it for v1.5.2?

I did, as I stated at the end of the message but it failed to build.
Now I suspect it is because of the missing dependencies, as I saw
something about nftables in the block of error messages I got.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by petterreinholdtsen** [comment]
[Gustavo Iñiguez Goia]
> The missing Go dependencies for version 1.5.2 in Debian Bullseye are
> (as of today):

These seem to be in Bookworm already.  I asked for them on the
#debian-golang IRC channel, and was told it was already in place.

> github.com/google/nftables v0.0.0-20210514154851-a285acebcad3

<URL: https://tracker.debian.org/pkg/golang-github-google-nftables >

> github.com/iovisor/gobpf v0.2.0

<URL: https://tracker.debian.org/pkg/golang-github-iovisor-gobpf >

> github.com/evilsocket/ftrace v1.2.0

<URL: https://tracker.debian.org/pkg/golang-github-evilsocket-ftrace >

So I guess the only missing piece of the puzzle is opensnitch itself.
Are you up for the task of maintaining it in Debian?

-- 
Happy hacking
Petter Reinholdtsen

**Comment by petterreinholdtsen** [comment]
[git70]
> But I don't know if you need to hurry?
> https://lists.debian.org/debian-devel-announce/2023/01/msg00004.html

Personally I believe it is too late to get it past the ftpmasters in NEW
before the package freeze, but would love to be proven wrong.  Every
second the initial upload is delayed reduces the changes, of course, but
not conviced they are good to begin with. :)

We are discussing the debian packaging on the #debian-golang IRC
channel.
-- 
Happy hacking
Petter Reinholdtsen

**Comment by petterreinholdtsen** [comment]
Thanks to the good work of Gustavo, the "unofficial" version 1.5.2.1-1
was just uploaded to Debian for approval by the ftpmasters (aka the NEW
queue).  This make it possible to get it into Debian before the package
freeze in less then a month, even thought it is quite unlikely it will
get through the queue in time.

<URL: https://ftp-master.debian.org/new.html > show 116 packages in the
queue.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by gustavo-iniguez-goya** [comment]
thank you VERY MUCH Petter for sponsoring opensnitch, and helping out with all the work with the debian package.
It'd have taken ages without your help.

**Comment by petterreinholdtsen** [comment]
The opensnitch package was just accepted into the Debian archive,
<URL: https://tracker.debian.org/pkg/opensnitch >.

Now the polishing should begin. :)

-- 
Happy hacking
Petter Reinholdtsen

**Comment by gustavo-iniguez-goya** [comment]
oh my! thank you very much @petterreinholdtsen !

**Comment by gustavo-iniguez-goya** [comment]
done :heavy_check_mark:

**Comment by petterreinholdtsen** [comment]
I would recommend spending some time on the Debian package maintenance and paying attention to https://tracker.debian.org/pkg/opensnitch .
