### ISSUE TITLE
pip3 upgrade needed when compiling from source

### ISSUE THREAD

**Issue by themighty1** [evilsocket/opensnitch#305]
I was following the compilation instructions from here
https://github.com/gustavo-iniguez-goya/opensnitch/wiki/Compilation
on a fresh most recent Bodhi Linux install and the compilation failed due to problems with pyqt.
Turns out pyqt requires a more recent version of pip3 than what is shipped by default on Ubuntu-based distros  (v9), so would be nice to include an extra step into the compilation instructions:

pip3 install --upgrade --user pip

This worked for me. I was able to finish the compilation without any errors.

**Comment by gustavo-iniguez-goya** [comment]
added!
