### ISSUE TITLE
"for this session" better wording.

### ISSUE THREAD

**Issue by themighty1** [evilsocket/opensnitch#307]
For many days I was under the impression that when in popup I select "for this session" that means "for this process's session" which in my mind means "until this instance of the process quits". 
It's only when I looked closely at the Rules tab that I realized that it means until system's restart.
I suggest that we rename it to "until restart" in the GUI.
Or better still "until reboot" because reboot is less ambiguous - it definitely means the whole machine.

**Comment by xenDE** [comment]
IMHO it's best to use wording from littlesnitch, because I use both.

**Comment by gustavo-iniguez-goya** [comment]
What do you think on using the github "forums" to talk about ideas, requests, general help (not issues), etc? This repo doesn't have it enabled, but I enabled it here: https://github.com/gustavo-iniguez-goya/opensnitch/discussions

**Comment by themighty1** [comment]
Nice, thanks, discussions is good in some cases.
This "better wording" issue is an enhancement, so it is best to keep it here in the issues.

**Comment by gustavo-iniguez-goya** [comment]
what words should we use for this option? "until restart", "until restart (daemon)", "until reboot", ...

The rules are valid "until restart the daemon".

**Comment by themighty1** [comment]
Just to clarify, if the user pauses the daemon from the GUI and then resumes, will the "for this session" rule persist?

**Comment by gustavo-iniguez-goya** [comment]
Yes, if the daemon is paused, "for this session" rules will persist. In this case, we only stop intercepting new connections, but the daemon remains running.

If daemon is stopped (via systemctl/service), when it starts again it'll ony load the rules from disk. **GUI rules are not deleted from the list of the tab Rules.**

A feature (or fix) I've been thinking in lately is to synchronize the rules between UI and daemon.

**Comment by themighty1** [comment]
So, if the rule persists, then I would go with "until reboot". Since the end-user is not supposed to stop/start opensnitch manually, from his perspective the "for this session" rule will persist until system reboot.
