### ISSUE TITLE
make install - Text file busy

### ISSUE THREAD

**Issue by licaon-kter** [evilsocket/opensnitch#311]
Debian Sid 64-bit, `make install`:
```
make[1]: Entering directory '.../go/src/github.com/evilsocket/opensnitch/daemon'
cp: regular file '/usr/local/bin/opensnitchd' can't be created: Text file busy
make[1]: *** [Makefile:5: install] Error 1
```

I can install if I first stop the daemon, then install, then restart... which makes it a pain, so do I have to stop the networking first, right? Or directly unplug the cable? :(

**Comment by gustavo-iniguez-goya** [comment]
try stopping the service first:

```
service opensnitch stop
make install
service opensnitch start
```

**Comment by licaon-kter** [comment]
What happens when I stop the service exactly, all the programs just access the internet as they wish? That's...not what I want in a firewall. :+1: 

> if you compile from the sources

As opposed to precompiled .DEBs?

Can't that `cp` be replaced with whatever `apt` does?

**Comment by gustavo-iniguez-goya** [comment]
Well, dpkg will probably delete the target binary, and then copy the new one.

try: `sudo mv opensnitchd /usr/local/bin/` and then `sudo service opensnitchd restart`

**Comment by gustavo-iniguez-goya** [comment]
closing as this is something that is expected. We can help out with the doubts, but the `make install` is something to be used on a first installation, rather than on a regular basis.
