### ISSUE TITLE
something's wrong with the rules tab

### ISSUE THREAD

**Issue by themighty1** [evilsocket/opensnitch#312]
on latest master here's what I see
![Screenshot_2020-12-22_12-32-32](https://user-images.githubusercontent.com/555272/102873227-c0e4a780-4438-11eb-9d2f-448e1a9ec6a8.png)

The rules are missing.

**Comment by themighty1** [comment]
after some time I see all the rules, let me investigate how to replicate.

**Comment by gustavo-iniguez-goya** [comment]
Sometimes the QSplitter was not resized properly. It was reproducible by closing the GUI on a non-clean way (killing the GUI or by pressing CTRL-C), but it seems that I didn't fully fixed it.

**Comment by themighty1** [comment]
Had this happen again. Closing the window ( X ) and then opening it again restores the missing table without quiting the ui.

**Comment by themighty1** [comment]
I can reproduce this even on a clean ui shutdown. 
If the last open tab was rules then on the next ui launch the rules tab will open ok. 
However if the last open tab was not rules then on the next ui launch there will be a rules tab like on the screenshot I posted earlier.

**Comment by gustavo-iniguez-goya** [comment]
ok, thank you @themighty1 ! I'll try to reproduce and fix my **it :)

**Comment by gustavo-iniguez-goya** [comment]
btw, the view is resizable (left<->right), just in case you didn't notice it.

**Comment by gustavo-iniguez-goya** [comment]
@themighty1 can you add these lines to stats.py and try again?

```
        self.nodeLabel.setStyleSheet('color: green;font-size:12pt; font-weight:600;')
+       self.rulesSplitter.setStretchFactor(0,0)
+       self.rulesSplitter.setStretchFactor(1,2)
```

**Comment by themighty1** [comment]
yes, that fixed it.
