### ISSUE TITLE
[Feature Request] Add multi language support for opensnitch

### ISSUE THREAD

**Issue by freddii** [evilsocket/opensnitch#319]
At the moment the only language opensnitch is using is english.
It would be nice to have a support for more languages.

**Comment by gustavo-iniguez-goya** [comment]
Support added @freddii . I've added some instructions about how to add new languages, and update existing ones:
https://github.com/evilsocket/opensnitch/tree/master/ui/i18n

Note to all: Your default preferences will be lost (sorry for that..). Just open the preferences dialog and set it as you had before.

Also check that all is working as before (rules options applied correctly, etc.)
