### ISSUE TITLE
Application level bandwidth monitoring

### ISSUE THREAD

**Issue by black-perl** [evilsocket/opensnitch#32]
Hi,

Great work. Can by any means we can monitor application level bandwidth i.e incoming/outgoing data per second ?

**Comment by evilsocket** [comment]
Not yet, but it'll be implemented in the future for sure.

**Comment by black-perl** [comment]
thanks !

**Comment by rcastill** [comment]
Hi,

Sorry I'm re-opening this ancient issue, but I failed to find any other reference to this and cannot find the option in the UI. Is there any plans to implement application bandwidth monitoring?

**Comment by rcastill** [comment]
That's great to read!

Thanks
