### ISSUE TITLE
[Feature Request] import rules from exported rules.csv file

### ISSUE THREAD

**Issue by freddii** [evilsocket/opensnitch#324]
It might be handy to be able to import all rules from an exported rules.csv file.

**Comment by gustavo-iniguez-goya** [comment]
csv wouldn't be a proper format, because we'd need a delimiter to separate the fields.

Why do you need this feature? just to understand the necessity.

**Comment by freddii** [comment]
To be able to take my configs to another linux system on dual boot.

**Comment by gustavo-iniguez-goya** [comment]
The easiest way would be to zip /etc/opensnitchd/ and unzip it on the other system.

The configs and rules are reloaded if they're modified on disk, so once the target file is overwritten, the daemon will reload it.

**Comment by freddii** [comment]
Thanks. will try that :)

**Comment by gustavo-iniguez-goya** [comment]
I'll document it on the wiki, so others know it, just in case they need it.
