### ISSUE TITLE
add hint message "Delete Hosts logs" when in Hosts-tab, hovering over the [x]

### ISSUE THREAD

**Issue by freddii** [evilsocket/opensnitch#329]
It would be useful to have a message that shows "Delete Hosts logs"

![opensnitch](https://user-images.githubusercontent.com/7213207/104074295-044c5d80-5210-11eb-8dfd-aab1534b6a5d.png)

also in:
 - Events-tab there might be a hint message "Delete Events logs" when hovering over the [x] 
 - Preferences-Icon with hint message "Open Preferences"

**Comment by gustavo-iniguez-goya** [comment]
@freddii , @tioguda : I've added new sentences and words (preferences, stats, prompt, etc, etc...), and I've updated the .ts files

**Comment by tioguda** [comment]
Missed add the translation to delete the ports and users intercepted.

Greetings.
