### ISSUE TITLE
GUI not opening on Fedora 32

### ISSUE THREAD

**Issue by sebastianelsner** [evilsocket/opensnitch#332]
Hi,

while testing on Fedora 32 I found an issue with the rpms. The gui would not open, erroring with:

```python
Traceback (most recent call last):
  File "/usr/bin/opensnitch-ui", line 16, in <module>
    import grpc
ModuleNotFoundError: No module named 'grpc'
```

I was able to solve it by manually installing

```bash
sudo dnf install python3-grpcio
```

Maybe this should be included in the spec file as a requirement?

Regards

Sebastian

**Comment by gustavo-iniguez-goya** [comment]
Hi Sebastian!

Glad you fixed it by yourself. Yes, the thing is that python3-grpcio is not packaged in all rpm based distributions and versions, and it seems that we're incompatible with some python3-grpcio versions, like the one from OpenSuse Tumbleweed (for whatever reason, [not even a minimal hello-world works](https://stackoverflow.com/questions/65145129/unable-to-get-grpc-server-working-using-python3-grpcio-shipped-with-several-gnu)).

I'm trying to automate the builds to generate packages for Fedora >= 30, with that dependency added.

**Comment by gustavo-iniguez-goya** [comment]
I've released v1.3.5, and I've generated a rpm without the pip dependencies, adding as requirement all the packages that we need for installing it. Tested on f33 and f29, and it works fine :)

I haven't had time to test it on SuSe, but I'll give it a try just in case it works with latest python3-grpcio package.

Thank you for reporting this.

**Comment by sebastianelsner** [comment]
Thank you for fixing!

**Comment by vbooka1** [comment]
> I haven't had time to test it on SuSe, but I'll give it a try just in case it works with latest python3-grpcio package.

just FYI: `pip3 install --user grpcio` does NOT work in openSuSE and results in error "No module named 'grpc'".

installing grpc from repositories `zypper in python3-grpcio` does work.
