### ISSUE TITLE
[Feature Request] add an option to export or to copy hosts from the hosts tab

### ISSUE THREAD

**Issue by NRGLine4Sec** [evilsocket/opensnitch#336]
It could be useful to add the ability to export or to copy all the list of hosts in the host tab.

**Comment by gustavo-iniguez-goya** [comment]
I agree, I've been in the situation where I've wanted to copy all the connections of the Events tab. It'd be useful (we discussed it on the Discussions forum).

**Comment by gustavo-iniguez-goya** [comment]
I'll close this issue here. We were discussing UI improvements here, let's continue there: https://github.com/gustavo-iniguez-goya/opensnitch/discussions/114
