### ISSUE TITLE
[Feature Request] add more capability to modify the GUI interface configuration

### ISSUE THREAD

**Issue by NRGLine4Sec** [evilsocket/opensnitch#337]
It could be great to add some more capability to modify the GUI interface configuration. I would like to change the appearance of the Rules interface with an option to activate or desactivate columns.
For example, I don't really need the columns "operator_type", "operator_sensitive" and "operator_operand", and presently we coul'nt desactivate these columns.

Moreover, it could be great if the columns size (after rezising) could be keep for the next launch of the OpenSnitch GUI.

**Comment by gustavo-iniguez-goya** [comment]
I think that we could simply remove those fields. They are only useful for debugging purposes.

**Comment by NRGLine4Sec** [comment]
I agree, but I really think that it's important to be able to change the interface, like with keeping the column size after resize it, move column from the right to the left and vice versa...

**Comment by gustavo-iniguez-goya** [comment]
allowing to remember the position and size of the columns is not easy as it may seem. I understand that it is useful, but I'll put the focus on other tasks for now.

**Comment by gustavo-iniguez-goya** [comment]
now the GUI is more configurable.

**Comment by tredondo** [comment]
I'd also like to remove the Node field (what's the use if you only have one machine?), and the Process field, because it's duplicated by the Cmdline

![Image](https://github.com/user-attachments/assets/93a79f96-aaa8-4895-97a7-cf97d1f3043d)

**Comment by gustavo-iniguez-goya** [comment]
agree @tredondo ! it's quite annoying. I'll try to hide it when there's only one node.
