### ISSUE TITLE
hard to see when opensnitch is not running in statusbar

### ISSUE THREAD

**Issue by freddii** [evilsocket/opensnitch#339]
**Describe the bug**
At the moment the icons in system tray for a running/not running opensnitch do not differ much.

**Expected behavior (optional)**
If opensnitch does stop running or is deactivated, it might be useful to have a colourful orange or red icon of opensnitch in system tray.

**Comment by gustavo-iniguez-goya** [comment]
somehting like this when it's not running:
![opensnitch-ui-ko](https://user-images.githubusercontent.com/2742953/105169770-5056a680-5b1c-11eb-9ad9-7418bb24e7d7.png)

**Comment by freddii** [comment]
or just change the running icon in status tray to green. I think that would be best.

**Comment by freddii** [comment]
and for icon-off:
![icon-off](https://user-images.githubusercontent.com/7213207/105847003-5269ab00-5fdd-11eb-834b-338685aa1681.png)

**Comment by freddii** [comment]
for running
![icon-white](https://user-images.githubusercontent.com/7213207/105847293-b55b4200-5fdd-11eb-89ed-3f0e6a7a6252.png)

**Comment by freddii** [comment]
for running:
![icon-white](https://user-images.githubusercontent.com/7213207/105847362-d0c64d00-5fdd-11eb-94fd-39ad7c6573c3.png)

**Comment by gustavo-iniguez-goya** [comment]
I've been working on this. We have 3 states right now: not running (icon-off), paused(icon-paused, new) and running (icon-white). There's a 4th icon, icon-alert, which is displayed when a pop-up is not answered.

The icon-red icon won't be used for now. It we'd cool to be able to display daemon errors on the GUI (interception rules not loaded, rules parsing errors, etc.).

I'll test these new icons, I think they give a better idea of the app status :+1:

**Comment by gustavo-iniguez-goya** [comment]
I've tested this for some time, and while some icons are colorful in Cinnamon (bluetooh applet for example, and other propietary software), that's not the case on the default kubuntu theme:
![image](https://user-images.githubusercontent.com/2742953/107068087-7351ad80-67e0-11eb-8c7a-e30ae7d4c817.png)

If we change these icons would other users complain? well, I'm pretty sure that they will.

At least I'll add an icon for Pause State.

**Comment by gustavo-iniguez-goya** [comment]
done
