### ISSUE TITLE
Not works on Python 3.6

### ISSUE THREAD

**Issue by bl00mber** [evilsocket/opensnitch#344]
Installer places `grpc` to `/usr/local/lib/python3.6`, but installs `opensnitch` and `PyQt5` to `/usr/lib/python3`, producing #332 error. After `PyQt5` reinstalled to 3.6, if dist_path and version changed to 3.6 in `/usr/bin/opensnitch-ui`, fails with error:
```
Loading translations: /usr/lib/python3/dist-packages/opensnitch/i18n locale: en_US
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
```

**Comment by gustavo-iniguez-goya** [comment]
Hi @bl00mber , what distro are you using? did you installed the GUI manually or using the precompiled packages?

**Comment by bl00mber** [comment]
Ubuntu 16, installed using
`sudo dpkg -i opensnitch_1.3.5-1_amd64.deb python3-opensnitch-ui_1.3.5-1_all.deb; sudo apt -f install`

**Comment by gustavo-iniguez-goya** [comment]
ok, thank you! I'll try to reproduce it.

**Comment by gustavo-iniguez-goya** [comment]
ok, python3.6 does not exist on ubuntu16.04, so please, post all the steps you followed to install python3.6, grpcio, etc, in order to understand what's happening, and to try to reproduce it.

**Comment by gustavo-iniguez-goya** [comment]
It works on Ubuntu 16.04 with python3.5:

`$ sudo dpkg -i python3-opensnitch-ui_1.3.5-1_all.deb; sudo apt -f install`
(select to not install dependencies)
`$ sudo pip3 install grpcio==1.16.1`
`$ sudo pip3 install protobuf`

Notice that I installed the dependencies system wide.

**Comment by bl00mber** [comment]
Thanks! That's how I fixed this:
`python3.5 -m pip install grpcio==1.16.1 protobuf slugify`

**Comment by gustavo-iniguez-goya** [comment]
Great! I've added it to the Documentation/wiki.

By the way, I've realized that latest changes added to master don't work on ubuntu 16.04 (due to some libs versions). I'm investigating it. The effect is that the date of the rules is not updated when a new network event matches a particular rule.

**Comment by gustavo-iniguez-goya** [comment]
Ok, the problem is that UPSERTS (update events if insert fails due to conflicts) weren't introduced until SQLite 3.24.x, and Ubuntu 16.04 SQLite version is 3.11. 

On the other hand, if you have the GUI running and the you change a rule on disk, the rule is not updated on the GUI. So although it'll be less optimal, maybe the best approach here will be to replace the rule to 1) get rid of unsupported sqlite functionality and 2) reflext on the GUI the changes that may be performed on disk.
