### ISSUE TITLE
compilation having go issues - note: module requires Go 1.14

### ISSUE THREAD

**Issue by NESC1US** [evilsocket/opensnitch#359]
Present yourself (or at least say "Hello" or "Hi") and be kind && respectful.

**Describe the bug**
as mentioned in discussion, compilation instructions are failing for me on Ubuntu 20.04.2 LTS (go1.13.8 linux/amd64) 

**To Reproduce**
follow the [instruction](https://github.com/evilsocket/opensnitch/wiki/Compilation) on Ubuntu 20.04 with Go >= 1.13

1. sudo apt-get install git golang libnetfilter-queue-dev libpcap-dev protobuf-compiler python3-pip pyqt5-dev-tools qttools5-dev-tools qt5-default
2. go get github.com/golang/protobuf/protoc-gen-go; mv go .local
3. export GOPATH=~/.local/go
4. export PATH=$PATH:$GOPATH/bin
5. python3 -m pip install --user grpcio-tools
6. git clone https://github.com/evilsocket/opensnitch
7. cd opensnitch
8. make

**Post error logs:** 
make
make[1]: Entering directory '/home/user/foo/opensnitch/proto'
protoc -I. ui.proto --go_out=plugins=grpc:../daemon/ui/protocol/
python3 -m grpc_tools.protoc -I. --python_out=../ui/opensnitch/ --grpc_python_out=../ui/opensnitch/ ui.proto
make[1]: Leaving directory '/home/user/foo/opensnitch/proto'
make[1]: Entering directory '/home/user/foo/opensnitch/daemon'
go: downloading github.com/evilsocket/ftrace v1.2.0
go: downloading github.com/golang/protobuf v1.0.0
go: downloading github.com/google/gopacket v1.1.14
go: downloading github.com/vishvananda/netlink v1.1.0
go: downloading google.golang.org/grpc v1.11.3
go: extracting github.com/evilsocket/ftrace v1.2.0
go: downloading github.com/fsnotify/fsnotify v1.4.7
go: extracting github.com/vishvananda/netlink v1.1.0
go: downloading golang.org/x/sys v0.0.0-20190606203320-7fc4e5ec1444
go: extracting github.com/google/gopacket v1.1.14
go: extracting github.com/golang/protobuf v1.0.0
go: downloading golang.org/x/net v0.0.0-20180417003750-8d16fa6dc9a8
go: extracting github.com/fsnotify/fsnotify v1.4.7
go: downloading github.com/vishvananda/netns v0.0.0-20191106174202-0a2b9b5464df
go: extracting google.golang.org/grpc v1.11.3
go: downloading google.golang.org/genproto v0.0.0-20180413175816-7fd901a49ba6
go: extracting github.com/vishvananda/netns v0.0.0-20191106174202-0a2b9b5464df
go: extracting golang.org/x/net v0.0.0-20180417003750-8d16fa6dc9a8
go: extracting golang.org/x/sys v0.0.0-20190606203320-7fc4e5ec1444
go: downloading golang.org/x/text v0.3.0
go: extracting google.golang.org/genproto v0.0.0-20180413175816-7fd901a49ba6
go: extracting golang.org/x/text v0.3.0
go: finding github.com/google/gopacket v1.1.14
go: finding github.com/fsnotify/fsnotify v1.4.7
go: finding github.com/evilsocket/ftrace v1.2.0
go: finding github.com/vishvananda/netlink v1.1.0
go: finding google.golang.org/grpc v1.11.3
go: finding github.com/golang/protobuf v1.0.0
go: finding golang.org/x/net v0.0.0-20180417003750-8d16fa6dc9a8
go: finding google.golang.org/genproto v0.0.0-20180413175816-7fd901a49ba6
go: finding golang.org/x/sys v0.0.0-20190606203320-7fc4e5ec1444
go: finding github.com/vishvananda/netns v0.0.0-20191106174202-0a2b9b5464df
go: finding golang.org/x/text v0.3.0
\# github.com/evilsocket/opensnitch/daemon/ui/protocol
ui/protocol/ui.pb.go:25:11: undefined: proto.ProtoPackageIsVersion3
ui/protocol/ui.pb.go:140:27: undefined: proto.InternalMessageInfo
ui/protocol/ui.pb.go:216:32: undefined: proto.InternalMessageInfo
ui/protocol/ui.pb.go:368:33: undefined: proto.InternalMessageInfo
ui/protocol/ui.pb.go:414:31: undefined: proto.InternalMessageInfo
ui/protocol/ui.pb.go:464:32: undefined: proto.InternalMessageInfo
ui/protocol/ui.pb.go:583:30: undefined: proto.InternalMessageInfo
ui/protocol/ui.pb.go:648:26: undefined: proto.InternalMessageInfo
ui/protocol/ui.pb.go:730:34: undefined: proto.InternalMessageInfo
ui/protocol/ui.pb.go:818:34: undefined: proto.InternalMessageInfo
ui/protocol/ui.pb.go:818:34: too many errors
note: module requires Go 1.14
\# github.com/evilsocket/opensnitch/daemon/netfilter
cgo-gcc-prolog: In function ‘_cgo_5a6ca3b2fd31_Cfunc_stop_reading_packets’:
cgo-gcc-prolog:451:49: warning: unused variable ‘_cgo_a’ [-Wunused-variable]
make[1]: *** [Makefile:15: opensnitchd] Error 2
make[1]: Leaving directory '/home/user/foo/opensnitch/daemon'
make: *** [Makefile:11: opensnitch_daemon] Error 2

**OS (please complete the following information):**
 - OS: Ubuntu
 - Kernel version:
Linux 5.4.0-65-generic #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
 - Version
cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"
go version
go version go1.13.8 linux/amd64

**Comment by themighty1** [comment]
@NESC1US , thanks.
What is your output of 
`protoc --version` ?

**Comment by gustavo-iniguez-goya** [comment]
This also occurs on Debian Sid: libprotoc 3.12.4

**Comment by NESC1US** [comment]
there are two versions of protobuf-compiler deb packages available in Ubuntu 20.04 default repositories (--version output in brackets): 3.12.3-2ubuntu2~20.04sav0 (libprotoc 3.12.3) and 3.6.1.3-2ubuntu5 (libprotoc 3.6.1) - neither affects the result of make

the error also happens when starting `make opensnitch_daemon`
all consist of protocol, opensnitch_daemon and gui - both protocol and gui don't crash and complete successfully.

**Comment by gustavo-iniguez-goya** [comment]
0. create this script:
clean_proto.sh
```
#!/bin/sh

if [ -z $1 ]; then
    echo "usage: ./$basename path/to/ui.pb.go"
fi

sed -i '/.*xxx.*/d' $1
sed -i '/.*XXX.*/d' $1
sed -i 's/ConnInterface/Conn/' $1
sed -i 's/cc grpc/cc *grpc/' $1
sed -i 's/IsVersion3/IsVersion2/' $1
sed -i 's/IsVersion6/IsVersion4/' $1
sed -i '/.*RegisterMapType.*/d' $1
```

1. execute it: `$ bash clean_proto.sh ui/protocol/ui.pb.go`

2. open the proto file, and delete all the occurrences with 5 consecutives }

try compiling it again.

you can always extract the compiled protocol from the latest packages and copy it to your sources:
`$ dpkg -x opensnitch_1.3.6-1_amd64.deb v1.3.6`
`$ cp v1.3.6/usr/share/gocode/src/github.com/evilsocket/opensnitch/daemon/ui/protocol/ui.pb.go ui/protocol/`

**Comment by gustavo-iniguez-goya** [comment]
hey @NESC1US , any update on this issue?

**Comment by NESC1US** [comment]
yes, the fix worked, thanks for the massive help.
I noticed that python3-pyqt5.qtsql is missing from dependency list, it is needed for opensnitch-ui
`
$ opensnitch-ui
Traceback (most recent call last):
  File "/usr/local/bin/opensnitch-ui", line 22, in <module>
    from opensnitch.service import UIService
  File "/usr/local/lib/python3.8/dist-packages/opensnitch/service.py", line 20, in <module>
    from dialogs.prompt import PromptDialog
  File "/usr/local/lib/python3.8/dist-packages/opensnitch/dialogs/prompt.py", line 16, in <module>
    from config import Config
  File "/usr/local/lib/python3.8/dist-packages/opensnitch/config.py", line 3, in <module>
    from database import Database
  File "/usr/local/lib/python3.8/dist-packages/opensnitch/database.py", line 1, in <module>
    from PyQt5.QtSql import QSqlDatabase, QSqlQueryModel, QSqlQuery
ModuleNotFoundError: No module named 'PyQt5.QtSql'`

**Comment by gustavo-iniguez-goya** [comment]
ouch, yes, the requirements.txt file is not updated. Thank you for pointing it out.

**Comment by themighty1** [comment]
I ran into similar errors when trying to compile the lastest master on Ubuntu 20.04
I could compile the master branch just fine a month ago.
Is the compilation issue because of my environment or because something's changed in opensnitch's code?
Anyway, my protoc --version is libprotoc 3.6.1
The errors I got were: 
```
ui/protocol/ui.pb.go:1461:7: undefined: grpc.ClientConnInterface
ui/protocol/ui.pb.go:1465:11: undefined: grpc.SupportPackageIsVersion6
ui/protocol/ui.pb.go:1478:5: undefined: grpc.ClientConnInterface
ui/protocol/ui.pb.go:1481:21: undefined: grpc.ClientConnInterface
make[1]: *** [Makefile:15: opensnitchd] Error 2
```

running the bash script above made the errors go away.

**Comment by raboof** [comment]
> ui/protocol/ui.pb.go:1461:7: undefined: grpc.ClientConnInterface

This means the version of `protoc-gen-go` you're using generates code that requires version 1.27.0 or later of `google.golang.org/grpc`. #381 should fix it.
