### ISSUE TITLE
Not working when rules are "always".

### ISSUE THREAD

**Issue by random29** [evilsocket/opensnitch#365]
Hi there. 

**Describe the bug**
So, when I updated to 1.36.r25 development version in aur, my opensnitch just freezed after reboot and not worked at all.
My system is Manjaro, last updates, python 3.9, compiled just nice, 5.10.18 kernel. 

**To Reproduce**
So, I deleted all rules, all content of /etc/opensnitch and settings in user folder. Removed opensnitch and reinstalled. After reboot started opensnitch and it worked just nice until I pushed **always allow** button to create rule. 
After some time, I founded, that opensnitch daemon freezes only when I use **always** rules, so now I use **until reboot** and just backup rules. 

**Post error logs:** 
So, there is no error logs.

If the daemon doesn't start:
 - Or launch it from a terminal (`/usr/bin/opensnitchd -rules-path /etc/opensnitchd/rules`) and post the errors logged to the terminal.
~ sudo /usr/bin/opensnitchd -rules-path /etc/opensnitchd/rules
[2021-03-04 09:23:26]  IMP  Starting opensnitch-daemon v1.3.6
[2021-03-04 09:23:26]  INF  Loading rules from /etc/opensnitchd/rules ...

Here you can see, that it doesn't throw errors, just freezing while loading rules. IDK.

**OS (please complete the following information):**
 - OS: Manjaro
 - Window Manager: xfce4
 - Kernel version: 5.10.18-1-MANJARO #1 SMP PREEMPT Tue Feb 23 18:07:15 UTC 2021 x86_64 GNU/Linux

Thanks for attention.

**Comment by gustavo-iniguez-goya** [comment]
ok, I'll take a look at it ASAP.

**Comment by gustavo-iniguez-goya** [comment]
@random29 thank you very much for reporting this problem. Please, verify and let me know if it fixes the issue.

**Comment by random29** [comment]
Thanks you for fix. Now is all working.
