### ISSUE TITLE
[Feature request] More friendly Debian packaging

### ISSUE THREAD

**Issue by dmknght** [evilsocket/opensnitch#367]
For now the opensnitch has parent folder which has `debian` dir and the `ui` which has different `debian` dir for different package and it is a little hard to build with Debian Packaging. So i think it is better to have
1. Sperate `ui` as different project. It should has different repo
2. Do multiple packages packging with 1 `debian` folder at parent folder only.
For the `2.`, i tried and likely it worked for me.
The `debian/rules` which merged `ui` and `daemon` installation
```
#!/usr/bin/make -f
export DH_VERBOSE = 1
#export DESTDIR = "debian/opensnitch"
#export PYBUILD_SYSTEM=distutils

override_dh_dwz:
	dwz -- debian/opensnitch/usr/bin/daemon || true
	mv debian/opensnitch/usr/bin/daemon debian/opensnitch/usr/bin/opensnitchd

override_dh_installsystemd:
	dh_installsystemd --restart-after-upgrade

%:
	dh $@ --builddirectory=_build --buildsystem=golang --with=golang
#	dh $@ --with python3 --buildsystem=pybuild

override_dh_auto_build:
	dh_auto_build
	cd ui && python3 setup.py build --force

override_dh_auto_install:
	dh_auto_install
	cd ui/i18n && make && cp -r locales/ ../opensnitch/i18n/ # Fixme lrelease not found, export path failed
	cd ui && python3 setup.py install --force --root=debian/opensnitch-ui --no-compile -O0 --install-layout=deb

override_dh_auto_clean:
	#cd ui && rm -rf opensnitch/i18n/
	#cd ui && python3 setup.py clean -a
	find . -name \*.pyc -exec rm {} \;
```
The file `opensnitch.install`
```
_build/bin/daemon usr/bin/
debian/tmp/usr/share/gocode usr/share/
daemon/default-config.json etc/opensnitchd/
daemon/system-fw.json etc/opensnitchd/
```
The file `opensnitch-ui.install` (I changed package name from `python3-opensnitch-ui` to `opensnitch-ui`
```
ui/debian/opensnitch-ui/usr/* usr/
```
Control file which merged `opensnitch` and `opensnitch-ui`. It also has missing packages that caused package build failed
```
Source: opensnitch
Maintainer: Debian Go Packaging Team <team+pkg-go@tracker.debian.org>
Uploaders:
 Gustavo Iniguez Goya <gooffy@gmail.com>,
Section: devel
Testsuite: autopkgtest-pkg-go
Priority: optional
Build-Depends:
 debhelper-compat (= 12),
 debhelper (>= 9),
 dh-systemd (>= 1.5),
 dh-golang,
 golang-any,
 golang-github-vishvananda-netlink-dev,
 golang-github-evilsocket-ftrace-dev,
 golang-github-google-gopacket-dev,
 golang-github-fsnotify-fsnotify-dev,
 golang-golang-x-net-dev,
 golang-google-grpc-dev,
 golang-goprotobuf-dev,
 pkg-config,
 libnetfilter-queue-dev,
 libmnl-dev,
 python3-setuptools,
 python3-all,
 debhelper (>= 7.4.3),
 dh-python,
 pyqt5-dev-tools,
 qtchooser,
 qttools5-dev-tools
Standards-Version: 4.5.1
Vcs-Browser: https://salsa.debian.org/go-team/packages/opensnitch
Vcs-Git: https://salsa.debian.org/go-team/packages/opensnitch.git
Homepage: https://github.com/evilsocket/opensnitch
Rules-Requires-Root: no
XS-Go-Import-Path: github.com/evilsocket/opensnitch

Package: opensnitch
Section: net
Architecture: any
Depends:
 ${misc:Depends}, ${shlibs:Depends},
Built-Using: ${misc:Built-Using}
Description: GNU/Linux firewall application
 OpenSnitch is a GNU/Linux firewall application.
 Whenever a program makes a connection, it'll prompt the user to allow or deny
 it.
 .
 The user can decide if block the outgoing connection based on properties of
 the connection: by port, by uid, by dst ip, by program or a combination
 of them.
 .
 These rules can last forever, until the app restart or just one time.
 .
 The GUI allows the user to view live outgoing connections, as well as search
 by process, user, host or port.

Package: opensnitch-ui
Architecture: all
Section: net
Depends:
 debconf, libqt5sql5-sqlite, python3:any, python3-setuptools, python3-six, python3-pyqt5,
 python3-pyqt5.qtsql, python3-pyinotify, python3-pip, whiptail | dialog, opensnitch,
 python3-slugify, python3-protobuf, python3-grpc-tools
Description: opensnitch application firewall GUI
 opensnitch-ui is a GUI for opensnitch written in Python.
 It allows the user to view live outgoing connections, as well as search
 for details of the intercepted connections.
 .
 The user can decide if block outgoing connections based on properties of
 the connection: by port, by uid, by dst ip, by program or a combination
 of them.
 .
 These rules can last forever, until restart the daemon or just one time.
```
Ui installation file `debian/opensnitch-ui.install`:

```
ui/debian/opensnitch-ui/usr/* usr/
ui/resources/opensnitch_ui.desktop etc/xdg/autostart/
```
I tested on Parrot OS 4.11 and everything is good.
Update:
1. Add `python3-grpc-tools` to `opensnitch-ui` depends
2. Likely `prerm` and `postinst` are safe to delete
3. Add launcher of `opensnitch-ui` to startup so it will start at boot with daemon.

**Comment by morfikov** [comment]
Since opensnitch and opensnitch-ui use different build systems, wouldn't it be better to split them into two separate projects?

**Comment by gustavo-iniguez-goya** [comment]
exactly @morfikov , I put 2 differents debian/ folders with that idea. Ideally I'd like to move the UI to a different repository.

By the way @dmknght , thank you for packaging it for parrotsec!

**Comment by dmknght** [comment]
> By the way @dmknght , thank you for packaging it for parrotsec!

I love OpenSnitch and i'm trying to have it as preinstalled package for home edition :D 
> exactly @morfikov , I put 2 differents debian/ folders with that idea. Ideally I'd like to move the UI to a different repository.

I think it is a better idea and with some docs / dev guide / whitepaper, maybe i can create other version of UI for opensnitch core :D

**Comment by SwampRabbit** [comment]
@gustavo-iniguez-goya I concur that option 1 of having the UI in a different repository is the best option.  I've actually been doing/testing the same thing @dmknght is doing for both options, debating which option to include in the MX Linux repos.

Option 1 IMHO is better long term because either can get updated without updating both, but option 2 is much easier on maintainers because we don't have to track 2 separate packages, but that isn't a big deal really.

I'm also testing dropping the UI post install extra package installation steps, rather to use the system provided packages, so users don't have to guess what to do.

**Comment by gustavo-iniguez-goya** [comment]
thank you!

> I'm also testing dropping the UI post install extra package installation steps, rather to use the system provided packages, so users don't have to guess what to do.

yes, that was mainly intended for "old" distros (ubuntu <= 18.04, Mint <= 19.x). But "modern" distros as far as I can tell have all the needed packages.

**Comment by jeremiah** [comment]
> thank you!
> 
> > I'm also testing dropping the UI post install extra package installation steps, rather to use the system provided packages, so users don't have to guess what to do.
> 
> yes, that was mainly intended for "old" distros (ubuntu <= 18.04, Mint <= 19.x). But "modern" distros as far as I can tell have all the needed packages.

Debian Bullseye doesn't have dh-systemd (though sid does.)

**Comment by SwampRabbit** [comment]
> Debian Bullseye doesn't have dh-systemd (though sid does.)

dh-systemd has been depreciated, its been in the works for some time, the dh-systemd package has been merged with the main debhelper package

Some background info [](https://bugs.debian.org/822670), but plenty more out there.

**Comment by jeremiah** [comment]
> > Debian Bullseye doesn't have dh-systemd (though sid does.)
> 
> 
> 
> dh-systemd has been depreciated, its been in the works for some time, the dh-systemd package has been merged with the main debhelper package
> 
> 
> 
> Some background info [](https://bugs.debian.org/822670), but plenty more out there.
> 
Yes, for sure. But dh-systemd should probably be removed as a dependency since it is deprecated.

**Comment by gustavo-iniguez-goya** [comment]
opensnitch is finally on Debian  https://tracker.debian.org/pkg/opensnitch, so we can close this issue.
