### ISSUE TITLE
[Verification] Opensnitch and other firewall software

### ISSUE THREAD

**Issue by bitpixl** [evilsocket/opensnitch#369]
Hi,

I'm somewhat confused about Opensnitch only tracking outgoing connections, which is fine, as long I'm able to use ... let's say gufw to configure incoming connections. Is this the case? Can they be used together? Should I configure gufw in a certain way so it doesn't interrupt Opensnitch?

Thank you in advance for explaining.

**Comment by gustavo-iniguez-goya** [comment]
Hi @bitpixl ,

Yes, you can use gufw or other software to handle incoming connections. Just configure gufw normally.
You can also use [/etc/opensnitchd/system-fw.json](https://github.com/evilsocket/opensnitch/blob/master/daemon/system-fw.json) to insert rules in any table or chain(no GUI yet, sorry), for example:
```
        {
            "Rule": {
                "Description": "Block input bad state",
                "Table": "filter",
                "Chain": "INPUT",
                "Parameters": "-p tcp -m conntrack --ctstate NEW -m tcp ! --tcp-flags FIN,SYN,RST,ACK SYN",
                "Target": "DROP",
                "TargetParameters": ""
            }
        }
```

**Comment by bitpixl** [comment]
Hi @gustavo-iniguez-goya,

thank you for the clarification and keep up the great work!
