### ISSUE TITLE
Issue Opensnitch GUI Linux Mint 20.1 Cinnamon

### ISSUE THREAD

**Issue by robjob1938** [evilsocket/opensnitch#371]
I need some help, this could be 100% me as this is day 10 of ever using Linux.

#1 I installed the needed packets from the installation notes:  apt-get install g++ python3-dev python3-wheel python3-slugify

after that did not work I read the linked file here and did everything in the comments.  https://github.com/gustavo-iniguez-goya/opensnitch/issues/16

#2  I tried uninstalling both the GUI and Opensnitch and reinstalling, no dice.

After trying to force the UI through the terminal   sudo opensnitch-ui    I get the following (which does not help me, but may help someone more knowledgeable.  Please help, I use this on my Pop!_os machine and it is exactly what I am looking for.

Traceback (most recent call last):
  File "/usr/bin/opensnitch-ui", line 22, in <module>
    from opensnitch.service import UIService
  File "/usr/local/lib/python3.8/dist-packages/opensnitch/service.py", line 17, in <module>
    import ui_pb2
  File "/usr/local/lib/python3.8/dist-packages/opensnitch/ui_pb2.py", line 22, in <module>
    create_key=_descriptor._internal_create_key,
AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_bin_opensnitch-ui.0.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/opensnitch-ui", line 22, in <module>
    from opensnitch.service import UIService
  File "/usr/local/lib/python3.8/dist-packages/opensnitch/service.py", line 17, in <module>
    import ui_pb2
  File "/usr/local/lib/python3.8/dist-packages/opensnitch/ui_pb2.py", line 22, in <module>
    create_key=_descriptor._internal_create_key,
AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'

**Comment by gustavo-iniguez-goya** [comment]
Hi @robjob1938 !

I've just tested it on a fresh Mint 20.1 installation and it has worked as expected .

Try uninstalling the GUI:
```
apt-get remove python3-opensnitch-ui
pip3 uninstall grpcio-tools
pip3 uninstall protobuf
pip3 uninstall grpcio
```

and reinstall it again (when it asks for installing dependencies answer No):
```
dpkg -i python3-opensnitch-ui_1.3.6-1_all.deb
apt-get -f install
```

Try launching it from a terminal as a regular user. If it fails install: `apt-get update; apt-get install python3-grpcio python3-protobuf` and try again. And let me know if it has worked. If no, please, post any error you see on the terminal.

**Comment by robjob1938** [comment]
Thanks for the quick reply.  I followed those instructions, and nothing changed.  I did make sure I had version 1.3.6-1.

When I run: opensnitchd
I get the following: 
standard@laptop:/etc/opensnitchd$ opensnitchd
[2021-03-19 23:05:02]  IMP  Starting opensnitch-daemon v1.3.6
[2021-03-19 23:05:02]  INF  Loading rules from /etc/opensnitchd/rules ...
[2021-03-19 23:05:02]  WAR  Is opnensitchd already running?
[2021-03-19 23:05:02]  !!!  Error while creating queue #0: Error unbinding existing q handler from AF_INET protocol family: operation not permitted

So it seems that opensnitch is running fine, it is a UI problem?????

and: opensnitch-ui

Traceback (most recent call last):
  File "/usr/bin/opensnitch-ui", line 22, in <module>
    from opensnitch.service import UIService
  File "/usr/local/lib/python3.8/dist-packages/opensnitch/service.py", line 20, in <module>
    from dialogs.prompt import PromptDialog
  File "/usr/local/lib/python3.8/dist-packages/opensnitch/dialogs/prompt.py", line 22, in <module>
    class PromptDialog(QtWidgets.QDialog, uic.loadUiType(DIALOG_UI_PATH)[0]):
  File "/usr/lib/python3/dist-packages/PyQt5/uic/__init__.py", line 203, in loadUiType
    exec(code_string.getvalue(), ui_globals)
  File "<string>", line 443, in <module>
ModuleNotFoundError: No module named 'resources_rc'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_bin_opensnitch-ui.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/opensnitch-ui", line 22, in <module>
    from opensnitch.service import UIService
  File "/usr/local/lib/python3.8/dist-packages/opensnitch/service.py", line 20, in <module>
    from dialogs.prompt import PromptDialog
  File "/usr/local/lib/python3.8/dist-packages/opensnitch/dialogs/prompt.py", line 22, in <module>
    class PromptDialog(QtWidgets.QDialog, uic.loadUiType(DIALOG_UI_PATH)[0]):
  File "/usr/lib/python3/dist-packages/PyQt5/uic/__init__.py", line 203, in loadUiType
    exec(code_string.getvalue(), ui_globals)
  File "<string>", line 443, in <module>
ModuleNotFoundError: No module named 'resources_rc'

**Comment by robjob1938** [comment]
I should also add that just double clicking the UI in Mint causes nothing to happen.

**Comment by robjob1938** [comment]
Python 3.8.5 is what is installed

**Comment by gustavo-iniguez-goya** [comment]
Yes, the daemon is running fine :+1: 

mmmh, did you install the UI manually? or have you ever had a previous version of opensnitch? This path suggest me that it's not properly installed or that you have a previous installation:
`/usr/local/lib/python3.8/dist-packages/opensnitch/`

Verify with the following command that your installation is under `/usr/lib/python3/opensnitch`: `dpkg -L python3-opensnitch-ui`
You'll see that the installed files are under `/usr/lib/python3/opensnitch/*` and `/usr/share/`

Remove the installation from `/usr/local/lib/python3.8/dist-packages/opensnitch/` and launch the ui as follow: `/usr/bin/opensnitch-ui`

**Comment by robjob1938** [comment]
Thank you, it does seem that files are under `/usr/lib/python3/dist-packages/opensnitch/` (I will post all of the resuts of `dpkg -L python3-opensnitch-ui` below.)

I understand that this is wrong folder location however I am too much of a novice to know how to fix this.  I once again tried to uninstall ` apt remove opensnitch python3-opensnitch-ui ` and `rm -rf /etc/opensnitchd/` which completely deletes any files for opensnitch in `/usr/lib/python3/dist-packages/`.  I then reinstall with `sudo dpkg -i opensnitch*.deb python3-opensnitch-ui*.deb; sudo apt -f install` which puts it right back into the `/usr/lib/python3/dist-packages/` folder (both opensnitch and opensnitch_ui-1.3.6.egg-info are in the dist-packages folder).

I also have to say everything in python3 folder is in the folder dist-packages

`standard@laptop:$ dpkg -L python3-opensnitch-ui
/.
/usr
/usr/bin
/usr/bin/opensnitch-ui
/usr/lib
/usr/lib/python3
/usr/lib/python3/dist-packages
/usr/lib/python3/dist-packages/opensnitch
/usr/lib/python3/dist-packages/opensnitch/__init__.py
/usr/lib/python3/dist-packages/opensnitch/config.py
/usr/lib/python3/dist-packages/opensnitch/customwidgets.py
/usr/lib/python3/dist-packages/opensnitch/database.py
/usr/lib/python3/dist-packages/opensnitch/desktop_parser.py
/usr/lib/python3/dist-packages/opensnitch/dialogs
/usr/lib/python3/dist-packages/opensnitch/dialogs/__init__.py
/usr/lib/python3/dist-packages/opensnitch/dialogs/preferences.py
/usr/lib/python3/dist-packages/opensnitch/dialogs/processdetails.py
/usr/lib/python3/dist-packages/opensnitch/dialogs/prompt.py
/usr/lib/python3/dist-packages/opensnitch/dialogs/ruleseditor.py
/usr/lib/python3/dist-packages/opensnitch/dialogs/stats.py
/usr/lib/python3/dist-packages/opensnitch/i18n
/usr/lib/python3/dist-packages/opensnitch/i18n/de_DE
/usr/lib/python3/dist-packages/opensnitch/i18n/de_DE/opensnitch-de_DE.qm
/usr/lib/python3/dist-packages/opensnitch/i18n/es_ES
/usr/lib/python3/dist-packages/opensnitch/i18n/es_ES/opensnitch-es_ES.qm
/usr/lib/python3/dist-packages/opensnitch/i18n/eu_ES
/usr/lib/python3/dist-packages/opensnitch/i18n/eu_ES/opensnitch-eu_ES.qm
/usr/lib/python3/dist-packages/opensnitch/i18n/pt_BR
/usr/lib/python3/dist-packages/opensnitch/i18n/pt_BR/opensnitch-pt_BR.qm
/usr/lib/python3/dist-packages/opensnitch/nodes.py
/usr/lib/python3/dist-packages/opensnitch/res
/usr/lib/python3/dist-packages/opensnitch/res/__init__.py
/usr/lib/python3/dist-packages/opensnitch/res/icon-alert.png
/usr/lib/python3/dist-packages/opensnitch/res/icon-off.png
/usr/lib/python3/dist-packages/opensnitch/res/icon-pause.png
/usr/lib/python3/dist-packages/opensnitch/res/icon-pause.svg
/usr/lib/python3/dist-packages/opensnitch/res/icon-red.png
/usr/lib/python3/dist-packages/opensnitch/res/icon-white.png
/usr/lib/python3/dist-packages/opensnitch/res/icon-white.svg
/usr/lib/python3/dist-packages/opensnitch/res/icon.png
/usr/lib/python3/dist-packages/opensnitch/res/preferences.ui
/usr/lib/python3/dist-packages/opensnitch/res/process_details.ui
/usr/lib/python3/dist-packages/opensnitch/res/prompt.ui
/usr/lib/python3/dist-packages/opensnitch/res/resources.qrc
/usr/lib/python3/dist-packages/opensnitch/res/ruleseditor.ui
/usr/lib/python3/dist-packages/opensnitch/res/stats.ui
/usr/lib/python3/dist-packages/opensnitch/resources_rc.py
/usr/lib/python3/dist-packages/opensnitch/service.py
/usr/lib/python3/dist-packages/opensnitch/ui_pb2.py
/usr/lib/python3/dist-packages/opensnitch/ui_pb2_grpc.py
/usr/lib/python3/dist-packages/opensnitch/utils.py
/usr/lib/python3/dist-packages/opensnitch/version.py
/usr/lib/python3/dist-packages/opensnitch_ui-1.3.6.egg-info
/usr/lib/python3/dist-packages/opensnitch_ui-1.3.6.egg-info/PKG-INFO
/usr/lib/python3/dist-packages/opensnitch_ui-1.3.6.egg-info/dependency_links.txt
/usr/lib/python3/dist-packages/opensnitch_ui-1.3.6.egg-info/not-zip-safe
/usr/lib/python3/dist-packages/opensnitch_ui-1.3.6.egg-info/top_level.txt
/usr/share
/usr/share/applications
/usr/share/applications/opensnitch_ui.desktop
/usr/share/doc
/usr/share/doc/python3-opensnitch-ui
/usr/share/doc/python3-opensnitch-ui/changelog.Debian.gz
/usr/share/doc/python3-opensnitch-ui/copyright
/usr/share/icons
/usr/share/icons/hicolor
/usr/share/icons/hicolor/48x48
/usr/share/icons/hicolor/48x48/apps
/usr/share/icons/hicolor/48x48/apps/opensnitch-ui.png
/usr/share/icons/hicolor/scalable
/usr/share/icons/hicolor/scalable/apps
/usr/share/icons/hicolor/scalable/apps/opensnitch-ui.svg
/usr/share/kservices5
/usr/share/kservices5/kcm_opensnitch.desktop
`

**Comment by robjob1938** [comment]
I figured it out:  `sudo pip3.8 uninstall opensnitch-ui`  did the trick  I have it working!  Thank you for your help, again I am a novice.  Do you have a location for donations to the project?  You can mark this issue as resolved

**Comment by robjob1938** [comment]
don't know if it helps but `dpkg -L opensnitch
`/.
/etc
/etc/init.d
/etc/init.d/opensnitch
/etc/logrotate.d
/etc/logrotate.d/opensnitch
/etc/opensnitchd
/etc/opensnitchd/default-config.json
/etc/opensnitchd/system-fw.json
/lib
/lib/systemd
/lib/systemd/system
/lib/systemd/system/opensnitch.service
/usr
/usr/bin
/usr/bin/opensnitchd
/usr/share
/usr/share/doc
/usr/share/doc/opensnitch
/usr/share/doc/opensnitch/changelog.Debian.gz
/usr/share/doc/opensnitch/copyright
/usr/share/gocode
/usr/share/gocode/src
/usr/share/gocode/src/github.com
/usr/share/gocode/src/github.com/evilsocket
/usr/share/gocode/src/github.com/evilsocket/opensnitch
/usr/share/gocode/src/github.com/evilsocket/opensnitch/daemon
/usr/share/gocode/src/github.com/evilsocket/opensnitch/daemon/conman
/usr/share/gocode/src/github.com/evilsocket/opensnitch/daemon/conman/connection.go
/usr/share/gocode/src/github.com/evilsocket/opensnitch/daemon/core
/usr/share/gocode/src/github.com/evilsocket/opensnitch/daemon/core/core.go
/usr/share/gocode/src/github.com/evilsocket/opensnitch/daemon/core/system.go
/usr/share/gocode/src/github.com/evilsocket/opensnitch/daemon/core/version.go
/usr/share/gocode/src/github.com/evilsocket/opensnitch/daemon/dns
/usr/share/gocode/src/github.com/evilsocket/opensnitch/daemon/dns/parse.go
/usr/share/gocode/src/github.com/evilsocket/opensnitch/daemon/dns/track.go
/usr/share/gocode/src/github.com/evilsocket/opensnitch/daemon/firewall
/usr/share/gocode/src/github.com/evilsocket/opensnitch/daemon/firewall/config.go
/usr/share/gocode/src/github.com/evilsocket/opensnitch/daemon/firewall/rules.go
/usr/share/gocode/src/github.com/evilsocket/opensnitch/daemon/log
/usr/share/gocode/src/github.com/evilsocket/opensnitch/daemon/log/log.go
/usr/share/gocode/src/github.com/evilsocket/opensnitch/daemon/main.go
/usr/share/gocode/src/github.com/evilsocket/opensnitch/daemon/netfilter
/usr/share/gocode/src/github.com/evilsocket/opensnitch/daemon/netfilter/packet.go
/usr/share/gocode/src/github.com/evilsocket/opensnitch/daemon/netfilter/queue.c
/usr/share/gocode/src/github.com/evilsocket/opensnitch/daemon/netfilter/queue.go
/usr/share/gocode/src/github.com/evilsocket/opensnitch/daemon/netfilter/queue.h
/usr/share/gocode/src/github.com/evilsocket/opensnitch/daemon/netlink
/usr/share/gocode/src/github.com/evilsocket/opensnitch/daemon/netlink/socket.go
/usr/share/gocode/src/github.com/evilsocket/opensnitch/daemon/netlink/socket_linux.go
/usr/share/gocode/src/github.com/evilsocket/opensnitch/daemon/netstat
/usr/share/gocode/src/github.com/evilsocket/opensnitch/daemon/netstat/entry.go
/usr/share/gocode/src/github.com/evilsocket/opensnitch/daemon/netstat/find.go
/usr/share/gocode/src/github.com/evilsocket/opensnitch/daemon/netstat/parse.go
/usr/share/gocode/src/github.com/evilsocket/opensnitch/daemon/procmon
/usr/share/gocode/src/github.com/evilsocket/opensnitch/daemon/procmon/activepids.go
/usr/share/gocode/src/github.com/evilsocket/opensnitch/daemon/procmon/activepids_test.go
/usr/share/gocode/src/github.com/evilsocket/opensnitch/daemon/procmon/audit
/usr/share/gocode/src/github.com/evilsocket/opensnitch/daemon/procmon/audit/client.go
/usr/share/gocode/src/github.com/evilsocket/opensnitch/daemon/procmon/audit/parse.go
/usr/share/gocode/src/github.com/evilsocket/opensnitch/daemon/procmon/cache.go
/usr/share/gocode/src/github.com/evilsocket/opensnitch/daemon/procmon/details.go
/usr/share/gocode/src/github.com/evilsocket/opensnitch/daemon/procmon/find.go
/usr/share/gocode/src/github.com/evilsocket/opensnitch/daemon/procmon/find_test.go
/usr/share/gocode/src/github.com/evilsocket/opensnitch/daemon/procmon/parse.go
/usr/share/gocode/src/github.com/evilsocket/opensnitch/daemon/procmon/process.go
/usr/share/gocode/src/github.com/evilsocket/opensnitch/daemon/procmon/process_test.go
/usr/share/gocode/src/github.com/evilsocket/opensnitch/daemon/procmon/watcher.go
/usr/share/gocode/src/github.com/evilsocket/opensnitch/daemon/rule
/usr/share/gocode/src/github.com/evilsocket/opensnitch/daemon/rule/loader.go
/usr/share/gocode/src/github.com/evilsocket/opensnitch/daemon/rule/loader_test.go
/usr/share/gocode/src/github.com/evilsocket/opensnitch/daemon/rule/operator.go
/usr/share/gocode/src/github.com/evilsocket/opensnitch/daemon/rule/operator_test.go
/usr/share/gocode/src/github.com/evilsocket/opensnitch/daemon/rule/rule.go
/usr/share/gocode/src/github.com/evilsocket/opensnitch/daemon/rule/rule_test.go
/usr/share/gocode/src/github.com/evilsocket/opensnitch/daemon/rule/testdata
/usr/share/gocode/src/github.com/evilsocket/opensnitch/daemon/rule/testdata/000-allow-chrome.json
/usr/share/gocode/src/github.com/evilsocket/opensnitch/daemon/rule/testdata/001-deny-chrome.json
/usr/share/gocode/src/github.com/evilsocket/opensnitch/daemon/rule/testdata/live_reload
/usr/share/gocode/src/github.com/evilsocket/opensnitch/daemon/rule/testdata/live_reload/test-live-reload-delete.json
/usr/share/gocode/src/github.com/evilsocket/opensnitch/daemon/rule/testdata/live_reload/test-live-reload-remove.json
/usr/share/gocode/src/github.com/evilsocket/opensnitch/daemon/statistics
/usr/share/gocode/src/github.com/evilsocket/opensnitch/daemon/statistics/event.go
/usr/share/gocode/src/github.com/evilsocket/opensnitch/daemon/statistics/stats.go
/usr/share/gocode/src/github.com/evilsocket/opensnitch/daemon/ui
/usr/share/gocode/src/github.com/evilsocket/opensnitch/daemon/ui/client.go
/usr/share/gocode/src/github.com/evilsocket/opensnitch/daemon/ui/config.go
/usr/share/gocode/src/github.com/evilsocket/opensnitch/daemon/ui/notifications.go
/usr/share/gocode/src/github.com/evilsocket/opensnitch/daemon/ui/protocol
/usr/share/gocode/src/github.com/evilsocket/opensnitch/daemon/ui/protocol/ui.pb.go
/usr/share/gocode/src/github.com/evilsocket/opensnitch/proto
/usr/share/gocode/src/github.com/evilsocket/opensnitch/proto/ui.proto

and `dpkg -L python3-opensnitch-ui`
/.
/usr
/usr/bin
/usr/bin/opensnitch-ui
/usr/lib
/usr/lib/python3
/usr/lib/python3/dist-packages
/usr/lib/python3/dist-packages/opensnitch
/usr/lib/python3/dist-packages/opensnitch/__init__.py
/usr/lib/python3/dist-packages/opensnitch/config.py
/usr/lib/python3/dist-packages/opensnitch/customwidgets.py
/usr/lib/python3/dist-packages/opensnitch/database.py
/usr/lib/python3/dist-packages/opensnitch/desktop_parser.py
/usr/lib/python3/dist-packages/opensnitch/dialogs
/usr/lib/python3/dist-packages/opensnitch/dialogs/__init__.py
/usr/lib/python3/dist-packages/opensnitch/dialogs/preferences.py
/usr/lib/python3/dist-packages/opensnitch/dialogs/processdetails.py
/usr/lib/python3/dist-packages/opensnitch/dialogs/prompt.py
/usr/lib/python3/dist-packages/opensnitch/dialogs/ruleseditor.py
/usr/lib/python3/dist-packages/opensnitch/dialogs/stats.py
/usr/lib/python3/dist-packages/opensnitch/i18n
/usr/lib/python3/dist-packages/opensnitch/i18n/de_DE
/usr/lib/python3/dist-packages/opensnitch/i18n/de_DE/opensnitch-de_DE.qm
/usr/lib/python3/dist-packages/opensnitch/i18n/es_ES
/usr/lib/python3/dist-packages/opensnitch/i18n/es_ES/opensnitch-es_ES.qm
/usr/lib/python3/dist-packages/opensnitch/i18n/eu_ES
/usr/lib/python3/dist-packages/opensnitch/i18n/eu_ES/opensnitch-eu_ES.qm
/usr/lib/python3/dist-packages/opensnitch/i18n/pt_BR
/usr/lib/python3/dist-packages/opensnitch/i18n/pt_BR/opensnitch-pt_BR.qm
/usr/lib/python3/dist-packages/opensnitch/nodes.py
/usr/lib/python3/dist-packages/opensnitch/res
/usr/lib/python3/dist-packages/opensnitch/res/__init__.py
/usr/lib/python3/dist-packages/opensnitch/res/icon-alert.png
/usr/lib/python3/dist-packages/opensnitch/res/icon-off.png
/usr/lib/python3/dist-packages/opensnitch/res/icon-pause.png
/usr/lib/python3/dist-packages/opensnitch/res/icon-pause.svg
/usr/lib/python3/dist-packages/opensnitch/res/icon-red.png
/usr/lib/python3/dist-packages/opensnitch/res/icon-white.png
/usr/lib/python3/dist-packages/opensnitch/res/icon-white.svg
/usr/lib/python3/dist-packages/opensnitch/res/icon.png
/usr/lib/python3/dist-packages/opensnitch/res/preferences.ui
/usr/lib/python3/dist-packages/opensnitch/res/process_details.ui
/usr/lib/python3/dist-packages/opensnitch/res/prompt.ui
/usr/lib/python3/dist-packages/opensnitch/res/resources.qrc
/usr/lib/python3/dist-packages/opensnitch/res/ruleseditor.ui
/usr/lib/python3/dist-packages/opensnitch/res/stats.ui
/usr/lib/python3/dist-packages/opensnitch/resources_rc.py
/usr/lib/python3/dist-packages/opensnitch/service.py
/usr/lib/python3/dist-packages/opensnitch/ui_pb2.py
/usr/lib/python3/dist-packages/opensnitch/ui_pb2_grpc.py
/usr/lib/python3/dist-packages/opensnitch/utils.py
/usr/lib/python3/dist-packages/opensnitch/version.py
/usr/lib/python3/dist-packages/opensnitch_ui-1.3.6.egg-info
/usr/lib/python3/dist-packages/opensnitch_ui-1.3.6.egg-info/PKG-INFO
/usr/lib/python3/dist-packages/opensnitch_ui-1.3.6.egg-info/dependency_links.txt
/usr/lib/python3/dist-packages/opensnitch_ui-1.3.6.egg-info/not-zip-safe
/usr/lib/python3/dist-packages/opensnitch_ui-1.3.6.egg-info/top_level.txt
/usr/share
/usr/share/applications
/usr/share/applications/opensnitch_ui.desktop
/usr/share/doc
/usr/share/doc/python3-opensnitch-ui
/usr/share/doc/python3-opensnitch-ui/changelog.Debian.gz
/usr/share/doc/python3-opensnitch-ui/copyright
/usr/share/icons
/usr/share/icons/hicolor
/usr/share/icons/hicolor/48x48
/usr/share/icons/hicolor/48x48/apps
/usr/share/icons/hicolor/48x48/apps/opensnitch-ui.png
/usr/share/icons/hicolor/scalable
/usr/share/icons/hicolor/scalable/apps
/usr/share/icons/hicolor/scalable/apps/opensnitch-ui.svg
/usr/share/kservices5
/usr/share/kservices5/kcm_opensnitch.desktop

**Comment by gustavo-iniguez-goya** [comment]
great @robjob1938 ! glad to have helped you :)
