### ISSUE TITLE
protoc-gen-go: unable to determine Go import path for "ui.proto"

### ISSUE THREAD

**Issue by EdEdEddyEddy** [evilsocket/opensnitch#373]
Hello, I am glad to see this project being worked on again! I am struggling to compile from source.

**Describe the bug**
I am doing this in a python venv. Following these instructions: https://github.com/evilsocket/opensnitch/wiki/Compilation

**To Reproduce**
I enter python venv by sourcing the ~/pyenv/bin/activate, I export the go path, export the path. Continue following installation instructions, receive an error when I run "make"

1. source ~/pyenv/bin/activate
2. export GOPATH=~/pyenv
3. export PATH=$PATH:$GOPATH/bin
4. git clone https://github.com/evilsocket/opensnitch
5. cd opensnitch
6. make (error happens)

**Post error logs:** 

make[1]: Entering directory '/home/ed/pyenv/opensnitch/proto'
protoc -I. ui.proto --go_out=plugins=grpc:../daemon/ui/protocol/
protoc-gen-go: unable to determine Go import path for "ui.proto"

Please specify either:
	• a "go_package" option in the .proto source file, or
	• a "M" argument on the command line.

See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.

--go_out: protoc-gen-go: Plugin failed with status code 1.
make[1]: *** [Makefile:4: ../daemon/ui/protocol/ui.pb.go] Error 1
make[1]: Leaving directory '/home/ed/pyenv/opensnitch/proto'
make: *** [Makefile:8: protocol] Error 2

**Expected behavior (optional)**
Expected the compile to succeed

**Screenshots**

**OS (please complete the following information):**
 - OS: [Gentoo x64]
 - Window Manager: [bspwm]
 - Kernel version: 5.11.6-gentoo-x86_64

**Additional context**

**Comment by gustavo-iniguez-goya** [comment]
Hi @EdEdEddyEddy !

Please, modify proto/ui.proto and add the following line:
`option go_package = "opensnitch/daemon/ui/protocol`

**Comment by EdEdEddyEddy** [comment]
> Hi @EdEdEddyEddy !
> 
> Please, modify proto/ui.proto and add the following line:
> `option go_package = "opensnitch/daemon/ui/protocol";`
> or
> `option go_package = "./";`

Thank you for following up!!
I am trying to do this but I am met with the error below:
(I have tried using tab, placing under all: ui.pb.go: and just doing anything a noob can to  get it to work
make[1]: Entering directory '/home/ed/pyenv/src/opensnitch/proto'
Makefile:13: *** missing separator.  Stop.
make[1]: Leaving directory '/home/ed/pyenv/src/opensnitch/proto'
make: *** [Makefile:8: protocol] Error 2

I have tried adding to the top and bottom of file but was unable to run make 

`option go_package = "./";

all: ../daemon/ui/protocol/ui.pb.go ../ui/opensnitch/ui_pb2.py

../daemon/ui/protocol/ui.pb.go: ui.proto
        protoc -I. ui.proto --go_out=plugins=grpc:../daemon/ui/protocol/

../ui/opensnitch/ui_pb2.py: ui.proto
        python3 -m grpc_tools.protoc -I. --python_out=../ui/opensnitch/ --grpc_>

clean:
      	@rm -rf ../daemon/ui/protocol/ui.pb.go
        @rm -rf ../ui/opensnitch/ui_pb2.py
        @rm -rf ../ui/opensnitch/ui_pb2_grpc.py

`

**Comment by EdEdEddyEddy** [comment]
> Hi @EdEdEddyEddy !
> 
> Please, modify proto/ui.proto and add the following line:
> `option go_package = "opensnitch/daemon/ui/protocol";`
> or
> `option go_package = "./";`

Thank you for replying!!
I was able to add the second option into proto/ui.proto and I am now met with another hurdle:

`make[1]: Entering directory '/home/ed/pyenv/src/opensnitch/proto'
protoc -I. ui.proto --go_out=plugins=grpc:../daemon/ui/protocol/
python3 -m grpc_tools.protoc -I. --python_out=../ui/opensnitch/ --grpc_python_out=../ui/opensnitch/ ui.proto
make[1]: Leaving directory '/home/ed/pyenv/src/opensnitch/proto'
make[1]: Entering directory '/home/ed/pyenv/src/opensnitch/daemon'
go: github.com/evilsocket/ftrace@v1.2.0: missing go.sum entry; to add it:
	go mod download github.com/evilsocket/ftrace
make[1]: *** [Makefile:15: opensnitchd] Error 1
make[1]: Leaving directory '/home/ed/pyenv/src/opensnitch/daemon'
make: *** [Makefile:11: opensnitch_daemon] Error 2
`

When I try to run "go mod download github.com/evilsocket/ftrace" I get:
go mod download: module github.com/evilsocket/ftrace: not a known dependency


Not sure how to go about it at this point, your help will be great. Would love to get opensnitch working again, and very happy you are working on it. I was using your github before and saw the recent notice to use this one.

**Comment by EdEdEddyEddy** [comment]
update - i've been trying to get around this, i used the ftrace "go get -u github.com/evilsocket/ftrace" manually, also tried adding the go mod command to a go.sum file, not sure I can complete this. I was able to install the version from your github fine, ran out of ideas to try. couldn't get much help from gentoo users, did not find anyone using or familiar

**Comment by gustavo-iniguez-goya** [comment]
Maybe @NP-Hardass can you help here:
https://github.com/gustavo-iniguez-goya/opensnitch/pull/62

I thought that she/he had packaged opensnitch for gentoo.

**Comment by z0xyz** [comment]
i also have this issue , i added the both of the two lines (on at a time) , yet nothing worked

**Comment by gustavo-iniguez-goya** [comment]
@z0xyz , try the following:

add to proto/ui.proto this line:
`option go_package = "github.com/evilsocket/opensnitch/daemon/ui/protocol";`

and execute:
`cd proto; protoc -I. ui.proto --go_opt=paths=source_relative --go_out=plugins=grpc:../daemon/ui/protocol/`

**Comment by EdEdEddyEddy** [comment]
> @z0xyz , try the following:
> 
> add to proto/ui.proto this line:
> `option go_package = "github.com/evilsocket/opensnitch/daemon/ui/protocol";`
> 
> and execute:
> `cd proto; protoc -I. ui.proto --go_opt=paths=source_relative --go_out=plugins=grpc:../daemon/ui/protocol/`

@z0xyz let me know your output for the above, i tried and the command ran but when I tried to make it showed:
make[1]: Entering directory '/home/ed/pyenv/src/opensnitch/proto'
python3 -m grpc_tools.protoc -I. --python_out=../ui/opensnitch/ --grpc_python_out=../ui/opensnitch/ ui.proto
make[1]: Leaving directory '/home/ed/pyenv/src/opensnitch/proto'
make[1]: Entering directory '/home/ed/pyenv/src/opensnitch/daemon'
go: github.com/evilsocket/ftrace@v1.2.0: missing go.sum entry; to add it:
	go mod download github.com/evilsocket/ftrace
make[1]: *** [Makefile:15: opensnitchd] Error 1
make[1]: Leaving directory '/home/ed/pyenv/src/opensnitch/daemon'
make: *** [Makefile:11: opensnitch_daemon] Error 2

If I try to go mod download it s till shows: 
go mod download: module github.com/evilsocket/ftrace: not a known dependency

@NP-Hardass do you remember ever having any of these issues and if so what did you modify to get through this part of the compile?

**Comment by gustavo-iniguez-goya** [comment]
```
make[1]: Entering directory '/home/ed/pyenv/src/opensnitch/proto'
python3 -m grpc_tools.protoc -I. --python_out=../ui/opensnitch/ --grpc_python_out=../ui/opensnitch/ ui.proto
make[1]: Leaving directory '/home/ed/pyenv/src/opensnitch/proto'
make[1]: Entering directory '/home/ed/pyenv/src/opensnitch/daemon'
```

that looks good. there should exist the file ui.pb.go under daemon/ui/protocol/

**Comment by NP-Hardass** [comment]
Sorry, for some reason I thought github supported reply by email...  I have my ebuild for 1.0.1 locally.  Let me try porting it to use this repo, and the latest, and I'll report back (as well as commit it to my public repo, if it is successful)

**Comment by EdEdEddyEddy** [comment]
I want to give this a try outside python venv, but I've already broken my system before using sudo pip on the very old version. I've ran out of ideas.

@gustavo-iniguez-goya should I try to make install even though it's outputting errors? I also don't want to overwrite my working version from your github.

**Comment by EdEdEddyEddy** [comment]
@gustavo-iniguez-goya while I can't figure out what I did wrong to get the compile to fail in python env, it seems like this ebuild manages to compile the ui on gentoo: https://github.com/pentoo/pentoo-overlay/blob/master/app-admin/opensnitch/opensnitch-1.3.6.ebuild , I am wondering how I could get around to compiling just the daemon, if you have any ideas please let me know!!

**Comment by buraksecer** [comment]
> 

Bro thx  I've been looking for this for 3 hours 💯
