### ISSUE TITLE
[Request] Version Command line Argument

### ISSUE THREAD

**Issue by zero77** [evilsocket/opensnitch#374]
Can you please add a command line argument like `-v` output `v1.5.41` to quickly show the current version, without having to open the ui, thanks.

**Comment by gustavo-iniguez-goya** [comment]
Something like this?

```
opensnitchd -version
[2021-03-22 12:16:38]  INF  OpenSnitch daemon 1.3.6
```

**Comment by zero77** [comment]
@gustavo-iniguez-goya 
Yes, but perhaps just the version number.

**Comment by NRGLine4Sec** [comment]
Hi @gustavo-iniguez-goya
I'm agree with @zero77, it is more convenient to just have the version number when you want to make script with this sort of command :
```bash
opensnitch_version="$(opensnitchd -version)"
```

**Comment by gustavo-iniguez-goya** [comment]
done! thank you @NRGLine4Sec and @zero77 :)
