### ISSUE TITLE
no statistics or events in arch linux

### ISSUE THREAD

**Issue by AnirudhChandupatla** [evilsocket/opensnitch#377]
I was able to install Opensnitch in Arch Linux, but when I opened it there were no events or any pop ups asking what needs to be denied or allowed.
![image](https://user-images.githubusercontent.com/16043410/112093898-3be86600-8bc0-11eb-9047-568da6291822.png)

**Comment by gustavo-iniguez-goya** [comment]
Hi @AnirudhChandupatla 

Please, verify that the daemon is running: `pgrep opensnitchd`

Also take a look at the daemon log: `/var/log/opensnichd.log` and look if there's any error messages (and attach it anyway). 

Finally, try launching the daemon from a terminal as root, and post the output:
`# /usr/bin/opensnitchd -rules-path /etc/opensnitchd/rules/`

last question: do you know the version that you have installed? Is it the 1.3.6 from the release page, or the AUR package was compiled from a later commit?

thank you!

**Comment by AnirudhChandupatla** [comment]
![image](https://user-images.githubusercontent.com/16043410/112490871-c6d68580-8da5-11eb-88cd-6bdc04c468ba.png)
I was able to run it using /usr/bin/opensnitchd -rules-path /etc/opensnitchd/rules/ command 
I installed 1.3.6-1 from chaotic-aur

**Comment by AnirudhChandupatla** [comment]
Yeah that worked, thanks
