### ISSUE TITLE
Request install from source instructions in wiki

### ISSUE THREAD

**Issue by kortschak** [evilsocket/opensnitch#389]
Hi, thanks for doing this work.

**Describe the bug**

The Wiki [home page](https://github.com/evilsocket/opensnitch/wiki) has a link [How to install or compile from sources opensnitch](https://github.com/evilsocket/opensnitch/wiki/Installation). However, the link takes the user to a page that describes installation from packages.

It would be helpful to have an install from sources page noting required deps that are not described in the go.mod file. I have attempted to build from source, but have not been able to with either the current master (e2be2b769a35f56799899a37fd3aafe5934fa07f) or the latest release (v1.3.6) and having this documentation would help fix that.

**To Reproduce**

1. Navigate to installation page.
2. Read documentation.

**Comment by kortschak** [comment]
On further reading, I see that these do exist [here](https://github.com/evilsocket/opensnitch/wiki/Compilation). I will send a PR to make this clearer.

**Comment by gustavo-iniguez-goya** [comment]
merged @kortschak , thank you!
