### ISSUE TITLE
[feature request]: allow easy promotion/demotion of rule lifetimes

### ISSUE THREAD

**Issue by kortschak** [evilsocket/opensnitch#393]
At the moment, rule lifetimes can be altered by editing the rule. However, this makes is a chore to promote or demote a set of rules. Where this would be important is in setting up a new installation of opensnitch; the user may want to run the fw with rules being applied until reboot for a number of days and then after vetting them (easily done via the tabular UI in Statistics) promote them to always. Ideally, this would also adjust the name to reflect the lifetime.

**Comment by gustavo-iniguez-goya** [comment]
Interesting idea @kortschak ,

What if we add more options to the contextual menu of the Tab Rules?

![image](https://user-images.githubusercontent.com/2742953/113515816-0015af00-9577-11eb-9078-3d28174f38c1.png)

**Comment by kortschak** [comment]
That would work.
