### ISSUE TITLE
Browser based translation/localization

### ISSUE THREAD

**Issue by ovari** [evilsocket/opensnitch#394]
Can instructions to the [README.md](https://github.com/evilsocket/opensnitch/tree/master/ui/i18n#readme) on how to provide translations using a browser please be added?

We would like to provide a `hu` (Hungarian - magyar) translation.

Thank you

P.S. We heard about your program from [Snitching on Phones That Snitch On You](https://puri.sm/posts/snitching-on-phones-that-snitch-on-you/)

> OpenSnitch is a really powerful tool but software like this requires a lot of time spent training the firewall, and can sometimes cause odd app errors until you realize the firewall is just doing it’s job. It would definitely benefit from a set of “known good” baseline rules you could apply so you only get prompted for the real outliers. Because of this I don’t know that it’s something the average user would want to install by default, but it’s definitely something useful for people facing more extreme threats.
>
> This would also be a great tool for an IT organization to deploy throughout a fleet of computers along with custom rules that factor in their known good services. It would add an additional layer of protection that would be relatively seamless for their employees.

**Comment by gustavo-iniguez-goya** [comment]
hi @ovari ,

You can read the instructions here: https://github.com/evilsocket/opensnitch/tree/master/ui/i18n

If you have any problem don't hesitate to ask.

**Comment by Danny3** [comment]
I would like to contribute too with translations for my language, but with my limited time I hope that one day I could use something simpler like Transifex where the are 90% of the other projects I contribute to and which already uses the Gettext (.po) system. 
As far as I remember Transifex it's free for open source programs.

**Comment by gustavo-iniguez-goya** [comment]
I can help with the translations. Tell me what your locale code is (hu_HU, fi_FI, etc) and I'll create the files for you to translate using `linguist`. Post the translations back here again, I'll test them, and if everything is fine I'll commit them.

**Comment by ovari** [comment]
Previously the locale code was `hu_HU`; however, the locale code is now `hu`.

A list of locales are shown in the ... drop-down at:
https://transvision.mozfr.org/

Do your other locales need updating to remove the capitals, the country, label?

Thank you

**Comment by Danny3** [comment]
I need for Romanian
I assume the code should be ro_RO

**Comment by gustavo-iniguez-goya** [comment]
> Do your other locales need updating to remove the capitals, the country, label?

As far as I can tell no. On Debian based systems there's no way to select a locale without the country, according to `dpkg-reconfigure locales`. You can also check out what's in this dir `~$ ls /usr/share/i18n/locales`

You can see what your current locale is as follow:
```
~$ python3
>>> from PyQt5 import QtWidgets, QtGui, QtCore
>>> locale = QtCore.QLocale.system()
>>> locale.name()
```

or: `~$ echo $LANG`

It'll pprobably be something like `hu_HU.UTF-8`

**Comment by ovari** [comment]
```
~$ echo $LANG
hu_HU.UTF-8
```

**Comment by gustavo-iniguez-goya** [comment]
thank you @ovari ! Here you have both Hungarian and Romanian translation files:
[opensnitch-hu_HU.ts.gz](https://github.com/evilsocket/opensnitch/files/6447132/opensnitch-hu_HU.ts.gz)
[opensnitch-ro_RO.ts.gz](https://github.com/evilsocket/opensnitch/files/6447133/opensnitch-ro_RO.ts.gz)

open it with `linguist` . It's expected to be launched from the cloned repo:

```
~$ git clone https://github.com/evilsocket/opensnitch.git
~$ cd opensnitch/ui/i18n
~$ linguist locales/hu_HU/opensnitch-hu_HU.ts
```

You should see each Qt dialog on the right side of `linguist`, so you can view how the translations fit in real time.

**Comment by gustavo-iniguez-goya** [comment]
hey, have you had the time to take a look at this?

**Comment by ovari** [comment]
Thanks for your instructions. Unfortunately they didn't work for us. However, we extracted the `opensnitch-hu_HU.ts` file and will add translations as `<translation type="unfinished"></translation>` and remove the ` type="unfinished"`.

Seems that https://github.com/evilsocket/opensnitch/tree/master/ui/i18n/locales has `ro_RO`, but no `hu_HU`.

**Comment by ovari** [comment]
@gustavo-iniguez-goya Can you please merge https://github.com/evilsocket/opensnitch/pull/411 as then your instructions at https://github.com/evilsocket/opensnitch/issues/394#issuecomment-835738628 may work. What do you think? Thank you

**Comment by ovari** [comment]
Do the leading and trailing spaces need to be in the translation?

For example
````
        <source>    You are about to delete this rule.    </source>
        <source>    Are you sure?</source>
````

Thank you

**Comment by gustavo-iniguez-goya** [comment]
Yes, in that particular case yes.

By the way, I don't see the strings translated in the PR  #411, can you verify that you pushed the correct .ts file?
All strings appear as `<translation type="unfinished"></translation>`

**Comment by ovari** [comment]
> Yes, in that particular case yes.

Sorry, don't understand what you are replying to.

> By the way, I don't see the strings translated in the PR #411, can you verify that you pushed the correct .ts file?
All strings appear as `<translation type="unfinished"></translation>`

Yes, that should be the correct file as it is the file you attached at https://github.com/evilsocket/opensnitch/issues/394#issuecomment-835738628.

We are currently translating the file in a text editor; however, once the file with the untranslated strings are on GitHub we can translate using the web browser. It will also enable others to translate too as the file will be visible for all. Please merge PR #411. Thank you

**Comment by gustavo-iniguez-goya** [comment]
> Do the leading and trailing spaces need to be in the translation?

Yes, in that particular case yes.

> We are currently translating the file in a text editor; however, once the file with the untranslated strings are on GitHub we can translate using the web browser. It will also enable others to translate too as the file will be visible for all. Please merge PR #411. 

oh, ok. The thing is that I commited that file already, precisely for you to test the translation easier. However I've just realized that I commited the file to a wrong location.

Ok, nevermind, I'll merge the PR.
