### ISSUE TITLE
[feature request] Default rules to "destination IP" instead of just everything

### ISSUE THREAD

**Issue by gigaSproule** [evilsocket/opensnitch#396]
Quite a few times, I click allow or deny and then realise that it's not applied to for just the destination IP/host. It would be great to have an option to choose what a default rule looks like. Currently a rule can be defaulted to action, duration and target, but adding in the option for destination IP (and maybe the others, port, ect.?) would be great. If there is already a way to do this and I'm just being stupid, please do point it out.

p.s. great bit of software, so thank you for the hard work you put in and I know you are doing this in your spare time, so please don't take this as a demand. If it was annoying me enough, I'd figure out how to do it myself :laughing:

**Comment by gustavo-iniguez-goya** [comment]
no worries ^^, some requests need some debate, because users are already used to a specific behaviour, but adding more options to customize it is easy.

Sorry but I'm not sure if I understood you correctly. It isn't Default target: "destination IP" what you are asking for?:

![image](https://user-images.githubusercontent.com/2742953/113461116-903ee180-941b-11eb-9a34-0bc6994a4626.png)

when a new pop-up appears it should default to the destination IP:
![image](https://user-images.githubusercontent.com/2742953/113461496-1c9dd400-941d-11eb-8e24-a635e7383d63.png)

**Comment by gigaSproule** [comment]
I could be wrong, but isn't that for every executable, or is it just for the given one? For example, this is what I've been setting up (maybe wrongly?):
![Screenshot from 2021-04-03 16-42-04](https://user-images.githubusercontent.com/1058957/113489984-4e677700-94bf-11eb-86a4-196f5efb2e5f.png)

**Comment by gustavo-iniguez-goya** [comment]
Yes, if you select `to spam.com` on the first combo box (without expanding the "extended view"), it'll apply the rule to all executables. Isn't it what you wanted? (`it's not applied to for just the destination IP/host`)

Or you want to apply a rule to "spam.com" but only for firefox? In such case, bear in mind that if you select `spam.com` it'll apply the rule only to `spam.com`, not `www.spam.com`, not `ftp.spam.com`, etc...  To allow/deny all connections to the domain `spam.com` you have to select `to .*spam.com`

**Comment by gigaSproule** [comment]
So in that scenario, I would want it to be for just Firefox. A noddy example, but something I could force a pop-up for :wink:.

The reasoning behind that is that I use Chrome for work related stuff (where I need to allow analytics, etc.) but Firefox for non-work related stuff. So I don't want to allow the same connections to be open for all executables.

**Comment by gustavo-iniguez-goya** [comment]
Closing because you can configure the field Destination IP to be by default marked in the Preferences dialog:

![image](https://user-images.githubusercontent.com/2742953/120978941-55d42680-c775-11eb-9a86-9bad91834293.png)
