### ISSUE TITLE
Suggestion: Disable/Enable aka Pause/Resume From Tray Context Menu

### ISSUE THREAD

**Issue by metal450** [evilsocket/opensnitch#398]
Looks like this project has moved here from the old repo at https://github.com/gustavo-iniguez-goya/opensnitch? :)

Suggestion/request: it would be very convenient to have Disable/Enable (aka pause/resume) in the tray icon's context menu.  Sometimes I quickly open the firewall to perform some operation that's usually blocked, & this would alleviate restoring the full UI twice.

Thanks! :)

**Comment by gustavo-iniguez-goya** [comment]
good idea @metal450 ! actually while playing with librem5 I've realized that this option would be also really useful.

By the way, have you tried latest version 1.4.0rc1? if you could try it out and give us some feedback would be really useful as always :]

**Comment by metal450** [comment]
Just installed it, will let you know if I see any issues :)

**Comment by gustavo-iniguez-goya** [comment]
woah, this one looked easy at first glance, but when there're several nodes connected it's not that easy to handle all the states.
Anyway, it should cover the majority of cases.

On the other hand, Phosh (librem5 desktop), does not have a system tray :/

**Comment by metal450** [comment]
Great, glad u got it! :)
