### ISSUE TITLE
Suggestion: Option to default notifications with different selections

### ISSUE THREAD

**Issue by metal450** [evilsocket/opensnitch#399]
When OpenSnitch shows a notification, it would be helpful if:

* By default, it could appear as though you already clicked "+" (i.e. the version of the notification dialog where you can check 'destination ip,' etc). Or really, I personally don't see any reason for the other version of the dialog (as it's currently shown initially) - might as well just always come up with the controls there, since both show the same information, but it just requires an extra click on "+" to be able to change anything. I see no downside to having that just be the only version of the dialog.
* A way to configure what option are checked on that dialog by default.  For example, now that my rules are mostly setup, when I get notifictions at this point the vast majority of the time I intend to tick 'Destination IP.'  So for each notification, I need 3 actions: +, tick Destination IP, then click deny/allow.  Knowing that this is almost always what I do, those first 2 steps could be skipped, by configuring the sofware with the default options to be shown on that dialog.

**Comment by gustavo-iniguez-goya** [comment]
point 1 make sense @metal450, in fact, a few days ago I proposed on another thread a "compact" view for the pop-ups:

![image](https://user-images.githubusercontent.com/2742953/114475132-f683eb00-9bf7-11eb-8049-5ba30e100613.png)

and display the details by clicking on the [+] button. With an option on the preferences dialog to let the users choose what style of pop-ups to display.

point 2: rather than configure the options (like having a section/widget on the Preference dialog), the pop-up could "remember" the option chosen by the user. what do you think, would it be enough?

**Comment by metal450** [comment]
1) Sure, as long as in prefs we can always have it show the 'full' version by default ;)  Personally don't need the minimized version, but as a different topic, if some would like it, I don't see why not

2) Sure, just as good! :)

**Comment by gustavo-iniguez-goya** [comment]
> when I get notifictions at this point the vast majority of the time I intend to tick 'Destination IP.' So for each notification, I need 3 actions: +, tick Destination IP, then click deny/allow.

I was rereading this issue. Do you mean that you select (only) the field Destination IP to block, or that you select Destination IP besides another field?

Apart from that, I've realized that checking the [+] button disables the countdown. So if it's configured to show the advanced option by default, the pop-ups only will timeout after 120s (hardcoded).

**Comment by metal450** [comment]
> I was rereading this issue. Do you mean that you select (only) the field Destination IP to block, or that you select Destination IP besides another field?

Yeah, usually I just block by 'from this executable' & domain (which it refers to as 'IP').

> Apart from that, I've realized that checking the [+] button disables the countdown. So if it's configured to show the advanced option by default, the pop-ups only will timeout after 120s (hardcoded).

Seems like those are 2 different concerns: 1) how the dialog is shown, vs 2) if the countdown continues. I realize that those are implicitly handled together currently, but the feel like two separate concerns.

In any case, my thought about the 'advanced view' concept was just that...there really didn't seem to be a benefit to the non-advanced view currentlyl.  If you add a *more* simple view, then that may no longer be the case - but as it is now, simple view is pretty much identical to advanced view...just that it doesn't let you change 3 of the checkboxes there.  It doesn't really 'simplify' the info being displayed.

**Comment by gustavo-iniguez-goya** [comment]
> there really didn't seem to be a benefit to the non-advanced view currentlyl. If you add a more simple view, then that may no longer be the case - but as it is now, simple view is pretty much identical to advanced view

yeah, it's just the "presentation view". Clicking on [+] gives you access to the "editing view", which is in my opinion uglier. I wouldn't like that view as the main/sole view.

But I understand that having to click several times every time a pop-up appears can be a pain. What if we just let configure more default options for the pop-ups on the Preferences dialog? At least the options that already are when clicking on the [+] button.

**Comment by NRGLine4Sec** [comment]
I'am agree with @metal450, it's more convenient to access to the "editing view" by default. But as @gustavo-iniguez-goya said, it should be an option to don't make it by default for everyone (specifically for non advanced users).

**Comment by metal450** [comment]
I just tried out the new 1.4.0-rc2 - love the ability to default to advanced :)  However, I couldn't find how to make it remember the user selections?

**Comment by gustavo-iniguez-goya** [comment]
Here:

**Comment by metal450** [comment]
Ahhh! Gotcha, so that means 'by default, check the following box.'  Thanks! :)
