### ISSUE TITLE
New connection blocked while UI prompt open.

### ISSUE THREAD

**Issue by kolorafa** [evilsocket/opensnitch#40]
It works briliantly, something I did love from WinXP time with few good Firewalls i did use that did ask you for every app/connection with allow/disallow.

The only problem for now is that even if you have app whitelisted it still will be blocked until you clear all prompts.

Way to reproduce:
1. run opensnitch
2. use for example ssh to connect to server - whitelist ssh app
2.a try if it's working, no more promots
3. use different app not whitelisted that will show opensnitch allow/deny prompt
4. try to connect to ssh without closing the opensnitch prompt

Expected output: you are still allowed to connect to ssh
Actual result: ssh is blocked until all prompts are closed.

Why does it matter?
For example you are trying to connect to your PC remotly
- you are AFK and there is some random app that did try to connect somewhere
- all new connections are blocked
- you try to connect to server and you can't because:
a) remote access app does a connection back (eg. dns query or actual reverse connection) an is delayed (blocked)
b) remote access app got disconnected (for example network error) and try to reconnect but is delayed (blocked)

$ sudo opensnitch 
[2017-05-04 20:51:03,858] (INFO) Using rules database from /home/kolorafa/opensnitch.db
[2017-05-04 20:51:03,858] (INFO) OpenSnitch v0.0.2 running with pid 28879.
[2017-05-04 20:51:03,874] (INFO) Enabling ProcMon ...
[2017-05-04 20:51:03,880] (INFO) ProcMon running ...

Overall gread job!

**Comment by kolorafa** [comment]
It will probably be fixed while implementing [this](https://github.com/evilsocket/opensnitch/issues/20)

**Comment by in1t3r** [comment]
This is one of the problems especially if you are using wm's like i3wm because then if you switch on one workspace and try to open something new while forgetting that you already have a prompt on another one. The workaround on the wm like i3wm is to enable sticky mode for the window so it stay on every workspace when you move.  And yeah this is a bad problem.

**Comment by adisbladis** [comment]
Just an FYI, I have a fix for this which just needs some code polish, will make a PR after work today :)

**Comment by in1t3r** [comment]
thx looking forward to that.
