### ISSUE TITLE
Python UI questions about grpc and start up

### ISSUE THREAD

**Issue by dmknght** [evilsocket/opensnitch#405]
1. Package dependencies
From the old installation script, i see ui needs package `grpcio-tools` https://github.com/evilsocket/opensnitch/blob/master/ui/debian/postinst#L11
But when i tested with `sudo pip3 install grpcio`, the ui is likely fine. So i would like to ask is `grpcio` enough for opensnitch-ui?
2. In your opinion, what is the best way to start `opensnitch-ui` with system? i don't think start only `opensnitch` daemon service is enough.

**Comment by gustavo-iniguez-goya** [comment]
Hi @dmknght ,

1) grpcio-tools is composed of several packages: grpcio and protobuf as you can [see here](https://github.com/grpc/grpc/blob/v1.27.0/tools/distrib/python/grpcio_tools/setup.py#L223):
```
    install_requires=[
        'protobuf>=3.5.0.post1',
        'grpcio>={version}'.format(version=grpc_version.VERSION),
    ],
```

So if you only install `grpcio`, `opensnitch-ui` will fail with an error stating that it can import "google". You'll need to install protobuf as well (`pip3 install protobuf`)

2) OpenSnitch has 2 components: a daemon and a GUI, so yes, you need to launch the GUI besides the daemon (or you can also can configure it to control the daemon from another computer in the network).

The best way to autostart the GUI is following the freedesktop standard that almost every DE follows:
https://specifications.freedesktop.org/autostart-spec/autostart-spec-latest.html

When installing the GUI with our packages, we add a .desktop file to `$HOME/.config/autostart/` , the file is here:
https://github.com/evilsocket/opensnitch/blob/master/ui/resources/opensnitch_ui.desktop

**Comment by dmknght** [comment]
@gustavo-iniguez-goya thank you so much for the reply. Well i've just found something
1. Debian packaged `python3-grpc-tools` already. Cheers! So it means no need for pip nor extra work. That explains why only `grpcio` worked for me :D 
2. For me the most tricky problem is everything must be done during package installation time so the UI must be autostart globally. I have to dig more in it. But can the prompt `Allow this connection` be embedded to daemon? Something like `opensnitch core` -> something like UI-less firewall? I think that could makes sense but ofc it brings development problems.

**Comment by dmknght** [comment]
so the solution is:
1. add `python3-grpc-tools` into `depends` for `opensnitch-ui`
2. Ui launcher at `/etc/xdg/autostart/`. Case solved :D

**Comment by gustavo-iniguez-goya** [comment]
> Debian packaged python3-grpc-tools already. Cheers! So it means no need for pip nor extra work. That explains why only grpcio worked for me :D

Aha, I see. Interesting, python3-grpc-tools is at version 1.14.x:
```apt show python3-grpc-tools
Package: python3-grpc-tools
Version: 1.14.1-1+b5
Depends: (...) python3-grpcio, python3-protobuf, (...)
```

however python3-grpcio version is at version 1.30.x:
```
apt show python3-grpcio
Package: python3-grpcio
Version: 1.30.2-3
```

python3-grpc-tools, nor python3-grpcio are packaged for Mint19.x, Debian 9 or Ubuntu <=18.04.

For the next release I'll provide a deb package without dialogs to install pip packages, adding `python3-grpcio` and `python3-protobuf` as dependencies. If someone needs the package without these dependencies, they'll still be able to install the package without them.

Thank you!
