### ISSUE TITLE
Offline Installation?

### ISSUE THREAD

**Issue by edent** [evilsocket/opensnitch#407]
Morning! Love the project. Is there a way to install this *before* a device connects to the Internet?

I copied across the two .deb files via a USB stick, but couldn't install them because of a lack of Python libraries. I don't want to connect my new machine to the net until OpenSnitch is installed.

Is there a downloadable list of all dependencies for Ubuntu?

I think this is similar to #237

**Comment by gustavo-iniguez-goya** [comment]
hi @edent !

> Is there a way to install this before a device connects to the Internet?

Not for now. If you have another computer, you can install the daemon on one computer and configure the Address to point to the other computer where you can launch the GUI to listen on a TCP socket:
computer1: `/etc/opensnitchd/default-config.json` -> `(...) "Address": "192.168.1.100:50051" (...)`
computer2 (192.168.1.100): `/usr/bin/opensnitch-ui --socket [::]:50051`

> Is there a downloadable list of all dependencies for Ubuntu?

I've extracted the dependencies on a kubuntu 20.04 using `apt-rdepends`:  [ui-deps.txt](https://github.com/evilsocket/opensnitch/files/6437940/ui-deps.txt) 

Probably you won't need all of them but I hope you'll find it useful :)

**Comment by dmknght** [comment]
> Morning! Love the project. Is there a way to install this _before_ a device connects to the Internet?
> 
> I copied across the two .deb files via a USB stick, but couldn't install them because of a lack of Python libraries. I don't want to connect my new machine to the net until OpenSnitch is installed.
> 
> Is there a downloadable list of all dependencies for Ubuntu?
> 
> I think this is similar to #237

You may want to check my topic #367 which solved problem. Unfortunately it is not having public `.deb` file and you have to compile it.

**Comment by gustavo-iniguez-goya** [comment]
answered.
