### ISSUE TITLE
Problem with AppImages

### ISSUE THREAD

**Issue by mariomadproductions** [evilsocket/opensnitch#408]
Hi. When using this app with an AppImage [(ArchiveWeb.page](https://github.com/webrecorder/archiveweb.page), I noticed that there doesn't seem to be a way to create an exception that works for different instances of the process - because app images seem to have a randomised process path (e.g.` /tmp/.mount_archivSJ24T4/archiveweb.page`). Maybe there is some way to change the AppImage behaviour (but I don't know if that's a good idea), or maybe there is something that could be changed on OpenSnitch's side?

**OS (please complete the following information):**
 - OS: Linux Mint
 - Window Manager: Cinnamon
 - Kernel version: Linux pc 5.4.0-72-generic #80-Ubuntu SMP Mon Apr 12 17:35:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
 - Version: 20.1

**Comment by gustavo-iniguez-goya** [comment]
Hi @mariomadproductions ,

Thank you for reporting this behaviour. There's a way to filter connections from this appimage (I have no idea if it'd apply to all appimages):

`[x] From this executable: ^(/tmp/\.mount_Archiv[0-9A-Za-z]+/archiveweb.page)$`

I've tested it and it works, but I don't know if the random part of the path could contain more characters like _ or - (in such case you should just have to include them between the [ ]).

**Comment by mariomadproductions** [comment]
Ah, reading an old issue I was under the impression that regex didn't work. Just tried that - works fine.

**Comment by gustavo-iniguez-goya** [comment]
I'll add this information to the wiki, thank you!

**Comment by nitschis** [comment]
I really think this should be automatic as it would be too confusing for most people.

Also, I think the wiki should be updated to (removing "Archive"):
`^(/tmp/\.mount_[0-9A-Za-z]+/archiveweb.page)$`
As "/tmp/\.mount_**Archiv**" is only relevant for this example.

**Comment by NRGLine4Sec** [comment]
@nitschis 
For some AppImage, the executable is not in the root path in the tmp directory. For example :
`^(/tmp/\.mount_KeePas.*/usr/bin/keepassxc)$`

**Comment by gustavo-iniguez-goya** [comment]
> Maybe a new "AppImage" dropdown option could be added, which automatically adds the executable this way.

I agree @nitschis . There's a feature request to add rules templates. We could add as you suggest a dropdown: AppImages, System Apps (ntpd, xbrlapi, dirmngr, /lib/systemd-*), etc

**Comment by mbnoimi** [comment]
> Maybe a new "AppImage" dropdown option could be added, which automatically adds the executable this way.

+1

**Comment by Jabster28** [comment]
couldn't this be faked though? any application could make an executable under an appimage directory that they assume the host has, and now that new executable inherits the rules of the actual application

**Comment by gustavo-iniguez-goya** [comment]
Yes @Jabster28 . Given that the appimages are uncompress to /tmp, anyone could brute force the temporary dirs that they create.

One way of mitigating this problem would be by creating restrictive rules. For example, instead of allowing only the cmdline, allow cmdline + UID + dst port + dst ip/host.

**Comment by nitschis** [comment]
I think a simple solution to this problem would be to save the checksum of the executable. This would be a security addition in general, but I think it should be optional to only use it with appimages.

**Comment by gustavo-iniguez-goya** [comment]
I agree, we've long discussed about this feature here #413
