### ISSUE TITLE
[Questions] How do I troubleshoot Not running status?

### ISSUE THREAD

**Issue by Techtonictools** [evilsocket/opensnitch#410]
I discovered opensnitch in a reddit post. It looks like a powerful tool. 

**Problem:**
OpenSitch UI has Not running status after installation

**To Reproduce**
Clean install latest debian 10 x64 buster on a Macbook Pro 17" 8,3 including 3rd party drivers/firmware for the NIC and gnome desktop
download the v1.4.0-rc 1 opensnitch amd64 .deb and python3 opensnitch ui all .db files from opensnitch installation page on github and install them 
follow the guidance from the debian package manager to fix the installation, then complete the installation.
as root create a directory for the socket file, set perms to logged in user
set the default-config.json Server.Address to use that directory
set defaultaction to deny and defaultduration to always
Launch the UI, reboot, try launching the UI again to see if the status changed

**Post error logs:** 
In /var/log/opensnitchd.log, there is a line that says it is starting to write to the log file. No text after that.

**If the daemon doesn't start:**
systemd says opensnitch.service is loaded active and running

**If the deb or rpm packages fail to install:**
 I used apt to fix the install so I don't have the spew, hopefully that error was be unrelated.

**Expected behavior (optional)**
I'd like for it to be running

**OS (please complete the following information):**
 - OS: Debian 10 buster
 - Window Manager: GNOME 3.30.2
 - Kernel version: Linux debian 4.19.0-16 amd64 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux
 
 
**Additional context**
There are two NICs. One wifi NIC with the BCM4331 chip and a wired BCM57765 chip that isn't currently connected, just the wifi is connected
the osui.sock file isn't created in the path specified in the default-config.json file
the service does appear to be blocking requests such as SMB share requests

**Comment by gustavo-iniguez-goya** [comment]
Hi @Techtonictools ,

Thank you for the detailed report, much appreciated.

> as root create a directory for the socket file, set perms to logged in user
> set the default-config.json Server.Address to use that directory

> systemd says opensnitch.service is loaded active and running

Probably it's due to the location change of the server address then.

Could you close the GUI and relaunch it from a terminal like this: `opensnitch-ui --socket /path/to/sock-file.sock` ?

**Comment by Techtonictools** [comment]
I closed the gui, dumped the processes and ran that command. The UI never opened. I don't see the UI when doing winkey+tab and I didn't see it there prior to executing the launch command. There were no entries in the log file for it.


	root@debian:/home/user# ps aux|grep opensnitch
	root       762  1.1  0.2 1981884 34444 ?       Ssl  13:13   0:00 /usr/bin/opensnitchd -rules-path /etc/opensnitchd/rules
	user      1380  0.0  0.0   2388   764 tty2     S+   13:13   0:00 /bin/sh -c pkill -15 opensnitch-ui; opensnitch-ui
	user      1389  2.4  0.8 1278580 131192 tty2   Sl+  13:13   0:01 /usr/bin/python3 /usr/bin/opensnitch-ui
	root      1572  0.0  0.0   6208   828 pts/0    S+   13:14   0:00 grep opensnitch
	root@debian:/home/user# opensnitch-ui --socket /home/user/opensnitch/handle.sock
	Loading translations: /usr/lib/python3/dist-packages/opensnitch/i18n locale: en_US
	Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
	No protocol specified
	qt.qpa.screen: QXcbConnection: Could not connect to display :0
	Could not connect to any X display.

	root@debian:/home/user# ls /home/user/opensnitch/
	total 8.0K
	drwxr-xr-x  2 user root 4.0K May 12 08:13 .
	drwxr-xr-x 19 user user 4.0K May 12 13:31 ..
	root@debian:/home/user#

**Comment by Techtonictools** [comment]
Here is the config file

	root@debian:/home/user# more /etc/opensnitchd/default-config.json 
	{
	    "Server":
	    {
		"Address":"unix:///home/user/opensnitch/handle.sock",
		"LogFile":"/var/log/opensnitchd.log"
	    },
	    "DefaultAction": "deny",
	    "DefaultDuration": "always",
	    "InterceptUnknown": false,
	    "ProcMonitorMethod": "proc",
	    "LogLevel": 2
	}
	root@debian:/home/user#

**Comment by gustavo-iniguez-goya** [comment]
ok, let me reproduce it. By the way, don't lunch the GUI as root. Try it again as your regular user.

**Comment by gustavo-iniguez-goya** [comment]
tested with: `opensnitch-ui --socket unix:///dev/shm/osui.sock` (notice the `unix://` prefix, it's important)
and: `Address": "unix:///dev/shm/osui.sock"`

and work as expected.

**Comment by Techtonictools** [comment]
I tried executing the command as a non-root user and have a different error. No log entries, but there is the spew:

user@debian:~$ opensnitch-ui --socket /home/user/opensnitch/handle.sock
	Loading translations: /usr/lib/python3/dist-packages/opensnitch/i18n locale: en_US
	Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
	E0512 14:40:57.408168868    5512 server_chttp2.cc:50]        {"created":"@1620855657.408150703","description":"Name or service not known","errno":-2,"file":"src/core/lib/iomgr/resolve_address_posix.cc","file_line":104,"os_error":"Name or service not known","syscall":"getaddrinfo","target_address":"/home/user/opensnitch/handle.sock"}
	Traceback (most recent call last):
	  File "/usr/bin/opensnitch-ui", line 71, in <module>
	    server.add_insecure_port(args.socket)
	  File "/usr/local/lib/python3.7/dist-packages/grpc/_server.py", line 962, in add_insecure_port
	    address, _add_insecure_port(self._state, _common.encode(address)))
	  File "/usr/local/lib/python3.7/dist-packages/grpc/_common.py", line 166, in validate_port_binding_result
	    raise RuntimeError(_ERROR_MESSAGE_PORT_BINDING_FAILED % address)
	RuntimeError: Failed to bind to address /home/user/opensnitch/handle.sock; set GRPC_VERBOSITY=debug environment variable to see detailed error message.
	user@debian:~$

**Comment by gustavo-iniguez-goya** [comment]
lunch it but adding `unix://` -> `user@debian:~$ opensnitch-ui --socket unix:///home/user/opensnitch/handle.sock`

**Comment by Techtonictools** [comment]
I didn't see that unix path prefix until now.  After executing that, the UI opens and now it shows the running status. Thanks, I'm looking forward to using it. How can I launch it from the GNOME UI favorites?

**Comment by gustavo-iniguez-goya** [comment]
I think that you have to drag&drop opensnitch icon from the list of apps to the left side of the screen where Gnome UI favorites usually is (I don't use Gnome so I'm just guessing here).

By the way, in order to make the change permanent modify the file `/home/user/.config/autostart/opensnitch_ui.desktop` and edit the line Exec=: `Exec=opensnitch-ui --socket unix:///home/user/opensnitch/handle.sock`

...I've just realized that the socket is not configurable from the GUI, I'll add it in coming releases.

And if you don't see the opensnitch systray icon in Gnome, you'll need to install the appindicator extension https://extensions.gnome.org/extension/615/appindicator-support/ (Gnome removed systray icons some months ago)

**Comment by Techtonictools** [comment]
Editing the .desktop fixed everything. My last question about launching from favorites was related to running the opensnitch UI outside a terminal window and with the .desktop change the UI is running now when launching from Gnome Activities. Thank you!
