### ISSUE TITLE
Install Instructions

### ISSUE THREAD

**Issue by SeaDude** [evilsocket/opensnitch#42]
Hello, 

I must be missing something in the install instructions: 

Using: 

`sudo apt-get install build-essential python-dev python-setuptools libnetfilter-queue-dev python-pyqt5` 

does not result in an `opensnitch` directory to `cd` into. Can't seem to find any `opensnitch` command on my machine after issuing these commands. 

Advice? 

Thanks

**Comment by arielf** [comment]
The instructions are missing the cloning of this git repository:
You need to have `git` installed and then do:
```
git clone https://github.com/evilsocket/opensnitch
```
before you can do the `cd opensnich`

**Comment by arielf** [comment]
Just found out that even with the repository and the full linux-source package installed, I get this error in the last step:

```
$ sudo python setup.py install

...

netfilterqueue.c:437:42: fatal error: libnfnetlink/linux_nfnetlink.h: No such file or directory

```
