### ISSUE TITLE
If UI Was Maximized, Cannot Restore From Minimize

### ISSUE THREAD

**Issue by metal450** [evilsocket/opensnitch#420]
**Describe the bug**
One bug I've observed ever since starting to use OpenSnitch: if the UI is maximized, then I minimize it to the taskbar, trying to restore it again fails.  Here's how to repro (on Kubuntu 20.04, using OpenSnitch 1.4.0rc2):

1) Click the OpenSnitch tray icon to reveal the UI
2) Maximize
3) Click OpenSnitch's item on the taskbar (to minimize)
4) Click OpenSnitch's item on the taskbar (to restore)
5) It does not restore - the UI flickers on screen for a bit, but it remains 'hidden.'  This is the bug.  To get it out of this 'stuck' state, you can either right click -> close from the systray & relaunch; or from the taskbar, you can right click->more actions->Maximize, after which you can again restore it from the taskbar.  However, if you maximize & then minimize it again, it will get stuck again.

Here's a video showing the behavior: 

https://user-images.githubusercontent.com/1877409/130189877-5b67a5f7-1273-4839-a38d-027b6608e9a1.mp4

**OS (please complete the following information):**
 - OS: Kubuntu 20.04
 - Window Manager: KDE
 - Kernel version: Linux Latitude-5490-Kubuntu 5.4.42-050442-generic #202005200734 SMP Wed May 20 07:36:21 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
 - Version [20.04

**Comment by themighty1** [comment]
Discussed earlier in https://github.com/gustavo-iniguez-goya/opensnitch/issues/77

**Comment by metal450** [comment]
Ah, I guess it didn't come up because it had been closed.  However, I've observed this ever since I started using OpenSnitch, just mentioning it now (as it was more of a nuisance than an actual "functional" issue)

**Comment by themighty1** [comment]
@gustavo-iniguez-goya , maybe you could tag this issue as "help wanted", so someone could find a universal fix which works for all DEs. The last time I tried to fix this, it worked in my DE but broke something in another DE.

**Comment by gustavo-iniguez-goya** [comment]
What if we apply your solution @themighty1 only for KDE by reading XDG_SESSION_DESKTOP environment variable? (or other method)

**Comment by gustavo-iniguez-goya** [comment]
fixed in latest v1.4.0
