### ISSUE TITLE
Add application description, eg `Application firewall`

### ISSUE THREAD

**Issue by ovari** [evilsocket/opensnitch#422]
1. Can a description for OpenSnitch please be added?
a) This will change `No description` to something like `Application firewall` (see image below)
b) This will show a description in the menu, say for Linux Mint
2. Can this description also be translatable?

![image](https://user-images.githubusercontent.com/17465872/119244121-91d18e00-bbb0-11eb-890f-eb273318a5e7.png)

What do you think?

Thank you

**Comment by gustavo-iniguez-goya** [comment]
Yeah, no problem!

Add this field to file `~/.config/autostart/opensnitch_ui.desktop`:
```
Comment=Application firewall
Comment[hu]=<HUNGARIAN TRANSLATION>
```

Test it out by closing/reopening the Startup applications dialog, and post here the translation to hungarian.

**Comment by ovari** [comment]
```
Comment=Application firewall
Comment[hu]=Alkalmazási tűzfal
```

Not sure, but is this a `web application firewall` or `application firewall`?

```
Comment=Web application firewall
Comment[hu]=Webalkalmazási tűzfal
```

If it is a `web application firewall`, other translations may be available at:
https://www.microsoft.com/en-us/language/Search?&searchTerm=Application%20firewall&langID=382&Source=true&productid=0

Thank you

**Comment by gustavo-iniguez-goya** [comment]
this is an application firewall. Thank you! I'll add the translation.

**Comment by ovari** [comment]
1. Can the GenericName have a translation? 
```
GenericName=OpenSnitch Firewall
GenericName[hu]=OpenSnitch tűzfal
```

2. It adds the description to the Startup Applications, but not to the Linux Mint Menu?

# Linux Mint Menu
![OpenSnitchLinuxMintMenu](https://user-images.githubusercontent.com/17465872/119253748-fe22b080-bbf5-11eb-9f38-c9bba5e791a3.png)

# Startup Applications
![OpenSnitchStartup](https://user-images.githubusercontent.com/17465872/119253749-ff53dd80-bbf5-11eb-8f13-0bcbbbfa7693.png)

Thank you

**Comment by gustavo-iniguez-goya** [comment]
Cinnamon will probably take the description from a different place than the Startup Applications dialog. I have no idea from where actually.

**Comment by ovari** [comment]
> Cinnamon will probably take the description from a different place than the Startup Applications dialog. I have no idea from where actually.

@clefebvre can you please provide assistance? Thank you

**Comment by gustavo-iniguez-goya** [comment]
> Cinnamon will probably take the description from a different place than the Startup Applications dialog. I have no idea from where actually.

Nope, sorry. I've just modified /usr/share/applications/opensnitch_ui.desktop and it displays the app description correctly on the Cinnamon menu

**Comment by ovari** [comment]
Thank you!

1. Does that mean that /usr/share/applications/opensnitch_ui.desktop will be populated with the same string? Or do we need to add this string somewhere else too?
1. Can something like the instructions below please be added to the [README.md](https://github.com/evilsocket/opensnitch#readme) file?

>* Please add something like the following line, in alphabetical order by `<LOCALE CODE>`, to [/ui/resources/opensnitch_ui.desktop](https://github.com/evilsocket/opensnitch/blob/master/ui/resources/opensnitch_ui.desktop)
`Comment[<LOCALE CODE>]=<LOCALE TRANSLATION>`
>
>* Please add something like the following line, in alphabetical order by `<LOCALE CODE>`, to [/ui/i18n/opensnitch_i18n.pro](https://github.com/evilsocket/opensnitch/blob/master/ui/i18n/opensnitch_i18n.pro)
`TRANSLATIONS += locales/<LOCALE CODE>/opensnitch-<LOCALE CODE>.ts`
>
>* Please create and add your translation at `https://github.com/evilsocket/opensnitch/blob/master/ui/i18n/locales/<LOCALE CODE>/opensnitch-<LOCALE CODE>.ts`

Thank you once again

**Comment by gustavo-iniguez-goya** [comment]
> Does that mean that /usr/share/applications/opensnitch_ui.desktop will be populated with the same string? Or do we need to add this string somewhere else too?

In reality, the file `~/.config/autostart/opensnitch_ui.desktop` is a symbolic link that points to `/usr/share/applications/opensnitch_ui.desktop`, so changing the strings in one side will be enough.

> Can something like the instructions below please be added to the README.md file?

Sure. I'll add it ASAP.

**Comment by ovari** [comment]
Should a link to the [i18n README.md](https://github.com/evilsocket/opensnitch/blob/master/ui/i18n/README.md) be added to the [main README.md](https://github.com/evilsocket/opensnitch#readme) page? Something to indicate to people visiting your main page that they can contribute a translation?

**Comment by gustavo-iniguez-goya** [comment]
No, I don't think that the link should go in the main README. There's already a note to redirect users to the wiki, where everything is centralized, including how to localize the GUI: https://github.com/evilsocket/opensnitch/wiki/Adding,-updating-and-installing-new-translations

I'll add there the rest of translations we've talked about here.

**Comment by ovari** [comment]
> Sure. I'll add it ASAP but to this [README.md](https://github.com/evilsocket/opensnitch/blob/master/ui/i18n/README.md) and to the wiki.

Can you please provide an update on this? Thank you

**Comment by gustavo-iniguez-goya** [comment]
I added instructions about how to translate the .desktop file here:
https://github.com/evilsocket/opensnitch/wiki/Adding,-updating-and-installing-new-translations

I didn't update the `ui/i18n/README.md` file because those instructions are specific for .ts files. Better centralized the informatio in one place.
