### ISSUE TITLE
[Question] Can I use the block lists feature as an allow lists?

### ISSUE THREAD

**Issue by Techtonictools** [evilsocket/opensnitch#425]
I'm liking OpenSnitch a lot since it is blocking things I didn't know were going on and it has a lot of power. I'm looking to use it to block everything except for what I want to allow. 

In another scenario outside of OpenSnitch using a Windows OS, a proxy tool and focusing on http requests, I began maintaining a block list along with ad blockers. But I quickly found there is more I want blocked than allowed. That realization flipped the approach perspective from "block domains" to "allow domains" to reduce the workload and be secure by default. I want to do that same thing with OpenSnitch on debian.

Should I be able to use OpenSnitch to only load requests from Firefox whose domain is in the HOSTS list file?

**Describe the bug**
I'm not sure there is a bug, but the request is to use an allow list in v1.4.0rc1 or later

**To Reproduce**
1. Create '000-firefox allow domains' rule and set: `[X] Priority rule` and have a domain list in the `[X} To this list of domains` with the HOSTS format.
Flip the `Action` from Deny to Allow
`[X] From this executable` and set firefox path (usr/lib/firefox-esr/firefox-esr)
2. Create rule '001-firefox deny all'  use `[X] From this executable` pointing to firefox-exr
`Action` Deny

**Steps to reproduce the behavior:**
1. Follow the above repro and in the file pointed to in the `000-firefox allow domains` rule add 127.0.0.1 www.speedtest.net
2. Launch firefox and load www.speedtest.net

**Post logs:** 
When performing the repro, the Events tab shows the initial page load request www.speedtest.net -> 53 UDP and the rule associated with it is 001-firefox deny all and the `Action` is deny.

**Expected behavior (optional)**
Some of the speedtest.net web page would load, but not requests from that page that have domains missing from the allow list

**OS (please complete the following information):**
 - OS: debian 10 x64
 - Window Manager: GNOME 3.3.02
 - Kernel version: 4.19.0-16-amd64

**Comment by gustavo-iniguez-goya** [comment]
hi @Techtonictools !

>  Can I use the block lists feature as an allow lists?

Yes, it should work.

I've tried to reproduce the bug, but it seems to work for me:
![image](https://user-images.githubusercontent.com/2742953/119397460-6d6fd180-bcd6-11eb-9c2b-c6a1c91376e5.png)

Notice how the speedtest layout is broken, due to not being able to load the css resources.

rules:
![image](https://user-images.githubusercontent.com/2742953/119398009-3cdc6780-bcd7-11eb-8315-08e8d43a7ae7.png)
![image](https://user-images.githubusercontent.com/2742953/119398112-61d0da80-bcd7-11eb-94a8-232363768da4.png)


```
$ cat /tmp/x/x.txt
127.0.0.1 www.speedtest.net
```

**Comment by gustavo-iniguez-goya** [comment]
uh, did you change the daemon action to Deny? 

![image](https://user-images.githubusercontent.com/2742953/119399140-cf313b00-bcd8-11eb-85a4-48878ba22a2c.png)

By default the default action is Allow.

**Comment by Techtonictools** [comment]
![opensnitch_allowdomainsrule](https://user-images.githubusercontent.com/49133697/119423439-1e1aa880-bcb8-11eb-966b-1f5d2a72c9ef.png)
![opensnitch_firefox deny all](https://user-images.githubusercontent.com/49133697/119423455-2a9f0100-bcb8-11eb-9158-2e19a5fe063c.png)
![opensnitch_prefs_nodes](https://user-images.githubusercontent.com/49133697/119423469-32f73c00-bcb8-11eb-981b-b778b040be01.png)
![opensnitch_events](https://user-images.githubusercontent.com/49133697/119423473-37235980-bcb8-11eb-9b48-49b8694a642c.png)
![opensnitch_rules](https://user-images.githubusercontent.com/49133697/119423723-c9c3f880-bcb8-11eb-85bc-e0041abd0161.png)


Any ideas? What additional information do you need to help me with this?

**Comment by Techtonictools** [comment]
In the rules list screen shot (not the rule itself), it shows rule 001-firefox `Action`  Allow because I allowed flipped the setting just to post the screen shot on the machine w/the problem. I normally have it set to Deny.

**Comment by gustavo-iniguez-goya** [comment]
I've reproduced it locally, so I'll investigate it. No idea why yesterday it worked for me.

**Comment by gustavo-iniguez-goya** [comment]
> I've reproduced it locally, so I'll investigate it. No idea why yesterday it worked for me.

oops, sorry, I was testing it with a wrong domain (speedtest.com instead of speedtest.net). So yes, I can confirm that it works for me.

The only difference I see, is that your rule `000-firefox...` has the field "operator_operand" empty. Could you edit that rule and save it again? if necessary restart the daemon, but be sure that the field is not empty, and then try it again.

**Comment by Techtonictools** [comment]
I edited the rule by changing the name, clicked apply then close and waited for the service to restart. After restart, that field value for operator_operand  is still blank. I created a new rule with the name 000 and same settings. The result is the same. The field is blank so now there are two rules with that anomaly. What should be there? 

Aside from that, an error that occurs which I don't know if it is related, When I'm in the rule creation dialog and click the search icon to select a directory for the exception list, the choose folder dialog appears behind the Rule dialog. In front is a black looking dialog that reads "python 3 "" is ready". I'm not sure if that is related to the problem your seeing, but it too is a 100% repro for me.

**Comment by Techtonictools** [comment]
> 
> 
> > I've reproduced it locally, so I'll investigate it. No idea why yesterday it worked for me.
> 
> oops, sorry, I was testing it with a wrong domain (speedtest.com instead of speedtest.net). So yes, I can confirm that it works for me.
> 
> The only difference I see, is that your rule `000-firefox...` has the field "operator_operand" empty. Could you edit that rule and save it again? if necessary restart the daemon, but be sure that the field is not empty, and then try it again.

What value do you have for the operator_operand column in the `000-firefox...` rule?

**Comment by Techtonictools** [comment]
Here is the screenshot of the python error mentioned in a comment above that occurs when attempting to choose the directory for the exception list

![image](https://user-images.githubusercontent.com/49133697/119873729-af1c9a00-bed9-11eb-9da7-3f875b69bb3e.png)

**Comment by gustavo-iniguez-goya** [comment]
> What value do you have for the operator_operand column in the 000-firefox... rule?

list

Ok, that field is empty when the rule is created from the GUI (instead of editing an existing one, created by the pop-up dialog). I'll try to reproduce it that way.

regarding the python error, I haven't seen it before, I'll try to reproduce it with Gnome

**Comment by gustavo-iniguez-goya** [comment]
> Ok, that field is empty when the rule is created from the GUI (instead of editing an existing one, created by the pop-up dialog). I'll try to reproduce it that way.

sorry, I'm unable to reproduce this problem :-/

> regarding the python error, I haven't seen it before, I'll try to reproduce it with Gnome

I've also tried to reproduce this problem, but it works for me (although not in Debian, but in Fedora)

Could you close the GUI and launch it from a terminal? maybe it outputs errors to the terminal.

**Comment by Techtonictools** [comment]
> 
> 
> > Ok, that field is empty when the rule is created from the GUI (instead of editing an existing one, created by the pop-up dialog). I'll try to reproduce it that way.
> 
> sorry, I'm unable to reproduce this problem :-/
> 
> > regarding the python error, I haven't seen it before, I'll try to reproduce it with Gnome
> 
> I've also tried to reproduce this problem, but it works for me (although not in Debian, but in Fedora)
> 
> Could you close the GUI and launch it from a terminal? maybe it outputs errors to the terminal.

I saw there was an updated release so I went to uninstall it using the directions on https://github.com/evilsocket/opensnitch/wiki/Installation, then installed the latest. The GUI doesn't communicate with the service, there isn't a node nor socket handle and systemctl status shows that there was an error parsing system-fw.json. 

So I looked in /etc/opensnitchd/ and the file isn't there. Just opensnitch.o and rules is in that directory. So I created the default-config.json and rebooted hoping it would start working but it doesn't find that system-fw.json file. So I can't launch the gui from the terminal to see if it outputs any errors. What goes in the system-fw.json?

**Comment by gustavo-iniguez-goya** [comment]
Also post the content of the rule `/etc/opensnitchd/rules/000-firefox allow domains`, maybe I can reproduce the problem by importing it on my system.

**Comment by gustavo-iniguez-goya** [comment]
> So I can't launch the gui from the terminal to see if it outputs any errors. What goes in the system-fw.json?

Reinstalling latest packages should install everything again.

**Comment by gustavo-iniguez-goya** [comment]
> I've also tried to reproduce this problem, but it works for me (although not in Debian, but in Fedora)

Finally, reproduced on debian 10, gnome.

**Comment by Techtonictools** [comment]
> 
> 
> Also post the content of the rule `/etc/opensnitchd/rules/000-firefox allow domains`, maybe I can reproduce the problem by importing it on my system.

I upgraded to the latest 1.4.0rc2 and instead of using the choose folder dialog to enter the directory path to the exception list in the '000-firefox allow' rule, I typed it in manually. The operator_operand value for that rule wasn't there after restarting the service. 

I tried to surf with those two rules setup in the new version and now the blocking and allow is working as expected. Then I went back to the UI and see the operator_operand is populated with the value `list`, but I didn't touch any config files. So all is good. 

As an aside, I'm looking for the request domains that get killed when loading a site because they are not in the exception list. I see in the event tab the domain is listed. But I'm looking for a way to copy the rejected domain I want to load so I can put it in the exception list. Is there a text log file I can copy from?

**Comment by gustavo-iniguez-goya** [comment]
> Is there a text log file I can copy from?

If you select a cell (regardless if the row is selected) and you hit CTRL-C, the value of that cell will be copied to the clipboard. You can do it in any lists, so you could double click on the events tab or the double click on the rule, and copy that domain.
Only one domain will be copied.

You can also save the list of events displayed, by clicking on the Save button. The list of events will be saved as CSV. If you filter by a word, or an action (deny/allow) only that list of events will be saved.

**Comment by Techtonictools** [comment]
> 
> 
> > Is there a text log file I can copy from?
> 
> If you select a cell (regardless if the row is selected) and you hit CTRL-C, the value of that cell will be copied to the clipboard. You can do it in any lists, so you could do it from the events tab or the double click on a rule, and copy that domain from the list.
> Only one domain will be copied.
> 
> You can also save the list of events displayed, by clicking on the Save button. The list of events will be saved as CSV. If you filter by a word, or an action (deny/allow) only that list of events will be saved.

Beautiful. Thank you! BTW, there was one repro step different between the opensnitch versions that I took. The first version I tried using a custom handle in my home/opensnitch directory. With the latest version, I left the IPC (or whatever) handle default `unix:/tmp/osui.sock`
