### ISSUE TITLE
Missing installation files 

### ISSUE THREAD

**Issue by Techtonictools** [evilsocket/opensnitch#428]
Hello, I'm test driving and learning how to use opensnitch. I had ver 1.4.0.rc-1 installed and was having a problem and wanted to upgrade to the latest. I followed the uninstall instructions then did the install of 1.4.0.rc2. The UI launches but it doesn't connect with the service.

**Post error logs:** 
Log output from systemctl
	● opensnitch.service - OpenSnitch is a GNU/Linux application firewall.
	   Loaded: loaded (/lib/systemd/system/opensnitch.service; enabled; vendor preset: enabled)
	   Active: active (running) since Thu 2021-05-27 14:26:20 PDT; 3min 22s ago
	     Docs: https://github.com/gustavo-iniguez-goya/opensnitch/wiki
	  Process: 770 ExecStartPre=/bin/mkdir -p /etc/opensnitchd/rules (code=exited, status=0/SUCCESS)
	 Main PID: 774 (opensnitchd)
	    Tasks: 18 (limit: 4915)
	   Memory: 64.4M
	   CGroup: /system.slice/opensnitch.service
		   └─774 /usr/bin/opensnitchd -rules-path /etc/opensnitchd/rules

	May 27 14:26:20 debian systemd[1]: Starting OpenSnitch is a GNU/Linux application firewall....
	May 27 14:26:20 debian systemd[1]: Started OpenSnitch is a GNU/Linux application firewall..
	May 27 14:26:20 debian opensnitchd[774]: [2021-05-27 21:26:20]  IMP  Starting opensnitch-daemon v1.4.0rc2
	May 27 14:26:20 debian opensnitchd[774]: [2021-05-27 21:26:20]  INF  Loading rules from /etc/opensnitchd/rules ...
	May 27 14:26:20 debian opensnitchd[774]: [2021-05-27 21:26:20]  ERR  Error parsing firewall configuration /etc/opensnitchd/system-fw.json: unexpected end of JSO
	May 27 14:26:20 debian opensnitchd[774]: [2021-05-27 21:26:20]  ERR  Error parsing configuration /etc/opensnitchd/default-config.json: unexpected end of JSON in
	May 27 14:26:20 debian opensnitchd[774]: [2021-05-27 21:26:20]  INF  Process monitor method /proc
	May 27 14:26:20 debian opensnitchd[774]: [2021-05-27 21:26:20]  INF  Running on netfilter queue #0 ...

log file:
	[2021-05-27 21:48:30]  IMP  Start writing logs to /var/log/opensnitchd.log

	[2021-05-27 22:09:55]  IMP  Got signal: terminated
	[2021-05-27 22:12:03]  IMP  Start writing logs to /var/log/opensnitchd.log

	[2021-05-27 22:16:51]  IMP  Got signal: terminated
	[2021-05-27 22:18:07]  IMP  Start writing logs to /var/log/opensnitchd.log

	[2021-05-27 22:20:17]  IMP  Got signal: terminated

uninstall spew:

	theUser@debian:~/Downloads$ sudo apt remove opensnitch python3-opensnitchui
	Reading package lists... Done
	Building dependency tree       
	Reading state information... Done
	E: Unable to locate package python3-opensnitchui
	theUser@debian:~/Downloads$ sudo apt remove opensnitch python3-opensnitch-ui
	Reading package lists... Done
	Building dependency tree       
	Reading state information... Done
	The following packages were automatically installed and are no longer required:
	  dh-python libdouble-conversion1 libexpat1-dev libnetfilter-queue1 libpcre2-16-0 libpython3-dev libpython3.7-dev libqt5core5a libqt5dbus5 libqt5designer5
	  libqt5gui5 libqt5help5 libqt5network5 libqt5printsupport5 libqt5sql5 libqt5sql5-sqlite libqt5svg5 libqt5test5 libqt5widgets5 libqt5xml5 libxcb-xinerama0
	  python-pip-whl python3-crypto python3-dev python3-entrypoints python3-keyring python3-keyrings.alt python3-pip python3-pyinotify python3-pyqt5
	  python3-pyqt5.qtsql python3-secretstorage python3-sip python3-wheel python3.7-dev qt5-gtk-platformtheme qttranslations5-l10n
	Use 'sudo apt autoremove' to remove them.
	The following packages will be REMOVED:
	  opensnitch python3-opensnitch-ui
	0 upgraded, 0 newly installed, 2 to remove and 4 not upgraded.
	After this operation, 25.8 MB disk space will be freed.
	Do you want to continue? [Y/n] y
	(Reading database ... 169816 files and directories currently installed.)
	Removing opensnitch (1.4.0~rc2-1) ...
	Synchronizing state of opensnitch.service with SysV service script with /lib/systemd/systemd-sysv-install.
	Executing: /lib/systemd/systemd-sysv-install disable opensnitch
	Removed /etc/systemd/system/multi-user.target.wants/opensnitch.service.
	Removing python3-opensnitch-ui (1.4.0~rc2-1) ...
	Processing triggers for mime-support (3.62) ...
	Processing triggers for hicolor-icon-theme (0.17-2) ...
	Processing triggers for gnome-menus (3.31.4-3) ...
	Processing triggers for desktop-file-utils (0.23-4) ...
	theUser@debian:~/Downloads$ sudo rm /etc/opensnitchd -r
	theUser@debian:~/Downloads$ sudo rm -rf /etc/opensnitchd
	theUser@debian:~/Downloads$

install spew:

	theUser@debian:~/Downloads$ sudo dpkg -i opensnitch_1.4.0.rc2-1_amd64.deb python3-opensnitch-ui_1.4.0.rc2-1_all.deb;sudo apt -f install
	Selecting previously unselected package opensnitch.
	(Reading database ... 168807 files and directories currently installed.)
	Preparing to unpack opensnitch_1.4.0.rc2-1_amd64.deb ...
	Unpacking opensnitch (1.4.0~rc2-1) ...
	Selecting previously unselected package python3-opensnitch-ui.
	Preparing to unpack python3-opensnitch-ui_1.4.0.rc2-1_all.deb ...
	Unpacking python3-opensnitch-ui (1.4.0~rc2-1) ...
	Setting up opensnitch (1.4.0~rc2-1) ...
	Removed /etc/systemd/system/opensnitch.service.
	Synchronizing state of opensnitch.service with SysV service script with /lib/systemd/systemd-sysv-install.
	Executing: /lib/systemd/systemd-sysv-install enable opensnitch
	Created symlink /etc/systemd/system/multi-user.target.wants/opensnitch.service → /lib/systemd/system/opensnitch.service.
	Setting up python3-opensnitch-ui (1.4.0~rc2-1) ...
	gtk-update-icon-cache: Cache file created successfully.
	Processing triggers for systemd (241-7~deb10u7) ...
	Processing triggers for gnome-menus (3.31.4-3) ...
	Processing triggers for desktop-file-utils (0.23-4) ...
	Processing triggers for mime-support (3.62) ...
	Processing triggers for hicolor-icon-theme (0.17-2) ...
	Reading package lists... Done
	Building dependency tree       
	Reading state information... Done
	0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.

directory listing to find system-fw.json

	theUser@debian:~/Downloads$ ls /etc/opensnitchd
	total 20K
	drwxr-xr-x   3 root root 4.0K May 27 15:22 .
	drwxr-xr-x 130 root root  12K May 27 15:22 ..
	drwxr-xr-x   2 root root 4.0K May 27 15:22 rules
	theUser@debian:~/Downloads$

**OS (please complete the following information):**
 - OS: debian 10.9 x64 buster
 - Window Manager: GNOME 3.30.2
 - Kernel version: Linux debian 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux

**Comment by gustavo-iniguez-goya** [comment]
Ok, it seems that removing the directory `/etc/opensnitchd` by hand breaks the apt somehow.

Type this:  `apt remove --purge opensnitch`; `dpkg -i opensnitch_1.4.0.rc2-1_amd64.deb`

I'll update the wiki to clarify the uninstallation steps.

**Comment by Techtonictools** [comment]
That solved the problem. Thank you.
