### ISSUE TITLE
[FAQ] General working principles

### ISSUE THREAD

**Issue by tr13dm03** [evilsocket/opensnitch#431]
It would be useful and interesting for newcomers to be able to read a general overview of how the program accomplishes its intended task and its general working principles in the FAQ section, or somewhere else.

**Comment by gustavo-iniguez-goya** [comment]
Hi @tr13dm03 ,

There're some general info in the FAQ section and much more in detail [here](https://github.com/evilsocket/opensnitch/wiki/Why-OpenSnitch-does-not-intercept-application-XXX).

But basically:

When a local process opens a new connection, the connection is redirected to a [netfilter queue](https://www.netfilter.org/projects/libnetfilter_queue/index.html). 

Our daemon listens on that queue, parses the connection and tries to get the PID of the process that initiated it.

If the properties of the Process and/or the connection don't match with any rule, we prompt the user to allow or deny the outgoing connection.
