### ISSUE TITLE
opensnitch-ui / AttributeError: type object 'Config' has no attribute 'init'

### ISSUE THREAD

**Issue by shollingsworth** [evilsocket/opensnitch#439]
Hello, I'm running into an issue on Ubuntu 20.04 after installing the deb packages for `1.3.6-1`

Recieving the following error
```
Loading translations: /usr/local/lib/python3.8/dist-packages/opensnitch/i18n locale: en_US
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
Traceback (most recent call last):
  File "/usr/bin/opensnitch-ui", line 60, in <module>
    service = UIService(app, on_exit)
  File "/usr/local/lib/python3.8/dist-packages/opensnitch/service.py", line 43, in __init__
    self._cfg = Config.init()
AttributeError: type object 'Config' has no attribute 'init'
```

pip is showing these packages installed

```
# installed
unicode_slugify==0.1.3
grpcio==1.38.0
grpcio-tools==1.38.0
pyinotify==0.9.6
PyQt5==5.14.1
protobuf==3.17.3
```

Anybody have ideas on how to fix it?

I did try to compile the latest release candidate but got the same errors.

TIA! :)

**Comment by gustavo-iniguez-goya** [comment]
Hi @shollingsworth !

> object 'Config' has no attribute 'init'

Verify please that you're not mixing different releases, Config class has an init() method https://github.com/evilsocket/opensnitch/blob/1c73a48b9c01b4656148c52b798ee7e3874b4923/ui/opensnitch/config.py#L46

I've just compiled latest sources on a fresh VM and has worked as expected.

Delete everything from /usr/lib/python3/dist-packages/opensnitch/* /usr/lib/python3.8/dist-packages/opensnitch/*  /usr/local/lib/python3/dist-packages/opensnitch/* /usr/local/lib/python3.8/dist-packages/opensnitch/* and try again.

**Comment by shollingsworth** [comment]
Did some more digging, and it looks like my problem was a conflict with a package named "config"

I'll look at the `ui/` source and see if there might be a way to avoid this. Thanks for looking into this!

```Name: config
Version: 0.5.0.post0
Summary: A hierarchical, easy-to-use, powerful configuration module for Python
Home-page: http://docs.red-dove.com/cfg/python.html
Author: Vinay Sajip
Author-email: vinay_sajip@red-dove.com
License: Copyright (C) 2004-2020 by Vinay Sajip. All Rights Reserved. See LICENSE for license.
Location: /usr/local/lib/python3.8/dist-packages
```
