### ISSUE TITLE
Use the firewall zone defined in NetwrokManager

### ISSUE THREAD

**Issue by dzamlo** [evilsocket/opensnitch#44]
If you install and start [firewalld](http://www.firewalld.org/), you can set a zone for each connection in NetworkManager. It would be very nice if it was possible to use them for filtering (allowing an application only in one zone for example). 
As far as I understand, NetworkManager use D-Bus to communicate the zone of the connection with firewalld.

**Comment by hobarrera** [comment]
Not at all a fan of this. This restricts usage of opensnitch to just NetworkManager users. An alternate GUI can be developed for this sort of thing once the deamon/UI split is done.
