### ISSUE TITLE
[Doc request]  Please add Getting Started section to Wiki

### ISSUE THREAD

**Issue by BillDietrich** [evilsocket/opensnitch#444]
I've just started using OpenSnitch, and I'm pretty confused, maybe some of this is wrong.

Please add a "Getting Started" section containing something like:

1- Do the installation as specified in [URL].

2- Launch the app through your system GUI.

3- See the OpenSnitch icon [icon] appear in System Tray.

4- You may see alerts start to pop up right away, saying "app X tried to access IP address N".  For each first-time alert, the default should be "deny", and you have 15 seconds to change that to "allow" if you wish.

5- To see and modify the rules accumulated so far, click on the OpenSnitch icon in the System Tray.  A GUI listing the rules will appear.  You can click on each rule and then click on the Trash Can icon to delete it.  Or you can click on a rule and right-click on it to modify allow/deny or duration etc.  The list may take up to 15 seconds to show the update in the GUI.  Note: if you modify the action of a rule (e.g. change from deny to allow), the name of it may not change (e.g. may stay as "deny-...").

6- You can double-click on a rule to open it and see a list of sub-rules it contains.

7- Some standard accesses/rules you probably want to change to allow/always: in Fedora, Network Manager accessing fedoraproject.org (why ?), systemd-resolved accessing many domains on port 53 (DNS), and chronyd accessing a variety of IP addresses to UDP port 123 (Network Time Protocol).

8- Test that OpenSnitch is working.  Change a rule for your browser to "deny" and try to access a page.

**Comment by BillDietrich** [comment]
Guess I forgot to set a title on the request, sorry.

Please add:

9- Icons in top-left of GUI:

- [floppy disk icon]: save configuration as a CSV file.

- [green-red icon]: open Preferences.  (note: tool-tip for this icon is missing)

- [file-plus icon]: create a new rule.  New rule will have no sub-rules (I assume this is okay).

**Comment by gustavo-iniguez-goya** [comment]
Than you @BillDietrich !

I've updated the Getting Started section: https://github.com/evilsocket/opensnitch/wiki/Getting-started

**Comment by BillDietrich** [comment]
Looks good, thanks !

For me, OpenSnitch started with "Deny" as default.

Typo in the text: "blicking".

**Comment by gustavo-iniguez-goya** [comment]
fixed.

**Comment by gustavo-iniguez-goya** [comment]
Thank you @BillDietrich for your suggestions and comments, much appreciated!
