### ISSUE TITLE
Could not start opensnitch-ui

### ISSUE THREAD

**Issue by echometer** [evilsocket/opensnitch#447]
Hello, I'm a Manjaro user and I installed opensnitch through the aur. 

**Describe the bug**
I cannot start opensnitch-ui

**To Reproduce**
run opensnitch-ui in terminal

run opensnitch-ui in terminal

**Post error logs:** 
Traceback (most recent call last):
  File "/usr/bin/opensnitch-ui", line 16, in <module>
    import grpc
  File "/usr/lib/python3.9/site-packages/grpc/__init__.py", line 23, in <module>
    from grpc._cython import cygrpc as _cygrpc
ImportError: libabsl_strings.so.2103.0.1: cannot open shared object file: No such file or directory

**OS (please complete the following information):**
 - OS: Manjaro
 - Window Manager: xfce4
 - Kernel version: `Linux hhl-pc 5.12.9-1-MANJARO #1 SMP PREEMPT Thu Jun 3 14:56:42 UTC 2021 x86_64 GNU/Linux`
 - Version 21.0.7 "Ornara"

**Comment by echometer** [comment]
I installed abseil-cpp instead of abseil-cpp-git and it was able to run

**Comment by gustavo-iniguez-goya** [comment]
Thank you @echometer for report it. It'll serve as a log for future users :)
