### ISSUE TITLE
unison trafic not catch !

### ISSUE THREAD

**Issue by Maziar123** [evilsocket/opensnitch#451]
i use ver 1.4.0.rc.2.r26

seems traffic of unison direct server  not catch !
(unison https://www.cis.upenn.edu/~bcpierce/unison/)

my use for example unison -socket xxxx

xxxx= any number

**Comment by gustavo-iniguez-goya** [comment]
Hi @Maziar123 ,

I've just tested this:

![image](https://user-images.githubusercontent.com/2742953/124817179-b79cd180-df69-11eb-99d1-b068a70e46f6.png)

computer1: unison -socket 12345
compuert2: unison -testServer /tmp/unison/ socket://192.168.1.103:12345/tmp/

Can you provide more details on how do you launch client and server?

**Comment by Maziar123** [comment]
server linux " computer1: unison -socket 2022
client linux gui direct tcp coonection 


my linux manjaro last update

**Comment by gustavo-iniguez-goya** [comment]
tested with the unison gui:
![image](https://user-images.githubusercontent.com/2742953/124903843-aa70f880-dfe4-11eb-90fd-ab6aba379e44.png)

Please, provide more details:
- output of iptables -V
- output of iptables -t mangle -L
- IP of both computers.
- Settings of unison-gtk (screenshot of the profile used for example, showing the ).
- /var/log/opensnitchd.log in DEBUG mode (Preferences -> Nodes -> log level: DEBUG

**Comment by Maziar123** [comment]
1.  iptables -V -> iptables v1.8.7 (nf_tables)

2.iptables -t mangle -L
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination         

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination         
LIBVIRT_PRT  all  --  anywhere             anywhere            

Chain LIBVIRT_PRT (1 references)
target     prot opt source               destination         
CHECKSUM   udp  --  anywhere             anywhere             udp dpt:bootpc CHECKSUM fill
CHECKSUM   udp  --  anywhere             anywhere             udp dpt:bootpc CHECKSUM fill
CHECKSUM   udp  --  anywhere             anywhere             udp dpt:bootpc CHECKSUM fill

3. both internal LAN 172.16.xx.xx


4.setting of unison is default TCP direct from Linux to linux-server

**Comment by gustavo-iniguez-goya** [comment]
ok, still no clues. Could you post the nft ruleset? -> `nft list ruleset` 

Silly question: if you try to connect to the unison server using telnet (or nc) does opensnitch intercepts the connection? 
 server: `unison -socket 12345`
 client: `telnet a.b.c.d 12345`

Could you also verify that no other rule is allowing the unison traffic? I know that it sounds obvious... but I have no idea why it's not working for you.

**Comment by gustavo-iniguez-goya** [comment]
closing due to lack of information. 

In order to continue investigating this issue:
- Set daemon's log level to DEBUG (Preferences->Nodes->Default log level)
- write the exact commands typed in the terminal
- dump unison logs to a file using the flag `-log`
- post the file `/var/log/opensnitchd.log` 
- Write the date when you started the test, to be able to match it against the opensnitchd.log.
