### ISSUE TITLE
Opensnitch will never open

### ISSUE THREAD

**Issue by alexholox** [evilsocket/opensnitch#453]
Hi, I'm on openSUSE Leap 15.3. My problem is opensnitch will never open no matter what. It will load for less than a second and then closeimmediately, so I can't use it. I have installed both the GUI and the daemon from YaST and I can't open this program. Is there any solution to this? The installation guide says you tested it briefly on this distro, so it shouldn't be incompatible. Please help, and many thanks in advance.

**Comment by gustavo-iniguez-goya** [comment]
Hi @alexholox ,

I just tested it on OpenSuse Leap 15.3 (livecd iso) and worked as expected, using https://github.com/evilsocket/opensnitch/releases/download/v1.4.0-rc.2/opensnitch-1.4.0rc2-1.x86_64.rpm and https://github.com/evilsocket/opensnitch/releases/download/v1.4.0-rc.2/opensnitch-ui-1.4.0rc2-1.fc29.noarch.rpm

- What version did you install?
- Could you launch `opensnitch-ui` from a terminal and paste the output?

**Comment by alexholox** [comment]
The downloads you posted somehow updated my build and now it opens. Many thanks.

The ones I downloaded before this were the ones in the release page: https://github.com/evilsocket/opensnitch/releases/tag/v1.3.6

Somehow this new links are different. Anyone having problems, use what Gustavo just posted.

**Comment by gustavo-iniguez-goya** [comment]
The links I posted are the version v1.4.0rc which is not released yet, so github doesn't list it as the latest "stable" release.
I think that we're very close to release the v1.4.0.
