### ISSUE TITLE
1.40rc2 not letting through ICMP

### ISSUE THREAD

**Issue by byReqz** [evilsocket/opensnitch#455]
Hi, 

ive been using the -git version from the AUR for ages but since the update to 1.40rc2 yesterday, no pings are getting through.

**To Reproduce:**
It stops working as soon as you install 1.40rc2 for me. The "stable" 1.3.6 works fine. Also works when the FW is turned off (obviously).

**Post error logs:** 
The log on debug mode does not mention anything about the connections but shows everything else fine. Nping and Ping ICMP probes just time out on local and on remote hosts without any answers.

**Expected behavior (optional)**
ICMP not being touched by opensnitch.

**Screenshots**
no errors present

**OS (please complete the following information):**
 - OS: Arch Linux
 - Window Manager: KDE Plasma 5.22.3
 - Kernel version: 5.12.15-arch1-1
 - Backend: nftables (iptables-nft, using iptables itself does not change anything)

**Additional context**
Clean building the Package did not help. /etc/opensnitchd/system-fw.json (which allows ICMP) is present but doesnt seem to be used.

**Comment by gustavo-iniguez-goya** [comment]
>     Backend: nftables (iptables-nft, using iptables itself does not change anything)

Thank you for the detailed information @byReqz ! It really helps to analyze the problems.

I think that opensnitch is using nftables, which was added recently, but the system-fw rules haven't been adapted to work with nftables yet. Could you verify that you have opensnitch firewall ruless added to nftables? `nft list ruleset` , the should be two nftables tables (opensnitch-filter for ip and ip6).

**Comment by byReqz** [comment]
Hi, yeah there are opensnitch-filter and opensnitch-magle for IPv4 and 6.

**Comment by gustavo-iniguez-goya** [comment]
ok, unfortunately nftables system-fw.json feature is not ready yet, finished but it needs more work.

This rule should allow ICMP traffic:
`nft insert rule opensnitch-mangle output icmp type { echo-request,echo-reply } accept`

**Comment by byReqz** [comment]
Thanks for your answer but it doesn't seem to work. 

![123](https://user-images.githubusercontent.com/32552517/125619577-52cc2b9d-9554-4045-a555-71dd6a7db31d.png)

**Comment by sonsu** [comment]
I am having the same issue on 
OS: Ubuntu LTS 20.04 Desktop (minimal) install with 1.4.0.rc2
Extra info:
 `nft` command is not installed, tcp/udp works as expected, but ICMP just hangs
```
x@x-virtual-machine:~$ cat /etc/opensnitchd/system-fw.json 
{
    "SystemRules": [
        {
            "Rule": {
                "Description": "Allow icmp",
                "Table": "mangle",
                "Chain": "OUTPUT",
                "Parameters": "-p icmp",
                "Target": "ACCEPT",
                "TargetParameters": ""
            }
        }
    ]
}
```

When reverted back to 1.3.6, ICMP works as expected (is allowed through)

**Comment by gustavo-iniguez-goya** [comment]
For now if the firewall in use is nftables and the DefaultAction is deny ICMP will be blocked. I'm making progress to allow to configure nftables system firewall so we can allow it and configure other rules.

In your case @sonsu, what's the output of `iptables -V`?

**Comment by pizzadude** [comment]
I have the same problem. Fedora 34, which uses nftables & firewalld frontend. Default action on GUI is allow, default action in nodes is deny. ICMP is blocked. I can't connect to my VPN with the firewall enabled either.

**Comment by pizzadude** [comment]
I think I fixed it. By checking "Intercept Unknown Connections", I am able to allow the wireguard vpn connection with opensnitch.

**Comment by pizzadude** [comment]
I have the same issue in the latest opensnitch version in Fedora 34. Unless I disable the daemon completely, I can't ping anything.

**Comment by vebmaster** [comment]
debian 10
ping doesn't work

**Comment by Arjdroid** [comment]
Having the same issue here on Arch Linux latest using opensnitch-git from the AUR. I am using iptables-nft. 

Output of `sudo iptables -V` is `iptables v1.8.7 (nf_tables)`

Output of `sudo opensnitchd -version` is `1.4.0rc3`

All ICMP requests _do_ trigger an alert but even if I click allow the ping response is not there.

**Comment by vebmaster** [comment]
debian 10
Build from source code (26.07.2021)
1.4.0rc3
ping doesn't work
```
sudo opensnitchd -version
[2021-07-26 11:52:04]  INF  iptables version: [iptables v1.8.2 (nf_tables)
]
[2021-07-26 11:52:04]  WAR  iptables not available: fw, using nftables instead of iptables ([iptables v1.8.2 (nf_tables)
])
1.4.0rc3
```

**Comment by gustavo-iniguez-goya** [comment]
I changed how the firewall type to use is determined. By default we'll use iptables, that way we can use system-fw.json to add rules (to allow icmp for example). 

If someone needs to use nftables, then they can use `"Firewall": "nftables"` (default-config.json). nftables' system-fw.json is not ready yet.

**Comment by molitona** [comment]
> Thanks for your answer but it doesn't seem to work.
> 
> ![123](https://user-images.githubusercontent.com/32552517/125619577-52cc2b9d-9554-4045-a555-71dd6a7db31d.png)

Works, but not persistent. And, here is how I made it persist on Arch too (This is my own solution, many ways discussed with developer before to no avail).

> !/bin/bash
> 
> IFACE=$1
> ACTION=$2
> 
> if [[ $ACTION = up ]]; then
>     if [[ $IFACE = wlp6s0 ]]; then
> 	 nft insert rule opensnitch-mangle output icmp type echo-request accept
>     fi
> fi

in

> /etc/NetworkManager/dispatcher.d


Then

> sudo systemctl restart NetworkManager.service

**Comment by andryyy** [comment]
Still doesn't work for me on a Mint 20.2 with iptables.

My default for iptables is iptables-legacy, if that matters.

When I use nft it fails, too:

```
[2021-08-19 13:57:46]  WAR  nftables mangle rules not loaded: 0
[2021-08-19 13:57:46]  WAR  Error adding nftables mangle tables:%!(EXTRA *fmt.wrapError=Receive: netlink receive: no such file or directory)
[2021-08-19 13:57:46]  ERR  Error while Running DNS nftables rule: Receive: netlink receive: no such file or directory
[2021-08-19 13:58:16]  WAR  nftables mangle rules not loaded: 0
[2021-08-19 13:58:16]  ERR  Error while Running DNS nftables rule: Receive: netlink receive: no such file or directory
[2021-08-19 13:58:46]  WAR  nftables mangle rules not loaded: 0
[2021-08-19 13:58:46]  ERR  Error while Running DNS nftables rule: Receive: netlink receive: no such file or directory

```

Probably because of missing tables. I created the mangle table and it only complained about the DNS nftables rule. Is there a default set I should import?

**Comment by gustavo-iniguez-goya** [comment]
Be sure that the item "Firewall": "iptables" exists in /etc/opensnitchd/default-config.json , and restart the daemon (service opensntich restart)

**Comment by andryyy** [comment]
I did and also pulled a fresh copy of that file.

I purge everything and will try again tomorrow. :)

**Comment by seonwoolee** [comment]
I too am having this problem on Arch Linux, using iptables ` v1.8.7 (legacy)` and opensnitch version 1.4.0.rc3. I put `"Firewall": "iptables" in ` /etc/opensnitchd/default-config.json`, restarted opensnitchd, and it still doesn't work.

**Comment by gustavo-iniguez-goya** [comment]
hey @seonwoolee , thank you for reporting this.

problem found. Will fix it soon.

**Comment by andryyy** [comment]
In the meantime I forgot to post my test results. They were negative obviously. :)

Thanks for looking into it!

**Comment by vebmaster** [comment]
> Works, but not persistent.

what is the name of this console client what is on the screen?

**Comment by molitona** [comment]
It's not my screenshot (I replied to an existing comment).
BTW, It's a zsh shell custom theme (I guess it's powerlevel10k). Basically, they're shell scripts to customize shell prompt for the awesome ZSH shell.

**Comment by gustavo-iniguez-goya** [comment]
@molitona @andryyy @seonwoolee could you test latest change to see if the ICMP works again (i.e.: if the rules defined in /etc/opensnitchd/system-fw.json take precedence over the interception ones).

I've also realized that we're denying connections that we can't parse, unconditionally, ignoring what was defined in the configuration.
