### ISSUE TITLE
after system crash opensnitch-ui wont start because db is corrupted

### ISSUE THREAD

**Issue by themighty1** [evilsocket/opensnitch#460]
My machine crashed, upon restart opensnitch-ui gives:

> Loading translations: /usr/local/lib/python3.8/dist-packages/opensnitch/i18n locale: en_US
> QSqlQuery::value: not positioned on a valid record
> None setQuery() exception:  int() argument must be a string, a bytes-like object or a number, not 'NoneType'
> setQuery() error:  database disk image is malformed Unable to execute statement
> Segmentation fault (core dumped)

I manually deleted the db file on disk and successfully restarted opensnitch-ui.

Maybe there should be an info popup saying sth like "db file /tmp/file.db is corrupted. pls remove and try again"

**Comment by gustavo-iniguez-goya** [comment]
hey,

Yeah, besides showing a pop-up if the DB is corrupted, we could set some flags to ON if the DB file is gonna be written to disk:
PRAGMA journal_mode = ON
PRAGMA synchronous = ON

they're set to off now, I didn't take it into account when allowing to write events to disk.

By the way, can you recover to DB with: `sqlite3 file.db ".recover" | sqlite3 new.db` ?

**Comment by themighty1** [comment]
oops, already releted the corrupted db, sorry

**Comment by gustavo-iniguez-goya** [comment]
@themighty1 what would be a good message for the warning dialog?

"The DB is corrupted and it's not safe to continue. Remove, backup or recover the file before continue."

I just tried `sqlite3 corrupted.db .recover | sqlite3 new.db` and works fine.
