### ISSUE TITLE
[Feature request] Disable notifications in the tray

### ISSUE THREAD

**Issue by vebmaster** [evilsocket/opensnitch#462]
Hello.
You can add a parameter to the settings that allows you to disable notifications in the tray when unknown connections are blocked. So that there are no notifications at all.
Thank you.

**Comment by gustavo-iniguez-goya** [comment]
Hi @vebmaster ,

Give us more details, 
- is the notification fired after answering to the pop-up dialog?
- is the notification fired having On or Off [x] Intercept unknown connections?
- is the notification fired even without answering the pop-ups?
- etc

**Comment by vebmaster** [comment]
> is the notification fired after answering to the pop-up dialog?
pop-up dialog disable

> is the notification fired having On or Off [x] Intercept unknown connections?
The notification appears only with the enabled option

> is the notification fired even without answering the pop-ups?
pop-up dialog disable

**Comment by gustavo-iniguez-goya** [comment]
thank you @vebmaster , it'll be added

**Comment by TheTee82** [comment]
@gustavo-iniguez-goya 

Not sure if related or not (or perhaps making it easier for you):
- on KDE (5.x)
  - opensnitch-ui does not proper identify itself as an application to the system
  - it is possible to disable all notifications for an app via `System Settings` -> `Notifications` -> `Applications: [Configure]` and selecting the proper application and then disable the `Show popups` checkbox (see screenshot below)
    - opensnitch-ui notifications can currently only be disabled by selecting `Other applications` which in turn disables popups for ALL other applications

I'm not sure if this is a viable workaround or if it's easier for you to internally disable notifications.

![image](https://user-images.githubusercontent.com/60312106/129517676-2211c298-fed4-4db8-bfb9-fb58ef3b6274.png)

**Comment by gustavo-iniguez-goya** [comment]
Since 843412d73e7af8b91524a63d889e99f5cb9af149 it's possible to disable all notifications, as well as the pop-ups, from the Preferences dialog.

Regarding the integration with DEs, now it's possible to configure notifications from the system settings of every DE, if System notifications is selected in OpenSnitch.

**Comment by TheTee82** [comment]
@gustavo-iniguez-goya 

>it's possible to disable all notifications, as well as the pop-ups, from the Preferences dialog

Great.
Tested on 1.5.0rc2 and both options work very fine now:
- when 'Desktop notifications' in Preferences -> UI are disabled
- when 'Desktop notifications' in Preferences -> UI are enabled AND KDE Settings -> Notifications -> Application Settings -> OpenSnitch -> Show popups is disabled

**Comment by gustavo-iniguez-goya** [comment]
Thank you very much for the feedback. Closing.
