### ISSUE TITLE
Installed opensnitch_1.4.0.rc3_amd64.deb and it didn't install in the tray

### ISSUE THREAD

**Issue by ovari** [evilsocket/opensnitch#464]
Hi,

**Describe the bug**
While in operating system was set to the Hungarian locale, installed opensnitch_1.4.0.rc3_amd64.deb. After installation, there was no icon in the system tray and no program in the Linux Mint Menu.

**OS (please complete the following information):**
 - OS: Linux Mint 20.2 Cinnamon
 - Window Manager: Not sure
 - Kernel version: 5.4.0-80-generic
 - Version: Not sure

Thank you

**Comment by gustavo-iniguez-goya** [comment]
Did you install the GUI? https://github.com/evilsocket/opensnitch/releases/download/v1.4.0-rc.3/python3-opensnitch-ui_1.4.0.rc3-1_all.deb

**Comment by ovari** [comment]
That should do the trick. Thanks for the quick response.
