### ISSUE TITLE
Please allow more strings to be translateable

### ISSUE THREAD

**Issue by ovari** [evilsocket/opensnitch#465]
### Események

![Események](https://user-images.githubusercontent.com/17465872/127232089-449619a7-3395-4285-9f80-7a9fe212b570.png)

Please allow the column headings in the image above to be translatable, i.e.
1. <s>Time</s> Done
2. <s>Node</s> Done
3. <s>Action</s> Done
a) allow (and whatever the other options are), please note that this is not a column heading
4. <s>Destination</s> Done
5. <s>Protocol</s> Done
6. <s>Process</s> Done
7. <s>Rule</s> Done

### Csomópontok

![Csomópontok](https://user-images.githubusercontent.com/17465872/127231340-341c1ba8-b033-42bf-8a64-c123125f7da8.png)

Please allow the column headings in the image above to be translatable, i.e.
1. LastConnection
2. Addr
3. Status
a) online (and whatever the other options are), please note that this is not a column heading
4. Hostname
5. Version
6. Uptime
7. Rules
8. Connections
9. Dropped
10. Version

![Csomópontok](https://user-images.githubusercontent.com/17465872/127231900-495b1abc-fda0-45b6-95d6-9f85138abd51.png)

Please allow the column headings in the image above to be translatable, i.e.
1. LastConnection
2. allow (and whatever the other options are), please note that this is not a column heading
3. Hits
4. UserID
5. DstIP
6. DstHost
7. DstPort
8. Process
9. Args
10. CWD

### Szabályok

![Szabályok](https://user-images.githubusercontent.com/17465872/127232287-fd32b0a1-2370-4110-ad26-661454176ca2.png)

Please allow the column headings in the image above to be translatable, i.e.
1. time
2. node
3. name
4. enabled
a) True
b) False
5. precedence
a) True
b) False
6. action
a) allow (and whatever the other options are), please note that this is not a column heading
7. duration
a) until restart (and whatever the other options are), please note that this is not a column heading
8. operator_type
a) simple (and whatever the other options are), please note that this is not a column heading
9. operator_operand
a) process.path (and whatever the other options are), please note that this is not a column heading
10. operator_data

### Gazdagépek

![Gazdagépek](https://user-images.githubusercontent.com/17465872/127232596-624a52c4-4e8d-4dd9-bfa3-b0b67544fb1b.png)

Please allow the column headings in the image above to be translatable, i.e.
1. what
2. hits

### Alkalmazások

![Alkalmazások](https://user-images.githubusercontent.com/17465872/127232659-5eb49e86-0a38-4db6-b09c-f002c32154e8.png)

Please allow the column headings in the image above to be translatable, i.e.
1. what
2. hits

### Címek

![Címek](https://user-images.githubusercontent.com/17465872/127232700-473e22fb-730f-4f14-9433-7509a939231a.png)

Please allow the column headings in the image above to be translatable, i.e.
1. what
2. hits

### Kikötők

![Kikötők](https://user-images.githubusercontent.com/17465872/127232745-23913284-85bd-4ca7-9251-da0110fb2256.png)

Please allow the column headings in the image above to be translatable, i.e.
1. what
2. hits

### Felhasználók

![Felhasználók](https://user-images.githubusercontent.com/17465872/127232946-372f61b4-70c8-4bbe-a620-64c8a85fb9bc.png)

Please allow the column headings in the image above to be translatable, i.e.
1. what
2. hits

### Mentés CSV formátumban

![Mentés CSV formátumban](https://user-images.githubusercontent.com/17465872/127233572-8e8ca7e9-44a9-4ddb-b30c-8ff3fac077d7.png)

Please allow the following strings in the image above to be translatable, i.e.
1. Look in:
2. Name
3. Size
4. Type
5. Date Modified
6. File name:
7. Files of type:
8. All files (*)
9. Save
10. Cancel

Thank you

**Comment by gustavo-iniguez-goya** [comment]
ok, noted. I'll work on it the next weeks.

**Comment by ovari** [comment]
Please let us know when you require the Hungarian translations. Thank you once again.

**Comment by gustavo-iniguez-goya** [comment]
The columns names of the details view can be translated now. Note that the name of the column must be a word without spaces and symbols, I've placed a note for translators.

The columns of the main views cannot yet be translated.

> Mentés CSV formátumban

Regarding this dialog, I think I cannot create translations for it. It's part of the system, so unless I'm wrong it takes the locales of your system. But it makes me wonder why the UI is translated and that dialog no...

**Comment by ovari** [comment]
Thanks for the updated.

Note to self: https://github.com/evilsocket/opensnitch/commit/f96e44dc93370f4679e00bfb347a368d4cf7f094 patch where the `<translation type="unfinished"></translation>` strings are.

**Comment by ovari** [comment]
`<source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;If checked, opensnitch will prompt you to allow or deny connections that don&apos;t have an asocciated PID, due to several reasons, mostly due to bad state connections.&lt;/p&gt;&lt;p&gt;The pop-up dialog will only contain information about the network connection.&lt;/p&gt;&lt;p&gt;There&apos;re some scenarios where these are valid connections though, like when establishing a VPN using wireguard.&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>`

Are these typos:
1. `opensnitch` → `OpenSnitch`
2. `asocciated` → `associated`
3. `wireguard` → `WireGuard`

**Comment by ovari** [comment]
@gustavo-iniguez-goya are you able to add more unfinished strings into https://github.com/evilsocket/opensnitch/blob/v1.4.0/ui/i18n/locales/hu_HU/opensnitch-hu_HU.ts as the headings aren't translated? We can then translate them for you. Thank you

**Comment by gustavo-iniguez-goya** [comment]
Yes, I'll allow to translate them, but it'll take me some time, it requires a little bit of more work.

**Comment by ovari** [comment]
@gustavo-iniguez-goya can you please update the file at https://github.com/evilsocket/opensnitch/blob/v1.4.0/ui/i18n/locales/hu_HU/opensnitch-hu_HU.ts so we can then add the Hungarian translations using a web browser?

Thank you

**Comment by gustavo-iniguez-goya** [comment]
Sure @ovari , I'll notify you when it's done.

**Comment by gustavo-iniguez-goya** [comment]
@ovari Hungarian translation for 1.4.0 is complete and seems aligned with what is on github:
https://hosted.weblate.org/projects/opensnitch/gui/hu/

Translations for 1.5.0 version are here: https://hosted.weblate.org/projects/opensnitch/gui-1-5-0/hu/
And for master branch: https://hosted.weblate.org/projects/opensnitch/gui-main-branch/hu/

There won't be new translations for 1.4.0 nor for 1.5.0.

**Comment by ovari** [comment]
@gustavo-iniguez-goya Hungarian translations in 1.5 branch should be 100% complete.

Does GUI (main branch) automatically update from 1.4 and 1.5 branches?

Thank you

**Comment by gustavo-iniguez-goya** [comment]
Thank you very much @ovari !

No, only `gui-main-branch` will be updated from the master branch. The other branches were out-of-sync, but from now on I expect to keep everything updated.
