### ISSUE TITLE
[Feature request] add a note field in the rule edit view

### ISSUE THREAD

**Issue by NRGLine4Sec** [evilsocket/opensnitch#466]
It could be useful to add a note field in the edit view to inform interesting informations for one specific rule.
For exemple, I'm blocking `www.imf.org` and `www.ecb.europa.eu` from `gnome-calculator` binary and I would like to add a quick note to remind me why this program want to go outside (https://gitlab.gnome.org/GNOME/gnome-calculator/-/blob/master/lib/currency-provider.vala).

**Comment by gustavo-iniguez-goya** [comment]
it's not a bad idea @NRGLine4Sec  :+1:

**Comment by gustavo-iniguez-goya** [comment]
added: https://github.com/evilsocket/opensnitch/commit/3c524c19423e616ba7d52cbbd9bc195ad32ff4ea
