### ISSUE TITLE
Send alerts via notification daemon

### ISSUE THREAD

**Issue by noperator** [evilsocket/opensnitch#468]
I understand that OpenSnitch UI opens a connection prompt dialog window when it detects unknown connections. Could OpenSnitch also optionally send an alert via the system's notification daemon (i.e., through `libnotify`)?

I've got OpenSnitch UI windows assigned to a specific workspace, so this would help alert me to the fact that I need to approve an unknown connection, no matter which workspace I'm on.

**Comment by gustavo-iniguez-goya** [comment]
Hi @noperator ,

Do you use our systray icon? We already display alerts using qt, so we could use the same subsystem. Although by using libnotify we could display alerts even if systems that doesn't support systray icons (out of the box, like gnome), or the mobiles (purism)

We'll let customized alerts in future versions (like 1.5.x) to fulfill the demands #462

**Comment by noperator** [comment]
Admittedly, I don't use systray at all—I'm driving Debian 10 via i3 window manager, and don't have a fully fledged desktop environment installed.

Though I don't normally have [systray enabled through i3bar](https://i3wm.org/docs/userguide.html#_tray_output), I just enabled it and don't see the [systray icon mentioned in the wiki](https://github.com/evilsocket/opensnitch/wiki/Getting-started#:~:text=new%20icon%20appeared%20on%20the%20systray). I'll keep troubleshooting to see if that's a problem on my end. Will follow up if I figure it out.

**Comment by noperator** [comment]
Okay, I ended up [configuring i3](https://github.com/noperator/dotfiles/blob/b6f8ad351a10680783cf3c0b6ce96d82f13faff5/.config/i3/config#L229) to specifically assign the "statistics window" (titled `OpenSnitch Network Statistics 1.4.0rc3`) to a workspace of my choosing—which allows the pop-up connection prompt dialog (simply titled `OpenSnitch v1.4.0rc3`) to continue to float in my focused workspace.

So, no need for the systray icon _or_ alerts through the notification daemon. @gustavo-iniguez-goya, thanks for your quick response here!

**Comment by gustavo-iniguez-goya** [comment]
Feature added in latest v1.5.0rc2 :+1:
