### ISSUE TITLE
Icon missing from systray - tint2 panel

### ISSUE THREAD

**Issue by Fekal-Matter** [evilsocket/opensnitch#469]
No icon in system tray for "enabled" state. On fresh boot it goes - paused, off and then no icon (should be running/enabled). Right-click and disable - icon appears (paused), enable - no icon.
Panel is tint2. Maybe it is tint2 issue, idk.

**Comment by gustavo-iniguez-goya** [comment]
Hi @Fekal-Matter ,

I need more information:

- post opensnitch version.

**OS (please complete the following information):**
 - OS: [e.g. Debian GNU/Linux, ArchLinux, Slackware, ...]
 - Window Manager: [e.g. GNOME shell, KDE, enlightenment, ...]
 - Kernel version: echo $(uname -a)
 - Version [e.g. Buster, 10.3, 20.04]
 
**Post error logs:** 
 - Launch it from a terminal and reproduce the issue.
 - Post the errors logged to the terminal.

- Is the daemon running when this problem occur? (`pgrep -a opensnitchd`)

**Comment by Fekal-Matter** [comment]
- Opensnitch: v1.4.0-rc.3
- OS: Devuan Beowulf (Debian Buster without systemd, with sysvinit)
- Window Manager: openbox
- Kernel: Linux devuan 4.19.0-17-amd64 (hastag should be here but github sucks)1 SMP Debian 4.19.194-3 (2021-07-18) x86_64 GNU/Linux

Killed and stopped tint2, opensnitch service and opensnitch-ui.
1) Started `tint2` in terminal. only thing it has to say during opensnitching was:
`add_icon: 29360134 (), pid 3160, visual 0x56186a494d68, colormap 29360133, depth 24, width 22, height 22`
2) `service opensnitch start`. all good as expected.
3) Run `opensnitch-ui`. enable-disable from system tray (i have to guess location where to right click, since there is no icon when it is enabled, when disabled - icon appears). triggered popups with "unusual activities". 
terminal output during all this is barely worth mentioning:
```
Loading translations: /usr/lib/python3/dist-packages/opensnitch/i18n locale: en_US
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-user'
new node connected, listening for client responses... /local
```
4) There is more interesting stuff going on with tint2conf (tint2 panel configuration tool) - a black hole appears with space distortions. I altered `.png`-s to see difference and that kind of worked, but couldn't  do with `.svg`-s because incscape sucks as much as github and I am stupid. Anyway, github sucks and cannot upload image, so there it is: https://ibb.co/t3tyNHw. (
enabled, disabled, enabled after tint2conf apply without changes, disabled after tint2conf apply without changes - from up to down)

I guess the `svg` thing might mess things up, or it is still a tint2 thing, tried to ask tint2 dev, but gitlab is even worse than github (signup is bannable offence). go figure.

**Comment by Fekal-Matter** [comment]
Here is the whole taskbar: https://ibb.co/dGjBVfw - pretty much default config - just some size and color adjustments for better visuals. Here some things can be observed and noticed:
leftmost is the tint2config icon (like button or something), then 4 virtual desktops (identifieable by numbers 1-4), systray and clock.
After running tint2config and applying unchanged setup, the leftmost tint2config icon suddenly appears in the mysterious (transparent?) square in system tray where snitch should be.

And like my previous exerience here was, and still is - github sucks and by a lot.
...nothing to preview - so i could only hope that the ibb image link shows up and this reply gets posted.
just in case - here is a link: https://ibb.co/dGjBVfw

**Comment by Fekal-Matter** [comment]
Sorry for the spam, but can't edit posts. Thanks github - the leader of open and free source something.
In the full taskbar image there is system tray colored blue and for the reference added pnmixer (volume icon, installed, not "photoshopped")

**Comment by Fekal-Matter** [comment]
Did some more research and found that it is all about that stupid svg.

line 105 in
`/usr/lib/python3/dist-packages/opensnitch/service.py`
change svg
`        self.white_image = QtGui.QPixmap(os.path.join(self._path, "res/icon-white.svg"))`
to png
`        self.white_image = QtGui.QPixmap(os.path.join(self._path, "res/icon-white.png"))`

That's it. Problem solved.

Hope you can get rid of the svg, especially when other icons are png.
