### ISSUE TITLE
[Feature Request] Native popup

### ISSUE THREAD

**Issue by GreenLunar** [evilsocket/opensnitch#476]
Hello, I'm a happy ArchLinux user of OpenSnitch under Xfce desktop, and I want to ask for a new feature.
Please consider using `notify-send` for notifications, as the current one doesn't comply with the appearance and settings of the native desktop notification.

**Comment by gustavo-iniguez-goya** [comment]
Hi @GreenLunar ,

I agree, it's scheduled for the next release. It was previously requested here #468 , so let's follow up the request there.

Thank youu! :)
