### ISSUE TITLE
Can't start monitoring.

### ISSUE THREAD

**Issue by RDKRACZ** [evilsocket/opensnitch#488]
**Describe the bug**
![Screenshot from 2021-09-01 11-15-31](https://user-images.githubusercontent.com/43277609/131645679-c1461bf5-2b05-4cba-b4f9-f5e4f8886bb6.png)

**To Reproduce**
Install opensnitch Arch Linux package
Start the GUI
Try to start monitoring
**Logs:** 
```
opensnitch-ui
Loading translations: /usr/lib/python3.9/site-packages/opensnitch/i18n locale: en_US
```
```
opensnitchd
[2021-09-01 09:16:59]  IMP  Starting opensnitch-daemon v1.3.6
[2021-09-01 09:16:59]  INF  Loading rules from /home/k0rr/rules ...
[2021-09-01 09:16:59]  !!!  Path '/home/k0rr/rules' does not exist
```

If the daemon doesn't start:
 - Post last 15 lines of the log file `/var/log/opensnitchd.log`
```
cat: /var/log/opensnitchd.log: No such file or directory
```
 - Or launch it from a terminal (`/usr/bin/opensnitchd -rules-path /etc/opensnitchd/rules`) and post the errors logged to the terminal.
```
[2021-09-01 09:22:53]  IMP  Starting opensnitch-daemon v1.3.6
[2021-09-01 09:22:53]  INF  Loading rules from /etc/opensnitchd/rules ...
[2021-09-01 09:22:53]  WAR  Is opnensitchd already running?
[2021-09-01 09:22:53]  !!!  Error while creating queue #0: Error unbinding existing q handler from AF_INET protocol family: operation not permitted
```

**OS**
 - OS: EndeavourOS
 - Window Manager: Mutter (Muffin)
 - Kernel version: 5.13.13-arch1-1 
 - Version: Rolling release

**Comment by gustavo-iniguez-goya** [comment]
Hi @RDKRACZ ,

Please, use the AUR opensnitch-git package and let me know if it starts. The v1.3.6 had several issues that are fixed.

**Comment by AnirudhChandupatla** [comment]
I too having same issue, I am using Manjaro. "Status not running" and opensnitchd command giving same error output. Is there any stable version which didn't had this issue?

**Comment by gustavo-iniguez-goya** [comment]
Hi @AnirudhChandupatla ,

Please, use the AUR opensnitch-git package and let me know if it starts. The v1.3.6 had several issues that are fixed.

**Comment by odnar-dev** [comment]
try this :
```sh
# Enable a opensnitchd to start automatically at boot
sudo systemctl enable opensnitchd
# start opensnitchd service
sudo systemctl start opensnitchd.service 
# check if opensnitchd service is running
systemctl status opensnitchd.service 
```

**Comment by xtrahigh** [comment]
`sudo systemctl enable --now opensnitchd.service`
This worked for me.

**Comment by gustavo-iniguez-goya** [comment]
Thank you @odnar-dev , I always forget to do this on Arch/Manjaro/etc. I added it to the FAQs.
