### ISSUE TITLE
Opensnitch blocks outgoing pings.

### ISSUE THREAD

**Issue by ashvinlobo** [evilsocket/opensnitch#490]
Hi All,

Ashvin here....am new to git hub but am on linux for quite some time now.

Lately i installed Kubuntu 20.04.03 on my desktop and i was trying to sort out 
a few issues with my firewall. I used ping to ping an external server but i got
a feedback with ping 100% loss. I have apparmor on my pc. I tried disabling 
apparmor but still no go.

Last of all i tried disabling opensnitch and ran ping again. The ping went through
without any issue. I tried multiple times and all attempts were successful but
the minute i enable opensnitch latest rc, i cannot go through.

Results of `/usr/bin/opensnitchd -rules-path /etc/opensnitchd/rules`
[2021-09-06 13:15:48]  INF  iptables version: [iptables v1.8.7 (legacy)]
[2021-09-06 13:15:48]  IMP  Starting opensnitch-daemon v1.4.0rc3
[2021-09-06 13:15:48]  INF  Loading rules from /etc/opensnitchd/rules ...
ERROR: nfq_create_queue() queue not created
[2021-09-06 13:15:48]  WAR  Is opensnitchd already running?
[2021-09-06 13:15:48]  !!!  Error while creating queue #0: Error binding to queue: operation not permitted

Please assist....Ashvin

**Comment by gustavo-iniguez-goya** [comment]
:wave: Ashvin

> v1.4.0rc3

try latest v1.4.0rc4 https://github.com/evilsocket/opensnitch/releases/tag/v1.4.0-rc.4

Install the new configuration file when it'll ask you to do so, and be sure that it contains the item "Firewall": "iptables" (`/etc/opensnitchd/default-config.json`)

**Comment by ashvinlobo** [comment]
Hi 

I have the same version rc4 and this is how my config.json file looks:
{
    "Server": {
        "Address": "unix:///tmp/osui.sock",
        "LogFile": "/var/log/opensnitchd.log"
    },
    "DefaultAction": "allow",
    "DefaultDuration": "once",
    "InterceptUnknown": false,
    "ProcMonitorMethod": "ebpf",
    "LogLevel": 2,
    "Firewall": "iptables",
    "Stats": {
        "MaxEvents": 150,
        "MaxStats": 25
    }
}
 Strange...things were normal with the previous versions of opensnitch. Love it :)

**Comment by gustavo-iniguez-goya** [comment]
aah, ok then. This problem was fixed a few days ago: https://github.com/evilsocket/opensnitch/commit/d11a98e418901bf4c4643f6e1a4d50bec7d29971#diff-f77b12a53ece5f6b7050800bbdbf8cc5ebe87f1b1387cf739f243e43e2ce886b

It'll be included on next version.

**Comment by ashvinlobo** [comment]
Hi Mate....well cool then am waiting for the next release very eagerly. As a suggestion, could you add dark or light themes? keep up the good work :) and thank you very much

**Comment by gustavo-iniguez-goya** [comment]
v1.4.0 released with this problem fixed, for iptables.

light and dark themes are in the roadmap for the next version. Usually if the GUI doesn't adapt to the theme style of your WM it's a configuration problem of your setup. Qt and others UI toolkits doesn't always play nice https://github.com/evilsocket/opensnitch/wiki/Known-problems#The-GUI-does-not-change-to-dark-style-theme

**Comment by ashvinlobo** [comment]
Hi Gustavo...Thank You very much.

**Comment by ashvinlobo** [comment]
Hi Gustavo....i have the same problem...even if i allow ping through opensnitch i cant go through. The minute i disable opensnitch the ping goes through. In my config file the firewall is iptables. I use iptables along with CSF Firewall.

**Comment by ashvinlobo** [comment]
i tried installing the new version over the old one....
sudo dpkg -i opensnitch*.deb python3-opensnitch-ui*.deb; sudo apt -f install
(Reading database ... 318110 files and directories currently installed.)
Preparing to unpack opensnitch_1.4.0-1_amd64.deb ...
Failed to stop opensnitch.service: Unit opensnitch.service not loaded.
Failed to disable unit: Unit file opensnitch.service does not exist.
Unpacking opensnitch (1.4.0-1) over (1.4.0~rc4-1) ...
**dpkg: warning: unable to delete old directory '/usr/lib/systemd/system': Directory not empty
dpkg: warning: downgrading opensnitch from 1.4.0-1 to 1.4.0~rc4-1**
Preparing to unpack opensnitch_1.4.0.rc4-1_amd64.deb ...
Unpacking opensnitch (1.4.0~rc4-1) over (1.4.0-1) ...
Preparing to unpack python3-opensnitch-ui_1.4.0-1_all.deb ...
Unpacking python3-opensnitch-ui (1.4.0-1) over (1.4.0~rc4-1) ...
**dpkg: warning: downgrading python3-opensnitch-ui from 1.4.0-1 to 1.4.0~rc4-1**
Preparing to unpack python3-opensnitch-ui_1.4.0.rc4-1_all.deb ...
Unpacking python3-opensnitch-ui (1.4.0~rc4-1) over (1.4.0-1) ...
More than one copy of package opensnitch has been unpacked
 in this run !  Only configuring it once.
More than one copy of package python3-opensnitch-ui has been unpacked
 in this run !  Only configuring it once.
Setting up opensnitch (1.4.0~rc4-1) ...
Created symlink /etc/systemd/system/multi-user.target.wants/opensnitch.service → /lib/systemd/system/opensnitch.service.
Setting up python3-opensnitch-ui (1.4.0~rc4-1) ...
gtk-update-icon-cache: Cache file created successfully.
Processing triggers for systemd (245.4-4ubuntu3.11) ...
Processing triggers for desktop-file-utils (0.24-1ubuntu3) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

Strange thats its being downgraded

**Comment by gustavo-iniguez-goya** [comment]
It seems that you installed both 1.4.0 and 1.4.0rc4 at the same time by doing dpkg -i .. *.deb

Try installing the deb packages with the full name instead of using wildcards: dpkg -i python3-opensnitch-ui_1.4.0-1_all.deb

**Comment by ashvinlobo** [comment]
Sorry to trouble you mate....i was wrong to leave the rc files in my download folder. I reinstalled opensnitch after deleting the files and now all is well. Pinging normally. Thank you very much.

**Comment by ashvinlobo** [comment]
Hi Gustavo....i found out the root cause for this small cruel issue and it makes me look like a fool but am happy to help.

I had a new install of ubuntu budgie and i had installed opensnitch on it. I noticed pings being blocked and went hunting through the permanent application rules and noticed /usr/bin/ping being blocked so i changed the rule to allow always and restarted the application. The pings flow smoothly now. .....:)

**Comment by gustavo-iniguez-goya** [comment]
great @ashvinlobo ! :)
