### ISSUE TITLE
localhost packets are lost when opensnitch is active

### ISSUE THREAD

**Issue by themighty1** [evilsocket/opensnitch#499]
When sending data from localhost client to localhost server, some packets are lost. This can be reproduced with simple client/server code

client.py

```
import socket, os, time

sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
server_address = ('127.0.0.1', 12345)
sock.connect(server_address)
randomHeader = os.urandom(1234)
randomBlob = os.urandom(1024*1024*30)
sock.settimeout(1)

while True:
    print("sending blob")
    sock.send(randomHeader)
    sock.send(randomBlob)
    print("receiving data")
    data = sock.recv(4096)
    if data.decode() != "ready":
        raise("unexpected server response")
        break
    time.sleep(1) 
```

server.py

```
import socket

sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
server_address = ('127.0.0.1', 12345)
sock.bind(server_address)
sock.listen(1)
conn, client_address = sock.accept()
sock.settimeout(3)

while True:
    data = b''
    while len(data) != 1024*1024*30 + 1234:
        data += conn.recv(1024*1024)
        print("bytes so far: ", len(data))
    print("received 30MB")
    conn.send("ready".encode())

```

If you run this without opensnitch active, the client will continue to send in a loop endlessly. 
But if opensnitch is active, after a few loops (no more than 10 on my machine), server will be stuck waiting for lost data.

This specifically manifests when a small headers is sent first followed by a large body. Only the header is received, but the body is lost. Wireshark confirms that the body is lost and does not appear in wireshark trace.

This may be the reason why people experienced hung applications which expect localhost data.
This behaviour happens both under ebpf and proc monitor methods.

**Comment by gustavo-iniguez-goya** [comment]
thank you @themighty1 for taking a look at this.

I cannot reproduce this problem on my machine :(

launched server.py on one terminal, launched client.py on another, opensnitch asks to allow the connection, and from that on it keeps sending and receiving as expected. 

I don't see how we can be interfering in this particular case because we're intercepting the connection only once. Maybe other IPCs are creating a lot of new connections from localhost to localhost?

**Comment by themighty1** [comment]
Thanks. I did a fresh reboot into another kernel, disabled the vpn daemon, restarted opensnitch and the behaviour is still there. Sometimes the server or the client will wait for the packet for a few seconds and will resume when the packet eventually arrives.
Maybe that's why you didn't see the server hanging. I modified the code above to add timeouts. This was the app will exit if a packet doesnt arrive for too long.
Let me know whether it works for you.

**Comment by gustavo-iniguez-goya** [comment]
Now it fails by timeout, but also without opensnitch running. I'll give it a try again tonight.

**Comment by themighty1** [comment]
Hmmm, I had this script running for hours on my system without opensnitch and there never was a timeout.

**Comment by themighty1** [comment]
@gustavo-iniguez-goya , turns out the problem comes from opensnitch detecting an iptables rules change and reloading the rules.
I think it is a false positive. I can see that opensnitch iptables rules are intact yet it still thinks they've changed.
Do you have  "IMP  firewall rules changed, reloading" in your log repeating every 30 sec?

**Comment by themighty1** [comment]
nvm, I had old opensnitchd service still in the system. Sorry for the noise.

**Comment by gustavo-iniguez-goya** [comment]
np :+1:
