### ISSUE TITLE
Error while Running DNS nftables rule & ebpf error

### ISSUE THREAD

**Issue by bugsymaxi** [evilsocket/opensnitch#501]
Hi,

i have just compiled the latest branch and started using it. However, i get the following error while using nftables as default firewall in the default-config.
Chosing iptables works as expected.

```
[2021-09-13 09:44:52]  WAR  nftables mangle rules not loaded: 0
[2021-09-13 09:44:52]  IMP  nftables firewall rules changed, reloading
[2021-09-13 09:44:52]  ERR  Error while Running DNS nftables rule: Receive: netlink receive: no such file or directory
```

```
➜  ~ iptables -V
iptables v1.8.7 (nf_tables)
```

Further, running ebpf does not work.

```
[2021-09-13 10:06:02]  ERR  eBPF Failed to load /etc/opensnitchd/opensnitch.o: open /etc/opensnitchd/opensnitch.o: no such file or directory
[2021-09-13 10:06:02]  WAR  error starting ebpf monitor method: open /etc/opensnitchd/opensnitch.o: no such file or directory
```

Operating System: Debian GNU/Linux 11 (bullseye)
Kernel: Linux 5.10.0-8-amd64
Architecture: x86-64

**Comment by gustavo-iniguez-goya** [comment]
> /etc/opensnitchd/opensnitch.o: no such file or directory

regarding this error, you can get the eBPF module from the packages (`dpkg -x opensnitch_1.4.0-1_amd64.deb 1.4.0; sudo cp 1.4.0/etc/opensnitchd/opensnitch.o /etc/opensnitchd/`), or following the instructions and compiling it by yourself: https://github.com/evilsocket/opensnitch/tree/v1.4.0/ebpf_prog

**Comment by bugsymaxi** [comment]
> dpkg -x opensnitch_1.4.0-1_amd64.deb 1.4.0; sudo cp 1.4.0/etc/opensnitchd/opensnitch.o /etc/opensnitchd/

Thanks. eBPF works now.

**Comment by gustavo-iniguez-goya** [comment]
regarding the nftables error, list the rules of the filter table: `nft list table filter`

There should be a line like this one: `udp sport 53 queue flags bypass num 0`

Maybe the table and chain already exist when it tries to create them, and that's why it's writing out that error to the log.

**Comment by bugsymaxi** [comment]
I found the issue.
My VPN had netlock enabled. As it also uses nftables, any firewall changes are denied.

I run opensnitch with iptables as workaround, because iptables bridges to nftables anyway.

Thanks.
