### ISSUE TITLE
Login to desktop is delayed

### ISSUE THREAD

**Issue by Techtonictools** [evilsocket/opensnitch#503]
**Describe the bug**
On boot or resume from hibernate the login screen appears and after entering my credentials, I get a black screen for a long time before the desktop appears. It may seem unrelated to opensnitch, but I'm 100% sure it is opensnitch causing it. 

**To Reproduce**
Install the latest, reboot and login.

**Expected**
A black screen for a second or two and then the desktop should load.

**Actual**
There is a super long delay before the desktop loads. 

**Post error logs:** 
I didn't see any errors or related information in the log.

**Expected behavior (optional)**
After login, the desktop should appear w/in a few seconds.

**OS (please complete the following information):**
 - OS: debian bullseye
 - Window Manager: GNOME
 - Kernel version: Linux dev 5.10.0-8-amd64 #1 SMP Debian 5.10.46-4 (2021-08-03) x86_64 GNU/Linux
 - Version v1.4.0

**Additional context**
In debian emergency mode, opensnitch was disabled and I rebooted the system. Doing that allowed login to complete in a normal amount of time. 
With opensnitch running and lots of patience, the desktop eventually appears after login. 
It did feel like an NVIDIA driver problem initially, but I had uninstalled the NVIDIA drivers and there was no change.

**Comment by gustavo-iniguez-goya** [comment]
Do you have these system commands allowed?

/usr/bin/host , /usr/bin/xbrlapi , /usr/bin/dirmngr If not, add them to a regexp rule and try again.

https://github.com/evilsocket/opensnitch/wiki/Known-problems#desktop-environment-does-not-boot-up

If the problem persists, set log level to DEBUG and after the desktop appear copy the log and post it here so we can analyze it.
There'll probably be some command that is being denied.

**Comment by Techtonictools** [comment]
I didn't have a rule to allow system commands while running the release candidate so if I need that now with v1.4.0 then that would be the problem.

**Comment by gustavo-iniguez-goya** [comment]
I've been thinking for some time now that maybe we could create a deb package of common rules. Since anyone will end up having to configure them at some point.

Or at least publish a directory with the common rules, explaining what they do or why they're needed.

**Comment by chucky345** [comment]
preferences --> nodes --> Default action when the GUI is disconnected  (set to reject or allow)
