### ISSUE TITLE
Silent Rule Replacement (data loss)

### ISSUE THREAD

**Issue by metal450** [evilsocket/opensnitch#512]
Hi again :)

**Describe the bug**
I realized that if you create a new rule and title it the same thing as an existing rule, the existing rule will be silently wiped out/overwritten.

**To Reproduce**
1) Create a rule, i.e. TestRule. Enter some sample content.
2) Create a rule, name it the same thing, enter some different content
3) The original rule is overwritten & lost (with no warning). Only new rule remains.

In practice, I had a rule for a particular application that had a pretty long/complex regex, allowing only specific domains. Later, a notification popped up for that app (for a domain I apparently hadn't handled).  I created a rule named after the application, not having recalled that the previous rule was there, and almost immediately upon doing so, I started getting a million more notifications - because all the previous rule for that application were lost. The whole original list had to then be recreated by hand, as it was nowhere to be found.

**Expected behavior (optional)**
Show a warning before overwriting any data, perhaps encouraging the user to name their new rule something different to avoid data loss.

**OS (please complete the following information):**
- OpenSnitch v1.4.0
 - OS: Kubuntu 20.02
 - Window Manager: KDE
 - Kernel version: 5.4.42-050442-generic 
 - Version 20.04

**Comment by gustavo-iniguez-goya** [comment]
yes, you're right. The problem is that rules are identified by their name, instead of an id or uuid.

So there're 2 points where we have to check if the rule already exist: 1) when creating a new rule manually, 2) when a rule is created after answering a pop-up

ok, I'll take a look at this.
