### ISSUE TITLE
Build: Use non-deprecated protoc-gen-go

### ISSUE THREAD

**Issue by cinerea0** [evilsocket/opensnitch#521]
Hello, I'm having some trouble packaging opensnitch for Void Linux.

**Describe the bug**
I noticed that [this commit](https://github.com/evilsocket/opensnitch/commit/0776c1b895c11c9e8b0ad438c3e4141721a1cdae) indicated the intent to move to the newer version of protoc-gen-go. However, the build process for the daemon still requires the old version in order to compile properly. I think it would make more sense to use the same, newer version of protoc-gen-go throughout the whole project.

**To Reproduce**
Attempt to compile opensnitch using [this version](https://github.com/protocolbuffers/protobuf-go) of protoc-gen-go.

**Post error logs:** 
```
make[1]: Entering directory '/builddir/opensnitch-1.4.1/proto'
protoc -I. ui.proto --go_out=plugins=grpc:../daemon/ui/protocol/ --go_opt=paths=source_relative
--go_out: protoc-gen-go: plugins are not supported; use 'protoc --go-grpc_out=...' to generate gRPC

See https://grpc.io/docs/languages/go/quickstart/#regenerate-grpc-code for more information.
make[1]: *** [Makefile:4: ../daemon/ui/protocol/ui.pb.go] Error 1
make[1]: Leaving directory '/builddir/opensnitch-1.4.1/proto'
make: *** [Makefile:8: protocol] Error 2
```

**OS (please complete the following information):**
 - OS: Void Linux
 - Window Manager: N/A
 - Kernel version: 5.13.19
 - Version Rolling

---
As a side note, I noticed that [this commit](https://github.com/evilsocket/opensnitch/commit/35975bc76018dbf37a68283463ab9d74948b6892) was not included in the latest 1.4.1 release and I'd like to know why.

**Comment by gustavo-iniguez-goya** [comment]
>I noticed that this commit was not included in the latest 1.4.1 release and I'd like to know why.

In some restricted environments there's no network connectivity, so until now I've been using go mod vendor to compile the packages. For 1.4.1 I just didn't need that commit in particular (v1.4.1 only has GUI fixes), besides that branch will only receive bug fixes.

On the other hand, on the systems I've tried it out just `go build -o opensnitchd .` resolves and downloads the dependencies, but on another systems it doesn't, so `go get` should help resolving missing dependencies in all cases.

Honestly I've been using the old way of compiling, so I didn't run into these issues. 

Anyway, I've just tested it out and it seems to create the proto just fine (Debian Bullseye, go 1.15):

    apt install ca-certificates libnetfilter-queue-dev libpcap-dev protobuf-compiler 
    go get github.com/golang/protobuf/{proto,protoc-gen-go}
    export GOPATH=~/go
    export PATH=$PATH:$GOPATH/bin
    git clone https://github.com/evilsocket/opensnitch
    cd opensnitch/proto/
    make
    ls -l ../daemon/ui/protocol/
    total 60
    -rw-r--r--. 1 x x 59414 Oct  2 12:49 ui.pb.go

    cd ../daemon/
    make
    (...)
    go: downloading google.golang.org/grpc v1.27.0
    go: downloading google.golang.org/protobuf v1.26.0
    go: downloading github.com/golang/protobuf v1.5.0
    
Could you try it again? notice that I included `go get github.com/golang/protobuf/{proto,protoc-gen-go}`

**Comment by cinerea0** [comment]
Sorry, to clarify, I am able to compile this properly using the deprecated `github.com/golang/protobuf` module. I'm moreso asking if it would be possible to move to using the newer `google.golang.org/protobuf` module to create the proto.

**Comment by gustavo-iniguez-goya** [comment]
oops, you're totally right. 

```
$ go get google.golang.org/protobuf
$ go install google.golang.org/protobuf/cmd/protoc-gen-go
$ go get google.golang.org/grpc/cmd/protoc-gen-go-grpc
$ cd proto
$ protoc -I. ui.proto --go_out=../daemon/ui/protocol/ --go-grpc_out=../daemon/ui/protocol/ --go_opt=paths=source_relative --go-grpc_opt=paths=source_relative
```

change grpc version in go.mod from 1.27 to 1.32:
`google.golang.org/grpc v1.32.0`

compile.

@themighty1 did you run into these errors? how did you solve them?

**Comment by themighty1** [comment]
@gustavo-iniguez-goya , I didn't have those errors. neither did I change my go.mod

**Comment by cinerea0** [comment]
@gustavo-iniguez-goya Thank you! Changing the `protoc` command and updating the grpc version on go.mod fixed the problem and allowed me to compile with the newer version of `protoc-gen-go`. Do you think that these changes will eventually make it into the project?

**Comment by gustavo-iniguez-goya** [comment]
Sure @cinerea0 , I'll commit it ASAP. Than you for reporting this (and packaging the app for void btw!).

**Comment by sysfu** [comment]
> Hello, I'm having some trouble packaging opensnitch for Void Linux.

Were you ultimately able to successfully package this for Void?

I'm running OpenSnitch without issues on (debian based) PureOS but would like to get it installed and working on Void too.
