### ISSUE TITLE
AppImage release

### ISSUE THREAD

**Issue by JaxxArmstrong** [evilsocket/opensnitch#522]
May I recommend consider offering AppImage releases, which makes life much more simple for us users, but also for you as you know there will be no dependacy-Hell which translates into less support.

**Comment by gustavo-iniguez-goya** [comment]
Hi @JaxxArmstrong ,

Thank you for the suggestion. Personally I'll keep offering deb and rpm packages for now.
If you can create a functional AppImage I'll be more than glad to test it out.

> no dependacy-Hell

What dependency hell?

**Comment by JaxxArmstrong** [comment]
I wasn't referring to a existing dependency-Hell, but in order to avoid any future ones.

**Comment by gustavo-iniguez-goya** [comment]
Ok then. For now there won't be an AppImage, but as I said, if someone wants to contribute they only should send a PR with the files needed to create it (daemon and GUI) and the instructions to build it.

Thank you for the suggestion!

**Comment by shuvashish76** [comment]
Duplicate open issue #1510
