### ISSUE TITLE
GUI crashes due to Wayland

### ISSUE THREAD

**Issue by ryanolton** [evilsocket/opensnitch#526]
**Describe the bug**

This issue only happens primarily after a dialog opens and I make a selection and the dialog closes, but always after some time has passed (an hour or two) without any dialogs. If I leave for the day and come back the next morning, the GUI will have crashed overnight. The icon will disappear from Gnome-shell and no more alerts appear.

This appears to be a Wayland-specific issue, and was not present in version v1.4.0-rc.3 and earlier.

Include the following information:
 - OpenSnitch version 1.4.1
 - OS: Fedora
 - Version: 34
 - Window Manager: GNOME Shell
 - Kernel version: 5.14.9

**To Reproduce**

I have only seen this occur while under Wayland, in both GNOME Shell but also KDE Plasma (both using Wayland with Fedora 34).

1. Boot into a Wayland session
2. Have the Opensnitch GUI running in GNOME Shell
3. Wait for a dialog to appear, or simply wait a few hours

**Post error logs:** 

```
Loading translations: /usr/lib/python3/dist-packages/opensnitch/i18n locale: en_US
QSocketNotifier: Can only be used with threads started with QThread
new node connected, listening for client responses... /tmp/osui.sock
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
The Wayland connection experienced a fatal error: Protocol error
```

This appears and the GUI closes

Again, this only became an issues starting with version v1.4.0-rc.4, and worked fine on v1.4.0-rc.3 and earlier. If I install v1.4.0-rc.3 (both GUI and daemon), it works without issue.

**Comment by gustavo-iniguez-goya** [comment]
Thank you @ryanolton for reporting this,

> only became an issues starting with version v1.4.0-rc.4, and worked fine on v1.4.0-rc.3 and earlier

hmm, I'll take a look at those changes.

**Comment by gustavo-iniguez-goya** [comment]
> qt.qpa.wayland: Wayland does not support QWindow::requestActivate()

yup, I see that error as well. I guess that all these messages are just warnings. Does it still crash or now is running fine despite the errors logged to the terminal?

>  is that what you were targeting with your code fix?

nope, it was a different thing. Just after launching the GUI on f34, it crashed on that line.

**Comment by gustavo-iniguez-goya** [comment]
>If I add a line of code similar to this:
>self.setMinimumSize(self._width, self._height)
>... right before setMaximumSize then the I do not get a crash.

if this fixes the problem then we can add it as workaround. It works fine on my machine, I'll test it in some more.

**Comment by ryanolton** [comment]
> > If I add a line of code similar to this:
> > self.setMinimumSize(self._width, self._height)
> > ... right before setMaximumSize then the I do not get a crash.
> 
> if this fixes the problem then we can add it as workaround. It works fine on my machine, I'll test it in some more.

@gustavo-iniguez-goya I have created a PR (https://github.com/evilsocket/opensnitch/pull/540) that seems to work better on my local machine. Setting the width and height **after** initially showing the prompt instead of during `init` seemed to retain the correct sizing for me. Please free to review and make any changes you feel necessary.

**Comment by gustavo-iniguez-goya** [comment]
tested! it indeed fixes a little glitch that I was seeing after use setMinimumSize()

Thank you @ryanolton ! :)
