### ISSUE TITLE
not sure whether this is an issue -> opensnitch can't find processes for certain udp connections

### ISSUE THREAD

**Issue by in1t3r** [evilsocket/opensnitch#53]
opensnitch cannot find processes for certain connections on my machine for example that is multicast of kodi and ntp query to different servers. I run Debian sid with systemd so this might not happen on other machines. Btw netstat and ss do show process owners as kodi and ntpd so I didn''t pass through code yet to see how you guys are getting the process names, but it doesn't work for some udp outgoing connections.
`[2017-05-09 17:30:30,898] (WARNING) Could not find process for udp connection 10.21.35.100:47628 -> 239.255.255.250:1900
[2017-05-09 17:31:57,012] (WARNING) Could not find process for udp connection 10.21.35.100:123 -> 5.39.80.28:123
`

**Comment by in1t3r** [comment]
In my case kodi is whitelisted and ntpd is not so I'm not sure whether that helps or not.

**Comment by cwh1te** [comment]
I'm seeing this issue as well.

Trying to figure out how to whitelist nslookup...

**Comment by adisbladis** [comment]
I think this issue may have been largely solved by https://github.com/evilsocket/opensnitch/commit/993f46be91db80f0b9fdac9ccee1bfc6abfe9d95
@in1t3r @cwh1te Can you test and see if you are still experiencing this issue?

**Comment by adisbladis** [comment]
No feedback and I think this is resolved.
If this is still an issue we can re-open.
