### ISSUE TITLE
Changing Preferences->Database->In memory doesn't change the config

### ISSUE THREAD

**Issue by themighty1** [evilsocket/opensnitch#530]
When I changed Preferences->Database->In memory and restarted the UI, the entry 
in ~/.config/opensnitch/settings.conf kept saying

[database]
file=/home/user/opensnitchdb
type=0

and opensnitchdb was continued to be used enev though the UI now says "In memory"

**Comment by gustavo-iniguez-goya** [comment]
I tried to reproduce it but it works fine on my system. Any idea about how to reproduce it? like modify the option after come back from suspend/hibernate.. or.. ?

**Comment by gustavo-iniguez-goya** [comment]
Do you still have this issue @themighty1 ? with latest sources or a released version?

**Comment by gustavo-iniguez-goya** [comment]
ok, closing then. Open the issue again if you reproduce it.
