### ISSUE TITLE
GUI opens up automatically after login on Wayland 

### ISSUE THREAD

**Issue by Danny3** [evilsocket/opensnitch#535]
**Describe the bug**
Firewall's GUI opens up by itself immediately after  login.
I noticed that this behavior happens only on the Wayland session.

Include the following information:
 - OpenSnitch version: 1.4.0 (even though I remember installing the latest 1.41, does it show the daemon's version ?)
 - OS: Kubuntu
 - Version: 21.10
 - Window Manager: KDE Plasma 5.23 (upgraded to it from the backports PPA)
 - Kernel version: Linux DL1 5.14.14-xanmod2 #0~git20211021.d659a56 SMP Thu Oct 21 05:44:46 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**To Reproduce**
I enabled the Wayland session on KDE Plasma

1. Go to 'System Settings'
2. Then 'Startup and Shutdown'
3. Then click on the 'Behavior...' button at the bottom of the page
4. Tick the checkbox after 'Automatically log in:', if it's not already ticked
5. Leave user in the drop-down as your user
6. And then change the drop-down selection after 'with session" to 'Plasma (Wayland)'
7. Click Apply button on the bottom of the page and rrestart computer

**Post error logs:** 
I don't think they are needed for this problem, but I'll be more than happy to post them if required.

**Expected behavior (optional)**
Start the firewall the same way as the X11 session with the UI hidden by default and with the systray icon visible to show it when needed.

**Screenshots**
-

**Additional context**
I saw that in the System Settings -> Autostart there is one entry called "OpenSnitch" with its icon, but there's nothing else that could explain this behavior and there's no toggle button to temporary deactivate it for testing, only to delete it, which I tried to avoid.

This problem happened also with KDE Plasma 5.22 and 5.21, probably even with 5.20 or before, I don't even remember when I started using the Wayland session.

If somehow you cannot reproduce it, please try to also activate the systemd startup of KDE Plasma like I did with this command:
kwriteconfig5 --file startkderc --group General --key systemdBoot true

**Comment by Danny3** [comment]
I added that like after I uninstalled and installed OpenSnitch, since I didn't have the original service.py file anymore
Unfortunately the GUI shows up again !
For some reason the "X-KDE-Autostart-after=panel" doesn't seem to have any effect on my system.
I think I will have to try to install the firewall on a live session of Kubuntu 21.10 from a pendrive.
Maybe there's something conflicting because of my changes since I installed it.

**Comment by gustavo-iniguez-goya** [comment]
ok @Danny3 , thank you very much.

**Comment by mariomadproductions** [comment]
I'm having this issue on Linux Mint 20.2 Cinnamon.

**Comment by gustavo-iniguez-goya** [comment]
ok @mariomadproductions , do you have other system tray icons? 

Could you kill the GUI (`pkill opensnitch-ui`), launch it from a terminal and paste the output? : `$ /usr/bin/opensnitch-ui`

**Comment by mariomadproductions** [comment]
Yes I do, and in fact OpenSnitch does appear in the tray on startup, but I have to click the icon or close the window to "minimise" it into the tray.

```
user@pc:~$ pkill opensnitch-ui
user@pc:~$ /usr/bin/opensnitch-ui
Loading translations: /usr/lib/python3/dist-packages/opensnitch/i18n locale: en_GB
new node connected, listening for client responses... /tmp/osui.sock
```

**Comment by gustavo-iniguez-goya** [comment]
mm, ok, it looks like Qt is not detecting that the panel is running. In this situation we assume that the systray icon has not been added, so we launch the GUI.

launching it from the terminal shows the GUI as well?

**Comment by mariomadproductions** [comment]
> launching it from the terminal shows the GUI as well?

Actually, it seems that when I launch it from the terminal or GUI (menu) *after* login, it goes straight to the tray. Strange...
