### ISSUE TITLE
[Feature Request] Domain / Sub-Domain Regex Wildcard Improvements

### ISSUE THREAD

**Issue by bob04619** [evilsocket/opensnitch#536]
### Summary:

First off, great work on the software!

One issue (or feature request) I have is:

Assume a new request is made to a subdomain with three levels or higher, e.g. www.yahoo.com

The popup UI window appears, click +, then Destination IP combo-box suggests:

...
www.yahoo.com
to *.yahoo.com
...

At first I added a bunch of rules using the second option, *.yahoo.com, assuming it would also block requests to the main domain of the search: yahoo.com, but it does not. Is it possible to add this option:

Pseudo text for UI combo-box: to (*.)yahoo.com
Regex: ``(.*\.)?yahoo\.com``

With this regex potential sub-domains _and_  the main "search" domain are blocked.

Since it could be confusing adding another item in the UI combo-box (and should it be added at the third, fourth, etc level of the domain?), perhaps we could have a global preference such as: "Include search domain in wildcard rules".

Also if a request is made to a domain with two levels, e.g. yahoo.com, the GUI suggests:

yahoo.com
to *yahoo.com

However this will also include substringed domains such as abcyahoo.com. The second option could be replaced with my suggestions above so substrings of the search domain are excluded:

yahoo.com
to (*.)yahoo.com

Thanks

**Comment by gustavo-iniguez-goya** [comment]
what about this regex? `"^(|.*\.)?yahoo\.com"` I think it covers better the intended use case: match `yahoo.com` and `*.yahoo.com` but no `xxxyahoo.com`

```
$ echo "ssyahoo.com" | grep -E "^(|.*\.)?yahoo\.com"
$
$ echo "ss.yahoo.com" | grep -E "^(|.*\.)?yahoo\.com"
ss.yahoo.com
$ echo "yahoo.com" | grep -E "^(|.*\.)?yahoo\.com"
yahoo.com
```
