### ISSUE TITLE
The internet stops randomly while OpenSnitch is running

### ISSUE THREAD

**Issue by Ahmed-E-86** [evilsocket/opensnitch#537]
**Describe the bug**
Sometimes, the internet does not work at all, and I have to restart my machine. Before restarting my machine, I tried restarting my router and my WIFI connection, but that does not help.

The last time this issue happened, I was downloading a torrent, and the download was fine, but everything else did not work. I can not load any page from the browser, stream video, or use any API depends on the internet, and I tried to ping the IP of my router, and I kept getting this message:
`ping: sendmsg: No buffer space available`
but after disabling OpenSnitch, I recovered my connection without having to restart my machine.

Include the following information:
 - OpenSnitch version: 1.4.0rc3
 - OS: Kubuntu 21.10
 - Window Manager: KDE Plasma 5.23.2
 - Kernel version: 5.13.0-20

**To Reproduce**
The issue happens randomly, there is nothing in particular that triggers this issue as far as I know.

**Additional context**
This issue is not new, it kept happening when I was using the older version of Kubuntu (version 20.04), but I thought that it was an issue with my ISP, or a hardware problem.

**Comment by gustavo-iniguez-goya** [comment]
hey @Ahmed-E-86 , so after upgrading to v1.4.1 started working?

**Comment by Ahmed-E-86** [comment]
> hey @Ahmed-E-86 , so after upgrading to v1.4.1 started working?

I am sorry. I forgot. Everything works fine, I will reopen it if something new happens.
