### ISSUE TITLE
Fedora 35 opensnitch-ui won't start

### ISSUE THREAD

**Issue by vladimir-production** [evilsocket/opensnitch#538]
1. Bug description: opensnitch-ui won't start on Fedora 35.
2. opensnitch-1.4.0-1.x86_64.rpm and opensnitch-ui-1.4.1-1.noarch.f29.rpm installed
3. Fedora Linux 35. Bug present in fresh install and after upgrade from F34. Both virtual machine and baremetal installs.
4. Window manager: KDE Plasma 5.22.5, KDE Frameworks version 5.87.0, Qt version: 5.15.2
5. Kernel versions: 5.14.14-200.fc34.x86_64 and 5.14.14-300.fc35.x86_64
6. Steps to reproduce: install Fedora 35 then start opensnitch-ui

Then it fails to load with the followin error:

opensnitch-ui
Loading translations: /usr/lib/python3/dist-packages/opensnitch/i18n locale: C
Traceback (most recent call last):
File "/usr/bin/opensnitch-ui", line 60, in
service = UIService(app, on_exit)
File "/usr/lib/python3/dist-packages/opensnitch/service.py", line 79, in
__init__
self._stats_dialog = StatsDialog(dbname="general", db=self._db)
File "/usr/lib/python3/dist-packages/opensnitch/dialogs/stats.py", line 446,
in __init__
self._load_settings()
File "/usr/lib/python3/dist-packages/opensnitch/dialogs/stats.py", line 548,
in _load_settings
self.rulesSplitter.setSizes([w/4, w/2])
TypeError: index 0 has type 'float' but 'int' is expected

**Comment by gustavo-iniguez-goya** [comment]
Hi @vladimir-production ,

This problem was fixed here https://github.com/evilsocket/opensnitch/commit/9ef64da588c4ec40c6cfe3e2f531029161e7dc73

You can copy the file until the next version is released: https://raw.githubusercontent.com/evilsocket/opensnitch/master/ui/opensnitch/dialogs/stats.py

**Comment by ElTimablo** [comment]
The suggested fix doesn't seem to work.
```[trobertson@brutacles ~]$ opensnitch-ui 
Traceback (most recent call last):
  File "/usr/bin/opensnitch-ui", line 22, in <module>
    from opensnitch.service import UIService
  File "/usr/lib/python3/dist-packages/opensnitch/service.py", line 17, in <module>
    from opensnitch.dialogs.stats import StatsDialog
  File "/usr/lib/python3/dist-packages/opensnitch/dialogs/stats.py", line 21, in <module>
    class StatsDialog(QtWidgets.QDialog, uic.loadUiType(DIALOG_UI_PATH)[0]):
  File "/usr/lib/python3/dist-packages/opensnitch/dialogs/stats.py", line 103, in StatsDialog
    Config.ACTION_REJECT:   PURPLE,
AttributeError: type object 'Config' has no attribute 'ACTION_REJECT'```

**Comment by gustavo-iniguez-goya** [comment]
well, that's a different error so I guess the fix worked :)

```
  File "/usr/lib/python3/dist-packages/opensnitch/dialogs/stats.py", line 103, in StatsDialog
    Config.ACTION_REJECT:   PURPLE,
AttributeError: type object 'Config' has no attribute 'ACTION_REJECT'```
```

aah, sorry!! that was my fault, I posted the wrong stats.py (from master branch). This is the correct one:
[stats.py.txt](https://github.com/evilsocket/opensnitch/files/7475784/stats.py.txt)

https://raw.githubusercontent.com/evilsocket/opensnitch/1.4.0/ui/opensnitch/dialogs/stats.py

**Comment by vladimir-production** [comment]
i can confirm. this fixes it at my end. thank you!

**Comment by gustavo-iniguez-goya** [comment]
you're welcome :) v1.4.2 released with these fixes.
https://github.com/evilsocket/opensnitch/releases/tag/v1.4.2
