### ISSUE TITLE
[Feature Request] A way to support rules to changing name/path executables (like AppImage)

### ISSUE THREAD

**Issue by cypherbits** [evilsocket/opensnitch#543]
When I execute some AppImage, it seems it extracts the executables on a new temporal path each time. If I have the AppImage software automatically starting on each system restart, OpenSnitch ask me again and again on each reboot if I want to allow the new connection from the new path. Old rules from old path are deprecated... 

I can't think right now of what the right solution could be.

**Comment by gustavo-iniguez-goya** [comment]
Hi @cypherbits ,

Try this: https://github.com/evilsocket/opensnitch/wiki/Rules-examples#allowing-or-denying-appimages

**Comment by cypherbits** [comment]
Thanks, I will try to whitelist it using regex, but `^(/tmp/.mount_Archiv[0-9A-Za-z]+/.*)$` would be for all AppImages not just one program, right?

**Comment by gustavo-iniguez-goya** [comment]
Yeah, that's right. However, as far as I remember, the name of the application is also part of the temporary directory, so you could write it like: `^(/tmp/.mount_.*<APPLICATION>.*/.*)$`

For mozilla (temp directory: `/tmp/.mount_MozillshcmPB`):  `^(/tmp/.mount_Mozill[0-9A-Za-z]+/.*)$`

**Comment by gustavo-iniguez-goya** [comment]
I think this issue was answered. Closing.

**Comment by lediur** [comment]
I think the rules example addresses the issue on a small scale, but requires editing rules after the fact and can require some work to apply in bulk. I would still be interested in some UI accommodation in the popup to detect AppImage path patterns and automatically offer the regexp mentioned above.

Something like this (in the dropdown in the bottom right corner):

```
From AppImages starting with
```

or

```
From this AppImage
```

when `/tmp/.mount_` starts the path and the prefix matches the application. I think handling this in the popup would improve this use case a lot even if it doesn't capture all possibilities.

Would that fall under this issue?
