### ISSUE TITLE
[Feature Request] Optional executable verification by hash or last modification date

### ISSUE THREAD

**Issue by cypherbits** [evilsocket/opensnitch#545]
Right now we are whitelisting executable paths, that means that if we allow /home/username/myProgram a malware could replace that file to gain connection access. We can prevent this by:

1. Easy+fast but can be bypassed way: check the last modification date and alert the user.

2. Use Blake3 hash to check file integrity. (I say Blake3 because it is a cryptographic hash but it is very fast).

And with this, I just thought of something, I propose: what about a new feature to allow executing a certain executable with a hash independently of where it is (path)?? This could "fix" https://github.com/evilsocket/opensnitch/issues/543 too.

**Comment by gustavo-iniguez-goya** [comment]
Hi @cypherbits ,

This was already requested here #413 so please, comment on that issue please :) . There're interesting comments and ideas.
