### ISSUE TITLE
Body of the 1.4.2 release page has 1.4.1 links.

### ISSUE THREAD

**Issue by KissesRefined** [evilsocket/opensnitch#546]
Body of the [1.4.2](https://github.com/evilsocket/opensnitch/releases/tag/v1.4.2) release page has 1.4.1 links. Assets section links are of the right version. 

rpm -> https://github.com/evilsocket/opensnitch/releases/download/v1.4.1/opensnitch-ui-1.4.1-1.noarch.rpm

deb -> https://github.com/evilsocket/opensnitch/releases/download/v1.4.1/python3-opensnitch-ui_1.4.1-1_all.deb 

Relevant for Fedora users at least.

**Comment by gustavo-iniguez-goya** [comment]
oops, you're right. Fixed.

Thank you @KissesRefined !
