### ISSUE TITLE
Compilation error for _protoc_compiler

### ISSUE THREAD

**Issue by themighty1** [evilsocket/opensnitch#552]
Im on Ubuntu 20.04 with go version go1.17 linux/amd64, trying to follow the steps in https://github.com/evilsocket/opensnitch/wiki/Compilation
At the step "make", I get: 

> make[1]: Entering directory '/home/default2/Desktop/opensnitch/proto'
> protoc -I. ui.proto --go_out=../daemon/ui/protocol/ --go-grpc_out=../daemon/ui/protocol/ --go_opt=paths=source_relative --go-grpc_opt=paths=source_relative
> python3 -m grpc_tools.protoc -I. --python_out=../ui/opensnitch/ --grpc_python_out=../ui/opensnitch/ ui.proto
> /usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.7) or chardet (3.0.4) doesn't match a supported version!
>   warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
> Traceback (most recent call last):
>   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "/home/default2/.local/lib/python3.8/site-packages/grpc_tools/protoc.py", line 20, in <module>
>     from grpc_tools import _protoc_compiler
> ImportError: cannot import name '_protoc_compiler' from 'grpc_tools' (/home/default2/.local/lib/python3.8/site-packages/grpc_tools/__init__.py)
> make[1]: *** [Makefile:7: ../ui/opensnitch/ui_pb2.py] Error 1
> make[1]: Leaving directory '/home/default2/Desktop/opensnitch/proto'
> make: *** [Makefile:8: protocol] Error 2

I tried to look around the issues, but didnt find a similar issue.
Does it have to do with my grpcio-tools? Do they need an upgrade?

> 
> python3 -m pip install --user grpcio-tools
> Requirement already satisfied: grpcio-tools in /home/default2/.local/lib/python3.8/site-packages (1.34.1)
> Requirement already satisfied: grpcio>=1.34.1 in /home/default2/.local/lib/python3.8/site-packages (from grpcio-tools) (1.34.1)
> Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from grpcio-tools) (45.2.0)
> Requirement already satisfied: protobuf<4.0dev,>=3.5.0.post1 in /usr/lib/python3/dist-packages (from grpcio-tools) (3.6.1)
> Requirement already satisfied: six>=1.5.2 in /usr/lib/python3/dist-packages (from grpcio>=1.34.1->grpcio-tools) (1.14.0)

**Comment by gustavo-iniguez-goya** [comment]
I think so @themighty1 . I've just compiled it on ubuntu 20.04 without problems:
```
ubuntu@ubuntu:~$ python3 -m pip install --user grpcio-tools
Collecting grpcio-tools
  Downloading grpcio_tools-1.42.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.4 MB)
     |████████████████████████████████| 2.4 MB 1.2 MB/s 
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from grpcio-tools) (45.2.0)
Collecting grpcio>=1.42.0
  Downloading grpcio-1.42.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.0 MB)
     |████████████████████████████████| 4.0 MB 10.8 MB/s 
Requirement already satisfied: protobuf<4.0dev,>=3.5.0.post1 in /usr/lib/python3/dist-packages (from grpcio-tools) (3.6.1)
Requirement already satisfied: six>=1.5.2 in /usr/lib/python3/dist-packages (from grpcio>=1.42.0->grpcio-tools) (1.14.0)
Installing collected packages: grpcio, grpcio-tools
Successfully installed grpcio-1.42.0 grpcio-tools-1.42.0

ubuntu@ubuntu:~$ git clone https://github.com/evilsocket/opensnitch
Cloning into 'opensnitch'...
remote: Enumerating objects: 8887, done.
remote: Counting objects: 100% (1378/1378), done.
remote: Compressing objects: 100% (840/840), done.
remote: Total 8887 (delta 886), reused 823 (delta 486), pack-reused 7509
Receiving objects: 100% (8887/8887), 14.73 MiB | 7.90 MiB/s, done.
Resolving deltas: 100% (4583/4583), done.

ubuntu@ubuntu:~$ cd opensnitch
ubuntu@ubuntu:~/opensnitch$ make protocol
make[1]: Entering directory '/home/ubuntu/opensnitch/proto'
protoc -I. ui.proto --go_out=../daemon/ui/protocol/ --go-grpc_out=../daemon/ui/protocol/ --go_opt=paths=source_relative --go-grpc_opt=paths=source_relative
python3 -m grpc_tools.protoc -I. --python_out=../ui/opensnitch/ --grpc_python_out=../ui/opensnitch/ ui.proto
make[1]: Leaving directory '/home/ubuntu/opensnitch/proto'
```

I also tested it on ubuntu 16, with grpcio==1.16.0 and worked fine as well.

**Comment by themighty1** [comment]
Thanks, uninstalled/reinstalled version 1.34.1 and problem went away.
