### ISSUE TITLE
eBPF Failed to load /etc/opensnitchd/opensnitch.o: open /etc/opensnitchd/opensnitch.o: no such file or directory

### ISSUE THREAD

**Issue by Bogdan107** [evilsocket/opensnitch#554]
**Describe the bug**
I have ERR message inside /var/log/opensnitch.log file.

Include the following information:
 - OpenSnitch version: `1.4.3`
 - OS: `Gentoo`
 - Version: `profile default/linux/amd64/17.1/no-multilib/hardened/selinux`
 - Window Manager: `SDDM`
 - Kernel version: `Linux ??? 5.15.6-gentoo-x86_64 #2 SMP PREEMPT Fri Dec 3 14:56:01 EET 2021 x86_64 AMD Ryzen 5 4600H with Radeon Graphics AuthenticAMD GNU/Linux`

**To Reproduce**
Select `eBPF` as "Process Monitor Method" in GUI.
```
$ grep -r ProcMonitorMethod /etc/opensnitchd/default-config.json
    "ProcMonitorMethod": "ebpf",
```

**Comment by gustavo-iniguez-goya** [comment]
Hi @Bogdan107 , did you compile the eBPF module? 
https://github.com/evilsocket/opensnitch/tree/master/ebpf_prog

**Comment by Bogdan107** [comment]
Hi!
No, I do not compile the eBPF module.
I read that instructions.

But I have some troubles:
1) If `tools/lib/bpf/bpf_helpers.h` file were been patched, then kernel source tree will be corrupted for the next programs, which needs `bfp_helpers.h` file.
**_May I expect, that system will be stable after this patch?_**
2) If I make a copy of kernel source tree for compiling this module, then I need to double `> 1Gb` space on the disk.
**_May I expect, that module, compiled with this kernel patch, will be worked correctly inside the kernel, which compiled without this patch?_**

**Comment by Bogdan107** [comment]
First changes, which I want in opensnitch:
Modify "Preferences" dialog in beforeShowDialog() stage:
1) check existing of file `/etc/opensnitch/opensnitch.o` or `<lib>/opensnitch.o` or `<lib64>/opensnitch.o` or `LD_LIBRARY_PATH` or something else;
2) if file `opensnitch.o` does not exists - remove or disable `ebpf` row from "Process monitor method" listbox.

**Comment by 4L3XK** [comment]
Compiling the eBPF module fixed the error messages and the ICMP and NFS issues for me.
`Linux version 5.10.0-11-amd64`

**Comment by Bogdan107** [comment]
I build ebpf_prog module #680 and already use opensnitch with _ProcMonitorMethod=ebpf_ !
