### ISSUE TITLE
[Feature Request] Different row colors in "Application rules" table

### ISSUE THREAD

**Issue by Bogdan107** [evilsocket/opensnitch#555]
### Summary:
If I disable some rules, then I expect, that those disabled rules will have some easy distinguishable visual difference from enabled rules inside the "Application rules" list.

May disabled rules have gray background or gray font color in "Application rules" table?
May "Allow" rules have "green" background in "Application rules" table?
May "Deny" rules have "red" background in "Application rules" table?

**Comment by gustavo-iniguez-goya** [comment]
Yes, I think this would be nice to have. In fact, I already worked on it, but many other things have taken precedence.

Once we add this, what I'd like to have is to allow to colorize rows based on certain patterns. For example to highlight a search when you're debugging something.

**Comment by gustavo-iniguez-goya** [comment]
This is partially done. Views/Lists are fully customizable now, and we'll let users create rules to highlight rows or cells based on patterns.

But for now, can we define default colors for: Rules not enabled, rules enabled, and deny/reject/allow rules?

Right now only Action and Enabled columns are colorized (allow -> green, deny -> red, reject -> purple).

**Comment by gustavo-iniguez-goya** [comment]
or maybe I'll define the default colors for now, and when this will be customizable then you can suggest new colors for rows and cells.

**Comment by gustavo-iniguez-goya** [comment]
added ability of personalize the colors.

If you're using latest sources from the master branch, you can override default rules action to colorize cells/rows by creating a json file under `~/.config/opensnitch/actions/ . Example of customizing rules' highlighting to match what was requested by OP:
```json
{
  "name": "defaultRulesDelegateConfig",
  "created": "",
  "updated": "",
  "actions": {
    "highlight": {
      "cells": [
        {
          "text": ["allow", "True"],
          "cols": [3, 4],
          "color": "green",
          "bgcolor": "",
          "alignment": ["center"]
        },
        {
          "text": ["deny", "False"],
          "cols": [3, 4],
          "color": "red",
          "bgcolor": "",
          "alignment": ["center"]
        },
        {
          "text": ["reject"],
          "cols": [3, 4],
          "color": "purple",
          "bgcolor": "",
          "alignment": ["center"]
        }
      ],
      "rows": [
          {
          "text": ["False"],
          "cols": [3],
          "color": "black",
          "bgcolor": "darkgray"
          },
          {
              "text": ["allow"],
              "cols": [4],
              "color": "white",
              "bgcolor": "green"
          },
          {
              "text": ["deny"],
              "cols": [4],
              "color": "white",
              "bgcolor": "crimson"
          }
      ]
    }
  }
}
```

Basically by creating a new Action of *name* defaultRulesDelegateConfig, defaultFWDelegateConfig or commonDelegateConfig you customize those actions to what you want. (The name of the file doesn't matter)

Color names: https://www.w3.org/TR/SVG11/types.html#ColorKeywords

**Comment by gustavo-iniguez-goya** [comment]
This will be configurable from the GUI of course. But if you could test it meanwhile it'd be great to get some feedback.

Example of colourizing Events rows based on text patterns (for example to colorize a row based on a rule with the text `block-domains`):

`~/.config/opensnitch/actions/commonActionsDelegate.json`

```json
{
  "name": "commonDelegateConfig",
  "created": "",
  "updated": "",
  "actions": {
    "highlight": {
      "cells": [
        {
          "text": ["allow", "✓ online"],
          "cols": [1, 2, 3],
          "color": "green",
          "bgcolor": "",
          "alignment": ["center"]
        },
        {
          "text": ["deny", "☓ offline"],
          "cols": [1, 2, 3],
          "color": "red",
          "bgcolor": "",
          "alignment": ["center"]
        },
        {
          "text": ["reject"],
          "cols": [1, 2, 3],
          "color": "purple",
          "bgcolor": "",
          "alignment": ["center"]
        }
      ],
      "rows": [
        {
          "text": ["->  53"],
          "cols": [3],
          "color": "white",
          "bgcolor": "green",
          "alignment": []
        },
        {
          "text": ["->  443"],
          "cols": [3],
          "color": "royalblue",
          "bgcolor": "",
          "alignment": []
        },
        {
          "text": ["block-domains"],
          "cols": [8],
          "color": "white",
          "bgcolor": "darkMagenta",
          "alignment": []
        }
      ]
    }
  }
}
```
