### ISSUE TITLE
[Feature Request] make opensnitch installable for systemdless systems

### ISSUE THREAD

**Issue by Twilight774** [evilsocket/opensnitch#558]
I have devuan (systemdless debian) and i can't install opensnitch without systemctl.
Can you please make it possible to install opensnitch without systemd?
`E: Sub-process /usr/bin/dpkg returned an error code (1)
opensnitch (1.4.1-1) …
/var/lib/dpkg/info/opensnitch.postinst: 6: systemctl: not found
dpkg:  opensnitch (--configure):
 installed opensnitch package post-installation script subprocess returned error exit status 127
`

**Comment by gustavo-iniguez-goya** [comment]
Hi @Twilight774 ,

That's my fault. The systemctl command is hardcoded in the postinst script, sorry for that.

Apart from that, does the daemon start after installing the deb package?

**Comment by Twilight774** [comment]
Hi @gustavo-iniguez-goya
> Apart from that, does the daemon start after installing the deb package?

Yes, manually
```
root@refracta:~# opensnitchd 
[2021-12-09 11:40:22]  IMP  Starting opensnitch-daemon v1.4.1
[2021-12-09 11:40:22]  INF  Loading rules from /root/rules ...
[2021-12-09 11:40:22]  !!!  Path '/root/rules' does not exist
root@refracta:~# mkdir rules
root@refracta:~# opensnitchd 
[2021-12-09 11:40:39]  IMP  Starting opensnitch-daemon v1.4.1
[2021-12-09 11:40:39]  INF  Loading rules from /root/rules ...
OK: libnetfiler_queue supports nfq_get_uid
OK: libnetfiler_queue supports nfq_get_uid

```

**Comment by gustavo-iniguez-goya** [comment]
ok, problem reproduced. We don't need those systemctl commands, on sysvinit systems at least, and the daemon starts just fine.

I'll fix it soon. Thank you @Twilight774 for reporting it.

**Comment by gustavo-iniguez-goya** [comment]
Tested and fixed. I'll need to reupload the packages.
