### ISSUE TITLE
[DEB] Opensnitch-ui doesn't have opensnitch dependency

### ISSUE THREAD

**Issue by Twilight774** [evilsocket/opensnitch#559]
Please, check the FAQ and Known Problems pages before creating the bug report:
https://github.com/evilsocket/opensnitch/wiki/FAQs
https://github.com/evilsocket/opensnitch/wiki/Known-problems

**Describe the bug**
Opensnitch-ui without opensnitch is meaningless

**Comment by gustavo-iniguez-goya** [comment]
No, sorry, it's not meaningless. You can have the daemon installed on multiple servers, and the GUI in your desktop.

You don't need the GUI on headless servers.

**Comment by Twilight774** [comment]
But GUI shouldn't work without the daemon? Am I right?

**Comment by gustavo-iniguez-goya** [comment]
Well, partially yes. You may have the GUI installed on one computer, without the daemon, and the daemon(s) on another computer. Does it have any sense not to install the daemon on the same computer the GUI is installed? I don't know. Probably in 99% of the installations users will install the GUI along with the daemon.

Personnally I wouldn't add that constraint. But on the other hand, if someone packages it for a distro (like void IIRC), they can add that dependency, or offer just one package that install both components.

If I were a Devuan user, I'd push to include it in the distro :)

**Comment by NRGLine4Sec** [comment]
Maybe the solution is to create a meta-package that include both ?
