### ISSUE TITLE
Multiple selected items in rule lists get automatically deselected

### ISSUE THREAD

**Issue by wsgcsysadmin** [evilsocket/opensnitch#560]
After selecting multiple items in a rule list they get automatically deselected after a few seconds.

I find this to be a problem when I want to delete lots of rules at one time.

The time it take for the deselection  to happen varies with the rules in the list. 

opensnitch 1.4.1-1 
python3-opensnitch-ui 1.4.2-1
Ubuntu Focal/20.04
Linux thing 5.4.0-91-generic #102-Ubuntu SMP Fri Nov 5 16:31:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**To Reproduce**
 - Open GU
 - Rules tab
 - Permanent Rule
 - Select one rule then shift-click to select multiple
 - Wait a bit

**Expected behavior**
The user should be able to easily select multiple rules, right click and then delete them.

**Comment by gustavo-iniguez-goya** [comment]
Hi @wsgcsysadmin , you're right.

For the time being, you can filter rules using the search box (by Duration, name, etc), then CTRL+a + right click -> Delete. It's not a solution, just a temporal workaround.

**Comment by tredondo** [comment]
> * Select one rule then shift-click to select multiple

Actually Shift+click behaves just like Click. Maybe @wsgcsysadmin meant Ctrl+click?

It would be nice to use Shift+click to select all rules from the selected one to the clicked one, like in other table controls.
