### ISSUE TITLE
[Feature Request] Mention starting opensnitchd daemon in Getting Started?

### ISSUE THREAD

**Issue by bayazidbh** [evilsocket/opensnitch#563]
Hi, I noticed that in the Getting Started page it doesn't mention about how to start the opensnitchd daemon.

I installed opensnitch from AUR, started it from the menu entry, and then was confused as to why I can't start or stop it from the Status button, nor why isn't there any pop-up appearing like in the screenshot.

It seems that opensnitch's deamon wasn't activated. It was quickly remedied by doing `sudo systemctl enable --now opensnitchd` but it wasn't obvious from the Getting Started page. Perhaps that could be added in the Getting Started page, just in case?

On another note, perhaps the GUI could detect if the daemon isn't running and escalate to try to run it? Though I confess, I'm not sure how that would work with a possible universal app distribution release (Flatpak and/or Snaps, not sure about AppImage's escalation capability) and with immutable OS.

**Comment by gustavo-iniguez-goya** [comment]
> It seems that opensnitch's deamon wasn't activated. It was quickly remedied by doing sudo systemctl enable --now opensnitchd but it wasn't obvious from the Getting Started page. Perhaps that could be added in the Getting Started page, just in case?

Sure @bayazidbh , no problem.

**Comment by gustavo-iniguez-goya** [comment]
Added to Installation https://github.com/evilsocket/opensnitch/wiki/Installation, since adding it to Getting Started maybe is out of place. It's more a post installation task.

I'll add it also to Known Problems.

Thank you!
