### ISSUE TITLE
[Feature Request] Show reject option in pop-ups

### ISSUE THREAD

**Issue by seonwoolee** [evilsocket/opensnitch#571]
### Summary:
I am loving the new reject feature so that applications don't have to wait to timeout. Could this reject option be added to the UI pop-ups? 

Also, a tangential question:  Will setting `DefaultAction` as `reject` in `/etc/opensnitchd/default-config.json` behave as expected, despite the UI not showing that as an option for the default action?

**Comment by gustavo-iniguez-goya** [comment]
Hi @seonwoolee ,

Yes, I think we'll end up adding it to the pop-ups. Thank you for the feedback!

>  Will setting DefaultAction as reject in /etc/opensnitchd/default-config.json behave as expected, despite the UI not showing that as an option for the default action?

mmh, no, that has not been added. I'll test it, and if it works fine I'll add it.
