### ISSUE TITLE
Upgrading opensnitch fails

### ISSUE THREAD

**Issue by yousefvand** [evilsocket/opensnitch#593]
**Describe the bug**
`yay` fails to upgrade from version `1.5.0.r6.9770cf5-1` to `1.5.0.r37.bb25362-1`
I have tried go get github.com/golang/protobuf/protoc-gen-go and got protoc-gen-go in $HOME/go/bin but still error exist. I don't set $GOPATH so it is $HOME/go by default (changing it doesn't help).

Include the following information:
 - OpenSnitch version:  `1.5.0.r6.9770cf5-1`
 - OS: ArchLinux
 - Version: 2022-01-01
 - Window Manager: KDE + KWIN
 - Kernel version: 5.16.0-arch1-1 #1 SMP PREEMPT Mon, 10 Jan 2022 20:11:47 +0000 x86_64 GNU/Linux

**To Reproduce**
Every time I try to upgrade Opensnitch.

**Expected behavior (optional)**
Smoothly upgrade to next version (as I always be able to)

**Error**
`cannot find package "github.com/golang/protobuf/protoc-gen-go" in any of:
        /usr/lib/go/src/github.com/golang/protobuf/protoc-gen-go (from $GOROOT)
        /home/me/.cache/yay/opensnitch-git/src/gopath/src/github.com/golang/protobuf/protoc-gen-go (from $GOPATH)
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: opensnitch-git`

**Comment by gustavo-iniguez-goya** [comment]
Hi @yousefvand ,

I don't use yay, so I don't know what's going on here. The few times I've used it I remember there was an option to delete local sources and compile it from upstream, is it possible that such option exists?

**Comment by yousefvand** [comment]
Hi. yay uses upstream (this repo) for compiling. I guess something is wrong with my GO environments variables but I cannot figure it out.

**Comment by gustavo-iniguez-goya** [comment]
hey @yousefvand , 

When executing `yay -S opensnitch-git` does it ask you to cleanBuild before proceeding? Did you try to clean Installed (I)?

```
[Aur:1] opensnitch-git-1.5.0.r37.bb25362-1

    1 opensnitch-git                             (Installed) (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 
```

If it fails with "... exists in the filesystem" try: `yay -S --overwrite '*' opensnitch-git`

Note that I'm not an Arch user, so proceed at your own risk O:) I think that you should really ask on the Arch forums.

**Comment by yousefvand** [comment]
I did uninstall opensnitch and installed it in clean mode as you suggested. Still get the same error.

**Comment by gustavo-iniguez-goya** [comment]
sorry @yousefvand , I don't know how to solve this problem :(. You better ask on Arch forums or even on the [AUR page](https://aur.archlinux.org/packages/opensnitch/), I'm sure they'll help you.
