### ISSUE TITLE
Jump to a rule from the events (right click)

### ISSUE THREAD

**Issue by BobSquarePants** [evilsocket/opensnitch#598]
From the Event view, I think it will be awesome if could right click on one entry and jump directly to the corresponding rule.
Cheers.

**Comment by BobSquarePants** [comment]
I just tried again the double-click. but nothing happen on my end.

https://user-images.githubusercontent.com/23012674/150636155-a0a144a7-710a-4d13-8cde-5ead422cd715.mp4

Blue circle = Right click
Yellow circle = left click

**Comment by BobSquarePants** [comment]
Indeed, it work. I didn't know they where clickable by column, I don't know how you can point it without making the GUI ugly :)

Maybe if someone double click on any other column, that only : Node, Process and Rule are clickable ?

**Comment by gustavo-iniguez-goya** [comment]
> I don't know how you can point it without making the GUI ugly :)

That's the million dollar question I think. In previous versions there was a small message suggesting that you could click on the rows to open a detailed view.

For v1.5.0 I added a help button with quick help. Historically other applications (*nix, mac, win) used to display a welcome dialog with hints, like "Did you know..." and [x] don't show this dialog again.

We'll keep improving it with all your feedback!

**Comment by BobSquarePants** [comment]
I think if a stupid (like me :) ) double click on a not clickable column, then a small hint/tooltip should appear ?
specifying which one are..

**Comment by gustavo-iniguez-goya** [comment]
> , then a small hint/tooltip should appear ?

Yes, I think it's doable :+1:

**Comment by gustavo-iniguez-goya** [comment]
All columns are clickable now, and there's a help button that explains the behaviour.
