### ISSUE TITLE
List of domains seem ineffective

### ISSUE THREAD

**Issue by BobSquarePants** [evilsocket/opensnitch#600]
When using the **To this list of domains** option in the rule. it seem to have no effect as a pop-up still appear.

OpenSnitch version: 1.4.1-1_amd64
OS: MX Linux 21
Window Manager: Xfce
Kernel version: SMP Debian 5.10.70-1

The rule
![2022-01-22-101220_](https://user-images.githubusercontent.com/23012674/150633033-7b351a14-cc95-4a22-996b-728ac48fd3f8.png)

The only file inside /usr/xxx/OpenSnitch/
**BlockedDomains.list** content:
```
#Test list
#
# google
.*\.google\.com
.*\.googleapis\.com
#
# Mozilla
.*\.telemetry\.mozilla\.org
.*\.addons\.mozilla\.org
.*\.services\.mozilla\.com
#
# FireFox
.*\.detectportal\.firefox\.com
```

Launching Firefox after the creation of the rule & list ->
![2022-01-22-1010_Should_not](https://user-images.githubusercontent.com/23012674/150633152-2e5579d7-8d1c-4015-ae53-65cbc3b7bdfa.png)

That pop-up should not appear, as detectportal.firefox.com is part of the rule..

Thanks.

**Comment by BobSquarePants** [comment]
FYI
Using **To this host** option work.
![2022-01-22-1155_FF](https://user-images.githubusercontent.com/23012674/150635725-a5ee8fcd-0baa-4b92-b628-63a7f53fe6d1.png)

field **To this host**
```
.*(google|googleapis|(telemetry|addons|services)\.mozilla|detectportal\.firefox)\.(com|net|org)
```

**Comment by gustavo-iniguez-goya** [comment]
I see. I think you're using version 1.4.x. In that version lists of regexp expressions is not supported.

Update to v1.5.x and let me know if it works: https://github.com/evilsocket/opensnitch/releases/tag/v1.5.0-rc.2

**Comment by BobSquarePants** [comment]
Indeed ! it work ! awesome ! 
Thanks @gustavo-iniguez-goya
