### ISSUE TITLE
Mixed Domain\IP lists support

### ISSUE THREAD

**Issue by sl805** [evilsocket/opensnitch#603]
### Summary:
Not all data sources provide structured lists of IP addresses\domains in  "hosts" format, for example: https://github.com/Neo23x0/signature-base/blob/master/iocs/c2-iocs.txt 

Is it possible to support text files which contain domains, ip-addresses or combination of them?

Best regards, sl805

**Comment by gustavo-iniguez-goya** [comment]
Support for lists of IP addresses and domains was added https://github.com/evilsocket/opensnitch/wiki/block-lists#notes

Support for mixed lists won't be supported for now.
