### ISSUE TITLE
The icon to clear the Events disappeared.

### ISSUE THREAD

**Issue by BobSquarePants** [evilsocket/opensnitch#605]
With version 1.4.1 it's was a clear events at the end of the arrow.

![Screenshot_2022-01-25_11-16-242](https://user-images.githubusercontent.com/23012674/150963463-0621eea2-9f42-4efc-b77d-dc1e405f3d07.png)

**Comment by BobSquarePants** [comment]
Is anyone have a workaround ? cli command or whatsoever ?

**Comment by BobSquarePants** [comment]
> Is anyone have a workaround ? cli command or whatsoever ?
I found a workaround : /var/log/opensnitchd.log :)

**Comment by gustavo-iniguez-goya** [comment]
That icon should be at the bottom now:

![image](https://user-images.githubusercontent.com/2742953/150966597-4ad1958a-95f2-4bd4-9e30-598b92348e6e.png)

I'm a bit perplexed, there should be at least a button.

What's the output of: `$ grep cmdClean /usr/lib/python3/dist-packages/opensnitch/res/stats.ui` ?

**Comment by BobSquarePants** [comment]
```       
<widget class="QPushButton" name="cmdCleanSql">
          <widget class="QPushButton" name="cmdCleanRules">
```

**Comment by gustavo-iniguez-goya** [comment]
Could you close the GUI (by right clicking on the systray icon), relaunch it again and see if the icon shows up?

**Comment by BobSquarePants** [comment]
I tried, but still no icon.
Maybe because I had the 1.4.1 version before, then unstill it with dpkg and install 1.5.0rc2 ?
I'll try a fresh install to see if the problem still occur.

**Comment by gustavo-iniguez-goya** [comment]
I tried that scenario, but it worked for me :/

**Comment by BobSquarePants** [comment]
I just tried with a fresh install (on MX Linux 21) Still the same.
If you want I can export this VM as an OVF ?

**Comment by gustavo-iniguez-goya** [comment]
That would be very useful. But instead of the VM, zipping the directory  /usr/lib/python3/dist-packages/opensnitch/` should be enough. Could you zip it and post it here?

**Comment by gustavo-iniguez-goya** [comment]
hey @BobSquarePants , coul you zip your directory `/usr/lib/python3/dist-packages/opensnitch/` so I can take a look and try to reproduce this issue?

**Comment by BobSquarePants** [comment]
[output.zip](https://github.com/evilsocket/opensnitch/files/7983910/output.zip)

**Comment by gustavo-iniguez-goya** [comment]
thank you @BobSquarePants . Problem reproduced, I'll fix it ASAP.

**Comment by BobSquarePants** [comment]
You're welcome. Glad that you could reproduced it.
