### ISSUE TITLE
[Feature Request] Rejecting from the new connection prompt

### ISSUE THREAD

**Issue by markozajc** [evilsocket/opensnitch#613]
### Summary:
It would be quite nice if it was possible to reject a connection right from the prompt - the only two options are deny and allow, and using the reject functionality requires editing the rule manually.

**Comment by gustavo-iniguez-goya** [comment]
Hi @markozajc !

I agree, I'll add it for next RC. I want to redesign a little bit the pop-up dialog, so it'll take some time.
