### ISSUE TITLE
Opensnitch does not catch / drop fwknop-client SPA UDP requests

### ISSUE THREAD

**Issue by brbar** [evilsocket/opensnitch#617]
Opensnitch does not show anything related to UDP requests made by fwknop client.
Nothing in events tab, there is no allow / deny dialog.
As a result this SPA UDP packet will not reach server but it will reach when you disable opensnitch according to tcpdump.

 - OpenSnitch version 1.5.0-1
 - OS: MX Linux 21
 - Window Manager: XFCE
 - Kernel version: 5.15.15-1~mx21+1

**To Reproduce**
1. Setup recent version of fwknop-client v2.6.10-12
2. Setup ~/.fwknoprc with a minimum necessary parameters
3. Run tcpdump on a server side: tcpdump -v -i eth0 udp and port 44111
4. Send SPA request using fwknop utility

**Expected behavior**
Opensnitch should catch such kind of UDP requests

**Comment by gustavo-iniguez-goya** [comment]
Thank you @brbar :+1:  I'll try to reproduce it.

**Comment by gustavo-iniguez-goya** [comment]
Ok, reproduced. I've got good and bad news:

- good news: we detect UDP SPA: `new connection udp => 40523:192.168.1.104 -> 192.168.1.1:62201 uid: 1000`

![image](https://user-images.githubusercontent.com/2742953/153396432-f39d081a-0701-4b6d-b0d1-d9efa3d8f2e2.png)


- bad news: sometimes when trying to access the process information, it's already gone. This can cause 2 behaviours:
  * Not display a pop-up: 
    ```
     new connection udp => 36455:192.168.1.104 -> 192.168.1.1:62201 uid: 1000
     PID can't be read /proc/ 1411336
     Could not find process by its pid 1411336 for: 192.168.1.104 (uid:1000) ->(udp)-> 192.168.1.1:62201
    ```
  * Display a pop-up, but in this situation the COMM field of the process is empty, and the GUI get freezed.
  
    ![image](https://user-images.githubusercontent.com/2742953/153396683-180cee43-fc4e-4da5-ba38-8bf6f8436e0a.png)


Something unexpected when connecting to a remote IP:

![image](https://user-images.githubusercontent.com/2742953/153401832-c9f2d618-4ff3-4322-a405-f6a325f7b204.png)

**Comment by gustavo-iniguez-goya** [comment]
Note: this problem could be avoided if we'd obtain (at least) the comm value via eBPF. If we had that value, we wouldn't need to exit applying the default action, so we could show a pop-up.

I implemented it, but I didn't commit it for v1.5.0.

**Comment by gustavo-iniguez-goya** [comment]
Regarding this log: `PID can't be read /proc/ 1411336` I wrote my concerns here:

https://github.com/evilsocket/opensnitch/blob/dd7cb13777719ae445cc19209386c006b22101ba/daemon/procmon/parse.go#L116-L117

Well, the answer is yes.

**Comment by brbar** [comment]
@gustavo-iniguez-goya
```
# uname -m
x86_64
# objdump -h /etc/opensnitchd/opensnitch.o | grep iptunnel
  7 kprobe/iptunnel_xmit 00000408  0000000000000000  0000000000000000  00000e90  2**3
```
I have ebpf selected in opensnitch gui settings as "Process monitor method"
Want to note that I'm sending this request to another machine. Did not tried to send on to local.

> Something unexpected when connecting to a remote IP

it happens because fwknop is trying to resolve your external IP, another option is to provide your IP directly with -a option:
```
# fwknop -a 123.123.123.123 -n myserv --verbose
```

**Comment by brbar** [comment]
@gustavo-iniguez-goya
What I need to do in order to see those connection attempts and make a rule for them like on your first screenshot? Because I tried to send those SPA requests many times and never seen that popup.
Right now the only solution is to disable opensnitch.

**Comment by gustavo-iniguez-goya** [comment]
Try enabling under Preferences -> Nodes -> [x] Debug invalid connections. You should see a pop-up of an "Outgoing connection".

The workaround in this case would be to obtain the Comm value of the process via eBPF, and the proper solution obtain the full path of the process + comm value via eBPF.

**Comment by brbar** [comment]
I got an error:
```
Error applying configuration: cannot open kprobe_events: open /sys/kernel/debug/tracing/kprobe_events: no such file or directory
```
Nothing in /sys/kernel/debug/:
```
# ls -l /sys/kernel/debug/
total 0
```

**Comment by gustavo-iniguez-goya** [comment]
ok, then try mounting debugfs:
```
 mount -t debugfs none /sys/kernel/debug/
```

There should be 2 dirs mounted:
```
$ mount | grep debug
debugfs on /sys/kernel/debug type debugfs (rw,nosuid,nodev,noexec,relatime,seclabel)
tracefs on /sys/kernel/debug/tracing type tracefs (rw,nosuid,nodev,noexec,relatime,seclabel)
```

If that works, you can make it persistent by adding it to your /etc/fstab: `debugfs    /sys/kernel/debug      debugfs  defaults  0 0`

**Comment by gustavo-iniguez-goya** [comment]
Issue fixed in 2 different ways. If we fail to obtain the path of the process, we'll use the comm name:

![Kazam_screencast_00009](https://user-images.githubusercontent.com/2742953/175431708-201c8da6-343c-4654-a8ed-cb82e0e17f11.gif)

If the path is available (for new processes it should be), then we'll use it:

![Kazam_screencast_00010](https://user-images.githubusercontent.com/2742953/175431873-3aa6ff84-f5bc-4892-9506-e9c2281bb85d.gif)
