### ISSUE TITLE
Clicking on a rule in the event tab resets columns width in the rule tab

### ISSUE THREAD

**Issue by Ileca** [evilsocket/opensnitch#619]
**To Reproduce**

In the rule tab, widen the columns to your liking.
Go to the event tab and click on one of your rules. It sends you to the rule tab.
Go back. Result: the columns are shrunk back.

**System**

- OpenSnitch version: 1.5-0rc2
- OS: Ubuntu
- Version: 21.10
- Window Manager: GNOME Shell 40.4.0
- Kernel version: 5.13.0-28-generic

**Comment by gustavo-iniguez-goya** [comment]
This issue should be fixed now. You can test it by downloading the file and replacing it with yours: https://raw.githubusercontent.com/evilsocket/opensnitch/3128dec63c270ca0d3ef912404bba6c8734cdfd7/ui/opensnitch/dialogs/stats.py

Thank you!
