### ISSUE TITLE
Remember selection

### ISSUE THREAD

**Issue by Ileca** [evilsocket/opensnitch#620]
1/ In any tab, when you select a row, scrolling up or down will not remember what you selected but the fixed selection relatively to the window instead. I am not sure I am crystal clear but when you select the last rule *of your window*, scrolling down will stop selecting this rule and keep selecting the last rule featured *in your window* instead.
I don't understand what purpose this behavior has. We can't scroll up and down without losing our point of reference.

2/ Scroll down in the rule tab, double click a rule, go back, the rule tab is reset. You went back to the top of the rules with no selection. This is really annoying if you want to check the details of many rules that are at the bottom of your rule tab.
I took the rule tab as an example but it's the same problem for every tab. The selection is not remembered.

3/ A corollary: when you double click on a rule in the event tab, it moves you to the rule tab. When you go back, OpenSnitch should have this rule selected as if you double clicked on it in the rule tab itself.
Again, this is also a problem for other tabs. Like when you click on the process column in the event tab and it moves you to the application tab.

Maybe I forgot something about the selection but that's what is coming to my mind right now.

**Comment by gustavo-iniguez-goya** [comment]
> 1/ ... scrolling up or down will not remember what you selected but the fixed selection relatively to the window instead.

It's the default behaviour of the widgets/list view. Before v1.5.0 version if a list had more than 256 elements and you scrolled down beyond that value, the scrollbar jumped back automatically to the row 256, making the view really useless. I fixed it, but I didn't modify the selection behaviour.

The behaviour you suggest needs to be implemented. :memo: 

> 2/ 

Correct :+1: I'll try to fix that problem. (note for myself: select row by "key" -> rule name, app name, host, ip, etc)

> 3/

It should be fixed by fixing the point 2.

**Comment by gustavo-iniguez-goya** [comment]
Fixed point 2.

**Comment by Ileca** [comment]
About 3/, I was thinking, shouldn't the normal behavior when you click on a rule/process in the even tab then "go back", to go back to the event tab, not the rule/applications tab? I mean, this is where you are coming from. I find the current behavior disorienting.

**Comment by gustavo-iniguez-goya** [comment]
closing this issue because the 3 points has been added.

Regarding the mentioned behaviour, it's a matter of tastes I guess.
