### ISSUE TITLE
[Feature Request] Automatic flush of unused rules

### ISSUE THREAD

**Issue by Ileca** [evilsocket/opensnitch#622]
Allow unused rules to be removed automatically after a set number of days.
You would have to prevent all our rules to be removed just because we didn't turn on our computer for a long time, though...
Meaning something more along the line of a number of days using OpenSnitch, like you have working days when shipping a package somewhere? I don't really know but a security valve for that kind of case.
You would also allow us to lock one rule as some rules could be used only once a month but be a sure occurrence we don't want to set back every month if our configuration flushes after 20 days.

Thank you.

**Comment by Juckjokar** [comment]
> Allow unused rules to be removed automatically after a set number of days. You would have to prevent all our rules to be removed just because we didn't turn on our computer for a long time, though... Meaning something more along the line of a number of days using OpenSnitch, like you have working days when shipping a package somewhere? I don't really know but a security valve for that kind of case. You would also allow us to lock one rule as some rules could be used only once a month but be a sure occurrence we don't want to set back every month if our configuration flushes after 20 days.
> 
> Thank you.

**Comment by NRGLine4Sec** [comment]
Personally, I'm not a fan of the idea that rules are automatically deleted.
On the other hand, it could be interesting if rules that have no hits since an arbitrary time are "marked" so that we can easily clean up when we can take some time to review the rules.

**Comment by gustavo-iniguez-goya** [comment]
I understood this feature request wrong. I thought it was related to temporary rules.

Permanent rules are by definition, permanent. If you don't want a permanent rule, it should not be there anyway. So automatic flush of permanent rules is not going to happen.

It has more sense to delete temporary rules, after a set number of days, etc.

Marking (/highlighting) rules would be doable now that we can colorize rules based on patterns.
