### ISSUE TITLE
No blocking of connections, no popup window, no entry in applications/internet on Ubuntu Maté 20.04

### ISSUE THREAD

**Issue by holgerjakobs** [evilsocket/opensnitch#624]
Please, check the FAQ and Known Problems pages before creating the bug report:
https://github.com/evilsocket/opensnitch/wiki/FAQs
https://github.com/evilsocket/opensnitch/wiki/Known-problems

**Describe the bug**
After installation, opensnitchd is active. Output of systemctl status opensnitch.service:
● opensnitch.service - Application firewall OpenSnitch
     Loaded: loaded (/lib/systemd/system/opensnitch.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2022-02-17 18:42:30 CET; 15min ago
       Docs: https://github.com/gustavo-iniguez-goya/opensnitch/wiki
    Process: 1209 ExecStartPre=/bin/mkdir -p /etc/opensnitchd/rules (code=exited, status=0/SUCCESS)
   Main PID: 1234 (opensnitchd)
      Tasks: 18 (limit: 38028)
     Memory: 66.0M
     CGroup: /system.slice/opensnitch.service
             └─1234 /usr/bin/opensnitchd -rules-path /etc/opensnitchd/rules

Feb 17 18:42:30 tuxedo.local.de systemd[1]: Starting Application firewall OpenSnitch...
Feb 17 18:42:30 tuxedo.local.de systemd[1]: Started Application firewall OpenSnitch.
Feb 17 18:42:30 tuxedo.local.de opensnitchd[1234]: [2022-02-17 17:42:30]  IMP  Starting opensnitch-daemon v1.5.0
Feb 17 18:42:30 tuxedo.local.de opensnitchd[1234]: [2022-02-17 17:42:30]  INF  Loading rules from /etc/opensnitchd/rules ...

Include the following information:
 - OpenSnitch version 1.5.0
 - OS: Ubuntu 20.04.3 LTS 
 - Maté Desktop
 - Kernel version: Linux 5.11.0-46-generic #51~20.04.1-Ubuntu SMP Fri Jan 7 06:51:40 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**To Reproduce**
Installation from .deb

None. There is no reaction when new connections are made. There is no entry in the application/internet menu. When I list the contents of the package opensnitch, there is only a single executable in /usr/bin called opensnitchd. Which executable could be registered in the application menu if there is no executable besides the daemon?

**Post error logs:** 
Lines from /var/log/syslog are not indicating any error
Feb 17 18:35:02 tuxedo opensnitchd[178766]: #033[2m[2022-02-17 17:35:02]#033[0m #033[97m#033[104m IMP #033[0m Starting opensnitch-daemon v1.5.0
Feb 17 18:35:02 tuxedo opensnitchd[178766]: #033[2m[2022-02-17 17:35:02]#033[0m #033[97m#033[42m INF #033[0m Loading rules from /etc/opensnitchd/rules ...
Feb 17 18:37:46 tuxedo systemd[1]: opensnitch.service: Succeeded.

If the daemon doesn't start:
It's running.

**Expected behavior (optional)**
I expected a pop up  window asking for permission to establish new connections, and an entry in applications/internet.

**Comment by gustavo-iniguez-goya** [comment]
closing since I believe that you needed to install the GUI package.
