### ISSUE TITLE
[Feature Request] Executable detector

### ISSUE THREAD

**Issue by GreenLunar** [evilsocket/opensnitch#630]
Ability to trace down executables.

### Summary:

 For more information, see #629

**Comment by gustavo-iniguez-goya** [comment]
Closing because the issue was a different problem.

**Comment by GreenLunar** [comment]
Please reopen this issue.
The problem may be different, but the idea is still valid.
If you can incorporate [FSpy](http://web.archive.org/web/20100712090331/http://mytty.org:80/fspy/) into OpenSnitch in a way which we know what files are involved during a request, it'd be amazing.
