### ISSUE TITLE
Apex legends server connection not caught but blocked

### ISSUE THREAD

**Issue by julikaiba** [evilsocket/opensnitch#642]
Running Apex legends, using steamplay, it cannot connect to ea's servers. For all connection popups generated (steam, wine, wineserver etc.) I clicked allow, however the connection still didnt work. Once I disabled OpenSnitch the connection worked instantly and without any problems. 
Looking at the caught events in OpenSnitch I cant see any denied/blocked connections. Neither does it seem to catch the attempts

While testing I also noticed that "ping" using the terminal seems to always work even when no rule is enabled (not sure if this is intended or not)

**Comment by julikaiba** [comment]
Creating a rule that allows executables from /* or setting the default nodes action without GUI to allow doesnt change a thing either.
I think I had this problem with one other program before but cant recall what it was

**Comment by gustavo-iniguez-goya** [comment]
Hi @julikaiba , for some reason there's some information missing, please, fill it out:

Include the following information:
 - OpenSnitch version.
 - OS: [e.g. Debian GNU/Linux, ArchLinux, Slackware, ...]
 - Version [e.g. Buster, 10.3, 20.04]
 - Window Manager: [e.g. GNOME Shell, KDE, enlightenment, i3wm, ...]
 - Kernel version: echo $(uname -a)
 - eBPF kprobes loaded: `cat /sys/kernel/debug/tracing/kprobe_events`

**Post error logs:** 
Go to Preferences -> Nodes -> set log level to DEBUG.
Launch the game, then upload the log or post the relevant lines.

Note: Before launching the game execute `date` or anottate the date, that way we can review the logs.

Also, check `[x] Debug invalid connections` under Preferences -> Nodes, and see if a pop-up shows up to allow or deny something.

**Comment by julikaiba** [comment]
OpenSnitch version: 1.5.0
OS: Manjaro
DE: Xfce 4.16
WM: Xfwm4
Kernel: Linux someones-pc 5.4.181-2-MANJARO #1 SMP PREEMPT Mon Feb 28 01:15:30 UTC 2022 x86_64 GNU/Linux

for some reason I cant upload the log, but the only lines written were the following:

`[2m[2022-03-02 22:16:30][0m [97m[104m IMP [0m Start writing logs to /var/log/opensnitchd.log
[2m[2022-03-02 22:16:30][0m [97m[41m ERR [0m eBPF Failed to load /etc/opensnitchd/opensnitch.o: open /etc/opensnitchd/opensnitch.o: no such file or directory
[2m[2022-03-02 22:16:30][0m [97m[43m WAR [0m error starting ebpf monitor method: open /etc/opensnitchd/opensnitch.o: no such file or directory
[2m[2022-03-02 22:16:30][0m [97m[43m WAR [0m Unable to set new process monitor method from disk: open /etc/opensnitchd/opensnitch.o: no such file or directory
[2m[2022-03-02 22:17:21][0m [97m[41m ERR [0m eBPF Failed to load /etc/opensnitchd/opensnitch.o: open /etc/opensnitchd/opensnitch.o: no such file or directory
[2m[2022-03-02 22:17:21][0m [97m[43m WAR [0m error starting ebpf monitor method: open /etc/opensnitchd/opensnitch.o: no such file or directory
[2m[2022-03-02 22:18:46][0m [97m[41m ERR [0m getting notifications: rpc error: code = Unavailable desc = transport is closing <nil>
[2m[2022-03-02 22:18:46][0m [97m[41m ERR [0m Connection to the UI service lost.

`

**Comment by gustavo-iniguez-goya** [comment]
Thank you!

> eBPF Failed to load /etc/opensnitchd/opensnitch.o: open /etc/opensnitchd/opensnitch.o: no such file or directory

Did you install opensnitch-ebpf-module-git? if not, please install it: https://aur.archlinux.org/packages/opensnitch-ebpf-module-git

It'll help to better intercept connections.

**Comment by nitschis** [comment]
Just wanted to report that I have the same problem. No popup or any indicator that apex is being blocked, yet connecting does not work until I disable opensnitch.

**Comment by gustavo-iniguez-goya** [comment]
thank you @nitschis. Please, I need to know OpenSnitch version, and logs in DEBUG level while the problem reproduces to investigate what's going on, see: https://github.com/evilsocket/opensnitch/issues/642#issuecomment-1057107393

Remember to install https://aur.archlinux.org/packages/opensnitch-ebpf-module-git if you're using an Arch based distro.

**Comment by nitschis** [comment]
@gustavo-iniguez-goya Thank you for your reply.

What is opensnitch-ebpf-module? After installing it, Apex connection worked. I did not get a popup, but I guess the general proton rule which I have set for other game might have been responsible for that?

In case, it is still relevant:

Opensnitch: 1.5.0-3

OS: 5.16.11-2-MANJARO @ latest update

KDE Plasma 5.24.2

```

sudo cat /sys/kernel/debug/tracing/kprobe_events                                                                                1 ✘ 
r64:kprobes/rtcp_v6_connect tcp_v6_connect
p:kprobes/pudp_sendmsg udp_sendmsg
p:kprobes/pudpv6_sendmsg udpv6_sendmsg
p:kprobes/piptunnel_xmit iptunnel_xmit
p:kprobes/ptcp_v4_connect tcp_v4_connect
r64:kprobes/rtcp_v4_connect tcp_v4_connect
p:kprobes/ptcp_v6_connect tcp_v6_connect
```

**Comment by gustavo-iniguez-goya** [comment]
the ebpf module interceptts connections at kernel level. If it's not installed then we have to rely on ProcFS (/proc/), which is less reliable thatn the ebpf one.

Thank you for confirming that installing the ebof module solved the issue!

**Comment by julikaiba** [comment]
Solved it for me as well. Thanks :)
