### ISSUE TITLE
Opensnitch UI won't open with qt-5.12.3

### ISSUE THREAD

**Issue by andrewfader** [evilsocket/opensnitch#644]
```
❯ opensnitch-ui
Loading translations: /usr/lib/python3.10/site-packages/opensnitch/i18n locale: en_US
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Cannot mix incompatible Qt library (5.15.2) with this library (5.15.3)
[1]    166367 IOT instruction (core dumped)  opensnitch-ui
```

Include the following information:
opensnitch-git 1.5.0.r17.a2f237a-1
Arch Linux 5.15.26-hardened1-1-hardened-git-r1049098 #1 SMP PREEMPT Fri, 04 Mar 2022 02:53:28 +0000 x86_64 GNU/Linux
Gnome on wayland

**Comment by gustavo-iniguez-goya** [comment]
> Cannot mix incompatible Qt library (5.15.2) with this library (5.15.3)

Hi @andrewfader , is opensnitch the only app that crashes? I see some reports of that warning:

https://forum.artixlinux.org/index.php/topic,3781.0.html
https://forum.manjaro.org/t/extra-qt5-es2-base-5-15-2-kde-r199-4-contains-libqt5core-so-5-form-5-15-3/71426
https://discuss.getsol.us/d/7015-cannot-mix-incompatible-qt-library-5152-with-this-library-5153

**Comment by andrewfader** [comment]
Correct. I guess it is an Arch bug.

**Comment by Scimmia22** [comment]
For future reference, this is almost always user error. People install things from outside of the Arch repos and never rebuild them.

**Comment by andrewfader** [comment]
Correct, had to rebuild qt5-styleplugins.
