### ISSUE TITLE
UI Runs But Displays No Window

### ISSUE THREAD

**Issue by gavinhoward** [evilsocket/opensnitch#645]
**Describe the bug**

`opensnitch-ui` starts, but no window appears. Instead, I get this output:

```
Loading translations: /home/gavin/.local/lib/python3.10/site-packages/opensnitch/i18n locale: en_US
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-gavin'
using IPASN DB: /usr/lib/python3/dist-packages/data/ipasn_20140513_v12.dat.gz
exception loading ipasn db: [Errno 2] No such file or directory: '/usr/lib/python3/dist-packages/data/ipasn_20140513_v12.dat.gz'
Install python3-pyasn to display IP's network name.
new node connected, listening for client responses... /tmp/osui.sock
```

Include the following information:
 - OpenSnitch v1.5.0.
 - OS: Gentoo/Linux
 - Version: Up-to-date (rolling release).
 - Window Manager: Awesome Window Manager
 - Kernel version: `Linux <hostname> 5.15.26-gentoo-x86_64 #5 SMP PREEMPT Sat Mar 26 22:20:39 MDT 2022 x86_64`

**To Reproduce**

Build and install the daemon and UI separately and manually on Gentoo. Use OpenRC to supervise the daemon. See **Additional Context**.

When I attempt to run `opensnitch-ui` from the command-line, I get the output above. It gives no errors (besides the one about `pyasn`) and keeps running, but no window is displayed.

**Expected behavior (optional)**

The `opensnitch-ui` window is displayed.

**Screenshots**
If applicable, add screenshots to help explain your problem. It may help to understand the issue much better.

**Additional context**

I had to build OpenSnitch manually.

The daemon built and installed without problems. I am running it under OpenRC with the following setup:

```
#!/sbin/openrc-run

description="opensnitchd"
supervisor=supervise-daemon
respawn_period="${respawn_period:-60}"
term_type="${term_type:-linux}"
command="/usr/local/bin/opensnitchd"
command_args_foreground="-rules-path /etc/opensnitchd/rules"
pidfile="/var/run/opensnitchd.pid"

depend() {
	use net
}

start_pre() {
	/bin/mkdir -p /etc/opensnitchd/rules
	return 0
}
```

The daemon starts without problems.

However, building and installing the UI had problems because Gentoo does not allow users to run Python `pip` without the `--user` flag.

So I changed the `Makefile` in the `ui/` directory to this:

```
all: opensnitch/resources_rc.py

install:
	@pip3 install --user --upgrade .

opensnitch/resources_rc.py: translations deps
	@pyrcc5 -o opensnitch/resources_rc.py opensnitch/res/resources.qrc
	sed -i 's/^import ui_pb2/from . import ui_pb2/' opensnitch/ui_pb2*

translations:
	@cd i18n ; make
	
deps:
	@pip3 install --user -r requirements.txt

clean:
	@rm -rf *.pyc
	@rm -rf opensnitch/resources_rc.py
```

The only two changes were to add the `--user` flag on both `pip` commands.

After that, building and installing with `make && make install` worked.

**Comment by gustavo-iniguez-goya** [comment]
Hi @gavinhoward ,

mmh, do you have an opensnitch icon on the system tray?

![image](https://user-images.githubusercontent.com/2742953/160289094-4d76be28-456c-443e-8768-88095efe24ec.png)

**Comment by gavinhoward** [comment]
Unfortunately, no, but that's probably because I'm running the Awesome Window Manager.

**Comment by gustavo-iniguez-goya** [comment]
if the systray is not available, the GUI should appear after launching opensnitch-ui, but maybe there's some condition that is preventing from showing it up.

AWM has a system tray according to their web, so I suggest you to install/use it, to be able to click on our systray icon to show/close the GUI. Otherwise there's no way of doing it.

**Comment by gavinhoward** [comment]
Oh, I didn't know it was necessary to start it from the systray.

I added it and OpenSnitch appeared. I clicked on the icon, and the window appeared.

Thank you.
