### ISSUE TITLE
Qt blocks Ctrl-C

### ISSUE THREAD

**Issue by adisbladis** [evilsocket/opensnitch#65]
The Qt mainloop blocks and intercepts Ctrl-C.
This means Ctrl-C does not lead to the application being terminated.

This was always the case. This issue has just been amplified now that the Qt mainloop is always running.

**Comment by allo-** [comment]
Same here. SIGTERM doesn't seem to reset the firewall rules. Is there currently any way to stop it without flushing iptables?

**Comment by adisbladis** [comment]
@allo- This issue will largely be resolved when https://github.com/evilsocket/opensnitch/issues/20 is fixed since the rules should not be directly handled by the ui.

I tried looking into it but me and gui programming don't really mix.

**Comment by adisbladis** [comment]
Fixed in https://github.com/evilsocket/opensnitch/pull/84
