### ISSUE TITLE
pop-up dialog: font of a particular section

### ISSUE THREAD

**Issue by Golddouble** [evilsocket/opensnitch#650]
Hello

First: Please note: I have inactivated antialiasing in my system, because I do not want to use it. 

Problem:
I don't like the font in the red framed text:
![k20220409-141757](https://user-images.githubusercontent.com/13977359/163538093-dd92749f-87d1-4eb0-a77b-100728231d1f.jpg)

Question:
Is there a way to change this font into Arial?

**OS:**
 - OS: MX-Linux 19.4 (Debian 10 based)
 - Window Manager: Xfce
 - Kernel version: 
 ```
$ echo $(uname -a)
Linux mx 4.19.0-20-amd64 #1 SMP Debian 4.19.235-1 (2022-03-17) x86_64 GNU/Linux
```

Thank you.

**Comment by gustavo-iniguez-goya** [comment]
Yes, install the app `qt5ct`. It'l let you customize qt5 apps.

**Comment by Golddouble** [comment]
Thank you for this hint.

1. I have changed the font in "qt5ct" as you can see in the picture.
2. I have pressed the apply-button
3. I have closed Opensnitch
4. I have started Opensnitch again

See here: https://i.imgur.com/5AvXB7Y.png

**Result:**
The font chosen in "qt5ct" is completely different. No font in the Opensnitch dialogue has this font.

The Opensnitch dialogue shows about two different fonts, as it was before. One is Arial, the other in the red frame is something different.

**Comment by Golddouble** [comment]
OK. The error was, that I did not have the entry "qt5ct" in the file `/etc/X11/Xsession.d/56xfce4-qtconfig`. I have fixed that now. And yes: Now some fonts have changed in Opensnitch. 
Here are the fonts I have chosen now:
![k20220417-085724](https://user-images.githubusercontent.com/13977359/163704381-0ed84785-adb2-4861-8ee3-4ae6dee21d4a.jpg)

I intentionally chose fonts that are very special. So it is easier to see, if they are applied.

However, only those fonts, that I was already satisfied with, changed. But the font in question, which I mentioned above, still does not change:
![k20220417-085722](https://user-images.githubusercontent.com/13977359/163704468-61504108-0196-4594-a4d9-1d413cb85d9d.jpg)

What do I miss? Thank you.

**Comment by gustavo-iniguez-goya** [comment]
aah, now I clearly see it. Those labels have an Ubuntu font, while the others use Sans. There's no reason to use the Ubuntu font, so I'll change it to Sans which is the default one.

Thank you for reporting this, I had no idea we were using that Ubuntu font :)

**Comment by gustavo-iniguez-goya** [comment]
If you want to test it: copy this file to `/usr/lib/python3/dist-packages/opensnitch/res/` : 
https://raw.githubusercontent.com/evilsocket/opensnitch/16c95d77fd560d0f193a465cdc1d46c042580244/ui/opensnitch/res/prompt.ui

**Comment by Golddouble** [comment]
Thank you.

Seems to work:
![k20220419-140853](https://user-images.githubusercontent.com/13977359/163999974-975ed38d-762b-4822-a953-2ee1e19084cc.jpg)
