### ISSUE TITLE
let the rule marked, when comming back

### ISSUE THREAD

**Issue by Golddouble** [evilsocket/opensnitch#651]
### Summary:
When I open a rule to edit it and after close the rule, I would appreciate, if it goes back to the rule where it started from. And that rule should be marked.

Version 1.5.0

1. I go to the rule tab
2. I double click on the second rule
3. I click on the "edit rule" button
4. I close the editor
5. I press the "arrow back" button
My exception is, that now the second rule is still marked blue. 
But no rule is marked now and I have to search again for the rule I have edited before.
That's not so user friendly.

**Comment by gustavo-iniguez-goya** [comment]
thank you @Golddouble ! This issue was first reported here #620 and fixed here: 9ff920fb60e65596b8932747bc61af2a81d173ee

I'm planned to release v1.5.1 in a couple or days.
