### ISSUE TITLE
pop-up dialog: box is too small

### ISSUE THREAD

**Issue by Golddouble** [evilsocket/opensnitch#653]
Hello

Problem:
The text in the expandable box is difficult to read because the box is too narrow:
![k20220419-142026](https://user-images.githubusercontent.com/13977359/164002335-0abaad55-bc00-436b-a3f2-a65fdfa5ff92.jpg)

Include the following information:
 - OpenSnitch version: 1.5.0
 - OS: Linux 19.4 (Debian GNU/Linux 10 (buster) )
 - Window Manager: Xfce 4.14.2
 - Kernel version: echo $(uname -a)
```
 $ echo $(uname -a)
Linux mx 4.19.0-20-amd64 #1 SMP Debian 4.19.235-1 (2022-03-17) x86_64 GNU/Linux
```

Thank you.

**Comment by gustavo-iniguez-goya** [comment]
[prompt.ui.txt](https://github.com/evilsocket/opensnitch/files/8514594/prompt.ui.txt)

Could you replace this pop-up dialog with yours?

`$ sudo cp prompt.ui.txt /usr/lib/python3/dist-packages/opensnitch/res/prompt.ui`

Close the GUI, reopen it again and force a pop-up. The box should have more room to display the text.

**Comment by Golddouble** [comment]
Thank you.

The replacement of `prompt.ui` has no effect.
 
(Opensnitch Version: in the meantime 1.5.1)

**Comment by Golddouble** [comment]
?

**Comment by gustavo-iniguez-goya** [comment]
This will be fixed once I finish merging the [firewall-policies](https://github.com/evilsocket/opensnitch/tree/firewall-policies) branch. In a couple of days I hope.

**Comment by Golddouble** [comment]
Thank you.

**Comment by Golddouble** [comment]
I have now installed version 1.5.2 .

But this is still sometimes an issue:
![k20230104-104643](https://user-images.githubusercontent.com/13977359/210527880-651dbdea-ed38-4b22-9cc0-604eac0ed833.png)

**Comment by gustavo-iniguez-goya** [comment]
Starting from this commit 0556dc1c81d7bdcdc715c31ca849e107d871ad7e this issue should be fixed. The combo boxes should have the default height size.
