### ISSUE TITLE
Error when trying to remove python3-opensnitch-ui

### ISSUE THREAD

**Issue by obeobe** [evilsocket/opensnitch#659]
Using:
* Pop OS 20.04.
* GNOME.
* Linux pop-os 5.16.19-76051619-generic #202204081339~1649696161~20.04~091f44b-Ubuntu SMP PREEMPT Thu Ap x86_64 x86_64 x86_64 GNU/Linux
* Not sure which opensnitch version, but I installed it last week, so very recent.

I try to remove python3-opensnitch-ui with the command: `apt remove python3-opensnitch-ui`.

This fails with error:
```
/var/lib/dpkg/info/python3-opensnitch-ui.postrm: 25: db_purge: not found
```

Please advise.

Thanks!

**Comment by gustavo-iniguez-goya** [comment]
Hi @obeobe ,

oops, sorry for that. Please, edit that file as root and remove the line "db_purge" . It should let you uninstall it.
I'll rebuild that package to fix that error.

Thank you for ~uninstalling~ reporting it!

**Comment by obeobe** [comment]
Hi @gustavo-iniguez-goya ,

Wow, that was crazy fast!!

Thanks for the suggestion. I can definitely do it, but I would like to double-check a couple of things first:
1. When I look at `/var/lib/dpkg/info/python3-opensnitch-ui.postrm`, I see two calls to `db_purge`:

```
...

pkill -15 opensnitch-ui || true
db_purge # <-- FIRST CALL

case "$1" in
    purge)
        purge_files
        ;;
    remove)
        db_purge # <-- SECOND CALL
        ;;
esac
```

1.1. I can also confirm that the value of `$1` in my case is `remove`, so it seems that the second `db_purge` call would be invoked as well.
1.2. Maybe I should just put an `exit 0` after the `pkill` line?

2. When I `locate opensnitch`, I see a bunch of stuff, like:
```
...
/etc/rc0.d/K01opensnitch
/etc/rc1.d/K01opensnitch
/etc/rc2.d/S01opensnitch
/etc/rc3.d/S01opensnitch
/etc/rc4.d/S01opensnitch
/etc/rc5.d/S01opensnitch
/etc/rc6.d/K01opensnitch
/etc/systemd/system/opensnitch.service
/etc/systemd/system/multi-user.target.wants/opensnitch.service
/home/user/.config/opensnitch
/home/user/.config/autostart/opensnitch_ui.desktop
/home/user/.config/opensnitch/settings.conf
...
/var/lib/dpkg/info/opensnitch.list
/var/lib/dpkg/info/opensnitch.postrm
/var/lib/dpkg/info/python3-opensnitch-ui.list
/var/lib/dpkg/info/python3-opensnitch-ui.md5sums
/var/lib/dpkg/info/python3-opensnitch-ui.postinst
/var/lib/dpkg/info/python3-opensnitch-ui.postrm
/var/lib/dpkg/info/python3-opensnitch-ui.prerm
/var/lib/systemd/deb-systemd-helper-enabled/opensnitch.service.dsh-also
/var/lib/systemd/deb-systemd-helper-enabled/multi-user.target.wants/opensnitch.service
/var/lib/systemd/deb-systemd-helper-masked/opensnitch.service
...
```
2.1. Just to note that I have originally attempted to remove both `opensnitch` and `python3-opensnitch-ui` with this command: `apt remove opensnitch python3-opensnitch-ui`.
2.2. After removing the `db_purge` line, can I expect `apt remove python3-opensnitch-ui` to also remove the above stuff?
2.2.1. If not - are these files supposed to remain after running `apt remove opensnitch python3-opensnitch-ui`? Or is there something else wrong?

Thanks again for the quick reply!
And I also want to note that I plan to re-install opensnitch. I was happy with it, and just wanted to remove it temporarily to check something...

**Comment by gustavo-iniguez-goya** [comment]
no problem ;)

db_purge: You can replace the references to db_purge by `db_purge 2>/dev/null || true` , in postrm and prerm.
I've rebuilt and tested the package and updated the release v1.5.1

In order to completely remove opensnitch-ui and all its files you need to use --purge: `sudo apt --purge remove python3-opensnitch-ui` .  By default apt doesn't remove installed configurations and extra files.

**Comment by obeobe** [comment]
It worked, thanks!!

**Comment by gustavo-iniguez-goya** [comment]
:+1:  closing

**Comment by licaon-kter** [comment]
I had to create **/usr/bin/db_purge** and `chmod 755` it:
```
#!/bin/sh

exit 0
```
