### ISSUE TITLE
[Feature Request] Allow/clarify regex in rule's "executable path"

### ISSUE THREAD

**Issue by BillDietrich** [evilsocket/opensnitch#661]
### Summary:
Allow regex in the "executable path" field of a rule, and fix the "tooltips" help for that field.

### Request:
If you hover the mouse over the "From this executable" field in a rule, the text says both "the user can not modify this field" and "you can use regex to deny executions from /tmp ...".  Which is it ?  Both can't be true.

If regexes are not supported in this field, please add support for them.

Please add an example to the help text showing how to make a regex in this field that accepts both "/usr/lib/firefox/firefox" and "/usr/lib64/firefox/firefox".  Various distros put executables in slightly different paths, and it would be best if users could have one rule that worked for both paths, as they hop from one distro to another, or use the same set of rules on multiple distros.

I'm using OpenSnitch 1.5.0-1 on openSUSE Tumbleweed.

Thanks.

**Comment by gustavo-iniguez-goya** [comment]
Hi Bill!

> If you hover the mouse over the "From this executable" field in a rule, the text says both "the user can not modify this field" and "you can use regex to deny executions from /tmp ...". Which is it ? Both can't be true.

Both are true :)  but "the user can not modify this field" sentence without context means nothing. There should be a link to the wiki "[learn more]" where what that sentence means is explained. Or directly remove the sentence.

That sentence means that the value is the path to the executable, received from the kernel and it's not manipulable by the user. That value is always static. So if you filter by executable, you can be sure that a process hasn't changed its name nor its path.

However if you filter by command line, the path to the executable might not be part of the command line:

```
$ cd /usr/bin
$ ./wget https://..../xxx.sh
```

Executable: `/usr/bin/wget`
Command line: `./wget https://..../xxx.sh`

If you filtered in this case by "From this command line: /usr/bin/wget ..." the rule wouldn't match this example.

Also and more important is, that a process can rewrite its command line on execution time:

![image](https://user-images.githubusercontent.com/2742953/167290456-d2848362-81a9-480d-998c-fff13c1f98ba.png)

The user launches a command (1), but hides it from tools like ps (2), but opensnitch detects the real command executed (3), and the command line typed (4).

The path of the point 3, is the rule field "From this executable".

> If regexes are not supported in this field, please add support for them.

regex are supported :+1: 

> Please add an example to the help text showing how to make a regex in this field that accepts both "/usr/lib/firefox/firefox" and "/usr/lib64/firefox/firefox". Various distros put executables in slightly different paths, and it would be best if users could have one rule that worked for both paths, as they hop from one distro to another, or use the same set of rules on multiple distros.

Ok :+1:  Besides adding an example, it'd be also useful to point users to the wiki page https://github.com/evilsocket/opensnitch/wiki/Rules-examples and add more examples there.

**Comment by gustavo-iniguez-goya** [comment]
@BillDietrich do you think this will be clear enough?
```
The value of this field is always the absolute path to the executable: /path/to/binary

Examples:
- Simple: /usr/lib/firefox/firefox
- Multiple paths: ^/usr/lib(64|)/firefox/firefox$
- Multiple binaries: ^(/usr/sbin/ntpd|/lib/systemd/systemd-timesyncd|/usr/bin/xbrlapi|/usr/bin/dirmngr)$ 
- Deny/Allow executions from /tmp:
^/(var/|)tmp/.*$

For more examples visit the [wiki page](https://github.com/evilsocket/opensnitch/wiki/Rules-examples) or ask on the [Discussion forums](https://github.com/evilsocket/opensnitch/discussions).
```

**Comment by gustavo-iniguez-goya** [comment]
@BillDietrich or suggest another text that explains better this field, and I'll write the examples :)
