### ISSUE TITLE
rule-set pop-up-window: please integrate html-code showing up

### ISSUE THREAD

**Issue by slynobody** [evilsocket/opensnitch#663]
**Describe the bug**
When a rule-set pop-up-window shows up, part of the information given has html-code on it (did occur in beta-versions before 1.5 already, was gone in major versions, did not vanish with 1.51)

btw: your debian-packages have dependency-problems, resulting in workarounds like needing to first install an older version that could be updated then.

os 1.51
debian 11
kde
5.17.6

**Comment by gustavo-iniguez-goya** [comment]
closing due to lack of information. Provide the requested information in order to keep analyzing the issue.
