### ISSUE TITLE
No such file or directory: '/etc/services'

### ISSUE THREAD

**Issue by gssantana** [evilsocket/opensnitch#671]
**Describe the bug**

Include the following information:
 - OpenSnitch version. v1.6.0-rc.1
 - OS: openSUSE Tumbleweed 20220607
 - Version openSUSE Tumbleweed 20220607
 - Window Manager: GNOME Shell
 - Kernel version: Linux brain 5.18.1-1-default #1 SMP PREEMPT_DYNAMIC Mon May 30 07:49:01 UTC 2022 (d00e88d) x86_64 x86_64 x86_64 GNU/Linux

**To Reproduce**

After install opensnitch server and gui v1.6.0-rc.1, when I try to open opensnitch-ui, I get the error No such file or directory: '/etc/services' 

**Post error logs:** 

Themes not available. Install qt-material if you want to change GUI's appearance: pip3 install qt-material.
Loading translations: /usr/lib/python3/dist-packages/opensnitch/i18n locale: en_US
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
is new file, or IN MEMORY, setting initial schema version
setting schema version to: 1
setting schema version to: 1
schema version: 1
db schema is up to date
exception loading ipasn db: No module named 'pyasn'
Install python3-pyasn to display IP's network name.
Traceback (most recent call last):
  File "/usr/bin/opensnitch-ui", line 74, in <module>
    service = UIService(app, on_exit)
  File "/usr/lib/python3/dist-packages/opensnitch/service.py", line 92, in __init__
    self._stats_dialog = StatsDialog(dbname="general", db=self._db, appicon=self.white_icon)
  File "/usr/lib/python3/dist-packages/opensnitch/dialogs/stats.py", line 397, in __init__
    self._fw_dialog = FirewallDialog(appicon=appicon)
  File "/usr/lib/python3/dist-packages/opensnitch/dialogs/firewall.py", line 47, in __init__
    self._fwrule_dialog = FwRuleDialog(appicon=self.appicon)
  File "/usr/lib/python3/dist-packages/opensnitch/dialogs/firewall_rule.py", line 55, in __init__
    self.net_srv = NetworkServices()
  File "/usr/lib/python3/dist-packages/opensnitch/utils.py", line 323, in __init__
    etcServices = open("/etc/services")
FileNotFoundError: [Errno 2] No such file or directory: '/etc/services'

**Comment by gustavo-iniguez-goya** [comment]
damn! thank you @gssantana 

I'll generate a new release + GUI packages. Meanwhile you can just copy the file https://raw.githubusercontent.com/evilsocket/opensnitch/master/ui/opensnitch/utils.py to your installation directory (/usr/lib/python3/dist-packages/opensnitch/)

**Comment by munix9** [comment]
@gustavo-iniguez-goya FYI:

According to the information in https://kubic.opensuse.org/blog/2019-12-05-usr-etc/, a possible solution could look like this:
```
--- a/ui/opensnitch/utils.py
+++ b/ui/opensnitch/utils.py
@@ -320,8 +320,12 @@ class NetworkServices():
     ports_list = []
 
     def __init__(self):
+        etcServicesPath = "/etc/services"
+        if not os.path.isfile(etcServicesPath) and os.path.isfile("/usr/etc/services"):
+            etcServicesPath = "/usr/etc/services"
+
         try:
-            etcServices = open("/etc/services")
+            etcServices = open(etcServicesPath)
             for line in etcServices:
                 if line[0] == "#":
                     continue
@@ -339,7 +343,7 @@ class NetworkServices():
             self.srv_array.append("wireguard/51820 WireGuard VPN")
             self.ports_list.append("51820")
         except Exception as e:
-            print("Error loading /etc/services:", e)
+            print("Error loading " + etcServicesPath + ":", e)
 
     def to_array(self):
         return self.srv_array
```
It first looks to see if an `/etc/services` exists. If not and a `/usr/etc/services` exists, this is used.
