### ISSUE TITLE
Themes not available.

### ISSUE THREAD

**Issue by BobSquarePants** [evilsocket/opensnitch#674]
Hi everyone,

in the preferences under the UI tab I can read (in red) -->
![Themes](https://user-images.githubusercontent.com/23012674/175057949-fea7a550-3292-4c2a-b656-05ca9455514a.png)

It seem that on my system I don't have pip3 installed (out of the box) 

I've tried 
```bash
apt update && apt install pip3
```
but I get
> E: Unable to locate package pip3

Any ideas ?
(suggestion: would it be possible to have a dark theme embedded in opensnitch gui ?) 

---

- OpenSnitch version :[v1.6.0-rc.1](https://github.com/evilsocket/opensnitch/releases/tag/v1.6.0-rc.1)
- OS: Devuan
- Window Manager: XFCE
- Kernel version: Linux 5.10.0-9-amd64 .1 SMP Debian 5.10.70-1 (2021-09-30) x86_64 GNU/Linux

**Comment by BobSquarePants** [comment]
I've downloaded the necessary

Too bad that it take the installation of 300MB + 2MB

> 
> Collecting qt-material
>   Downloading qt_material-2.12-py3-none-any.whl (1.7 MB)
>      |████████████████████████████████| 1.7 MB 3.4 MB/s 
> Collecting Jinja2
>   Downloading Jinja2-3.1.2-py3-none-any.whl (133 kB)
>      |████████████████████████████████| 133 kB 40.0 MB/s 
> Collecting MarkupSafe>=2.0
>   Downloading MarkupSafe-2.1.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25 kB)
> Installing collected packages: MarkupSafe, Jinja2, qt-material
> Successfully installed Jinja2-3.1.2 MarkupSafe-2.1.1 qt-material-2.12


As soon as those pip installation were done **the GUI quit.**
I rebooted the system and launched the GUI but it won't come up anymore...

**Comment by BobSquarePants** [comment]
I've redone the install on a fresh devuan 4

it work now... maybe because I did previously `sudo pip3 install qt-material` ?
Now I did without **sudo**

---

Now when I select a theme .xml in the GUI, hit apply the GUI freezes. I can move the windows but not the content. I force kill the GUI, re launch and the theme is applied.

**Comment by gustavo-iniguez-goya** [comment]
mmh, try the following: change the theme, and move the Preferences dialog to one edge of the desktop. There should be a message box "hidden" behind the Preference dialog that prevents clicking on the window.

**Comment by BobSquarePants** [comment]
indeed @gustavo-iniguez-goya 
![pop-up](https://user-images.githubusercontent.com/23012674/175896514-df0b40f8-ba2f-4005-b9a6-353448ca1bf9.png)

Thanks, closing.
