### ISSUE TITLE
System rules do not match the nftables

### ISSUE THREAD

**Issue by BobSquarePants** [evilsocket/opensnitch#675]
Hi,

it's my understanding that the **System rules** is the nftables ?

in the GUI\Rules\System rules
![SystemRules](https://user-images.githubusercontent.com/23012674/175066793-b1c5bc6f-2a11-4023-b9e4-d8be9ff8522b.png)

Those rules do not reflect the ones that I have in **/etc/nftables.conf** 

```
flush ruleset

table ip6 Tip6 {
	chain chPR {
		type filter hook prerouting priority 0; policy drop;
	}
}

table ip Tip {

	chain chIN {
		type filter hook input priority 0; policy drop;
		ct state established,related accept		
		iifname lo accept
	}
	chain chFW {
		type filter hook forward priority 0; policy drop;
	}
	chain chOUT {
		type filter hook output priority 0; policy drop;
		ct state established,related accept
	}
}
```

is that normal ?

Thanks.

**Comment by BobSquarePants** [comment]
Indeed when I do `nft list ruleset` I see all the rules.

Would it be possible for OpenSnitch to read also those from **etc/nftables.conf** ?

So we can edit them all in one place ?

Thanks @gustavo-iniguez-goya

**Comment by gustavo-iniguez-goya** [comment]
For now I don't think so, and I don't know if it'll be even possible, because we don't parse the rules directly from the kernel, we read them from our configuration file.

The idea has always been to coexist with other firewalls, but no allow to change their rules, so for now it'll work as is.
