### ISSUE TITLE
Compilation of ebpf_prog fails - failed to load BTF from vmlinux: Unknown error -2

### ISSUE THREAD

**Issue by Bogdan107** [evilsocket/opensnitch#680]
**Describe the bug**
I want to use ProcMonitorMethod=ebpf. For this, I need to compile ebpf_prog module.
Compilation fails with an error:
```
Error: failed to load BTF from /usr/src/linux-5.18.6-gentoo/vmlinux: Unknown error -2
```

Include the following information:
 - OpenSnitch version: 1.5.1
 - OS: Gentoo
 - Version: default/linux/amd64/17.1/no-multilib/hardened/selinux (getsebool:  SELinux is disabled)
 - Window Manager: Cinnamon
 - Kernel version: Linux win11 5.18.6-gentoo-x86_64 ?1 SMP PREEMPT_DYNAMIC Thu Jun 23 20:37:22 EEST 2022 x86_64 AMD Ryzen 5 4600H with Radeon Graphics AuthenticAMD GNU/Linux

**To Reproduce**
build script attached.

**Post error logs:** 
Compilation of ebpf_prog fails with an error:
```
Error: failed to load BTF from /usr/src/linux-5.18.6-gentoo/vmlinux: Unknown error -2
```

**Additional context**
1) Option CONFIG_PAHOLE_HAS_SPLIT_BTF automatically resets to "=Y":
```
$ grep BTF .config
# CONFIG_VIDEO_SONY_BTF_MPX is not set
CONFIG_PAHOLE_HAS_SPLIT_BTF=y
```
2) I don't use kernel 5.8, because it does not contain Makefile for AMD architecture.
```
Makefile:599: arch/amd64/Makefile: No such file or directory
make: *** No rule to make target 'arch/amd64/Makefile'.  Stop.
```

**Comment by Bogdan107** [comment]
This is build script "build_ebpf_prog.sh":
```
#!/bin/sh

set -e;

# https://github.com/evilsocket/opensnitch/tree/master/ebpf_prog

KERNDIR="/usr/src/linux";
OTMPDIR="/home/miki/del";
ODIR="${OTMPDIR}/opensnitch";
SAMPLESDIR="${KERNDIR}/samples/bpf";

export CC="/usr/bin/x86_64-pc-linux-gnu-gcc";
export CXX="/usr/bin/x86_64-pc-linux-gnu-g++";

KERNEL_OPTIONS_ENABLE="
    CONFIG_CGROUP_BPF
    CONFIG_BPF
    CONFIG_BPF_SYSCALL
    CONFIG_BPF_EVENTS
    CONFIG_KPROBES
    CONFIG_KPROBE_EVENTS

    CONFIG_FTRACE
    CONFIG_DEBUG_INFO
    CONFIG_DEBUG_INFO_DWARF5
    CONFIG_BPF_SYSCALL
    CONFIG_DEBUG_INFO_BTF
    CONFIG_DEBUG_INFO_REDUCED
";
KERNEL_OPTIONS_DISABLE="
    CONFIG_PAHOLE_HAS_SPLIT_BTF
";

Log() {
    #echo "";
    echo "--------------------------------------------------------";
    echo "$1";
    echo "";
};

Log "Install sources of opensnitch.";
rm -rf "${ODIR}";
cd "${OTMPDIR}";
git clone --depth 1 "https://github.com/evilsocket/opensnitch";

if [ -f "${KERNDIR}"/.config ]; then
    DSTCFG="/var/tmp/kernel-config-$(date +%Y-%m-%d_%H:%M:%M)";
    Log "Backup kernel config to ${DSTCFG}.";
    cp "${KERNDIR}"/.config "${DSTCFG}";
fi;

Log "Remove kernel sources.";
rm -rf "${KERNDIR}";

Log "Install pure kernel sources.";
# This will install kernel sources into /usr/src/linux-5.18.5-gentoo
# and make symlink /usr/src/linux-5.18.5-gentoo -> /usr/src/linux
USE=symlink emerge -1 gentoo-sources;

Log "Configure kernel: ENABLE options";
cd "${KERNDIR}";
for i in ${KERNEL_OPTIONS_ENABLE}; do
    echo "  Enable option: $i";
    /bin/sh scripts/config -e "$i";
done;

Log "Configure kernel: DISABLE options";
for i in ${KERNEL_OPTIONS_DISABLE}; do
    echo "  Disable option: $i";
    ./scripts/config -d "$i";
done;

Log "Patch bpf headers.";
patch "${KERNDIR}"/tools/lib/bpf/bpf_helpers.h < "${ODIR}"/ebpf_prog/file.patch

Log "Copy ebpf_prog sources into kernel tree.";
cd "${ODIR}"/ebpf_prog;
cp Makefile "${SAMPLESDIR}"/Makefile.opensnitch;
cp opensnitch-dns.c opensnitch-procs.c opensnitch.c "${SAMPLESDIR}"/;

Log "Prepare kernel.";
cd "${KERNDIR}" && yes "" | \
    make oldconfig && \
    make -j"$(nproc)" prepare && \
    make headers_install; # (~ 1 min)

Log "Build ebpf_prog.";
cd "${SAMPLESDIR}" && make -j"$(nproc)" -f Makefile.opensnitch CC="$CC" CXX="$CXX";

if [ ! -f "opensnitch.o" ]; then
    Log "File opensnitch.o not compiled. Abort!"
fi;

Log "Prepare module.";
objdump -h opensnitch.o; #you should see many section, number 1 should be called kprobe/tcp_v4_connect
llvm-strip -g opensnitch.o; #remove debug info

DST="/etc/opensnitchd";
Log "Install module into '${DST}' directory.";
cp opensnitch*.o "${DST}";
```

**Comment by Bogdan107** [comment]
This is build log for command:
```
/bin/sh build_ebpf_prog 2>&1 | tee /tmp/opensnitch__ebpf_prog__build.log
```
[opensnitch__ebpf_prog__build.log](https://github.com/evilsocket/opensnitch/files/8985972/opensnitch__ebpf_prog__build.log)

**Comment by Bogdan107** [comment]
This is kernel config file after build: [config.log](https://github.com/evilsocket/opensnitch/files/8985979/config.log)
File renamed to *.log extension, because system disallows txt files.

**Comment by gustavo-iniguez-goya** [comment]
Hi @Bogdan107 ,

Sorry to ask you for this, but please, post the errors (if any) compiling the modules as specified on the https://github.com/evilsocket/opensnitch/blob/master/ebpf_prog/README

Thank you in advance :)

**Comment by Bogdan107** [comment]
Proble with the next part: I use "Makefile.opensnitch", but must be "Makefile".
While I use "make -f Makefile.opensnitch", the other bpf tools use "Makefile".

When I replace name to Makefile, then compilation success.

I write a ebuild to automatically buld _ebpf_prog_ module of _opensnitch_ in the Gentoo.
This ebuild use hardcoded things. like the kernel version `5.18.6`. So, it is a resolution for my special case, but it's works!

Contents of file `/usr/local/portage/app-admin/opensnitch-module/opensnitch-module.ebuild`:
```
# Copyright 1999-2022 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=7
KVER=5.18.6

inherit linux-info

DESCRIPTION="eBPF kernel module for opensnitch - Desktop application firewall"
HOMEPAGE="https://github.com/evilsocket/opensnitch"
SRC_URI="https://github.com/evilsocket/opensnitch/archive/v${PV}.tar.gz -> ${P}.tar.gz
	https://www.kernel.org/pub/linux/kernel/v5.x/linux-${KVER}.tar.xz -> kernel-${KVER}.tar.xz"

LICENSE="GPL2"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

#DEPEND=""
RDEPEND=">=app-admin/opensnitch-${PV}"

S="${WORKDIR}/linux-${KVER}"
S_SNITCH="${WORKDIR}/opensnitch-${PV}"

src_prepare() {
	pushd "${S_SNITCH}"/ebpf_prog/ >/dev/null || die
		cp -f Makefile "${S}"/samples/bpf/Makefile
		#cp opensnitch-dns.c opensnitch-procs.c opensnitch.c "${S}"/samples/bpf/
		cp opensnitch.c "${S}"/samples/bpf/
	popd >/dev/null || die

	patch tools/lib/bpf/bpf_helpers.h "${S_SNITCH}"/ebpf_prog/file.patch
	
	default
}

src_configure() {
	set_arch_to_kernel
}

src_compile() {
	export CC

	# Prepare kernel:
	emake oldconfig

	# Enable kernel options:
	for opt in "
		CONFIG_CGROUP_BPF
		CONFIG_BPF
		CONFIG_BPF_SYSCALL
		CONFIG_BPF_EVENTS
		CONFIG_KPROBES
		CONFIG_KPROBE_EVENTS
		CONFIG_FTRACE
		CONFIG_DEBUG_INFO
		CONFIG_DEBUG_INFO_DWARF5
		CONFIG_BPF_SYSCALL
		CONFIG_DEBUG_INFO_BTF
		CONFIG_DEBUG_INFO_REDUCED
	"; do
		/bin/sh scripts/config --enable "${opt}"
	done

	# Disable kernel options:
	for opt in "
		CONFIG_PAHOLE_HAS_SPLIT_BTF
	"; do
		/bin/sh scripts/config --disaable "${opt}"
	done

	# Prepare kernel sources:
	emake prepare && emake headers_install

	# Build opensnitch module:
	pushd samples/bpf >/dev/null || die
	    emake || die
	    [ ! -f opensnitch.o ] && die
	    objdump -h opensnitch.o
	    llvm-strip -g opensnitch.o
	popd >/dev/null || die
}

src_install(){
	insinto /etc/opensnitchd/
	doins samples/bpf/opensnitch.o
}
```

**Comment by Bogdan107** [comment]
Error resolved: MUST to use directly `Makefile` name of the file.

**Comment by gustavo-iniguez-goya** [comment]
super cool @Bogdan107! :tada: 

I remember that other user created a .ebuild file to build the app, maybe you could join forces to help each other.

**Comment by Bogdan107** [comment]
> super cool @Bogdan107! tada
> 
> I remember that other user created a .ebuild file to build the app, maybe you could join forces to help each other.

I think, that more stronger way to build module with ebuild - by using eclass "linux-mod". In this way, ebuild automatically use current active kernel source tree, with all gentoo patches, installed in the system, without needs to customize things, like kernel version and SRC_URI in my version.
But I fails to build those varian of ebuild after some hours of tries. The main problem - is data in the Makefile.

My ebuild can be used as `-9999` version - as latest, presented in git. So, this variant may satisfy most of my needs in automatize of compiling of ebpf_prog module.

**My results of tries to build ebpf_prog as a kernel module:**
Success build of ebpf_prog module in portage system as kernel module is possible only if Makefile will be changed.

No reson to play with ebuild, while I can't to do this:
```
# Get sources:
git clone https://github.com/evilsocket/opensnitch
cd opensnitch/ebpf_prog
# Prepare kernel:
patch /usr/src/$(uname -r)/tools/lib/bpf/bpf_helpers.h
# Build module:
make -j$(nproc) KERNEL_DIR=/usr/src/$(uname -r) CC=/usr/bin/x86_64-pc-linux-gnu-gcc
# Install module:
for i in $(ls "*.o"); do cp $i /etc/opensnitchd/; done
```
Most desired change of _Makefile_:
- produce all build files under the current dir;
- do not write any files into the kernel dir;
- the single change in kernel tree - is patch for _tools/lib/bpf/bpf_helpers.h_ file.
