### ISSUE TITLE
[Feature Request] Add key bindings into table GUI/Rules/List of rules

### ISSUE THREAD

**Issue by Bogdan107** [evilsocket/opensnitch#681]
### Summary:
I open GUI and select Rules tab.
I select interested rule and wand to view details for this rule or edit it.
I double-click to it's row in table and expect to open "View/Edit rule" dialog. But data of the tab is switched to view "Show active conections, filtered for this rule"...

WTF?
I open "Rules" tab and want to make some things with some RULE, not with CONNECTIONS for this rule... But instead I compulsed to use "rule connections", not "rule details"...

I see another tabs and understand, that all tabs has the same behaviour - double-click action opens view "Show active connections, using value of the selected row as filter".

Ok. Those behaviour - is a conceptual for program and can't be changed.

To view details of the selected rule, I found this two ways:
- select row for rule and the click button ont the toolbar, which has no text neither helptext (may be this button has name "Properties");
- do right-click on the row of the rule and select "Edit" item in the pop-up menu.

E.g., view/edit rule without mouse - is impossible... Or possible, but intuitive is silent.

I expect, that I cant open "Edit rule" and "View rule" dialogs without mouse or with minimum of mouse usage.

I expect, that I can select interested rule by mouse or by keys Up/Down, and then opens "Edit rule/View rule" dialog by press some key, like "e" - for "Edit rule" dialog and "v" for "View rule" dialog.

### Add keybindings for "Rules" tab
Please, add this keybindings to the "Rules" tab:
- "E" - open "Edit rule" dialog for the selected rule;
- "V" - open "View rule" dialog for the selected rule (I don't want to change some part of rule by mischance);
- Ctrl-Tab - to swap between "Rules list" table (right part of page) and "Rules types" (left part of page).

### Add global keybindings
Please, add this keybindings to root window of GUI:
- Ctrl-F - activate "Filter" entry in the bottom of tab;
- Ctrl-P - open "Preferences" dialog;
- Ctrl-N - open "New rule" dialog;
- Alt-(E|N|P|H|A|D|O|U) - switch page: (E)Events, (N)Nodes, (R)Rules, (H)Hosts, (A)Applications, (D)Addresses, (P)Ports, (U)Users.

### Add helptext to buttons on the toolbar
Please, add helptext (pop-up text, which show when mouse hover over the button) to the buttons in the top-left of GUI:
- "Save ?what?" - for the first button;
- "Open Preferences dialog" - for the second button;
- "Create new rule dialog" - for the third button.

### Allow to change place of "Filter" widget
I want to place "Filter" widget above the "Tabs" widget.
Please, add an option to the "Preferences" dialog to allow to change position of "Filter" widget: "top" or "bottom".

### Add "View rule" dialog
There is only single way to view rule details - is "Edit rule" dialog. And this dialog has activated widgets, which values can be mischanged, so the rule can be mischanged. But I don't want to change some part of rule by mischance.
And I think, that programs for security MUST to have a read-only mode to prevent mischanges by default.
Please, add "View rule" dialog. This is the variant of "Edit rule" dialog. but with all widgets disabled - mode of all widgets changed to "read-only" value.

### Final
With this changes, usage of GUI must be more user-frendly and quicker.

**Comment by gustavo-iniguez-goya** [comment]
@Bogdan107 , there's no need for things like WTF, please remove it, then I'll think about this feature.

**Comment by Bogdan107** [comment]
> @Bogdan107 , there's no need for things like WTF, please remove it, then I'll think about this feature.
done
