### ISSUE TITLE
When applying a theme make the pop-up windows appear on top

### ISSUE THREAD

**Issue by BobSquarePants** [evilsocket/opensnitch#682]
indeed @gustavo-iniguez-goya 
![pop-up](https://user-images.githubusercontent.com/23012674/175896514-df0b40f8-ba2f-4005-b9a6-353448ca1bf9.png)

Thanks, closing.

_Originally posted by @BobSquarePants in https://github.com/evilsocket/opensnitch/issues/674#issuecomment-1167053088_

**Comment by gustavo-iniguez-goya** [comment]
Issue fixed. This one in particular was annoying as hell, thank you for reporting it.

You can verify it by replacing the utils.py file with yours 

https://raw.githubusercontent.com/evilsocket/opensnitch/f558ce75c08850ebd59cf0fa1dfcaff4611ccf8d/ui/opensnitch/utils.py
