### ISSUE TITLE
GUI crash

### ISSUE THREAD

**Issue by Pheidologeton** [evilsocket/opensnitch#693]
Please, check the FAQ and Known Problems pages before creating the bug report:
https://github.com/evilsocket/opensnitch/wiki/FAQs
https://github.com/evilsocket/opensnitch/wiki/Known-problems

**Describe the bug**
Opensnitch ui crash

Include the following information:
 - OpenSnitch version (latest git)
 - OS: Arch linux
 - Version: latest
 - Window Manager: KDE Wayland. X11 affected too
 - Kernel version: 5.18.9-262-tkg-cfs-llvm

**To Reproduce**
Start opensnitch-ui. Wait for rule creation prompt.

1. Start GUI
2. Wait until you are prompted to create a rule. At this point a crash occurs.

**Post error logs:** 
If it's a crash of the GUI: 
~~~
Themes not available. Install qt-material if you want to change GUI's appearance: pip3 install qt-material.
Loading translations: /usr/lib/python3.10/site-packages/opensnitch/i18n locale: ru_RU
is new file, or IN MEMORY, setting initial schema version
setting schema version to: 2
setting schema version to: 2
schema version: 2
db schema is up to date
Exception parsing .desktop file  /usr/share/applications/gqrx.desktop
using IPASN DB: /usr/lib/python3.10/site-packages/pyasn/data/ipasn_20140513_v12.dat.gz
exception loading ipasn db: [Errno 2] Нет такого файла или каталога: '/usr/lib/python3.10/site-packages/pyasn/data/ipasn_20140513_v12.dat.gz'
Install python3-pyasn to display IP's network name.
Exception parsing .desktop file  /usr/share/applications/gqrx.desktop
is new file, or IN MEMORY, setting initial schema version
setting schema version to: 2
setting schema version to: 2
schema version: 2
db schema is up to date
new node connected, listening for client responses... /tmp/osui.sock
Traceback (most recent call last):
File "/usr/lib/python3.10/site-packages/opensnitch/dialogs/prompt.py", line 181, in _check_advanced_toggled
self.adjust_size()
File "/usr/lib/python3.10/site-packages/opensnitch/dialogs/prompt.py", line 149, in adjust_size
self.setMinimumSize(self._width, self._height)
TypeError: arguments did not match any overloaded call:
setMinimumSize(self, int, int): argument 1 has unexpected type 'NoneType'
setMinimumSize(self, QSize): argument 1 has unexpected type 'NoneType'
fish: Job 1, 'opensnitch-ui' terminated by signal SIGABRT (Abort)
~~~

**Expected behavior (optional)**
The popup for creating a new rule is displayed correctly and does not crash.

**Comment by gustavo-iniguez-goya** [comment]
Thank you @Pheidologeton for reporting this problem. I've reverted the change to adjust the pop-ups size, so it shouldn't crash now.
If I ever add it again I¡ll try to reproduce this crash.
