### ISSUE TITLE
Incorrect popups

### ISSUE THREAD

**Issue by Pheidologeton** [evilsocket/opensnitch#694]
Please, check the FAQ and Known Problems pages before creating the bug report:
https://github.com/evilsocket/opensnitch/wiki/FAQs
https://github.com/evilsocket/opensnitch/wiki/Known-problems

**Describe the bug**
A process added to the whitelist still triggers in some cases. In this case, it is snowflake-pt-client, which is necessary for tor to work. According to the rule, it is allowed access to the network. But after some time, these popups appear. When I try to allow it, it just appears again. 

Include the following information:
 - OpenSnitch version. (Latest git)
 - OS: (Arch linux)
 - Version (Latest)
 - Window Manager: (KDE)
 - Kernel version: (Linux 5.18.9-262-tkg-cfs-llvm  TKG SMP PREEMPT_DYNAMIC Sun, 03 Jul 2022 13:03:04 +0000 x86_64 GNU/Linux)

**To Reproduce**
Describe in detail as much as you can what happened.
This error occurs randomly and not with all processes

1. Wait some time

**Post error logs:** 
 - Post last 15 lines of the log file `/var/log/opensnitchd.log`
~~~
^[[2m[2022-07-06 15:16:41]^[[0m ^[[97m^[[41m ERR ^[[0m Invalid rule received, applying default action
^[[2m[2022-07-06 15:22:49]^[[0m ^[[97m^[[43m WAR ^[[0m Error while asking for rule: rpc error: code = DeadlineExceeded desc = Deadline Exceeded -  (1445948) -> 127.0.0.1:46333 (proto:tcp uid:43)
^[[2m[2022-07-06 15:22:49]^[[0m ^[[97m^[[41m ERR ^[[0m Invalid rule received, applying default action
^[[2m[2022-07-06 15:37:25]^[[0m ^[[97m^[[43m WAR ^[[0m Error while asking for rule: rpc error: code = DeadlineExceeded desc = Deadline Exceeded -  (1445948) -> 127.0.0.1:46333 (proto:tcp uid:43)
^[[2m[2022-07-06 15:37:25]^[[0m ^[[97m^[[41m ERR ^[[0m Invalid rule received, applying default action
^[[2m[2022-07-06 15:55:38]^[[0m ^[[97m^[[43m WAR ^[[0m Error while asking for rule: rpc error: code = DeadlineExceeded desc = Deadline Exceeded -  (1445948) -> 127.0.0.1:46333 (proto:tcp uid:43)
^[[2m[2022-07-06 15:55:38]^[[0m ^[[97m^[[41m ERR ^[[0m Invalid rule received, applying default action
^[[2m[2022-07-06 16:43:09]^[[0m ^[[97m^[[43m WAR ^[[0m Error while asking for rule: rpc error: code = DeadlineExceeded desc = Deadline Exceeded -  (1445948) -> 127.0.0.1:46333 (proto:tcp uid:43)
^[[2m[2022-07-06 16:43:09]^[[0m ^[[97m^[[41m ERR ^[[0m Invalid rule received, applying default action
^[[2m[2022-07-06 17:07:40]^[[0m ^[[97m^[[43m WAR ^[[0m Error while asking for rule: rpc error: code = DeadlineExceeded desc = Deadline Exceeded -  (1445948) -> 127.0.0.1:46333 (proto:tcp uid:43)
^[[2m[2022-07-06 17:07:40]^[[0m ^[[97m^[[41m ERR ^[[0m Invalid rule received, applying default action
^[[2m[2022-07-06 17:22:08]^[[0m ^[[97m^[[43m WAR ^[[0m Error while asking for rule: rpc error: code = DeadlineExceeded desc = Deadline Exceeded -  (1445948) -> 127.0.0.1:46333 (proto:tcp uid:43)
^[[2m[2022-07-06 17:22:08]^[[0m ^[[97m^[[41m ERR ^[[0m Invalid rule received, applying default action
^[[2m[2022-07-06 17:24:51]^[[0m ^[[97m^[[43m WAR ^[[0m Error while asking for rule: rpc error: code = DeadlineExceeded desc = context deadline exceeded -  (1445948) -> 127.0.0.1:46333 (proto:tcp uid:43)
^[[2m[2022-07-06 17:24:51]^[[0m ^[[97m^[[41m ERR ^[[0m Invalid rule received, applying default action
^[[2m[2022-07-06 17:26:05]^[[0m ^[[97m^[[104m IMP ^[[0m Added new rule: ^[[31mdeny^[[0m if ^[[1mprocess.command^[[0m is '^[[33m/usr/bin/tor -f /etc/tor/torrc^[[0m'
^[[2m[2022-07-06 17:26:27]^[[0m ^[[97m^[[43m WAR ^[[0m Error while asking for rule: rpc error: code = Internal desc = Failed to serialize response! -  (1445964) -> stun.uls.co.za:53 (proto:udp uid:43)
^[[2m[2022-07-06 17:26:27]^[[0m ^[[97m^[[41m ERR ^[[0m Invalid rule received, applying default action
^[[2m[2022-07-06 17:28:29]^[[0m ^[[97m^[[43m WAR ^[[0m Error while asking for rule: rpc error: code = DeadlineExceeded desc = Deadline Exceeded -  (1445964) -> stun.uls.co.za:53 (proto:udp uid:43)
^[[2m[2022-07-06 17:28:29]^[[0m ^[[97m^[[41m ERR ^[[0m Invalid rule received, applying default action
^[[2m[2022-07-06 17:29:45]^[[0m ^[[97m^[[43m WAR ^[[0m Error while asking for rule: rpc error: code = Internal desc = Failed to serialize response! -  (1445964) -> stun.stunprotocol.org:53 (proto:udp uid:43)
^[[2m[2022-07-06 17:29:45]^[[0m ^[[97m^[[41m ERR ^[[0m Invalid rule received, applying default action
^[[2m[2022-07-06 17:29:57]^[[0m ^[[97m^[[43m WAR ^[[0m Error while asking for rule: rpc error: code = Internal desc = Failed to serialize response! -  (1445964) -> cdn.sstatic.net:53 (proto:udp uid:43)
^[[2m[2022-07-06 17:29:57]^[[0m ^[[97m^[[41m ERR ^[[0m Invalid rule received, applying default action
^[[2m[2022-07-06 17:30:02]^[[0m ^[[97m^[[43m WAR ^[[0m Error while asking for rule: rpc error: code = Internal desc = Failed to serialize response! -  (1445964) -> stun.stunprotocol.org:53 (proto:udp uid:43)
^[[2m[2022-07-06 17:30:02]^[[0m ^[[97m^[[41m ERR ^[[0m Invalid rule received, applying default action
^[[2m[2022-07-06 17:30:52]^[[0m ^[[97m^[[43m WAR ^[[0m Error while asking for rule: rpc error: code = Internal desc = Failed to serialize response! -  (1445964) -> stun.sonetel.com:53 (proto:udp uid:43)
^[[2m[2022-07-06 17:30:52]^[[0m ^[[97m^[[41m ERR ^[[0m Invalid rule received, applying default action
^[[2m[2022-07-06 17:31:15]^[[0m ^[[97m^[[43m WAR ^[[0m Error while asking for rule: rpc error: code = Internal desc = Failed to serialize response! -  (1445964) -> stun.stunprotocol.org:53 (proto:udp uid:43)
^[[2m[2022-07-06 17:31:15]^[[0m ^[[97m^[[41m ERR ^[[0m Invalid rule received, applying default action
~~~

**Expected behavior (optional)**
Processes added to the whitelist are not triggering

**Screenshots**
![Screenshot_1011](https://user-images.githubusercontent.com/61123444/177611955-18c6468d-d022-4d09-9935-3819c24e326b.png)

**Additional context**

**Comment by gustavo-iniguez-goya** [comment]
hi @Pheidologeton , you need to regenerate the protobuffer, there has been a change recently:

```bash
~ $ git clone https:..../opensnitch
~ $ cd opensnitch
opensnitch $ make protocol
opensnitch $ sudo cp ui/opensnitch/ui_pb2* /usr/lib/python3/dist-packages/opensnitch/
```

**Comment by pizzadude** [comment]
I noticed this in the logs.

```
[2022-07-07 11:23:34]  IMP  Start writing logs to /var/log/opensnitchd.log
[2022-07-07 11:23:35]  ERR  Error parsing firewall configuration /etc/opensnitchd/system-fw.json: json: cannot unmarshal string into Go struct field FwRule.SystemRules.Rule.Position of type uint64
[2022-07-07 11:23:38]  ERR  GetInfo() path can't be read
```

**Comment by pizzadude** [comment]
Also, this is the output of /sys/kernel/debug/tracing/kprobe_events

```
r10:kprobes/rtcp_v6_connect tcp_v6_connect
p:kprobes/pudp_sendmsg udp_sendmsg
p:kprobes/pudpv6_sendmsg udpv6_sendmsg
p:kprobes/piptunnel_xmit iptunnel_xmit
p:kprobes/ptcp_v4_connect tcp_v4_connect
r10:kprobes/rtcp_v4_connect tcp_v4_connect
p:kprobes/ptcp_v6_connect tcp_v6_connect
p:kprobes/p__x64_sys_execve __x64_sys_execve

```

This is /var/log/opensnitchd.log

```
[2022-07-07 17:01:03]  IMP  Start writing logs to /var/log/opensnitchd.log
[2022-07-07 17:01:04]  ERR  Error parsing firewall configuration /etc/opensnitchd/system-fw.json: json: cannot unmarshal string into Go struct field FwRule.SystemRules.Rule.Position of type uint64
[2022-07-07 17:01:05]  ERR  GetInfo() path can't be read
[2022-07-07 17:02:41]  WAR  Error while asking for rule: rpc error: code = Internal desc = Failed to serialize response! -  (48951) -> www.youtube.com:443 (proto:tcp uid:1000)
[2022-07-07 17:02:41]  ERR  Invalid rule received, applying default action
[2022-07-07 17:02:56]  WAR  Error while asking for rule: rpc error: code = Internal desc = Failed to serialize response! -  (48951) -> www.youtube.com:443 (proto:tcp uid:1000)
[2022-07-07 17:02:56]  ERR  Invalid rule received, applying default action
[2022-07-07 17:03:13]  WAR  Error while asking for rule: rpc error: code = Internal desc = Failed to serialize response! -  (48951) -> www.youtube.com:443 (proto:tcp uid:1000)
[2022-07-07 17:03:13]  ERR  Invalid rule received, applying default action
[2022-07-07 17:03:37]  WAR  Error while asking for rule: rpc error: code = Internal desc = Failed to serialize response! -  (48951) -> www.youtube.com:443 (proto:tcp uid:1000)
[2022-07-07 17:03:37]  ERR  Invalid rule received, applying default action
[2022-07-07 17:04:32]  IMP  Rule deleted allow-always-simple-home-pizzadude-net-downloadhelper-coapp-bin-net-downloadhelper-coapp-linux-64.json
[2022-07-07 17:04:49]  WAR  Error while asking for rule: rpc error: code = Internal desc = Failed to serialize response! -  (48951) -> www.youtube.com:443 (proto:tcp uid:1000)
[2022-07-07 17:04:49]  ERR  Invalid rule received, applying default action
[2022-07-07 17:05:11]  WAR  Error while asking for rule: rpc error: code = Internal desc = Failed to serialize response! -  (48951) -> www.youtube.com:443 (proto:tcp uid:1000)
[2022-07-07 17:05:11]  ERR  Invalid rule received, applying default action
[2022-07-07 17:05:27]  WAR  Error while asking for rule: rpc error: code = Internal desc = Failed to serialize response! -  (48951) -> www.youtube.com:443 (proto:tcp uid:1000)
[2022-07-07 17:05:27]  ERR  Invalid rule received, applying default action
[2022-07-07 17:05:46]  WAR  Error while asking for rule: rpc error: code = Internal desc = Failed to serialize response! -  (48951) -> www.youtube.com:443 (proto:tcp uid:1000)
[2022-07-07 17:05:46]  ERR  Invalid rule received, applying default action
```

These are the popups I get
![image](https://user-images.githubusercontent.com/1454420/177831410-26b43535-e230-4a18-bfc1-c42415923849.png)

Clicking "allow" does nothing.

@gustavo-iniguez-goya

**Comment by gustavo-iniguez-goya** [comment]
thank you @pizzadude !

The real problem here is the error deserializing the rule. That's usually cause by differences between the GUI and daemon's protobuffer.

My recommendation is to delete the files /usr/lib/python3/dist-packages/opensnitch/ui_pb*.
Generate protobuffers as [described here](https://github.com/evilsocket/opensnitch/issues/694#issuecomment-1176523647) and recompile the daemon.

I assume that your GUI files under /usr/lib/python3/dist-packages/opensnitch/ are the latest from git. Otherwise you'll need also to update them.

The generated files, opensnitch/daemon/ui/protocol/ui* and opensnitch/ui/opensnitch/ui_pb*, should have reference to the latest field added nolog:
```bash
$ grep nolog opensnitch/ui/opensnitch/ui_pb2*
opensnitch/ui/opensnitch/ui_pb2.py:      name='nolog', full_name='protocol.Rule.nolog', index=4,
$ grep -i nolog opensnitch/daemon/ui/protocol/ui.pb.go 
	Nolog                bool      `protobuf:"varint,5,opt,name=nolog,proto3" json:"nolog,omitempty"`
func (m *Rule) GetNolog() bool {
		return m.Nolog
```

Shall I generate new rpms to test?

**Comment by pizzadude** [comment]
I did both of those things multiple times, still same problem.

Here is my generated ui_pb2.py if that helps.

[ui_pb2.zip](https://github.com/evilsocket/opensnitch/files/9067199/ui_pb2.zip)

**Comment by gustavo-iniguez-goya** [comment]
Thank you @pizzadude , something is wrong with your protobuf file, there's a lot of code missing:
![image](https://user-images.githubusercontent.com/2742953/177870969-ee6649e5-609b-458c-b9f1-8c3ab52c8ee2.png)


Could you replace these files with yours? [ui_pb2-694.zip](https://github.com/evilsocket/opensnitch/files/9067399/ui_pb2-694.zip)


What grpcio-tools do you have installed btw? `$ pip3 show grpcio-tools`

**Comment by pizzadude** [comment]
```
pip3 show grpcio-tools                                                                                                    
Name: grpcio-tools
Version: 1.47.0
Summary: Protobuf code generator for gRPC
Home-page: https://grpc.io
Author: The gRPC Authors
Author-email: grpc-io@googlegroups.com
License: Apache License 2.0
Location: /home/pizzadude/.local/lib/python3.10/site-packages
Requires: grpcio, protobuf, setuptools
Required-by: 
```

I will try replacing the file and report back.

**Comment by pizzadude** [comment]
I tried downgrading grpcio and grpcio-tools to version 1.40.0 and 1.42.0, rebuilding, and it didn't solve the issue.

I tried replacing the files with the ones you attached and it didn't solve it either.

:(

**Comment by gustavo-iniguez-goya** [comment]
ok , I'll build new packages against latest sources. On the other hand, I just upgraded an old v1.5.0 installation on Arch to latest sources and works fine, so I think it must be something related with the protobuffers.

Anyway, check also that the running opensnitchd binary (pgrep -a opensnitchd) is using latest protobuf definitions:
```bash
$ pgrep -a opensnitchd
12345 /usr/bin/opensnitchd -rules-path /etc/opensnitchd/rules
$ strings /usr/bin/opensnitchd | grep -i nolog
(...)
github.com/evilsocket/opensnitch/daemon/ui/protocol.(*Rule).GetNolog
Nolog@protobuf:"varint,5,opt,name=nolog,proto3" json:"nolog,omitempty"
(...)
```

And see if the pop-ups works as expected with the protobuf I posted with new rules (like ping github.com, and see if the rule is created and applied), or if it fails with any application or one application in particular (like the one you posted, net.downloaded.coapp). I'll download also that app to see if I can reproduce it with it.

**Comment by pizzadude** [comment]
```
strings opensnitchd | grep -i nolog                                                                             master  
GetNolog
Nolog
json:"nolog"
Nolog@protobuf:"varint,5,opt,name=nolog,proto3" json:"nolog,omitempty"
os.openFileNolog
os.statNolog
os.statNolog.func1
os.lstatNolog
os.lstatNolog.func1
github.com/evilsocket/opensnitch/daemon/ui/protocol.(*Rule).GetNolog
nolog
nolog
os.openFileNolog
os.statNolog
os.lstatNolog
github.com/evilsocket/opensnitch/daemon/ui/protocol.(*Rule).GetNolog
```

One program it always fails with is aria2c when downloading a video with yt-dlp. 
yt-dlp --downloader aria2c -f "bestvideo[height<=?720][fps<=?30][vcodec!=?vp9]+bestaudio/best" https://www.youtube.com/watch?v=dWe7X88Vbys

**Comment by gustavo-iniguez-goya** [comment]
ok @pizzadude , I've tested the procs module on opensuse 15, kernel 5.9, and it's not getting the path of the processes, so that can lead to these errors.

Could you replace this opensnitch-procs.o with yours, stop the daemon, and launch the daemon of the zip as:
`# ./opensnitchd -rules-path /etc/opensnitchd/rules/`

[694.zip](https://github.com/evilsocket/opensnitch/files/9070702/694.zip)

You should see traces in the log like: ` IMP  ::: EXEC EVENT -> READ_CMD_LINE ppid: 0, pid: 3542, /usr/bin/tail`
Post some log lines like this one to see if it's getting the path correctly.

**Comment by pizzadude** [comment]
[2022-07-08 10:48:51]  IMP  Ruleset changed due to allow-always-simple-homepizzadudenpm-packagesbinaria2c.json, reloading ...
[2022-07-08 10:48:51]  IMP  Saved new rule: allow if process.path is '/home/pizzadude/.npm-packages/bin/aria2c'

[2022-07-08 10:46:25]  IMP  Saved new rule: allow if process.path is '/home/pizzadude/.local/bin/aria2c'
[2022-07-08 10:46:25]  IMP  Ruleset changed due to allow-always-simple-homepizzadudelocalbinaria2c.json, reloading ...

Weird... Those aren't the actual paths of aria2c. The actual path is /usr/bin/aria2c.

**Comment by gustavo-iniguez-goya** [comment]
good news then!

Yes, I expect that kind of behaviour. There'll be some rules that you'll have to update.

Without this module we were not able to detect connections initiated by short-lived processes like fwknop, it's more accurate now.

Anyway, I'll also check if the path is empty, to avoid these errors.

**Comment by gustavo-iniguez-goya** [comment]
I've pushed a change to solve these issues. @pizzadude could you compile the daemon + modules against latest sources?

**Comment by pizzadude** [comment]
Unfortunately I spoke too soon... Almost every electron application is detected as /proc/self/exe

**Comment by gustavo-iniguez-goya** [comment]
yeah, sorry. I added a workaround for that problem but I removed it on the last commit. Readded now.

What should be the correct path of that npm package? What was the path reported before these changes?

**Comment by pizzadude** [comment]
The correct path is /usr/bin/aria2c, it's not actually an npm package, idk why it picks it up as one.

**Comment by pizzadude** [comment]
Nope, there is no file at ~/.npm-packages/bin/aria2c or ~/.local/bin/aria2c. Only /usr/bin/aria2c

**Comment by gustavo-iniguez-goya** [comment]
great! please, if you see more quirks report them because it's really useful, thank you very much!

sorry if I already asked this, but is the aria2c binary launched by another app? or do you launch it directly? Would be interesting to strace it if it's launched by another app.

**Comment by pizzadude** [comment]
It is launched by another app, yt-dlp (youtube downloader).

**Comment by gustavo-iniguez-goya** [comment]
despite all new quirks, as far as I can tell now:

- we're able to intercept short-lived processes.
- we're more performant. I don't now in your case but on my system the difference is noticeable even if we use 1% CPU more.
- I don't see connections falling back to reading /proc/net/*, which means less I/O ops and less procs discovery times. (this in particular is not strictly related to the procs module)

Of course this is in its infancy and there's plenty of room for improvements. We'll see how it works out on others environments.

@Pheidologeton how about you? did you compile latest sources?

**Comment by Pheidologeton** [comment]
I built opensnitch and ebpf module. So far everything is working fine. I will be testing more. opensnitchd uses 0.025-0.05% CPU. I have hundreds of connections per second. If there are any problems I will contact you.

**Comment by gustavo-iniguez-goya** [comment]
thank you @Pheidologeton  :)

**Comment by gustavo-iniguez-goya** [comment]
time to break master branch again! sorry, just kidding. I've added the ability to get cmdline arguments directly from kernel.
That way we don't need to read /proc/<pid>/cmdline. It has its caveats though, but overall I think that is a good improvement.

Tested on kernels 5.18, 5.13, 5.11, 5.10, 5.9 and 5.6.6.  But please, if you can test it and report any problem it'd very useful.

Thank you!

**Comment by pizzadude** [comment]
I did some light testing and the latest changes seem to work ok so far.
