### ISSUE TITLE
Great project, I would like it to support localization into different languages.

### ISSUE THREAD

**Issue by NightFlexer** [evilsocket/opensnitch#699]
It would be cool if there was such a feature!

**Comment by gustavo-iniguez-goya** [comment]
Hi @NightFlexer ,

It has already been translated into several languages :) https://github.com/evilsocket/opensnitch/tree/v1.5.1/ui/i18n

And there's also a collaborative webpage to translate it, but the translations are broken at the moment, and not up to date with master branch: https://hosted.weblate.org/projects/opensnitch/gui/
