### ISSUE TITLE
opensnitch-ui packages installed in system locations with user as owner?

### ISSUE THREAD

**Issue by ivan-kljajic** [evilsocket/opensnitch#700]
Sorry if this is a stupid question: I am new to this application and to python on Linux. Anyway...

On Linux Mint Cinnamon 20.3 I have installed the latest opensnitch stable (one machine) and RC (another machine) using the package files and instructions provided (`sudo apt install ./opensnitch*.deb ./python3-opensnitch-ui*.deb`). On both, I see that the owner of the following directories and files is myself and not root. Is this expected / required? The other files/folders in these locations are owned by root on my two systems.

```
/usr/share/kservices5/kcm_opensnitch.desktop
/usr/share/doc/python3-opensnitch-ui/*
/usr/share/applications/opensnitch_ui.desktop
/usr/share/icons/hicolor/48x48/apps/opensnitch-ui.png
/usr/share/icons/hicolor/scalable/apps/opensnitch-ui.svg
/usr/lib/python3/dist-packages/opensnitch_ui-1.5.1.egg-info/*
/usr/lib/python3/dist-packages/opensnitch/*
/usr/bin/opensnitch-ui
```

**Comment by gustavo-iniguez-goya** [comment]
Hi @ivan-kljajic !

mmh, it's not required nor expected. I just did a fresh installation and you're right, those files are owned by the user that installs them.

**Comment by ivan-kljajic** [comment]
Hello again. I just installed the latest RC4 on a newly-built Linux Mint 21.1 (based off ubuntu 22.04) machine and the permissions issue seems to be gone in this version with one minor exception:

The symbolic link `~/.config/autostart/opensnitch_ui.desktop` is owned by root. For myself I would prefer files in my home directory to be owned by me, but this isn't really a big deal. I fixed it for myself by doing:
```
sudo chown -h ${LOGNAME}:${LOGNAME} ~/.config/autostart/opensnitch_ui.desktop
```
Note the `-h` option to `chown`. This is to just change the ownership of the symbolic link and not the ownership of the file to which it points, which I still want to be owned by root.

One thing I think might also be an issue is if the installer needs to create the `~/.config/autostart` folder then it might create that folder with root ownership, and thus prevent the user from adding their own autostart entries without having to `sudo`. I think I saw this when installing OpenSnitch 1.52 on a Rasberry PI OS (minimal desktop) machine that didn't have a user autostart folder until I installed opensnitch.

Anyways, thanks for the app!

**Comment by gustavo-iniguez-goya** [comment]
Thank you @ivan-kljajic !

I really don't know what's different with v1.5.x versions, because I've always created the packages in the same manner.

> One thing I think might also be an issue is if the installer needs to create the ~/.config/autostart folder then it might create that folder with root ownership, and thus prevent the user from adding their own autostart entries without having to sudo

oops! you're right.
