### ISSUE TITLE
[Feature Request] Sandboxed programs (wine)

### ISSUE THREAD

**Issue by dak8m** [evilsocket/opensnitch#701]
is it possible to add specific rules for executable files within wine?

Im not sure if this is possible but thought id ask as i usually have multiple .exes running through a single instance of proton(wine) and i can only add rules for the wine server/preloader itself

ty

**Comment by gustavo-iniguez-goya** [comment]
Hi @dak8m ,

mmh, yes, I think so, could you post the path to the binary and the cmdline arguments of the process? Or a screenshot of the pop-up, to see how we detect those apps.

If I remember correctly, in these cases you have to filter by the command line.

**Comment by dak8m** [comment]
This is what i get in the Events tab for anything running in proton:

![Untitled](https://user-images.githubusercontent.com/109321307/179336600-7878c8ac-e46a-4a2a-982f-bed51a9ee6f5.jpg)

how exactly do i filter by command line in the Events tab of opensnitch?

if i have to add rules manually for each executable will this also work if its sandboxed as a sub process of wine?

**Comment by gustavo-iniguez-goya** [comment]
> how exactly do i filter by command line in the Events tab of opensnitch?

double click on the Process or the Rule column and scroll to the ARGS column. Then you can select a line, copy it with CTRL-C and edit the Proton rule or create a new one:

![image](https://user-images.githubusercontent.com/2742953/179351074-8cfe438a-67bf-4a19-ad7b-d4b4e8cba113.png)

The copied line is in CSV format. Copy the field which corresponds to the ARGS column and that's all (without double quotes btw!).

> if i have to add rules manually for each executable will this also work if its sandboxed as a sub process of wine?

Yes :)

Alternatively you could delete your existing Proton rule, and when opensnitch prompts you to allow/deny it again you can select "from this command line", to create the rule automatically:

![image](https://user-images.githubusercontent.com/2742953/179351412-a70ae361-a8a4-43b3-86f3-e531cf880497.png)

**Comment by dak8m** [comment]
Choosing "from this command line" for everything fixed the issue for me, now it prompts me to make a rule for everything executed within wine

I did not know you could double click on the columns either!

Thankyou very much!
