### ISSUE TITLE
Using back slashes in path

### ISSUE THREAD

**Issue by dak8m** [evilsocket/opensnitch#706]
Opensnitch has created its own rule for an application in wine ( from this command line )

The path is:
S:\common\game\Launcher\..\bin\game.exe

If i try to edit this rule i get error: Command line regexp error

If i invert the slashes to:
S:/common/game/Launcher/../bin/game.exe

Now opensnitch will allow me to save the rule but the command line is wrong and the rule does not work

This also happens with "From this executable" path

**Comment by gustavo-iniguez-goya** [comment]
thank you @dak8m , reproduced. I'll try to fix it ASAP.

**Comment by gustavo-iniguez-goya** [comment]
@dak8m I think this issue is fixed https://github.com/evilsocket/opensnitch/commit/96a031ad125910b59166013dd4f08f24b16cab7e

it'd be great if you could test it and confirm that it works and doesn't breaks other rules. As far as I can tell it works as expected.

first backup the orig files:
```bash
$ sudo cp /usr/lib/python3/dist-packages/opensnitch/res/ruleseditor.ui  /usr/lib/python3/dist-packages/opensnitch/res/ruleseditor.ui.bak
$ sudo cp /usr/lib/python3/dist-packages/opensnitch/dialogs/ruleseditor.py  /usr/lib/python3/dist-packages/opensnitch/dialogs/ruleseditor.py.bak
```

then download the new ones: 
https://raw.githubusercontent.com/evilsocket/opensnitch/master/ui/opensnitch/res/ruleseditor.ui
https://raw.githubusercontent.com/evilsocket/opensnitch/master/ui/opensnitch/dialogs/ruleseditor.py

```bash
$ sudo cp ruleseditor.ui  /usr/lib/python3/dist-packages/opensnitch/res/ruleseditor.ui
$ sudo cp ruleseditor.py  /usr/lib/python3/dist-packages/opensnitch/dialogs/ruleseditor.py
```

**Comment by dak8m** [comment]
Thanks!

I ran out of time trying to debug this but im pretty sure the issue is im out of date using AUR. so if someone else could confirm it works that would be great and the ignore error below if this is the case

---
I am using 1.5.1-1 from: https://aur.archlinux.org/packages/opensnitch

`Themes not available. Install qt-material if you want to change GUI's appearance: pip3 install qt-material.
Traceback (most recent call last):
  File "/usr/bin/opensnitch-ui", line 23, in <module>
    from opensnitch.service import UIService
  File "/usr/lib/python3.10/site-packages/opensnitch/service.py", line 17, in <module>
    from opensnitch.dialogs.stats import StatsDialog
  File "/usr/lib/python3.10/site-packages/opensnitch/dialogs/stats.py", line 16, in <module>
    from opensnitch.dialogs.ruleseditor import RulesEditorDialog
  File "/usr/lib/python3.10/site-packages/opensnitch/dialogs/ruleseditor.py", line 18, in <module>
    from opensnitch.utils import Message, FileDialog, Icons
ImportError: cannot import name 'Icons' from 'opensnitch.utils' (/usr/lib/python3.10/site-packages/opensnitch/utils.py)
`

My old file did not import Icons

**Comment by gustavo-iniguez-goya** [comment]
ah, I should have asked you the version first. The fix is for latest sources from master branch.

I'll port it to the v1.5.0 and test it.

**Comment by gustavo-iniguez-goya** [comment]
[ruleseditor.py.txt](https://github.com/evilsocket/opensnitch/files/9168848/ruleseditor.py.txt)
[ruleseditor.ui.txt](https://github.com/evilsocket/opensnitch/files/9168850/ruleseditor.ui.txt)

ok, here're the good ones for v1.5.x version. If it works I'll add a couple more fixes and release a new v1.5.x version.

**Comment by dak8m** [comment]
Tested it and works great thanks!

I was going to upgrade to 1.6 for the fix but if you're still supporting 1.5 ill stay on the AUR version as its easier to update

**Comment by gustavo-iniguez-goya** [comment]
thank youuu @dak8m :) Yes, I'll update the v1.5.x version.

**Comment by gustavo-iniguez-goya** [comment]
v1.5.0 branch updated with this change.
