### ISSUE TITLE
One rule still enabled even with O.Snitch Firewall disabled v1.6.0-rc.2 

### ISSUE THREAD

**Issue by BobSquarePants** [evilsocket/opensnitch#710]
**Describe the bug**
![1](https://user-images.githubusercontent.com/23012674/182035595-de2ed3c3-1836-404a-bedb-15edf0f868d7.png)
I disabled the OpenSnitch firewall, but two rules remain active in the NFtables 
and one empty table.
```
table inet filter {
	chain input {
		type filter hook input priority filter; policy drop;
		udp sport 53 queue num 0 bypass
	}
}
table inet nat {
}
table inet mangle {
	chain output {
		type filter hook output priority mangle; policy drop;
		ct state related,new queue num 0 bypass
	}
```

Are those mandatory in order for OpenSnitch to work ?

 - OpenSnitch version : v1.6.0-rc.2 
 - OS: Devuan
 - Version: 5.10.0-9-amd64 # 1 SMP Debian 5.10.70-1 (2021-09-30) x86_64 GNU/Linux
 - Window Manager: XFCE4

**Comment by gustavo-iniguez-goya** [comment]
> Are those mandatory in order for OpenSnitch to work ?

yes, those are the rules to intercept outbound connections + responses to DNS queries.

But policy should be "allow", not drop. Did you change the default policy for Inbound and Outbound?

**Comment by BobSquarePants** [comment]
Thanks @gustavo-iniguez-goya 

I have already a rules for the DNS queries in my nftables config...
and I don't use at all ipv6 :imp: so I don't use `inet`

is there a way to remove
`table inet filter {
	chain input {
		type filter hook input priority filter; policy drop;
		udp sport 53 queue num 0 bypass
	}
}`

and let the user add this rules as he please ? because in my point of view this is not related to OpenSnitch, but to the system. As the purpose of OpenSnitch was to control what going out not in.

Thanks :)

**Comment by gustavo-iniguez-goya** [comment]
No at the moment. Those rules are hardcoded, and unless there's a bug that's not going to change soon. 
Anyway, it shouldn't interfere with the system or cause any problems.

system-fw.json rules though can be configured to use ip or/and ip6 tables instead of inet. But only by modifying the configuration manually, and actually, I'm not sure if we should allow users to change it from the GUI. 

closing as works-as-expected.

**Comment by BobSquarePants** [comment]
Thank you @gustavo-iniguez-goya ,

> system-fw.json rules though can be configured to use ip or/and ip6 tables instead of inet. But only by modifying the configuration manually,

That help me !, as long as I can change if needed that the most important, thx to have guide me, I will make some test :)

**Comment by BobSquarePants** [comment]
Wooo, I've tried to edit the `system-fw.json` but didn't worked I've edited line 50, but it had no effect. (of course I restarted the daemon) which line should I change in order to pass

> table inet filter {
> chain input {
> type filter hook input priority filter; policy drop;
> udp sport 53 queue num 0 bypass
> }
> }

on `ip` instead of `inet`

**Comment by gustavo-iniguez-goya** [comment]
that's expected. The inet filter and mangle tables are hardcoded for interception rules (filter-input sport 53, mangle-output queue 0), i.e., they canno be changed.

The tables defined in system-fw.json though, can be configured to create inet or ip/ip6/arp/netdev tables.

**Comment by BobSquarePants** [comment]
Hi @gustavo-iniguez-goya ,

I have the time again to try OpenSnitch...

I noticed in 1.6.0rc5 that this pushed rule by OpenSnitch remain

```shell
table inet filter {
	chain input {
		type filter hook input priority filter; policy accept; # ! O_o
		udp sport 53 queue num 0 bypass
	}
}
table inet nat {
}
```
If I'm correct this rule (that is placed at the end of the nftable ruleset)
Allow all incoming traffic ?! Am I right?

**Comment by BobSquarePants** [comment]
@gustavo-iniguez-goya 

The command for those Hardcoded should be more like

```shell
table inet filter {
	chain input {
		type filter hook input priority filter; policy drop; 
		udp sport 53 queue num 0 bypass #or accept
	}
}
```
Because `policy accept` will let the packet go trough even if it's not matching `udp sport 53 queue num 0 bypass`

see: https://wiki.nftables.org/wiki-nftables/index.php/Configuring_chains#Base_chain_policy

> **Base chain policy**
> This is the default verdict that will be applied to packets reaching the end of the chain (i.e, no more rules to be evaluated against).

> Currently there are 2 policies: accept (default) or drop.

>   The accept verdict means that the packet will keep traversing the network stack (default).
>  The drop verdict means that the packet is discarded if the packet reaches the end of the base chain.

Am i right ?
