### ISSUE TITLE
Your wiki page on Compilation does not include compiling ebpf_prog

### ISSUE THREAD

**Issue by emdee-is** [evilsocket/opensnitch#716]
Your wiki page on Compilation
https://github.com/evilsocket/opensnitch/wiki/Compilation
 does not include compiling the ebpf_prog
https://github.com/evilsocket/opensnitch/tree/master/ebpf_prog

Maybe pull the epbf page into the wiki and and pull down the Wiki page into the release when you do a release.

Maybe add a like to the AUR build recipe
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=opensnitch-ebpf-module-git

Maybe add a link to the Gentoo build recipes
https://github.com/pentoo/pentoo-overlay/tree/master/app-admin/opensnitch

Maybe open your wiki to allow general editing?

**Comment by gustavo-iniguez-goya** [comment]
Hi @emdee-is , I'm reading your comments as passive-agressive. Stop it already.

That said: https://github.com/evilsocket/opensnitch/blob/wiki/README.md

**Comment by emdee-is** [comment]
I don't know what "passive-agressive" is or even if it's good or bad - it sounds like a politically correct oxymoron to me.

That said: it's easy for me to stop trying to get opensnitch to work on Gentoo. I've spent enough time on it, so it's easy to "Stop it already".

**Comment by gustavo-iniguez-goya** [comment]
https://github.com/evilsocket/opensnitch/blob/wiki/README.md
