### ISSUE TITLE
Your README page on compiling the ebpf_prog is out of date

### ISSUE THREAD

**Issue by emdee-is** [evilsocket/opensnitch#717]
Your README page on compiling the ebpf_prog is out of date
https://github.com/evilsocket/opensnitch/tree/master/ebpf_prog

CONFIG_BPF_EVENTS is not in the 5.15.26 kernel

Maybe pull the epbf page into the wiki and and pull down the Wiki page into the release when you do a release.

**Comment by gustavo-iniguez-goya** [comment]
Thank you. It seems that it exists on that kernel version (and 5.19, etc):
https://elixir.bootlin.com/linux/v5.15.26/source/include/linux/module.h#L469
