### ISSUE TITLE
opensnitch.o is not stripped in the release

### ISSUE THREAD

**Issue by blshkv** [evilsocket/opensnitch#720]
**Describe the bug**
download opensnitch_1.5.2-1_amd64.deb, opensnitch_1.5.2-1_i386.deb and unpack it
/etc/opensnitchd/opensnitch.o size is 447K
run: llvm-strip opensnitch.o
The size will be: 1K

**To Reproduce**
always

**Expected behavior (optional)**
https://github.com/evilsocket/opensnitch/blob/master/ebpf_prog/README#L12
run
```llvm-strip -g opensnitch.o #remove debug info```

**Comment by gustavo-iniguez-goya** [comment]
Modules compilation is public and automated now, and stripped.

https://github.com/evilsocket/opensnitch/blob/master/.github/workflows/build_ebpf_modules.yml#L53
https://github.com/evilsocket/opensnitch/blob/master/utils/packaging/build_modules.sh#L56

https://github.com/evilsocket/opensnitch/actions/workflows/build_ebpf_modules.yml

Artifacts published here:
https://github.com/evilsocket/opensnitch/actions/runs/3190645548

From now on, modules published by the Action will be the ones distributed with our rpm/deb packages.
