### ISSUE TITLE
GUI: Events tab: delete button not visible at startup

### ISSUE THREAD

**Issue by uffejakobsen** [evilsocket/opensnitch#724]
GUI: The delete button ("delete all intercepted events") in the Events tab is not visible at startup.

You will have to switch to another tab and back to the "Events" tab - then it is visible.

OpenSnitch versions: 1.6.0.rc2, 1.6.0.rc1, 1.5.2, 1.5.1, 1.5.0
OS: Archlinux (latest updates applied) 
Kernel: Linux XXX 5.18.16-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 03 Aug 2022 11:25:04 +0000 x86_64 GNU/Linux
Window Manager: LXQt

**Comment by gustavo-iniguez-goya** [comment]
Thank you and sorry for the delay fixing this issue O:)
