### ISSUE TITLE
cannot do ping command while opensnitch is active

### ISSUE THREAD

**Issue by in1t3r** [evilsocket/opensnitch#74]
cannot do ping command while opensnitch is active, your version in @evilsocket repo. In mine it works fine but my lack improvement of non blocking connections.
ways to reproduce start opensnitch run it open some apps allow some rules and then try pinging google.com for example or even IP not a fqdn.

**Comment by adisbladis** [comment]
This is an issue with us not handling ICMP at all.
ICMP breaks some assumptions currently done in opensnitch (like not having sport and dport).

Here can be a good starting point for anyone interested in fixing this: https://github.com/evilsocket/opensnitch/blob/master/opensnitch/connection.py#L38

**Comment by boozedog** [comment]
I'm seeing this problem too, running 1.4.0~rc4-1 amd64 . I cannot ping any host (including localhost) when OpenSnitch is active ... and nothing appears in the event tab to indicate that something is being blocked.

**Comment by gustavo-iniguez-goya** [comment]
Please, install latest v1.4.0: https://github.com/evilsocket/opensnitch/releases/tag/v1.4.0

**Comment by boozedog** [comment]
> Please, install latest v1.4.0: https://github.com/evilsocket/opensnitch/releases/tag/v1.4.0

That worked! Thank you.

**Comment by alexfriman** [comment]
Same problem on v1.5.8
Linux 6.1.0-25-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.106-3 (2024-08-26) x86_64 GNU/Linux
