### ISSUE TITLE
Open Snitch v1.52 won't open in Linux Mint 21.0

### ISSUE THREAD

**Issue by bazio** [evilsocket/opensnitch#741]
I installed OPEN SNITCH v1.52 on LINUX MINT 21 (Vanessa) CINNAMON edition. NEMO window manager. Kernel 5.15.0-47.

I installed the two Open Snitch .deb files:

opensnitch_1.5.2-1_amd64.deb
python3-opensnitch-ui_1.5.2-1_all.deb

The .deb files installed fine via gui install but Open Snitch will not open after installation nor when Linux Mint 21 Cinnamon launches. Open Snitch appears in the Startup Applications list but it does not initiate.

There is an icon in the panel everytime LM starts up with a red circle with diagonal slash.

When you try to shut down LM, a window opens that says "A program is still running: UNKNOWN Not Responding". It gives you a selection to shut down anyway; you click shut-down-anyway and it takes 25 seconds for LM to shut down.

I then uninstalled OpenSnitch and followed your directions for installing via terminal. I installed both files via terminal and got error responses regarding python3-opensnitch as follows:

dpkg: error processing package python3-opensnitch-ui (--install):
 dependency problems - leaving unconfigured
Processing triggers for gnome-menus (3.36.0-1ubuntu3) ...
Processing triggers for desktop-file-utils (0.26+mint1+vanessa) ...
Processing triggers for mailcap (3.70+nmu1ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Errors were encountered while processing:
 python3-opensnitch-ui

That is the extent of what happens. Open Snitch does not open at all. There are no other error messages I can give you. Any help you can give is much appreciated.

Thanks very much
BAZIO

**Comment by gustavo-iniguez-goya** [comment]
Hi @bazio ,

> Open Snitch appears in the Startup Applications list but it does not initiate.

This problem is due to this bug: #647 The workaround is: `$ pip3 install --ignore-installed grpcio`

> dpkg: error processing package python3-opensnitch-ui (--install):

Regarding this problem, could you post the lines above that one? It should display the dependencies which is complaining about.

Anyway, the best I think is to start over:

`$ sudo apt remove --purge python3-opensnitch-ui`

`$ sudo apt install ./path-to-the-ui.deb`

`$ pip3 install --ignore-installed grpcio`

**Comment by gustavo-iniguez-goya** [comment]
Closing for now. Reopen it if you have the requested information.

**Comment by bazio** [comment]
Hello Gustavo Iñguez Goia:

Thank you very much for your response. It did not work. I then did a search
and found this solution at this URL on the linux mint forums:

https://forums.linuxmint.com/viewtopic.php?t=379567

At the bottom of the page they give these entries that they found on your
github page and this fixed my problem:

Found the solution on github:

First step was to go to github and download the 1.5.2-1 packages and
install them.

Fix provided by gustavo-iniguez-goya:

sudo apt install python3-pip python3-pyasn
pip3 install --user qt-material
pip3 install --user --ignore-installed grpcio

Correct icon now appears and I can click on it and see the
allowed/disallowed entries.

Mike

update with latest from gustavo

Thank you very much for this great program.

BAZIO

**Comment by snden** [comment]
After upgrading to Linux Mint 21.1 (Vera) I can't get Opensnitch to work. I tried opensnitch_1.5.2-1_amd64.deb python3-opensnitch-ui_1.5.2-1_all.deb and also opensnitch_1.5.1-1_amd64.deb python3-opensnitch-ui_1.5.1-1_all.PIP.deb . They install without problems, but cannot be run. In the terminal:
`$ opensnitch-ui
Traceback (most recent call last):
  File "/usr/bin/opensnitch-ui", line 23, in <module>
    from opensnitch.service import UIService
  File "/usr/lib/python3/dist-packages/opensnitch/service.py", line 13, in <module>
    from opensnitch import ui_pb2
  File "/usr/lib/python3/dist-packages/opensnitch/ui_pb2.py", line 32, in <module>
    _descriptor.EnumValueDescriptor(
  File "/usr/local/lib/python3.10/dist-packages/google/protobuf/descriptor.py", line 796, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_bin_opensnitch-ui.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/opensnitch-ui", line 23, in <module>
    from opensnitch.service import UIService
  File "/usr/lib/python3/dist-packages/opensnitch/service.py", line 13, in <module>
    from opensnitch import ui_pb2
  File "/usr/lib/python3/dist-packages/opensnitch/ui_pb2.py", line 32, in <module>
    _descriptor.EnumValueDescriptor(
  File "/usr/local/lib/python3.10/dist-packages/google/protobuf/descriptor.py", line 796, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
`
I tried to solve the problem according to the instructions:
https://github.com/evilsocket/opensnitch/issues/741
but that didn't help either.
I am asking for advice on how to get the firewall working. Thank you.

**Comment by gustavo-iniguez-goya** [comment]
hi @snden, could you post grpcio and protobuf versions?

`$ dpkg -l | grep python3-grpcio` , `" dpkg -l | grep python3-protobuf`
`$ pip3 list installed | grep -E "(protobuf|grpcio)"`

**Comment by snden** [comment]
$ pip3 list installed | grep -E "(protobuf|grpcio)"
grpcio                1.54.0
grpcio-tools          1.54.0
protobuf              4.22.3

$ dpkg -l | grep python3-protobuf
ii  python3-protobuf                              3.12.4-1ubuntu7.22.04.1                    amd64        Python 3 bindings for protocol buffers

$ dpkg -l | grep python3-grpcio
ii  python3-grpcio                                1.30.2-3build6                             amd64        GRPC system (Python 3)

**Comment by gustavo-iniguez-goya** [comment]
thank you @snden , please, uninstall protobuf pip package using pip3 and launch the GUI again: `$ pip3 uninstall protobuf`

LinuxMint 21.1 suffers of the grpcio problem of Ubuntu 22.04 #647 . AFAICT , using python3-protobuf from the repos (3.12.4) + grpcio from pip3 works on my system.
