### ISSUE TITLE
[Feature Request] No option able to set, ask for every connection on IP/URL address for specific application possible...

### ISSUE THREAD

**Issue by Nonie689** [evilsocket/opensnitch#748]
I would like a selection box that every connection from this application will raise a request to allow or not on this ip/url...

**Comment by gustavo-iniguez-goya** [comment]
:+1: This feature depends on another feature: send messages from the daemon to the server (GUI). Once it's done, then we'll add an option to the Rules editor, to allow trigger alerts when a rule matches  and react on it (send email, show message dialog, etc).

**Comment by gustavo-iniguez-goya** [comment]
Thinking about this issue again, there's a way of accomplish this (kind of):

- Create a rule to allow application X connect to a limited list of domains/IPs/ports, etc.

If application X tries to connect to an IP not explicitly allowed, you'll be prompted to allow or deny it.

https://github.com/evilsocket/opensnitch/wiki/block-lists#limiting-to-what-domains-an-application-can-connect-to
