### ISSUE TITLE
[Feature Request] I would like that I can choose a default time when I click deny and I [diffrerent] default time if I click accept...

### ISSUE THREAD

**Issue by Nonie689** [evilsocket/opensnitch#749]
Currently the selection is on both the same...!

**Comment by gustavo-iniguez-goya** [comment]
Yes, sorry for that. It's what it is. We offer already a lot of options. 

You can increase the default timeout (Preferences), or if you change any option of the pop-up the countdown is stopped, so you'll have more time to review the information of the pop-up.

Thank you!
