### ISSUE TITLE
[Feature Request] ui detect deamon whether install

### ISSUE THREAD

**Issue by BackMountainDevil** [evilsocket/opensnitch#754]
### Summary:

Ask for error notify about not having install opensnitch deamon when run python3-opensnitch-ui.

I konw opensnitch in forum of endeavouros. So I try install this via yay. And because the Great Wall firewall it got fail.. So I download deb from releases. I download python3-opensnitch-ui_1.5.2-1_all.deb  and install it. I start it and find it in the menubar. But it got blink window. Then I read wiki about install . Then I find I forget to download and install  opensnitch_1.5.2-1_amd64.deb . Then I did that and thing work out.

If you guy are busy, let me know and I will try to code&pr

**Comment by gustavo-iniguez-goya** [comment]
Hi @BackMountainDevil ,

I'm a bit confused. What distro are you using, EndeavourOS? or a deb based distro?

If you install the AUR package 
https://aur.archlinux.org/packages/opensnitch , it'll install both, the GUI + the daemon. 

On the other hand, the GUI can be used to manage remote nodes/daemons, so it doesn't need a daemon running on the same machine.

**Comment by BackMountainDevil** [comment]
it is EndeavourOS. I tried install from aur and failed because of "go: github.com/golang/protobuf/protoc-gen-go@latest: module github.com/golang/protobuf/protoc-gen-go: Get "https://proxy.golang.org/github.com/golang/protobuf/protoc-gen-go/@v/list": dial tcp 172.217.163.49:443: i/o timeout". So I turn to releases for deb.

quite cool design idea. It seems that is it unnecessary
