### ISSUE TITLE
[Feature Request] Add multicast label like the already present LAN label for multicast IP range

### ISSUE THREAD

**Issue by NRGLine4Sec** [evilsocket/opensnitch#755]
It could be convenient to add the `IPv4 multicast` label like the already present `LAN` label to the filter capability.
You can get the IPv4 multicast range here : [Multicast address - Wikipedia](https://en.wikipedia.org/wiki/Multicast_address#IPv4)

**Comment by gustavo-iniguez-goya** [comment]
Added 224.*/239.* .

I've just realized that I'll have to rename MULTICAST to MULTICAST IPV4. And maybe add ipv6
