### ISSUE TITLE
doubts in translation

### ISSUE THREAD

**Issue by gallegonovato** [evilsocket/opensnitch#759]
Good afternoon @evilsocket 

First of all thank you for your time and help.

I happen to be trying to help on Weblate with translation.

And I see 5m several times.

This for example can be 5 minutes or 5 meters. But I find it strange that it comes out twice and I hesitate between putting 5m . Or put in one minutes (of time) and in the other meters.

I don't know if I am right or it all refers to time. Or should I put it as it is.

A hug and thanks for your help and time.

**Comment by gustavo-iniguez-goya** [comment]
hey @gallegonovato ,

5m -> 5minutes

Usually it appears close to a label description of the field, like "Duration", along with other time units like 30s, 1h:

![image](https://user-images.githubusercontent.com/2742953/197001052-79105eab-e151-41e7-bfd0-2213eba231cc.png)

**Comment by gallegonovato** [comment]
Good afternoon:

Thank you for your help and response.

I then looked at entries like 192.168.1.0/24. Here I don't know if you want me to specify loopback addresses or loopback network device.

Even /dev/stdout could be translated standard output (stdout, from Standard Output) or /dev/standard output.

Sorry for the inconvenience but I like to look for what the developer thinks and then translate.

Best regards

**Comment by gustavo-iniguez-goya** [comment]
I think this issue has been answered. But if you have more doubts keep asking please :+1:

**Comment by gallegonovato** [comment]
Good afternoon @gustavo-iniguez-goya

I was looking and jotting down to make some changes in the Spanish translation. Since I don't know who translated them but they are wrong.

Then I wanted to make a proposal on https://hosted.weblate.org/translate/opensnitch/gui/es/?checksum=3ec98b374f97b5d3&sort_by=-priority,position

This one I think should also be marked not to modify. I don't know what you think.

A hug and thanks for your attention and time :)

**Comment by gallegonovato** [comment]
Good afternoon @gustavo-iniguez-goya

I have already checked the translation and now it is better. I still have to modify a few things.

I don't know what you think about the entry I told you about in the previous link.

I will try to check it also in other languages.

Thanks for your time
