### ISSUE TITLE
Wiki update for Ubuntu 22.04 build issues

### ISSUE THREAD

**Issue by mwigginsdev** [evilsocket/opensnitch#773]
On the [compilation](https://github.com/evilsocket/opensnitch/wiki/Compilation) page, can a second be added for Ubuntu 22.04 notes similar to the fedora section?

I ran into a similar issue to the fedora problem on ubuntu 22.04, however symlinking did not fix it for me.

Error when running `make` from root directory:
```
lrelease: could not find a Qt installation of ''
```

The following resolved my issue:
```
#set env var for QT version
export QT_SELECT=qt5

#install qt tools which includes lrelease
sudo apt install qttools5-dev
```

I recommend either adding the above as an Ubuntu 22.04 note or adding qttools5-dev as a dependency in the "Installation from sources" section. The listed dependencies do include `qttools5-dev-tools` and `qtbase5-dev-tools`, but those packages do not appear to include lrelease when installed from the Ubuntu 22.04 multiverse repositories.

**Comment by gustavo-iniguez-goya** [comment]
Added. Thank you @mwigginsdev !
