### ISSUE TITLE
OpenSUSE: RPM Signature Verification Failed

### ISSUE THREAD

**Issue by stunningoverarch1205** [evilsocket/opensnitch#776]
Hello,
First of all, a huge shout out to you for your amazing work. Really appreciate it.

**Description:**
While trying to install the RPM package, YAST complains that the package is broken and that the integrity check has failed. Examining the error, shows that the package header hasn't been signed. Manually verifying the package using the provided checksums shows no errors, indicating that the package is in fact intact, and just hasn't been signed. Note: It is possible to skip this, by using the "ignore" option (which is how, I have currently installed it), however this bypasses the additional security check in place. Since Opensnitch is a software, dedicated to privacy and security, it would better to sign the packages instead. 

**System Information:**
 - OpenSnitch version: 1.5.2
 - OS: OpenSUSE Tumbleweed
 - Window Manager: KDE Plasma 5.26.4
 - Kernel version: 6.0.12-1-default.

**To Reproduce**
Try installing the RPM package on OpenSUSE Tumbleweed using Zypper or YAST.

**Steps to reproduce the behavior:**
    (When done through YAST);
1. Open the package using YAST
2. Wait for the dependencies to load
3. Click "Accept"
4. The error mentioned below shows up, after a few seconds.

**Error Logs:** 
```
 Error: INVALID:opensnitch-1.5.2-1.x86_64 Signature verification failed [6-File is unsigned]
    Header SHA256 digest: OK
    Header SHA1 digest: OK
    Payload SHA256 digest: OK
    MD5 digest: OK
    Package header is not signed!
```

**Expected Behavior:**
YAST installing the package normally.

**Additional Context:**

- This happens to both, the main and the GUI packages.

- Running `rpm -qpi (package) | grep "Signature"` on each of the package in question, gives the same following output:
  `Signature   : (none)`

  This again indicates about the missing signature, like mentioned above.

- I even tried adding the provided GPG public key to my RPM key ring, but the same error occurs.

**Comment by gustavo-iniguez-goya** [comment]
Hi @stunningoverarch1205 ,

First of all, thank you for verifying the checksums. I thought no one checked them out ;)

You're right, rpm packages are not signed (debs are). The thing is that I had in the past some issues packaging signed rpms for older distros (centos/rhel 6), and compatibility issues with rhel 8.x (I don't remember the exact problem).

But I guess that I can sign at least the rpms for newer distros. I'll post a comment when it's done.

**Comment by gustavo-iniguez-goya** [comment]
rpm packages for v1.5.2 and v1.6.0rc3 signed with my gpg key.

Import my key and try installing again, it should not complain now:

rpm --import https://github.com/evilsocket/opensnitch/releases/download/v1.6.0-rc.3/gustavo_iniguez_goia.asc
