### ISSUE TITLE
Pop-up timeout limited at 99 seconds

### ISSUE THREAD

**Issue by Danny3** [evilsocket/opensnitch#783]
Hello!

**Describe the bug**
The default timeout of pop-ups is limited at 99 seconds

Include the following information:
 - OpenSnitch version: v1.6.0-rc.3
 - OS: Debian
 - Version: 12 (Bookworm)
 - Window Manager: KDE Plasma 5.26.4 (on Wayland)
 - Kernel version: 6.0.0-6-amd64 1 SMP PREEMPT_DYNAMIC Debian 6.0.12-1 (2022-12-09) x86_64 GNU/Linux

1. Go to firewall's UI
2. Click on the Settings icon, the one that looks like Plasma's "System Settings"
3. When the settings window opens click on the + (plus sign) on the "Default timeout" line until it reaches 99.
4. See how continuing to click the + sign doesn't do anything anymore as it's limited to 99 seconds.

**Expected behavior (optional)**
I expected to be be either unlimited or very high.
First time I noticed this was when I wanted to put 120 seconds, so 2 minutes, to not have to worry about not being able to read all the details off the connections.

I think I would want multiple things to be different here:

1.  If unlimited is not possible, like putting a 0 (zero), at least make the maximum possible half or an hour.
Having a meal, going to bathroom or being in a  game can easily make you miss this pop-ups.

2. I see that clicking on the - sign many times or putting a 0 is actually possible, but it's not clear what a 0 timeout means
Will the pop-up be displayed and very quickly closed with a "deny" action chosen or it will not be shown at all?
Or it means that the timeout is now disabled and the pop-up stays there and waits until you to choose allow, deny or close it, meaning that it will auto-choose the default action?
There's no tooltip here explaining what is the minimum, maximum and what a 0 value will do, so I would add these kind of tooltips.
3. Holding the + or - signs clicked doesn't  raise or decrease the numbers faster like in other programs and going from 1 to 99 fo example takes a lot of time and clicks.
4. Besides increasing the countdown limit or make it unlimited, I wish that alternatively there was a way that by clicking anywhere in the pop-up window, except the buttons, will just stop to countdown and I can read everything that I want to read or take a screenshot without fearing that I have to hurry that it will close with the wrong action.
Same for the case of exiting a game and seeing the pop-up window and having 1 or 2 seconds left to read and answer.
It would be great that if as soon as the window gets focus for being out of focus because of the game, the countdown is stopped or restarted, if such a thing is possible.

**Additional context**
BTW, the "Settings" icon and the last one (the shield) in the main UI window and, don't have any tooltips explaining what they are for and what will happen i you click on them.
It would be nice to have tooltips on them too.

And the "Action" dropdown in the settings, also doesn't have tooltips.
For example, I want to know what's the difference between "deny" and "reject" actions because they sound to me that they do the same thing, but there must be a difference in behavior.
It would be nice to have tooltips here too.
And one more thing fo the "Default timeout or any field that has a numeric value that needs to be set, it would be great to know also what units are expected, seconds, minutes or something else

Thank you!

**Comment by gustavo-iniguez-goya** [comment]
> First time I noticed this was when I wanted to put 120 seconds, so 2 minutes, to not have to worry about not being able to read all the details off the connections.

The timeout is hardcoded on the daemon to 120s. The default timeout on Linux is more or less the same:
```
~$ time telnet 1.1.1.1
Trying 1.1.1.1...
telnet: Unable to connect to remote host: timeout

real	2m9,858s
user	0m0,000s
sys	0m0,005s
```

On the other hand, while we're asking to deny/allow a connection, every other connection is denied or allowed based on the Default Action configured. So it has no sense to show a pop-up for 30 minutes.

What you can do is to force opensnitch to ask you again for unanswered connections, by changing Default Duration (of the rule) to 30s for example (and Default Timeout to 25s for example). Then if you miss a connection the following will occur:
 - The pop-up will be displayed for Default Timeout seconds (30s for example).
 - When a pop-up timeouts it'll apply the Default Action configured on the connection.
 - The rule will be created with the Default Duration. If you set it to 30s, when the rule timeouts and the app retries the connection, you'll be prompted again to allow or deny it.
 - Also whenever a pop-up is not answered, a system notification will be displayed, and added to the systray, as well as changing the systray icon from ![image](https://user-images.githubusercontent.com/2742953/209339664-bae1641e-4c96-4c1f-8e85-defc404745cb.png)  to ![image](https://user-images.githubusercontent.com/2742953/209339727-200c2579-6ec2-42b2-8800-715f0d318055.png) :

![image](https://user-images.githubusercontent.com/2742953/209338414-6b45ee84-10ad-469f-9b98-0a034e3fd036.png)

![image](https://user-images.githubusercontent.com/2742953/209339122-af310de5-a9e6-4f44-905e-cc30066922db.png)

So you have plenty of options to know that something happened and review it.

**Comment by gustavo-iniguez-goya** [comment]
> I see that clicking on the - sign many times or putting a 0 is actually possible, but it's not clear what a 0 timeout means
Will the pop-up be displayed and very quickly closed with a "deny" action chosen or it will not be shown at all?

0 disables the pop-ups and applies the Default Action on new connections.

> I wish that alternatively there was a way that by clicking anywhere in the pop-up window, except the buttons, will just stop to countdown 

This was requested long time ago, but I don't remember why I limited it to the buttons. I'll review it.

**Comment by gustavo-iniguez-goya** [comment]
Closing as I think that we have many options to warn users about not answered pop-ups. 

:heavy_check_mark:  Added option to disable countdown by clicking on the pop-up window.
:heavy_check_mark: I'll update the tooltip to describe that setting the timeout to 0 disables the pop-ups, or better, if the timeout is 0, mark the checek [x] Disable pop-ups

**Comment by trytomakeyouprivate** [comment]
setting it to zero makes it immediately choose the default option.

Just suggesting setting default to 30s means you have to click "always" every time you really want to set something. This means at least 2 clicks more. If its for applications thats okay, but not for individual connections.

Just leave this issue open, it really is a big deal.

Other requests like tooltips or even accelerated number incrementing is very optional.

Having the systray icon change is a real solution and possibly working workaround.

**Comment by beedell-roke** [comment]
Regarding [`issues/994#issuecomment-1646847531`](https://github.com/evilsocket/opensnitch/issues/994#issuecomment-1646847531), if the kernel is hard-coding this timeout, perhaps a report at kernel Bugzilla to change this is appropriate. The amount of duplicate issues, and interest, appear to demonstrate that this is desired.

**Comment by Danny3** [comment]
> Regarding [`issues/994#issuecomment-1646847531`](https://github.com/evilsocket/opensnitch/issues/994#issuecomment-1646847531), if the kernel is hard-coding this timeout, perhaps a report at kernel Bugzilla to change this is appropriate. The amount of duplicate issues, and interest, appear to demonstrate that this is desired.

Hardcoding stuff is bad in general in my opinion and I would say it is in this case is too.
Changing it through a variable passed to GRUB would be nice, but I think it would be better if we could change it through sysctl, for which at least on Debian we can create a file like"
```
/etc/sysctl.d/my-custom-options.conf
```
With a content like:
```
# Optimize Virtual memory (VM):
vm.swappiness=10
vm.dirty_background_ratio = 5
vm.dirty_ratio = 10
# Enable MTU probing
net.ipv4.tcp_mtu_probing = 1
# Enable the NT synchronization primitive driver which help a lot Windows games being run through WINE compatibility layer.
ntsync
```
And whatever variable name=value would be required for this one.
In case this program cannot change the sysctl options after we configure them in its interface.
Hopefully somebody creates such a bug report and a kernel developer decides to help us.
