### ISSUE TITLE
Settings window has some problems when maximized

### ISSUE THREAD

**Issue by Danny3** [evilsocket/opensnitch#784]
Hello!

**Describe the bug**
Settings window has some problems when maximized, possibly on Wayland only.

Include the following information:
 - OpenSnitch version: v1.6.0-rc.3
 - OS: Debian
 - Version: 12 (Bookworm)
 - Window Manager: KDE Plasma 5.26.4 (on Wayland)
 - Kernel version: 6.0.0-6-amd64 1 SMP PREEMPT_DYNAMIC Debian 6.0.12-1 (2022-12-09) x86_64 GNU/Linux

1. Go to firewall's UI
2. Click on the Settings icon, the one that looks like Plasma's "System Settings"
3. When the settings window opens click on the maximize icons on that window's title bar
4. See how clicking in the Pop-ups page on the drop-down show their options in the middle of the screen instead of directly below that drop-down

**Expected behavior (optional)**
I expected that the drop-downs' values show up directly underneath them like when the settings window is small.

**Additional context**
This problem is unfortunately not easy to reproduce as it not happening all the time and it's not yet clear why.
Sometimes even with the settings  window as maximized the show correctly.
But when they don't the only drop-down  that is the exception to all the other that are displaying in the wrong position is the first one on the "Nodes" page.
Maybe this one has something that makes it display correctly in all the cases.

So there are 2 cases that need to be tested:

1. Open the settings window in the normal windowed mode and them maximize it to full screen and check the drop-downs.
2. Open the settings window in the already maximized mode and check the drop-downs.

To be able to do the second case you need that after the first case you just close the settings window without restoring it first so it will remember its maximized state and it will open as maximized next time.

But the second case, which was easy for me as I prefer to open most of the windows as maximized, let to discovery to another problem

If you get bored of this maximized mode of the settings and want to revert t to the normal windowed mode by clicking on the restore button in the title bar, you can't as the window remains maximized.

I mean, maybe it works, but the restored version of the window has the width and height the same as the maximized one so it's not obvious that it worked or not.

I had to drag it from the title bar down and then manually resize the edges to make it smaller, which takes some time.

BTW, another problem, with the settings window smaller then fullscreen clicking to close the main UI window leaves the settings window still open.

I don't know if this is really a problem, if it's was intended that way, maybe for the user to not lose modified settings.

I just found it a bit weird.

Maybe it would be better if the user closes the main UI window to hide also the settings window an if he clicks back on the system tray icon on the firewall to show both again with the settings one in foreground, if that's possible.

LE:

Another place where the drop-down values are misplaced is the one in the bottom-right part or the window showing "50" by default. I don't know what this is for  and there's no tooltip while hovering over it.
On another test, this seems to be happening on Wayland only.

Thank you!

**Comment by gustavo-iniguez-goya** [comment]
hey @Danny3 , can you post a screenshot showing the problem? 

> Open the settings window in the normal windowed mode and them maximize it to full screen and check the drop-downs.
> Open the settings window in the already maximized mode and check the drop-downs.

I can't reproduce this issue on Plasma 5.26.3, Qt version 5.15.7. It works as expected:

![image](https://user-images.githubusercontent.com/2742953/210149441-60e557f9-2232-4f05-bc0c-6ef9e94b8c24.png)



Anyway, we don't control how the drop-downs are positioned on screen.

**Comment by Danny3** [comment]
Hi @gustavo-iniguez-goya!

>hey @Danny3 , can you post a screenshot showing the problem?

I wish.
Now I cannot reproduce it too! 😂

And I have tested all the drop-down, including the one in the bottom-right corner that has the number 50 as default and it opens from bottom up.

I've upgraded in the meantime to on Plasma 5.26.5, Qt version 5.15.7.

I guess it was something in one of these two that fixed it.

A bit strange since this was the only Qt programs where I saw such a thing.

Anyway, at least, from your comment I learned that you can attach printscreens to comments here and I will try to add that next time I see some UI issue.

Thanks for your time!
