### ISSUE TITLE
[Bug] UI Not Starting

### ISSUE THREAD

**Issue by zero77** [evilsocket/opensnitch#790]
Please, check the FAQ and Known Problems pages before creating the bug report:
https://github.com/evilsocket/opensnitch/wiki/FAQs
https://github.com/evilsocket/opensnitch/wiki/Known-problems

**Describe the bug**
Open the ui either with sudo or without and it fails to starts and gives the below error.

Include the following information:
 - OpenSnitch version. 1.6.0-rc.3-1
 - OS: Debian
 - Version Sid
 - Window Manager: i3wm
 - Kernel version: 6.0.0-6-amd64

**To Reproduce**

**Post error logs:** 
`using IPASN DB: /usr/lib/python3/dist-packages/data/ipasn_20140513_v12.dat.gz
new node connected, listening for client responses... /local
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/opensnitch/dialogs/firewall.py", line 98, in _cb_nodes_updated
    self._check_fw_status()
  File "/usr/lib/python3/dist-packages/opensnitch/dialogs/firewall.py", line 207, in _check_fw_status
    if j['Firewall'] == "iptables":
       ~^^^^^^^^^^^^
KeyError: 'Firewall'
Aborted`

If the daemon doesn't start:
N/A

If the deb or rpm packages fail to install:
N/A

**Expected behavior (optional)**

**Screenshots**

**Additional context**

**Comment by gustavo-iniguez-goya** [comment]
Hi @zero77 !

Thank you for reporting this issue. There's an obvious fix, but I'll try to reproduce this behaviour. It looks like a race condition when a node connects to the GUI.

By the way, you don't need to launch the GUI with sudo.

**Comment by gustavo-iniguez-goya** [comment]
I've been unable to reproduce this crash. I've applied a workaround not to crash when this problem occurs, but it'd be good to know the root of the problem.

If you can still reproduce this problem, set log level to debug in /etc/opensnitchd/default-config.json LogLevel -> 0, and post the log. Maybe there're errors connecting to the GUI.

**Comment by zero77** [comment]
Thanks @gustavo-iniguez-goya 

If i stop the opensnitch service the ui opens with out an error.
Are these the logs you are looking for:
https://pastebin.com/raw/TzLNjv4H

**Comment by gustavo-iniguez-goya** [comment]
woah, that's much worse than what I expected. Did you upgrade from a previous version? v1.5.x or 1.4.x maybe?

Could you also post the log file /var/log/opensnitchd.log?

This log: 
> new node connected, listening for client responses... >> /local <<

suggests me that you have and old grpcio version installed, which doesn't report the address of the nodes correctly.
It should be: `new node connected, listening for client responses... /tmp/osui.sock`

```bash 
$ pip3 list installed | grep -E "(grpcio|protobuf)"
$ dpkg -l | grep  -E "python3-(grpcio|protobuf)"
```

What's the value of Address in your /etc/opensnitchd/default-config.json ?

**Comment by zero77** [comment]
> woah, that's much worse than what I expected. Did you upgrade from a previous version? v1.5.x or 1.4.x maybe?

Yes i upgrade to each new version including the unstable ones.

> Could you also post the log file /var/log/opensnitchd.log?

Ok i will upload a copy of /var/log/opensnitchd.log

> This log:
> 
> > new node connected, listening for client responses... >> /local <<
> 
> suggests me that you have and old grpcio version installed, which doesn't report the address of the nodes correctly. It should be: `new node connected, listening for client responses... /tmp/osui.sock`



> ```shell
> $ pip3 list installed | grep -E "(grpcio|protobuf)"
> $ dpkg -l | grep  -E "python3-(grpcio|protobuf)"
> ```

I have been using an older version of protobuf==3.15.8 as this was suggested as a workaround for another error.

grpcio                       1.51.1
protobuf                     3.15.8

python3-grpcio         1.51.1-3      amd64
python3-protobuf     3.21.12-1+b1     amd64 

> What's the value of Address in your /etc/opensnitchd/default-config.json ?

```
    "Server": {
        "Address": "unix:///tmp/osui.sock",
        "LogFile": "/var/log/opensnitchd.log"
    },
    "DefaultAction": "deny",
    "DefaultDuration": "once",
    "InterceptUnknown": false,
    "ProcMonitorMethod": "ebpf",
    "LogLevel": 0
```

**Comment by gustavo-iniguez-goya** [comment]
reproduced! Installing grpcio version 1.51.1 first, and then protobuf==3.15.8 causes this situation.

There're several warnings stating that grpcio-tools 1.49. requires protobuf >= 4.21.6. But we're right now incompatible with that protobuf version, the GUI crashes.

So, you can uninstall grpcio and protobuf from your regular user (`user ~$ pip3 uninstall grpcio grpcio-tools protobuf`) and use Debian Sid packages (python3-grpcio 1.51.1, python3-protobuf 3.21.12-1+b1)

**Comment by zero77** [comment]
I Am still testing but this error may be down to some missing lines in the config file.

**Comment by zero77** [comment]
> reproduced! Installing grpcio version 1.51.1 first, and then protobuf==3.15.8 causes this situation.
> 
> There're several warnings stating that grpcio-tools 1.49. requires protobuf >= 4.21.6. But we're right now incompatible with that protobuf version, the GUI crashes.
> 
> So, you can uninstall grpcio and protobuf from your regular user (`user ~$ pip3 uninstall grpcio grpcio-tools protobuf`) and use Debian Sid packages (python3-grpcio 1.51.1, python3-protobuf 3.21.12-1+b1)

Thanks this has worked
