### ISSUE TITLE
Invalid signatures on debs

### ISSUE THREAD

**Issue by KOLANICH** [evilsocket/opensnitch#797]
```
gpg: Note: signatures using the SHA1 algorithm are rejected
gpg: Can't check signature: Invalid digest algorithm
```

**Comment by gustavo-iniguez-goya** [comment]
Hi @KOLANICH ,

Would you mind to share the command you used to verify it? What did you verify, the deb packages or the .dsc files?

**Comment by KOLANICH** [comment]
```
debsig-verify -v -d ./opensnitch_1.5.2-1_amd64.deb
```

(I have set up tne policy as described in https://blog.packagecloud.io/how-to-gpg-sign-and-verify-deb-packages-and-apt-repositories/)

```
dpkg-sig -v --verify ./opensnitch_1.5.2-1_amd64.deb
```

also fails, without saying what exactly is wrong.

**Comment by gustavo-iniguez-goya** [comment]
I can't either verify it with that command. That blog post is a bit outdated by the way. http://www.debian.org have to changed to https://www.debian.org

Anyway, you can verify the .dsc file (zipped in the file packages-builds-signatures.txt: `gpg --verify x86_64/deb/opensnitch_1.5.2-1.dsc`
As well as the readme.txt with the checksums of each package signatures: `gpg --verify readme.txt.asc`

**Comment by KOLANICH** [comment]
@gustavo-iniguez-goya, it says SHA1 is broken (it was broken long ago). Could you setup your gpg to use SHA256 instead?

**Comment by fr4nzap** [comment]
The signed `readme.txt.asc` states that hashes are SHA512 but the provided ones are not. I had to use `sha1sum`

Moreover they're not easy to use with `--check` and the filename `readme.txt` should probably be changed to `manifest` or something more descriptive. Thanks!
