### ISSUE TITLE
Cannot press escape | Make that dialog not steal the focus (!)

### ISSUE THREAD

**Issue by benchonaut** [evilsocket/opensnitch#804]
**Describe the bug**

Popup dialog  is too damn annoying ,
 * makes everything unusable (stealing focus)
 * does not accept shortkeys
 * steals focus when entering text
 ( AND NO ; I WOULD NOT PERMIT A THIRD PARTY WANNABE_GUI TO FOCUS ON TOP ON ITS OWN BEHALF)
 
maybe just add a button and send a desktop notification
( but the program is also bad at desktop notifications since they don't properly disapper and stack up,
sometimes only resolvable with xdotool or manual clicking 300 times .. congrats , you won the inusability award  )

Include the following information:
GOES THROUGH ALL VERSION , ANNOYING ANNOYING ANNOYING
THE WINDOW JUST STEALS FOCUS WITHOUT PERMISSION TO DO SO 
NO HOTKEYS ARE WORKING , NO ESCAPE IS WORKING

**Expected behavior (optional)**

i expect computers to break physically because ppl are completely pissed of after 2 minutes

many will just uninstall the proggy thinking "haha ,funny guys, but screwed up " ( and not issue tickets)

thingy is tooo unusable when it steals focus on every new connection 
( 4+ popups per minute )

**Screenshots**
no.. adjust your template  or make some nice photos of yourself 

**Additional context**
didnt you try this before ?

**Comment by gustavo-iniguez-goya** [comment]
Hi @benchonaut ,

This is the intended behaviour of the pop-ups by design. You can disable the pop-ups in the Preferences dialog :+1:

**Comment by benchonaut** [comment]
( i do not want to disable them ,  i would prefer having a desktop notification with a button "activate" and some basic info like
 
 ````
 review connection from {PROG}  to {target ip/port/rdns}
 [Activate]
 ````
to show the popup 
web interface would also be proper  and to disturbing so hard  )
 
 regards

**Comment by phil294** [comment]
It's nice that there's an option to have the popup be a notification. However, personally I'd like to keep it as a popup with all of its configurable options, but it *also* not become the focused window. It's very good that the focus resides on the expand button by default. This reduces the chance of accidentally triggering one of the buttons when it opens, but I've had it happen multiple times by now that I was in VSCode, furiously typing stuff including <kbd>Tab</kbd>, submitting something and having to revert it in the UI/rules tab.

On X11 at least, a window can be always on top and at the same time be inactive, which I'd like to be the default way. It can still be interacted by mouse and for keyboard, I'd need to Alt+Tab once (assuming a stacking window manager). Can't find a option to configure that, however.

I'm on XFCE where there is a `[x] Activate focus stealing prevention` option in Window Manager Tweaks > Focus, however setting this doesn't work, for some reason :( I guess Opensnitch has custom logic that, on render, puts itself into the foreground? iirc this is the only way the current logic could exist, unless xfce broke this setting recently. If so, this should be changed. If not, I guess I'm describing a new feature that would be nice to have.

Opensnitch is amazing!

**Comment by gustavo-iniguez-goya** [comment]
We use `activateWindow()`, which steals the focus on X11 (at least on Cinnamon). On Wayland/Gnome, removing this function still steals the focus.

https://doc.qt.io/qtforpython-6/PySide6/QtWidgets/QWidget.html#PySide6.QtWidgets.QWidget.activateWindow

```
Sets the top-level widget containing this widget to be the active window.

An active window is a visible top-level window that has the keyboard input focus.

This function performs the same operation as clicking the mouse on the title bar of a top-level window. On X11, the result depends on the Window Manager. If you want to ensure that the window is stacked on top as well you should also call raise() .
```

I can add an option to the Preferences to `not steal the focus`.
