### ISSUE TITLE
Installing opensnitch

### ISSUE THREAD

**Issue by Caver1** [evilsocket/opensnitch#81]
trying to install opensnitch in Ubuntu 16.04.
Installed dependencies as per the readme > cd to opensnitch>sudo python setup.py install
I get back the following;
Traceback (most recent call last):
  File "setup.py", line 26, in <module>
    sys.version_info[0]))
RuntimeError: Unsupported python version "2"
python 3 is installed.
Thanks,
Doug

**Comment by adisbladis** [comment]
Replace `sudo python setup.py install` with `sudo python3 setup.py install`

@evilsocket The README is too distro specific, what do you say we remove it completely? I think it does more harm than good at the moment.

**Comment by evilsocket** [comment]
@adisbladis mmm not sure that removing it is a good idea, maybe improving it with instructions for other major distros would be better?

**Comment by adisbladis** [comment]
@evilsocket I think that is a good idea but maybe move it to the github wiki and have a reference to that in the readme

**Comment by cwh1te** [comment]
@evilsocket Long term, a wiki entry with instructions for a variety of distributions seems sensible. In the short term, based on your reasoning expressed elsewhere (https://github.com/evilsocket/opensnitch/issues/19), it seems like removing the instructions might make sense. If a dev on a system with 2 installed Python versions can't figure out how to run setup, are they really in your current target audience?

**Comment by arielf** [comment]
As a developer (not of opensnitch, but generally), I vote to keep the instructions.  They are actually very helpful and allowed me to try this software for the 1st time quickly without getting into the nitty-gritty.

I would just change `python` to `python3` in the setup line (which is what made it work for me).

**Comment by evilsocket** [comment]
@cwh1te well, not really ... the installation itself might be trivial, but not everybody remember the name of every single dependency on every possible distro ( for instance, I don't :D ), so having at least the "apt-get install ..." side of things would help, regardless what the audience is.
