### ISSUE TITLE
couldn't be accessed by user Permission denied

### ISSUE THREAD

**Issue by wp-coin** [evilsocket/opensnitch#816]
```
N: Download is performed unsandboxed as root as file '/home/mason/Downloads/opensnitch_1.6.0-rc.4-1_amd64.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)


```

Include the following information:
 - OpenSnitch 1.6.0.
 - OS: ubuntu 
 - Version 20.04
 - Window Manager: NOME Shell,
 - Kernel version: 5.15.0-58-generic

during installation I get this message at the end

**Comment by gustavo-iniguez-goya** [comment]
Hi @wp-coin !

That error is related to your apt, no opensnitch, see here and here:
https://lists.debian.org/debian-user/2017/06/msg00684.html
https://askubuntu.com/a/908825
