### ISSUE TITLE
[Arch Linux] Opensnitch UI does not log connections unless the daemon is restarted

### ISSUE THREAD

**Issue by user52318908** [evilsocket/opensnitch#838]
The UI does not appear to be able to connect to the daemon unless the daemon is restarted.

 - OpenSnitch 1.5.5-1
 - OS: Arch Linux
 - KDE
 - Kernel version: Linux arch 6.1.9-arch1-2

1. Install OpenSnitch with `sudo pacman -S opensnitch`
2. Enable the service with `sudo systemctl enable --now opensnitchd.service`
3. Launch OpenSnitch with `opensnitch-ui`
4. Note that OpenSnitch is paused and no connections are logged in the UI (no rules are displayed either). Connections are still being filtered, as reflected in `/var/log/opensnitchd.log` 
5. Restart OpenSnitch with `sudo systemctl restart opensnitchd.service` - this can take a few seconds
6. OpenSnitch now appears as "Running" and connections are logged as expected

This is on a fresh install of Arch Linux with KDE.

**Comment by gustavo-iniguez-goya** [comment]
Hi @user52318908 ,

Thank you for reporting this issue. It was already reported here: #833

**Comment by user52318908** [comment]
My apologies, I thought these were two separate issues.
