### ISSUE TITLE
Set  proccess monitor method to eBPF and reboot, then login it take about 3min to load xfce desktop.

### ISSUE THREAD

**Issue by hamedsbt** [evilsocket/opensnitch#841]
I have installed opensnitch 1.6.0-rc4 when I set  proccess monitor method to: eBPF and reboot, after login it take **about 3min to load xfce desktop.**

 - OpenSnitch version: 1.6.0-rc4 (same issue 1.5.5)
 - OS: archlinux
 - Kernel version: 6.1.9-arch1-2

I have installed opensnitch 1.6.0-rc4 and opensnitch-ebpf-module-git then set  proccess monitor method to: eBPF and reboot, after login it take about 3min to load xfce desktop.
Also I have installed **opensnitch 1.5.5** and **opensnitch-ebpf-module 1.5.5-3** and have same issue.

```
$systemd-analyze time
Startup finished in 30.147s (firmware) + 6.069s (loader) + 2.562s (kernel) + 5.619s (userspace) = 44.399s 
graphical.target reached after 5.619s in userspace.

$systemctl status opensnitchd.service
* opensnitchd.service - OpenSnitch is a GNU/Linux application firewall.
     Loaded: loaded (/usr/lib/systemd/system/opensnitchd.service; enabled; preset: disabled)
     Active: active (running) since Thu 2023-02-09 10:47:44 +0330; 1min ago
```

My workaround:
1) disable opensnitch (to fix 3min to load xfce desktop)
2) reboot
3) run opensnitch-ui **before start service** (because if start service first then run opensnitch-ui, the opensnitch-ui does not connect to service)
4) manually start service (systemctl start opensnitchd.service)

**Comment by gustavo-iniguez-goya** [comment]
Hi @hamedsbt ,

You'll probably need to allow dirmngr, xbrlapi or some other system component:
https://github.com/evilsocket/opensnitch/wiki/Getting-started#notes-

Do the following please:

1. empty /var/log/opensnitchd.log:

`truncate -s0 /var/log/opensnitchd.log`

2. reboot
3. post the log /var/log/opensnitchd.log

**Comment by hamedsbt** [comment]
Thank you for reply, /var/log/opensnitchd.log:
```
[2m[2023-02-09 12:17:44][0m [97m[43m WAR [0m Error while pinging UI service: rpc error: code = DeadlineExceeded desc = Deadline Exceeded, state: READY
[2m[2023-02-09 12:17:46][0m [97m[43m WAR [0m Error while pinging UI service: rpc error: code = DeadlineExceeded desc = context deadline exceeded, state: READY
[2m[2023-02-09 12:17:48][0m [97m[43m WAR [0m Error while pinging UI service: rpc error: code = DeadlineExceeded desc = context deadline exceeded, state: READY
[2m[2023-02-09 12:17:50][0m [97m[43m WAR [0m Error while pinging UI service: rpc error: code = Unavailable desc = transport is closing, state: READY
[2m[2023-02-09 12:17:50][0m [97m[41m ERR [0m getting notifications: rpc error: code = Unavailable desc = transport is closing <nil>

[2m[2023-02-09 12:17:50][0m [97m[104m IMP [0m Got signal: terminated
[2m[2023-02-09 12:18:24][0m [97m[104m IMP [0m Start writing logs to /var/log/opensnitchd.log
[2m[2023-02-09 12:18:40][0m [97m[43m WAR [0m nfables filter rules not loaded: 1
[2m[2023-02-09 12:18:40][0m [97m[104m IMP [0m nftables firewall rules changed, reloading
[2m[2023-02-09 12:18:41][0m [97m[41m ERR [0m [-1] FindProcess() error: Unable to get process information
```

**Comment by gustavo-iniguez-goya** [comment]
> OS: archlinux

Sorry, I didn't realize that you were using Arch. Until this issue #833 is fixed I cannot analyze any issues affecting that version, because we need a version that is not faulty.
