### ISSUE TITLE
Creating rule from event

### ISSUE THREAD

**Issue by gustavo-iniguez-goya** [evilsocket/opensnitch#845]
### Discussed in https://github.com/evilsocket/opensnitch/discussions/843

<div type='discussions-op-text'>

<sup>Originally posted by **tavoda** February 10, 2023</sup>
Am I doing something wrong but I can't create rule from row in Events tab. Is it missing feature or some issue?</div>

**Comment by gustavo-iniguez-goya** [comment]
added @tavoda 3cec971. It will be available on next rc release.

**Comment by tavoda** [comment]
That was fast. Thanks!
