### ISSUE TITLE
`.config` folder is created in the home directory when the GUI is started

### ISSUE THREAD

**Issue by staticssleever668** [evilsocket/opensnitch#847]
**Describe the bug**
`~/.config` folder is created when the GUI starts.

 - OpenSnitch version: b7f065e018fbfa2d3fd79f4a4b3fa478f4f4128e (1.6.0rc4).
 - The rest doesn't apply here.

**To Reproduce**

1. Check that there is no `~/.config/opensnitch` or `~/.config`.
2. Start the GUI of OpenSnitch.
3. See both of them appear. 

**Post error logs:** 
\-

**Expected behavior (optional)**
No folder is created, or it's created under the value of `XDG_CONFIG_HOME` environment variable instead of user's home directory.

**Screenshots**
\-

**Additional context**
Offending line:
https://github.com/evilsocket/opensnitch/blob/b7f065e018fbfa2d3fd79f4a4b3fa478f4f4128e/ui/opensnitch/actions/__init__.py#L83

Also, see another such usage of `~/.config` in the same module:
https://github.com/evilsocket/opensnitch/blob/b7f065e018fbfa2d3fd79f4a4b3fa478f4f4128e/ui/opensnitch/actions/__init__.py#L70

**Comment by gustavo-iniguez-goya** [comment]
[According to the specification](https://specifications.freedesktop.org/basedir-spec/latest/ar01s03.html), a directory for user configuration is always created, defaulting to `$HOME/.config`:
```
$XDG_CONFIG_HOME defines the base directory relative to which user-specific configuration files should be stored. If $XDG_CONFIG_HOME is either not set or empty, a default equal to $HOME/.config should be used. 
```

so
> Expected behavior (optional)
> No folder is created, or it's created under the value of XDG_CONFIG_HOME environment variable instead of user's home directory.

doesn't seem to be correct. 

What's the value of XDG_CONFIG_HOME for your regular user? and what distribution are you using?

**Comment by staticssleever668** [comment]
> No folder is created,

This part is incorrect, you are right.

Sorry, I should've clarified. I have moved away `XDG_CONFIG_HOME` on my system to `~/.local/etc` to have as least stuff in my home directory as possible.

> what distribution are you using?

I don't think this matters at all, but I'm on Arch.

**Comment by gustavo-iniguez-goya** [comment]
thank you @staticssleever668 !

changed to respects XDG_CONFIG_HOME.

By the way, the PKGBUILD is broken, ping AUR maintainer to update the file utils.py to -> utils/__init__.py

**Comment by staticssleever668** [comment]
Hey @gustavo-iniguez-goya, I only now tried the changes, and they don't work.
There is no `xdg` module in `utils`, in addition to `__init__.py` file accidentally being named `__init.py`.

**Comment by gustavo-iniguez-goya** [comment]
sorry @staticssleever668 , a stupid mistake. pull latest sources again please

**Comment by staticssleever668** [comment]
It works now, thank you!
