### ISSUE TITLE
mullvad wireguard doesnt work on 1.6.0-rc4, works on 1.5.2

### ISSUE THREAD

**Issue by themighty1** [evilsocket/opensnitch#853]
mullvad wireguard was working ok on opensnitch 1.5.2. with "debug invalid connections" enabled.
As soon as I upgraded to 1.6.0-rc4 and enabled "debug invalid connections", it won't connect. OpenVPN does connect though.
So, I went back to 1.5.2. and it works as expected. 
If anyone else is using mullvad and can reproduce, pls make a note here, so we would know that it is an actual opensnitch issue and not something specific to my machine. Then we could debug this issue further.

**Comment by gustavo-iniguez-goya** [comment]
Hi @themighty1 !

VPN connections should work without that check enabled. What kernel are you using? 

Could you download and test these ebpf modules for v1.6.x?
 - 5.19-master for >= 5.19 kernels, 1.6.x
 - or 5.8-master for < 5.19 kernels, 1.6.x

https://github.com/evilsocket/opensnitch/actions/runs/4066522844

Anyway, you should be prompted to allow no-process-associated outgoing connections, so please:
 - empty opensnitchd.log
 - set log level to DEBUG
 - connect to the VPN

and upload the log file. I changed the paths where the daemon looks for ebpf modules.
On >= v1.6.x they should be under `/usr/lib/opensnitchd/ebpf`, and there should be an INF log like: `INF [eBPF] module loaded: ...`

**Comment by gustavo-iniguez-goya** [comment]
> VPN connections should work without that check enabled. 

Ok, yes but not in v1.6.0rc4, it was fixed in master and v1.5.x branches. It'll be available on next release.

**Comment by GrigorijST** [comment]
Mullvad 2023.1 - WireGuard (Linux Mint 21.1 / Kernel 6.2.0) works as should on Opensnitch 1.6.0-rc4 in my case.

"debug invalid connections" disabled

**Comment by gustavo-iniguez-goya** [comment]
fixed on latest v1.6.0-rc.5 release https://github.com/evilsocket/opensnitch/releases/tag/v1.6.0-rc.5
