### ISSUE TITLE
icons disappeared on v1.6.0-rc.4

### ISSUE THREAD

**Issue by Knoxi-Code** [evilsocket/opensnitch#856]
My icons from the gui are disappeared, after a few days.
I have already reinstalled the gui but nothing has changed.

System: Debian 11 Gnome

![2023-02-20_20-36](https://user-images.githubusercontent.com/115695509/220186644-5c73e08c-8fff-40bb-8071-69926ddaa1cb.png)

**Comment by gustavo-iniguez-goya** [comment]
Hi @Knoxi-Code ,

Do the icons appear just after you launch the GUI?

Launch please the GUI from a terminal: `$ opensnitch-ui`.
try to reproduce the issue again, and see if is there any errors on the terminal.

**Comment by Knoxi-Code** [comment]
Hey @gustavo-iniguez-goya  

the icons are completely dispersant for/by the start,  same situation on terminal start.
What surprises me is that the icons worked, after the first installation and after a few days they were suddenly gone. 

Terminaloutput:
``
Loading translations: /usr/lib/python3/dist-packages/opensnitch/i18n locale: de_DE
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Using server address: unix:///tmp/osui.sock
is new file, or IN MEMORY, setting initial schema version
setting schema version to: 2
setting schema version to: 2
schema version: 2
db schema is up to date
using IPASN DB: /usr/lib/python3/dist-packages/data/ipasn_20140513_v12.dat.gz
``

**Comment by Knoxi-Code** [comment]
Use opensnitch eventuelly python qt packages and my icon packe is lost ?
Like qt6-svg etc...

**Comment by gustavo-iniguez-goya** [comment]
Something weird has happened, hmm, maybe apt removed some packages when installing opensnitch?
an incompatiblity between pyqt5 and 6?

If you can reproduce it, see if apt removes any package on installing opensnitch.

**Comment by Knoxi-Code** [comment]
Okey somthing is wrong...


reinstall opensnitch then...
reinstall all qt Package with: 
```
python3 -m pip install pyqt5
python3 -m pip install pyqt5-sip 

python3 -m pip install pyqt6 
python3 -m pip install pyqt6-sip 
python3 -m pip install qt-material
```

opensnitch need the pyqt5, pyqt5-sip,  qt-material the Gui start again but witch no icons.
Test it with ''python3 -m pip...'' and ''pip...'' only, same result : /

**Comment by gustavo-iniguez-goya** [comment]
A couple of questions @Knoxi-Code:
- did you execute those commands as root or your regular user?
- in order to install qt-material you don't need to install manually pyqt5 nor pyqt5-sip. I'd suggest to uninstall those packages and install instead with apt Debian's `python3-pyqt5` package.

**Comment by Knoxi-Code** [comment]
only pip as user, because security reasons.
Same errors with `sudo apt-get install python3-pyqt5` package.

When i uninstall `sip` and start `opensnitch-ui` in the terminal
```
Traceback (most recent call last):
  File "/usr/bin/opensnitch-ui", line 3, in <module>
    from PyQt5 import QtWidgets, QtGui, QtCore
ModuleNotFoundError: No module named 'PyQt5.sip'
```

**Comment by gustavo-iniguez-goya** [comment]
I suspect that there's a mix of libs in the system, maybe some packages have been uninstalled and it caused the problems with the icons.

> ModuleNotFoundError: No module named 'PyQt5.sip'

That is expected if you uninstalled it frm pip and it's not installed from apt. Install `python3-pyqt5.sip` from apt.

I assumed that you installed opensnitch from the deb packages, but now I'm not sure. Did you installed it using the .deb packages or did you compile it from the sources?

You could also create a new user, with a clean pip environment, and see if the GUI works and have the icons.

**Comment by Knoxi-Code** [comment]
I have today unfortunately not so much time, I will test it the days.
All package now from apt, but with the same problem. 

Thanks already for your help :)

**Comment by gustavo-iniguez-goya** [comment]
hey @Knoxi-Code , any update on this issue?

**Comment by Knoxi-Code** [comment]
I dont no why this happend, i reinstall the system and everything working fine again.

Some kind of pip-python-pyqt bug.
You can close the issue. :)
