### ISSUE TITLE
Opensnitch UI not intercepting or seemingly connecting to service

### ISSUE THREAD

**Issue by dfo-db** [evilsocket/opensnitch#859]
The UI seems to not be able to pick up on the background service running.

Version: opensnitch-daemon v1.5.2
OS: Ubuntu 22.04.1 on Gnome
Kernel: 5.19.0-32-generic

1. Install service and UI from .deb using: sudo apt install ./opensnitch*.deb ./python3-opensnitch-ui*.deb
2. Install working grpcio using: python3.10 -m pip install --ignore-installed grpcio
3. Check on service to see if it's running, it is (see log below)
4. Open Opensnitch-ui and get a white cloud in top bar, with no events logging, etc.

**Screenshots**
UI showing no way to disable and no events:

![image](https://user-images.githubusercontent.com/111020872/220811229-94e604d7-c7cb-489e-98e9-da5032d954f5.png)

![image](https://user-images.githubusercontent.com/111020872/220811284-1ce881a9-d65a-47c1-bd89-6891d87e6554.png)

Service status/log:

![image](https://user-images.githubusercontent.com/111020872/220811336-f732bcd6-145e-4f3a-8646-512c27738b34.png)

**Comment by gustavo-iniguez-goya** [comment]
Hi @dfo-db ,

Look at those errors while reading *.json files under /etc/opensnitchd/ , could you verify that `/etc/opensnitchd/default-config.json` and `/etc/opensnitchd/default-config.json` are populated with a valid configuration?

They should have this content: 

https://github.com/evilsocket/opensnitch/blob/1.5.0/daemon/default-config.json
https://github.com/evilsocket/opensnitch/blob/1.5.0/daemon/system-fw.json

**Comment by dfo-db** [comment]
Works! Not sure if you want to keep it as a bug, but for whatever reason the /etc/opensnitchd directory is not writable.

Thanks

**Comment by gustavo-iniguez-goya** [comment]
I don't think this is a bug (:crossed_fingers: ), packages have been installed many many times, it'd have failed before.

Anyway, did you download the packages from github? and what command did you execute to install them? dpkg -i ...? apt install ...?

**Comment by dfo-db** [comment]
Sounds good! You know more about it than I do, so I'll take your word for it.

I installed it through sudo apt install ./opensnitch*.deb ./python3-opensnitch-ui*.deb

Thanks for your help and I love the project!
