### ISSUE TITLE
opensnitch-ui (<= 1.6.0rc4-1.noarch) needs protobuf package to 3.20.x or lower

### ISSUE THREAD

**Issue by iolpltuisciaoln** [evilsocket/opensnitch#860]
opensnitch-ui-1.5.2-1.noarch.rpm as well as opensnitch-ui-1.6.0rc4-1.noarch.f29.rpm not starting after Fedora upgrade to 37

**To Reproduce**
Linux localhost.localdomain 6.1.13-200.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Feb 22 17:53:57 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

rpm -i opensnitch-ui-1.6.0rc4-1.noarch.f29.rpm

**Post error logs:** 
❯ opensnitch-ui
Traceback (most recent call last):
  File "/usr/local/bin/opensnitch-ui", line 23, in <module>
    from opensnitch.service import UIService
  File "/usr/lib/python3/dist-packages/opensnitch/service.py", line 13, in <module>
    from opensnitch import ui_pb2
  File "/usr/lib/python3/dist-packages/opensnitch/ui_pb2.py", line 32, in <module>
    _descriptor.EnumValueDescriptor(
  File "/usr/local/lib64/python3.11/site-packages/google/protobuf/descriptor.py", line 796, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

**Comment by gustavo-iniguez-goya** [comment]
Hi @iolpltuisciaoln ,

Could launch the GUI from a terminal as follow?:
`$ PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python opensnitch-ui`

Let me know please if the GUI show up.

**Comment by iolpltuisciaoln** [comment]
Yes GUI starts this way after about a minute.

**Comment by gustavo-iniguez-goya** [comment]
thank you @iolpltuisciaoln !

I'll try to reproduce it and find a solution. I've got an idea.

**Comment by gustavo-iniguez-goya** [comment]
@iolpltuisciaoln , could you post info of your packages `python3-grpcio` and `python3-protobuf`?
`$ yum info python3-grpcio python3-protobuf`

I've just installed it on Fedora 38 beta and it doesn't crash. Maybe this crash is caused by a specific version of protobuf/grpcio.

Fedora 38 versions: python3-grpcio 1.48.3, python3-protobuf 3.19.6

**Comment by iolpltuisciaoln** [comment]
❯ dnf info python3-grpcio python3-protobuf
Last metadata expiration check: 2:57:38 ago on Sat 25 Feb 2023 11:41:39 MSK.
Installed Packages
Name         : python3-protobuf
Version      : 3.19.6
Release      : 1.fc37
Architecture : x86_64
Size         : 1.9 M
Source       : protobuf-3.19.6-1.fc37.src.rpm
Repository   : @System
From repo    : updates
Summary      : Python bindings for Google Protocol Buffers
URL          : https://github.com/protocolbuffers/protobuf
License      : BSD-3-Clause
Description  : This package contains Python libraries for Google Protocol Buffers

Available Packages
Name         : python3-grpcio
Version      : 1.48.3
Release      : 1.fc37
Architecture : x86_64
Size         : 2.2 M
Source       : grpc-1.48.3-1.fc37.src.rpm
Repository   : updates
Summary      : Python language bindings for gRPC
URL          : https://www.grpc.io
License      : Apache-2.0 AND BSD-2-Clause AND BSD-3-Clause AND MIT
Description  : Python language bindings for gRPC (HTTP/2-based RPC framework).

Name         : python3-protobuf
Version      : 3.19.4
Release      : 6.fc37
Architecture : noarch
Size         : 314 k
Source       : protobuf-3.19.4-6.fc37.src.rpm
Repository   : fedora
Summary      : Python 3 bindings for Google Protocol Buffers
URL          : https://github.com/protocolbuffers/protobuf
License      : BSD
Description  : This package contains Python 3 libraries for Google Protocol Buffers

**Comment by iolpltuisciaoln** [comment]
It somehow uses python 3.11:
❯ pip3 show protobuf
Name: protobuf
Version: 4.22.0
Summary: 
Home-page: https://developers.google.com/protocol-buffers/
Author: [protobuf@googlegroups.com](mailto:protobuf@googlegroups.com)
Author-email: [protobuf@googlegroups.com](mailto:protobuf@googlegroups.com)
License: 3-Clause BSD License
Location: /usr/local/lib64/python3.11/site-packages
Requires: 
Required-by: Electrum, grpcio-tools

**Comment by gustavo-iniguez-goya** [comment]
thank you  @iolpltuisciaoln , I'll regenerate the protobuffers with 3.19.0 and will post them here for you to test it (in 8h more or less...)

**Comment by gustavo-iniguez-goya** [comment]
I'm unable to reproduce this issue :-1:  and the current protobuffers seems to be generated with v3.20.0, so for now youll have to use the above workaround, well adding it to your `~/.bashrc` well adding it to your `/etc/environment` file.

By the way, regarding the delay showing up the GUI, you'll need to install and enable the extension gnome-shell-extension-appindicator: https://github.com/evilsocket/opensnitch/wiki/Known-problems#opensnitch-icon-does-not-show-up-on-gnome-shell

**Comment by iolpltuisciaoln** [comment]
partially fixed with
`pip3 uninstall protobuf`
starting is slow tho, gnome-shell-extension-appindicato and python3-notify2 are installed.
probably fc37 issue
