### ISSUE TITLE
apt update

### ISSUE THREAD

**Issue by Shuunen** [evilsocket/opensnitch#87]
Hi, 

I've tested opensnitch this morning on Linux Mint 18.1 (Kernel: x86_64 Linux 4.4.0-78-generic) which is based on Debian and Ubuntu (LTS).

I just had to `apt install libpcap-dev` to pass the install.

Then I started the opensnitch deamon & gui, it discovered a lot of my connections and I started to set rules until opensnitch-qt popups stop appearing.

I tryed it, for example after allowing git , I managed to use git & clone repos. Good.

But then I tryed to `apt update` and this was blocked by opensnitch.

After killing the deamon, `apt update` was working.

Any idea ?

**Comment by ei8fdb** [comment]
@Shuunen Do you have any logs of the _apt update_ issue?

**Comment by Shuunen** [comment]
Hi, I updated the sources to test on the latest code and did a fresh install

After starting an `apt update` , opensnitch-qt popup appeared for each update repository, and I don't reproduce the initial issue... 

Good :)

**Comment by ei8fdb** [comment]
Good news. 🎉

**Comment by Shuunen** [comment]
@ei8fdb I'm wondering, maybe it was like opensnitch-deamon or opensnitch-qt were flooded with requests, see what I mean ?

Because the first time I started opensnitch, I was doing a lot of things on my desktop, there were web browsers opened, terminal process in background, web servers were running, many processes that actually made a lot of requests to both internal & external ressources on many different ports...

Is it possible that opensnitch-deamon or opensnitch-qt were flooded and did not asked me to choose an action for all requests ? that would explain why

**Comment by ei8fdb** [comment]
@Shuunen It sounds possible, but I can't say. I've not been involved in the development. If you have logs they would help.

Maybe @evilsocket @adisbladis might be able to comment.

**Comment by Shuunen** [comment]
@ei8fdb I did not managed to find logfile, where should it be located ?

**Comment by adisbladis** [comment]
Opensnitch has no log files, only stdout/stderr.

I find it unlikely that opensnitch got flooded, much more likely you hit some edge case in some handling logic or a very eager exception handler that made processing of new packets stop.

Hard to tell and I have not been able to reproduce this issue.

**Comment by ei8fdb** [comment]
@adisbladis @Shuunen D'oh. My bad. Apologies for the incorrect information.
