### ISSUE TITLE
Allow disabling countdown

### ISSUE THREAD

**Issue by trytomakeyouprivate** [evilsocket/opensnitch#871]
To be user friendly, the program must be able to pop up and not disappear until a choice is done.

Currently the max countdown time is 99, changing that to something bigger in the config file doesnt work.

Please allow disabling the countdown and increasing the time, and by default set it to "never disappear until user interaction"

Awesome tool, I love it! It gives so much transparency.

**Comment by gustavo-iniguez-goya** [comment]
Hi @trytomakeyouprivate , thank you for the suggestions.

Right now, when you click on a pop-up the countdown is stopped. 

Please, read this comment for more information about the other suggestions: https://github.com/evilsocket/opensnitch/issues/783#issuecomment-1363931841
