### ISSUE TITLE
[Feature Request] Change default to "forver" instead of "until reboot"

### ISSUE THREAD

**Issue by trytomakeyouprivate** [evilsocket/opensnitch#872]
### Summary:
Making all changes temporary is not a good solution. This will annoy users by default so much, they might uninstall it.

Please make the default set to "forever", but instead disable the countdown, so the user has to do an active choice.

Great Tool!

**Comment by gustavo-iniguez-goya** [comment]
Hi @trytomakeyouprivate !

Defaulting to Forever may have undesired effects, like denying or allowing something forever that you didn't intend to. From that on, if something stops working is harder to determine what rule is causing the problem.

Anyway, users can already select the default options of the pop-ups on the Preferences dialog:

![image](https://user-images.githubusercontent.com/2742953/222234686-ec8ca1bc-ff05-4cf7-8d95-e2e416a856dc.png)

**Comment by trytomakeyouprivate** [comment]
ok I understand that you dont want this setting. But the effect of "until reboot" is, that by default users have to click every popup every time right? Of course this means they have active interaction, which is good, but this could be done differently, with more comfort.

Its not a big deal though, as you can change it.
