### ISSUE TITLE
[Feature Request] opensnitch-ui: longer default timeout + cancel timeout upon user interaction with the popup

### ISSUE THREAD

**Issue by lelutin** [evilsocket/opensnitch#875]
Using opensnitch + opensnitch-ui 1.5.8-2 from Debian sid

### Summary:

Currently the UI shows a popup when it intercepts new packets that don't match a rule. By default, the action is to deny the connection after only 15 seconds.

15 seconds is a very short time for users to acknowledge what that popup is saying and to take the appropriate action.

Moreover, while interacting with the dropdowns in the popup to choose another action the timeout continues to move forward and if they're not fast enough the UI will disappear under users' fingers and add a blocking rule that may not have been what they wanted.

So, it would be better in terms of UX to have a longer default timer, say 60 or even 90 seconds. Plus the timer should be stopped when users start interacting with the window.

**Comment by gustavo-iniguez-goya** [comment]
Hi @lelutin !

Thank you for these suggestions. Users can configure pop-ups default options from the Preferences dialog:

![image](https://user-images.githubusercontent.com/2742953/222983604-a3ade1d5-a71c-4924-9425-16fe3febe876.png)
---

On the other hand, on versions 1.5.x when you click on the [+] button the timer is stopped.
On versions >= 1.6.x we extended this option to stop the countdown by clicking in any part of the pop-up.

There'll probably be another debian version soon, and I think we'll change the default countdown, but no the option to disable it.

**Comment by lelutin** [comment]
@gustavo-iniguez-goya ah-ha. thanks for the details. I'll wait for version 1.6.x in debian than :)
