### ISSUE TITLE
Some connections appear to go through while the popup is still active w/ default reject

### ISSUE THREAD

**Issue by BetweenTheKeyboardAndChair** [evilsocket/opensnitch#878]
In Firefox (107.0), I'm seeing the browser load some sites while the pop up is still visible (w/time left) asking if I want to accept/reject the connection.  I can't tell how much is leaking since I only see the visible loads. I'm not seeing any consistent pattern. I did not notice this happening on RC2.
e.g.
In the browser URL, enter: https://some.bad.place
opensnitch pops-up asking if I want to allow the connection to some.bad.place (60 timer, default reject)
Meanwhile the page loads a second later while the pop up is still counting down.
There maybe a few second delay before the connection slips through.

Host setup:
opensnitch/now 1.6.0-rc.4-1 amd64
python3-opensnitch-ui/now 1.6.0-rc.4-1 all

Ubuntu 20.4
cinnamon/focal,now 4.4.8-4 amd64
Linux ucin 5.4.0-137-generic #154-Ubuntu SMP Thu Jan 5 17:03:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**To Reproduce**
The one reproducible case that I know will be really hard for you to set up. (Lots of configuration of the browser, and opensnitch to block other connections.)
What can I do to help debug this?  Are there logs I can send that will help?  If so, how to I generate/find them?  When giving instructions, assume I'm an idiot.  I have not done serious sysadmin in a long time.  I am not familiar with the linux networking tools. (Which is why I love opensnitch.)

**Comment by gustavo-iniguez-goya** [comment]
I guess you'll have a rule for `systemd-resolved`. If so, edit and restrict it to connect to port 53 and your DNS servers IPs.
(`resolvectl dns` or `cat /etc/resolv.conf`). You can also delete the rule, and then reallow it to only connect to port 53 and your DNS server IP.

On the other hand, the sites that load while the pop-up is visible should appear on the Events tab, could you take a look what rule is allowing or mathcing them (Rule column)?

Also, be sure that pop-ups' default Action is set to Deny under Preferences -> Pop-ups, and eventually, configure daemon's DefaultAction to Deny (Preferences->Nodes). Regarding this last option, bear in mind that it'll deny everything not explicitely allowed (good, but it can have some side effects, use with cautions)

**Comment by gustavo-iniguez-goya** [comment]
hey @BetweenTheKeyboardAndChair , did you try the suggested changes?
