### ISSUE TITLE
opensnitch-ui installation fails on Fedora 37 Silverblue

### ISSUE THREAD

**Issue by candied487** [evilsocket/opensnitch#879]
steps to reproduce :
rpm-ostree install opensnitch-ui-1*.rpm

error: Importing package 'opensnitch-ui': Analyzing /usr/local/bin/opensnitch-ui: Unsupported path; see https://github.com/projectatomic/rpm-ostree/issues/233
-------
backend can be layered without installation issues

**Comment by gustavo-iniguez-goya** [comment]
I'll close this issue as duplicate of #880, let's keep talking about it there.

Thank you!
