### ISSUE TITLE
library path failure on Lubuntu

### ISSUE THREAD

**Issue by nealrauhauser** [evilsocket/opensnitch#88]
Trying to install on Lubuntu VM just to see how opensnitch looks. There was a lack of libcap-dev dependency detection, which I easily resolved, but which needs fixing, and then this mystery.

> ./opensnitchd
> WARNING: No route found for IPv6 destination :: (no default route?). This affects only IPv6
> Traceback (most recent call last):
>   File "./opensnitchd", line 38, in <module>
>     from opensnitch.snitch import Snitch
>   File "/usr/local/lib/python3.5/dist-packages/opensnitch-0.0.2-py3.5.egg/opensnitch/snitch.py", line 31, in <module>
>     from opensnitch.iptables import IPTCRules
>   File "/usr/local/lib/python3.5/dist-packages/opensnitch-0.0.2-py3.5.egg/opensnitch/iptables.py", line 19, in <module>
>     import iptc
>   File "/usr/local/lib/python3.5/dist-packages/python_iptables-0.12.0-py3.5-linux-x86_64.egg/iptc/__init__.py", line 10, in <module>
>     from iptc.ip4tc import (is_table_available, Table, Chain, Rule, Match, Target,
>   File "/usr/local/lib/python3.5/dist-packages/python_iptables-0.12.0-py3.5-linux-x86_64.egg/iptc/ip4tc.py", line 13, in <module>
>     from .xtables import (XT_INV_PROTO, NFPROTO_IPV4, XTablesError, xtables,
>   File "/usr/local/lib/python3.5/dist-packages/python_iptables-0.12.0-py3.5-linux-x86_64.egg/iptc/xtables.py", line 812, in <module>
>     raise XTablesError("can't find directory with extensions; "
> iptc.xtables.XTablesError: can't find directory with extensions; please set XTABLES_LIBDIR
> 

A quick Google brings up this solution

https://github.com/ldx/python-iptables/issues/37

And this is the right incantation for Lubuntu

cat >> ~/.bashrc
export XTABLES_LIBDIR=/usr/lib/x86_64-linux-gnu/xtables/
ctrl-d

Once this is resolved, I get the following error, and I think this is a bit past my Python debugging skills.

> ./opensnitchd 
> WARNING: No route found for IPv6 destination :: (no default route?). This affects only IPv6
> Traceback (most recent call last):
>   File "./opensnitchd", line 77, in <module>
>     raise RuntimeError('DBUS_SESSION_BUS_ADDRESS not set')
> RuntimeError: DBUS_SESSION_BUS_ADDRESS not set
> 

I'm very excited by a Linux port of Little Snitch, willing to do whatever in terms of testing on various distros, just not sure how to proceed here.

**Comment by nealrauhauser** [comment]
I installed Linux Mint 18.1.

opensnitch still has the need for apt install libcap-dev

Does not have the other dependency issues.

Still has the DBUS error as reported above.

And then the VM hung hard, which is the sort of misbehavior I expect from Mint.

**Comment by adisbladis** [comment]
The library path is not an issue with Opensnitch but rather with certain distros. 

The DBUS_SESSION_ADDRESS issue is that you are not using the right sudo flags.
You need to inherit this from the user session.

I'm closing this since neither are issues with Opensnitch.
