### ISSUE TITLE
[rpm] Opensnitch-ui packages should install the binary into /usr/bin instead of /usr/local/bin 

### ISSUE THREAD

**Issue by Bennyhill500** [evilsocket/opensnitch#880]
The /usr/local/bin folder is supposed to be used by admins manually compiling/installing binary files and should not be touched by the package manager of the operating system, and for that reason Fedora Silverblue does not support .rpm files which install files there.

**Comment by gustavo-iniguez-goya** [comment]
oops, sorry folks, I totally forgot about this problem.

Actually, I'm not sure how to handle this problem properly. I was tempted for v1.6.0 to remove /usr/local/bin/opensnitch-ui on post-installation, only if it was installed properly under /usr/bin. It seems safe but.., or maybe instead of deleting it, rename it to opensnitch-ui.rpm_old

v1.6.1 is inminent, so I'll add it for that version.

**Comment by comminutus** [comment]
I was able to get the UI to run via [distrobox](https://github.com/89luca89/distrobox).  You can probably do something similar in [toolbox](https://docs.fedoraproject.org/en-US/fedora-silverblue/toolbox/) - but I prefer distrobox.  Here's what I did:
1. Install distrobox if you don't have it: `rpm-ostree install -Ay distrobox`
2. Setup a distrobox for opensnitch-ui
```
distrobox create -Yn opensnitch-ui -i fedora &&
distrobox enter opensnitch-ui
```
3. Download opensnitch-ui
4. Install opensnitch-ui in the newly created distrobox (my rpm is in ~/Downloads)
```
sudo dnf update -y
sudo dnf install -y ~/Downloads/opensnitch-ui-1.6.0.1-1.noarch.rpm
# The following fixes missing dependencies:
pip3 install grpcio grpcio-tools
# For themes:
pip3 install qt-material
# Fixes protobuf problems
pip3 uninstall -y protobuf
# Export the app so it's available in your desktop
distrobox-export --app opensnitch-ui
exit
```
The protobuf issues I believe are related to #647 
5. Setup this distrobox to run as a service:
```
podman generate systemd -f --name opensnitch-ui
mv container-opensnitch-ui.service ~/.config/systemd/user
systemctl --user daemon-reload
distrobox stop -Y opensnitch-ui
systemctl --user enable container-opensnitch-ui
systemctl --user start container-opensnitch-ui
systemctl --user status container-opensnitch-ui
```
6. Add OpenSnitch UI to run as startup applications (in Gnome Tweaks for example)

**Comment by gustavo-iniguez-goya** [comment]
This issue should be finally fixed. It now installs on Silverblue, and upgrading from previous versions replaces correctly the binary from /usr/local to /usr/bin automagically.

**Comment by steelowheel** [comment]
Sorry for bumping a closed issue, but can anyone confirm Opensnitch works on Kinoite? I just freshly installed Kinoite and then installed Opensnitch and its UI in BoxBuddy. But when I open the UI it doesn't show connections or just about anything. Also I was expecting to get allow/deny prompts but I have seen none.
