### ISSUE TITLE
[Feature Request] Log connections without the GUI running

### ISSUE THREAD

**Issue by user52318908** [evilsocket/opensnitch#881]
Would it be possible to have the ability to view the connections being made (same as in the GUI), but from a text log? The log in `/var/log/opensnitchd.log` only produces errors and warnings.

**Comment by gustavo-iniguez-goya** [comment]
Hi @user52318908 ,

I guess that you don't want to use the GUI at all. If by any chance you do, you could configure to save events to disk. The file is just a sqlite DB that you can query. 

Ok, jokes aside, there's a cli tool that I haven't updated in ages: https://github.com/gustavo-iniguez-goya/opensnitch/issues/54#issuecomment-676588489

I don't know if it still works, but it'd be interesting to update it, and/or rewrite it with cobra or other framework.
