### ISSUE TITLE
Problem loading/opening opensnitch-ui

### ISSUE THREAD

**Issue by vicxdev** [evilsocket/opensnitch#887]
Hi! I just finished the installation of opensnitch and after some troubleshooting, I found that opensnitch-ui doesn't open.
These are my specs:

 - OpenSnitch version: 1.6.0rc5
 - OS: Ubuntu (GNU/Linux)
 - Version: 22.04.2 LTS
 - Window Manager: -
 - Kernel version: Linux 5.15.0-60-generic # 66-Ubuntu SMP x86_64 GNU/Linux

I ran the opensnitch-ui command to see if there is a problem, but it stays loading and never opens. Here a capture:
![image](https://user-images.githubusercontent.com/85118830/227292369-138226cf-53a5-4010-a4f9-fc8189ad916a.png)

Someone who can help me? Thanks

**Comment by gustavo-iniguez-goya** [comment]
Hi @vicxdev ,

I think you're having this issue: #647 

Check if the process `opensnitch-ui` is consuming 100% of the CPU. Then try this solution: https://github.com/evilsocket/opensnitch/issues/647#issuecomment-1090545284

**Comment by gustavo-iniguez-goya** [comment]
Is there an icon like this one in the system tray?

![image](https://user-images.githubusercontent.com/2742953/227365640-c8331d57-077d-4586-8e5f-6591eba847de.png)

**Comment by gustavo-iniguez-goya** [comment]
Ok, I think you're running GNOME, so could you install the appindicator extension?
https://github.com/evilsocket/opensnitch/wiki/Known-problems#opensnitch-icon-does-not-show-up-on-gnome-shell

If the extension is not installed, the GUI should show up after ~10s of launching it.
If the extension is installed only the icon should show up on the systray.

If you're still having the issue #647 + appindicator extension => the systray icon shows up, but it's grayed out (like disabled, no nodes connected).
If you're still having the issue #647 + no appindicator extension => nothing shows up.

I think you're stuck on the last option. no appindicator + the issue 647. Please, install the extension and let me know if the icon shows up on the systray.

**Comment by ItsDrike** [comment]
Could you add a CLI option to start the GUI directly? I don't yet have system tray configured, because my bar doesn't yet have support for it on wayland. It would be neat if starting didn't require clicking on a tray icon.

**Comment by gustavo-iniguez-goya** [comment]
@ItsDrike what distro , WM and/or DE are you using?

@vicxdev :(

> If the extension is not installed, the GUI should show up after ~10s of launching it. 

If you kill/stop the GUI (`$ killall opensnitch-ui`) , does the GUI show up after 10s? Because if it doesn't show up, I'd bet that it's caused by the issue #647

**Comment by gustavo-iniguez-goya** [comment]
hey, any update on this issue?

**Comment by gustavo-iniguez-goya** [comment]
ok!
