### ISSUE TITLE
Systemd service

### ISSUE THREAD

**Issue by jcstryker** [evilsocket/opensnitch#89]
We will probably want a service file for the OpenSnitch daemon running as root, though access to the user DBUS_SESSION_BUS_ADDRESS variable becomes an issue.

Any thoughts?

**Comment by da2x** [comment]
Isn’t that problem what [polkit](https://www.freedesktop.org/wiki/Software/polkit/) is for?

**Comment by adisbladis** [comment]
@jcstryker The DBUS_SEESSION_BUS_ADRESS is not an issue since it will run as a system service.
The user session stuff is only temporary to make things a little bit easier :)

**Comment by plangton4** [comment]
@adisbladis any updates on the systemd service?
