### ISSUE TITLE
[Feature Request] Create rules from the events tab

### ISSUE THREAD

**Issue by strboul** [evilsocket/opensnitch#891]
Upon the first installation, I get a lot of popups coming up, and I had to give large permissions to some of the executable to at least have things going. At the same time, I'm keeping an eye on the Events tab to check if there are any connections I need to deny/reject/allow.

Right now, for example, I see an event that I want to deny.  I take a note of the details, then go to the Rules and I add/edit a/the rule manually. It'd be nice to be able to right click onto the events and have a window to create/edit rules. 

![image](https://user-images.githubusercontent.com/25015317/227894759-fbcd135f-a1f9-4e34-9d92-510a82a7dad6.png)

**Comment by gustavo-iniguez-goya** [comment]
Hi @strboul ,

This request was requested here #843 and added here 3cec971a1f7265d5d48b2a8425e5872871aeff70

Thank you!
