### ISSUE TITLE
World of Warcraft game lags

### ISSUE THREAD

**Issue by devastatorius** [evilsocket/opensnitch#892]
Hello.
Before posting bug report i faced this problem twice.
First comes on January 8 and 9 days, when i updated OpenSnitch to RC4 version.
Well, i didn't tried to play this game until today and i found this issue is not gone away.
After some hours i found this is OpenSnitch problem of newer versions. Currently i have running RC3 and no input lags and Latency is very little about 35ms. Newer versions sometimes gives me 2k-3k of ping, but sometimes they stay low as 35-40ms.
![screen](https://user-images.githubusercontent.com/3929571/227980336-56d225ab-8c4f-4b43-9c05-b5e50d3df1f9.jpg)

Strange thing is that, i get only input lags, only when some time (on example 20-30sec.) is passed not on fresh run, on example when i try to mount an animal or try to fish on nearby water or i try to interact with some of NPCs, this  make gameplay almost unplayable.

Also i tried different things like stock Ubuntu wine or Lutris wine installations, problem are same. I solved only when i installed OpenSnitch version which released before January 7 day, RC3 in other words.
Other apps, games has no issues only World of Warcraft.
About logs. /var/log/opensnitchd.log has no entries about this period when i played and tested game.

Some info about my PC.
OS: Ubuntu (transformed to Kubuntu from Lubuntu)
Version: 22.10
 - Window Manager: KDE
 - Kernel version: Linux northc 5.19.0-38-generic #39-Ubuntu SMP PREEMPT_DYNAMIC Fri Mar 17 17:33:16 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by gustavo-iniguez-goya** [comment]
Hi @devastatorius !

>  Newer versions sometimes gives me 2k-3k of ping, but sometimes they stay low as 35-40ms

Did you try latest rc5? you didn't mention it explicitly so I had to ask :)

I'll need logs in DEBUG level to analyze this issue. So please:
 - install latest rc5
 - set LogLevel to DEBUG (Preferences -> Nodes), or LogLevel to 0 in `/etc/opensnitchd/default-config.json`
 - empty the log file: `$ sudo truncate -s0 /var/log/opensnitchd.log`
 - reproduce the problem.
 - copy the log file `/var/log/opensnitchd.log` to other directory, and post it here (or email it to me, whatever you feel more comfortable with).

On the other hand, if you get again those 2k-3k ping values, launch a `top` and see if anything is using all the CPU.

**Comment by devastatorius** [comment]
I just send a zipped log.
But i forgot to mention, no network latency drops appear for now. Good ~40ms but input lag killing all. Need to wait a 10 seconds for return of action.

**Comment by gustavo-iniguez-goya** [comment]
Hi again @devastatorius !

Sorry for the late reply. After analyzing the logs, I haven't seen any obvious delay establishing new outbound connections (all seems to happen on the same second, maybe we'd need more granularity to better analyze these cases).

There're some common activity though that can be improved:
 - Connections to localhost:
   Please, create a new rule: "000 allow localhost", [x] Enable, [x] Priority rule, (*) Allow, [x] To this IP: 127.0.0.1

 - wineserver and wine-preloader:
   Rename the rules for `wineserver` and `wine-preloader` to "000-allow-wineserver" and "000-allow-wine-preloader", and mark `[x] Priority rule` for both rules.

By making these rules have priority, opensnitch won't check the rest of the rules, allowing outbound connections faster.

Let me know if it makes any difference.

**Comment by devastatorius** [comment]
Same problem after i made those changes.
When i run game it working good, until 40 seconds passed.

**Comment by gustavo-iniguez-goya** [comment]
Reviewing the logs again, there's a delay of about 1-2s between one connection to localhost => 6881 and the next one. That doesn't occur at the begginning of the logs, which usually occur on the same second:

at the beginning:
```
[2023-03-28 13:29:54]  DBG  ✔ /home/.../bin/wineserver -> 127.0.0.1:6881 (allow-bin-wineserver)
[2023-03-28 13:29:54]  DBG  new connection tcp => 53010:127.0.0.1 -> 127.0.0.1 ():6881 uid: 1000
            ^^^^^^^^
```

after some minutes:

```
[2023-03-28 13:36:01]  DBG  ✔ /home/.../bin/wineserver -> 127.0.0.1:6881 (allow-bin-wineserver)
[2023-03-28 13:36:04]  DBG  new connection tcp => 38778:127.0.0.1 -> 127.0.0.1 ():6881 uid: 1000
            ^^^^^^^^
```

```
[2023-03-28 13:40:50]  DBG  ✔ /home/.../bin/wineserver -> 127.0.0.1
:6881 (allow-bin-wineserver)
[2023-03-28 13:40:53]  DBG  new connection tcp => 53136:127.0.0.1 -> 127.0.0.1 ():6881 uid: 1000
            ^^^^^^^^
```

I cannot conclude though, if it's opensnitch blocking connections, or if it's simply that there're no new connections for those 1-2s, but it's something suspicious at least.

Could you add a rule to bypass localhost connections completely?

Using the firewall dialog rule:

![image](https://user-images.githubusercontent.com/2742953/231895122-b4d2a555-778f-4d11-8bbe-c0a1a42b3d63.png)


On the other hand, see if this message appears on the journalctl:
```bash
$ sudo journalctl -f | grep -i "timed out"
```

**Comment by luzpaz** [comment]
Any updates ?

**Comment by gustavo-iniguez-goya** [comment]
hey @luzpaz , we've changed some things that could impact this behaviour for the better. Did you try it with latest v1.6.1?

**Comment by devastatorius** [comment]
I can't test that thing right now, because my main machine with windows os.
I don't have time to install linux os.
Sorry for that.

**Comment by gustavo-iniguez-goya** [comment]
no problem @devastatorius , if you encounter this issue again in the future, please feel free to reopen the issue.
thank you for taking the time to report this problem!
