### ISSUE TITLE
GUI crash when deleting more than one row in system rules.

### ISSUE THREAD

**Issue by BobSquarePants** [evilsocket/opensnitch#895]
Hi,

When I select more than one row (rule) in System rules (GUI) then hit the deleted key
I got (as usual)

> Your are about to delete this rule.
> Are you sure?

Once I click yes, the GUI crash. When I restart the GUI both (or more) rules are still there.

This is not happening when selecting only one rule (working fine)

--
 - OpenSnitch version : 1.6.0rc5
 - OS: Devuan ❤️ 
 - Version: 4
 - Window Manager: XFCE
 - Kernel version: 5.10.0-9-amd64

**Comment by gustavo-iniguez-goya** [comment]
@BobSquarePants ,

Could launch the GUI from a terminal, and paste the error? I cannot reproduce it.

**Comment by BobSquarePants** [comment]
please -->

```shell
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 1125, resource id: 14167594, major code: 40 (TranslateCoords), minor code: 0
Segmentation fault
```

**Comment by gustavo-iniguez-goya** [comment]
That error doesn't seem to be related to the GUI code. But it could be a threads locking problem.

Could you launch it with --debug? `$ opensnitch-ui --debug` it'll print out more information.

**Comment by gustavo-iniguez-goya** [comment]
this issue looked more like a wayland<->qt compatibility issue, rather than an error in our code.
