### ISSUE TITLE
Minor theming issue

### ISSUE THREAD

**Issue by planetoryd** [evilsocket/opensnitch#898]
All dark themes from qt-material have terrible contrast here, the unfocused text is as dark as the background (tried some light themes, they are weird-looking too)

https://github.com/UN-GCPDS/qt-material/issues/85#issuecomment-1492974467 (my issue was the same as this)

**Comment by gustavo-iniguez-goya** [comment]
Hi @planetoryd ,

Thank you for the feedback. I'll close this issue since it's an issue of qt-material.
Let's keep track of it on qt-material's issue.
