### ISSUE TITLE
「Feature Request」Add support for redirecting traffic to user-specified interfaces

### ISSUE THREAD

**Issue by planetoryd** [evilsocket/opensnitch#901]
Besides `deny` and `allow`, it may `redirect` traffic to other interfaces. The purpose is to have a GUI-based solution to proxy-selective-routing on Linux, ie. selecting individual proxies for different applications, which is troublesome and inaccessible at this moment for most users. This feature should allow for greater privacy for an average user. 

TUN interfaces may be created through tun2socks for socks proxies, including Tor, and lokinet creates TUN/TAP interface on its own. I know that 'redirecting to interfaces' might not be the best solution for the said goal. Maybe it'd possible to redirect the traffic to Opensnitch and dispatch it to corresponding socks proxies directly, according to the rules, basically incorporating tun2socks.

It'd even better to `redirect` DNS resolution, based on the same set of firewall rules. Ex. One application binary is resolved through a proxied DNS server.

**Comment by gustavo-iniguez-goya** [comment]
Closing as duplicated of #738 and #437, although with more details :)
I'll give it another try with new ideas once 1.6.0 is released. Let's keep discussing about this on #437
