### ISSUE TITLE
[Feature Request] Keep more Events or for longer (Only getting 1-2 seconds worth now)

### ISSUE THREAD

**Issue by BetweenTheKeyboardAndChair** [evilsocket/opensnitch#907]
As of 1.6.0.RC6, the UI only seems to display the last 50 events (or so).  Given the number of times sites auto-retry refused connections (5-10 times), this means that I often only have the last few seconds of data in the event log.  I'd like to be able to see more.  

I like the new auto-pruning.  I'd like to keep the last 10m? of data.   Time based pruning can be a pain, so maybe:
- Increase the number of lines kept to 1000?
- Make the number of lines kept configurable?

**Comment by gustavo-iniguez-goya** [comment]
Hi @BetweenTheKeyboardAndChair ,

The events are not limited to ~50 events. Did you change the events limit?

**Comment by BetweenTheKeyboardAndChair** [comment]
Somehow the setting (that I never new existed) got set to 50.  This was for a clean install -- I purged the old version, and hand removed all remaining files -- before installing the new RC.

If someone has the time to check if this is a new install issue, great.  I really don't want to lose all my rules again.

This issue can be closed.

**Comment by gustavo-iniguez-goya** [comment]
50 is the default value for new installations. If you change the limit, when the main window is closed it'll be saved to disk.

The GUI settings are stored in your user home directory: `/home/$user/.config/opensnitch/settings.conf` and the setting key is `general_limit_results`

If you manage to reproduce it, open a new issue please.

On the other hand, uninstalling the deb package does not remove the rules (i.e.: the directory /etc/opensnitchd/rules/). But if you purge the package then yes. You can backup the dire before uninstalling, and copy the rules back again after installing.
