### ISSUE TITLE
Cannot find module providing package github.com/evilsocket/opensnitch/daemon/ui/protocol

### ISSUE THREAD

**Issue by alexchristy** [evilsocket/opensnitch#909]
**Bug:** When building the daemon from source, make throws an error saying that a package is missing.

Include the following information:
 - OpenSnitch version: 1.5.2
 - OS: Ubuntu
 - Version: 22.04
 - Window Manager: headless 
 - Kernel version: Linux ubuntu2204-test 5.15.0-69-generic #76-Ubuntu SMP Fri Mar 17 17:19:29 UTC 2023 x86_64 GNU/Linux

**To Reproduce**
When you clone the repository down and try to build just the daemon following the instructions in the wiki.

1. Clone the repository
2. cd ./opensnitch/daemon
3. make

**Post error logs:** 
```bash
github.com/evilsocket/opensnitch/daemon imports
	github.com/evilsocket/opensnitch/daemon/ui/protocol: cannot find module providing package github.com/evilsocket/opensnitch/daemon/ui/protocol
```

**Comment by gustavo-iniguez-goya** [comment]
Hi @alexchristy ,

Probably the creation of the protobuffer failed. See if you have the files `ui_grpc.pb.go` and `ui.pb.go` under daemon/ui/protocol/

The wiki describes more steps to compile the daemon from the sources. Could you post the output of all of them?

**Comment by alexchristy** [comment]
That's my bad. I did not realize that I needed to start from the top of the wiki page. Everything works perfectly now. Thank you so much for the help.
