### ISSUE TITLE
invalid object file location 

### ISSUE THREAD

**Issue by swestlake** [evilsocket/opensnitch#913]
opensnitch.o is in /etc location -- should be elsewhere, eg: /lib/ 

release OpenSnitch 1.6.0-rc.5-1
os: Debian Bullseye; x86-64

**Comment by gustavo-iniguez-goya** [comment]
Hi @swestlake ,

Latest 1.6.x packages install the modules under /usr/lib/opensnitchd/ebpf/ (dpkg --contents opensnitch_1.6.0-rc.5-1_amd64.deb, or dpkg -L opensnitch)

Maybe you upgraded from a previous version?

**Comment by swestlake** [comment]
"dpkg -L opensnitch" lists the path /etc/opensnitchd/opensnitch.o, but at the end of the listing,

/.
/etc
/etc/init.d
/etc/init.d/opensnitch
/etc/logrotate.d
/etc/logrotate.d/opensnitch
/etc/opensnitchd
/etc/opensnitchd/default-config.json
/etc/opensnitchd/system-fw.json
/lib
/lib/systemd
/lib/systemd/system
/lib/systemd/system/opensnitch.service
/usr
/usr/bin
/usr/bin/opensnitchd
/usr/lib
/usr/lib/opensnitchd
/usr/lib/opensnitchd/ebpf
/usr/lib/opensnitchd/ebpf/opensnitch-dns.o
/usr/lib/opensnitchd/ebpf/opensnitch-procs.o
/usr/lib/opensnitchd/ebpf/opensnitch.o
/usr/share
/usr/share/doc
/usr/share/doc/opensnitch
/usr/share/doc/opensnitch/NEWS.Debian.gz
/usr/share/doc/opensnitch/changelog.Debian.gz
/usr/share/doc/opensnitch/copyright
/etc/opensnitchd/opensnitch.o

apt policy opensnitch
opensnitch:
  Installed: 1.6.0-rc.5-1
  Candidate: 1.6.0-rc.5-1
  Version table:
 *** 1.6.0-rc.5-1 100
        100 /var/lib/dpkg/status

.. I'm not an expert in .deb packaging, but supposedly the previous one I used (opensnitch_1.5.2-1_amd64.deb) didn't remove it.

there's a "divert" feature with debian so more than one version of a package can co-exists but opensnitch was "upgraded" since it is listed with only with 1.6.0-rc.5-1

dpkg -l|grep -i opensnitch
ii  opensnitch                                        1.6.0-rc.5-1                       amd64        GNU/Linux interactive application firewall
ii  python3-opensnitch-ui                             1.6.0-rc.5-1                       all          GNU/Linux interactive application firewall

dpkg -c opensnitch_1.6.0-rc.5-1_amd64.deb, does not contain /etc/opensnitchd/opensnitch.o, which is expected..

the bug is rather imho in "1.5.2-1" since it didn't remove the /etc/opensnitchd/opensnitch.o file as it was supposed to.. but a developer wants to be careful not to remove any important user things in /etc..

thanks

**Comment by gustavo-iniguez-goya** [comment]
we moved out from /etc the ebpf modules on v1.6.x
