### ISSUE TITLE
Problem issuing a permanent DropBox Flatpak rule

### ISSUE THREAD

**Issue by dCo3lh0** [evilsocket/opensnitch#915]
Hi guys, i know of the method you guys use for AppImages that constantly changes the mount point, dropbox is a flatpak that constantly changes its path like this:

`/app/extra/.dropbox-dist/dropbox-lnx.x86_64-172.4.7555/dropbox`

How can i create a rule for this flatpak that constantly change its version folder, can you guys help me?

**Comment by gustavo-iniguez-goya** [comment]
Hi @dCo3lh0 ,

Try this:

From this executable: `^\/app\/extra\/\.dropbox-dist\/dropbox-lnx\..*\/dropbox$`

**Comment by dCo3lh0** [comment]
Thanks its working now
