### ISSUE TITLE
uninstalling python3-opensnitch-ui_1.6.0-rc.5-1 does not remove a file in /etc/xdg/autostart

### ISSUE THREAD

**Issue by swestlake** [evilsocket/opensnitch#916]
minor bug .. I was testing the package python3-opensnitch-ui_1.6.0-rc.5-1_all.deb, and it fails remove 
/etc/xdg/autostart/opensnitch_ui.desktop

**Comment by gustavo-iniguez-goya** [comment]
you're right @swestlake , thank you for reporting it!
