### ISSUE TITLE
UI does not update when removing rules

### ISSUE THREAD

**Issue by 852Kerfunkle** [evilsocket/opensnitch#921]
**Describe the bug**
When removing rules in the UI, the list sometimes does not update after removal.

Include the following information:
 - OpenSnitch 1.6.0rc5
 - OS: Fedora
 - Version 38
 - Window Manager: GNOME Shell
 - Kernel version: 6.2.12-300.fc38.x86_64

**To Reproduce**
1. Open the UI
2. Go to Rules
3. Remove one rule, with the context menu or pressing del - the list might update the first time.
4. Remove another rule, list doesn't update.

Navigating to another list and back forces it to update.

Thanks, especially for making this!

**Comment by gustavo-iniguez-goya** [comment]
Hi @852Kerfunkle ,

On Ubuntu 23 and Debian works as expected, I'll try to reproduce it on Fedora.

If you open an outbound connection (telnet 1.1.1.1, curl 1.1.1.1, etc), is the list of rules refreshed?

**Comment by 852Kerfunkle** [comment]
Hey @gustavo-iniguez-goya,

yes, it does seem to refresh when making an outbount connection (at least when it adds a new rule).

Just when tried to reproduce it, at first, I wasn't able to, everything was working as it should.

But then, I navigate to the **Events** tab and back to **Rules** and it immediately stopped working again. Also, now the list does not update on outbound connections, whether it creates a new rule or not.

Hope this helps.

**Comment by gustavo-iniguez-goya** [comment]
thank you! I'll try to reproduce it.

**Comment by gustavo-iniguez-goya** [comment]
well, taking a look at the code, when deleting a rule the list will only be refreshed when there's network activity.

Can you add a line to refresh the list when deleting a rule and see if the list is refreshed?

Bewlow _del_rule():
https://github.com/evilsocket/opensnitch/blob/c6decf1bad27b2dfa1c89800332322eb8eb21875/ui/opensnitch/dialogs/stats.py#L803-L806

This line: `self._refresh_active_table()`

**Comment by 852Kerfunkle** [comment]
While you took a good look at the code, I was losing my mind a little about not being able to reproduce it again, looking at recent changes to the system, etc :sweat_smile: 

This might very well be it. It will make the change locally and report back in a couple days/weeks if I still noticed it happening.

Thank you!

**Comment by gustavo-iniguez-goya** [comment]
mmh, maybe it's related to Wayland. Try launching the GUI as follow: `$ QT_QPA_PLATFORM=xcb opensnitch-ui`
That will force to use X11 instead of Wayland.

Anyway, I've added the line to refresh the list.

**Comment by 852Kerfunkle** [comment]
I'm using GNOME on xorg, I should probably have put that in the report.

**Comment by gustavo-iniguez-goya** [comment]
Hey, I think this issue have been fixed here: 177d67d0a6dc99b58abebb6080589f6e5385d708 .
The fix will be availble on next release.

If you reproduced it with > v1.6.4 reopen the issue please, in order to investigate it again.
