### ISSUE TITLE
[Feature Request] Support Source IP based rules

### ISSUE THREAD

**Issue by ItsDrike** [evilsocket/opensnitch#924]
### Summary:

(Following discussion #922)

Currently, opensnitch only supports rules based on a destination IP. It would be nice if support for Source IP address was also added. 

This could be very useful for laptop devices, or any other mobile devices. The main benefit of this would be the ability to only allow some applications to run in certain trusted networks (like only in the home network), or the ability to block internet access to certain apps on networks with policies against them (often things like work/university networks) - a good example would for example be a torrent service.

**Comment by gustavo-iniguez-goya** [comment]
added: https://github.com/evilsocket/opensnitch/commit/57739cc9741941a8cf5091678c9f4833edd1c2be
