### ISSUE TITLE
debian11,The UI starts very slowly, it takes 15-20 seconds to display the screen!

### ISSUE THREAD

**Issue by PP9995** [evilsocket/opensnitch#936]
The UI starts very slowly, it takes 15-20 seconds to display the screen!

debian11

I tested the version 15.2 and 16 are the same, so why?

How to quickly start and display the program?

**Comment by PP9995** [comment]
Also the status bar won't show the small icons?

**Comment by gustavo-iniguez-goya** [comment]
Hi @PP9995 ,

Please, open a Bug report and fill up the template: https://github.com/evilsocket/opensnitch/issues/new/choose

Thank you!
