### ISSUE TITLE
debian11,The UI starts very slowly, it takes 15-20 seconds to display the screen!

### ISSUE THREAD

**Issue by PP9995** [evilsocket/opensnitch#937]
The UI starts very slowly, it takes 15-20 seconds to display the screen!

debian11
Python 3.9.2 

I tested the version 15.2 and 16 are the same, so why?

How to quickly start and display the program?

Also the status bar won't show the small icons?

**Comment by gustavo-iniguez-goya** [comment]
Hi @PP9995 ,

Could you please provide the following information?

 - Desktop Environment + Window Manager: [e.g. GNOME Shell, KDE, enlightenment, i3wm, ...]
 - Launch the GUI from a terminal, reproduce the issue, and post any errors or warnings logged to the terminal.

**Comment by PP9995** [comment]
> Hi @PP9995 ,
> 
> Could you please provide the following information?
> 
> * Desktop Environment + Window Manager: [e.g. GNOME Shell, KDE, enlightenment, i3wm, ...]
> * Launch the GUI from a terminal, reproduce the issue, and post any errors or warnings logged to the terminal.

debian@debian:~$ opensnitch-ui
Themes not available. Install qt-material if you want to change GUI's appearance: pip3 install qt-material.
	 ~ OpenSnitch GUI - 1.6.0rc5 ~
	protobuf: 3.12.4 - grpc: 1.30.2
-------------------------------------------------- 
debian11.7 wayland 
Launch the GUI from a terminal:

Loading translations: /usr/lib/python3/dist-packages/opensnitch/i18n locale: en_US
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Using server address: unix:///tmp/osui.sock
is new file, or IN MEMORY, setting initial schema version
setting schema version to: 2
setting schema version to: 2
schema version: 2
db schema is up to date
using IPASN DB: /usr/lib/python3/dist-packages/data/ipasn_20140513_v12.dat.gz
new node connected, listening for client responses... /tmp/osui.sock

**Comment by gustavo-iniguez-goya** [comment]
I think you're running Gnome. If that's the case, please, install the extension gnome-shell-extension-appindicator (`sudo apt install gnome-shell-extension-appindicator`). Then you'll have to enable it https://github.com/ubuntu/gnome-shell-extension-appindicator

After enabling it, you'll have a new icon on the system tray.

If you're not running Gnome, please, tell us what Desktop Environment you are using.

**Comment by PP9995** [comment]
> I think you're running Gnome. If that's the case, please, install the extension gnome-shell-extension-appindicator (`sudo apt install gnome-shell-extension-appindicator`). Then you'll have to enable it https://github.com/ubuntu/gnome-shell-extension-appindicator
> 
> After enabling it, you'll have a new icon on the system tray.
> 
> If you're not running Gnome, please, tell us what Desktop Environment you are using.

yes,Gnome!
I installed the extension and restarted, but I still can't see the icon

**Comment by PP9995** [comment]
> I think you're running Gnome. If that's the case, please, install the extension gnome-shell-extension-appindicator (`sudo apt install gnome-shell-extension-appindicator`). Then you'll have to enable it https://github.com/ubuntu/gnome-shell-extension-appindicator
> 
> After enabling it, you'll have a new icon on the system tray.
> 
> If you're not running Gnome, please, tell us what Desktop Environment you are using.

OK, thank you! To restart the UI, the icons are now displayed normally
