### ISSUE TITLE
ICMP problem in ubuntu22.04

### ISSUE THREAD

**Issue by PP9995** [evilsocket/opensnitch#938]
opensnitch_1.6.0-rc.5
Cancel the ICMP rule in ubuntu22.04, the software will not pop up a window to prompt ICMP connection.
Under debian11, ICMP prompts everything is normal!

**Comment by gustavo-iniguez-goya** [comment]
Duplicated of #946 and #834 and #929. We'll keep analyzing this problem on of those issues.
