### ISSUE TITLE
[Feature Request] Allow to start UI in background even, when tray is not available.

### ISSUE THREAD

**Issue by WojtekWidomski** [evilsocket/opensnitch#940]
Allow to start UI in background (without showing statistics window) even, when tray is not available, for example using command line option or option in settings.

### Summary:
It is not possible to automatically start opensnitch-ui on login in background without installing gnome-shell-extension-appindicator and displaying tray icon (I do not like to have too many icons on panel and when I want to open statistics window I can do it from applications menu.)

**Comment by gustavo-iniguez-goya** [comment]
added
