### ISSUE TITLE
A few comments about compiling the ebpf_prog modules (openSUSE)

### ISSUE THREAD

**Issue by munix9** [evilsocket/opensnitch#954]
**Describe the bug**
A few comments about compiling the ebpf_prog modules (openSUSE)

Include the following information:
 - OpenSnitch version: 1.6.0+git.20230527.9c483b1
 - OS: openSUSE
 - Version: Leap 15.4, Leap 15.5, Tumbleweed
 - Window Manager: KDE
 - Kernel version: 5.14.21-150400, 5.14.21-150500, 6.3.2
 - linux-glibc-devel: 5.14-150400, 5.14-150500, 6.3

**To Reproduce**
I have a few comments about compiling the `ebpf_prog` modules (version 1.6.0/master) on openSUSE Leap and Tumbleweed (and possibly other distributions):

`-I$(KERNEL_HEADERS)/arch/x86/include/generated/`
becomes
`-I$(KERNEL_HEADERS)/arch/$(ARCH)/include/generated/`
to compile also under aarch64 (and probably others).

&nbsp;

`$(LLC) -march=bpf -mcpu=$(CPU) -filetype=obj -o $@`
becomes
`$(LLC) -march=bpf -mcpu=generic -filetype=obj -o $@`
because a `-mcpu=$(CPU)` gives a warning, e.g.
`'x86_64' is not a recognized processor for this target (ignoring processor)`

See also https://llvm.org/docs/CommandGuide/llc.html#cmdoption-llc-mcpu
For a list of available CPUs, use:
```
$ llvm-as < /dev/null | llc -march=bpf -mcpu=help
Available CPUs for this target:
  generic - Select the generic processor.
  probe - Select the probe processor.
  v1 - Select the v1 processor.
  v2 - Select the v2 processor.
  v3 - Select the v3 processor.

Available features for this target:
  alu32 - Enable ALU32 instructions.
  dummy - unused feature.
  dwarfris - Disable MCAsmInfo DwarfUsesRelocationsAcrossSections.

Use +feature to enable a feature, or -feature to disable it.
For example, llc -mcpu=mycpu -mattr=+feature1,-feature2
```

&nbsp;

`#include <linux/version.h>` in `ebpf_prog/opensnitch.c` and `ebpf_prog/opensnitch-dns.c` must be removed because it throws an error together with `-D__KERNEL__`:
```
$ head -4 /usr/include/linux/version.h
#ifdef __KERNEL__
#error "======================================================="
#error "You should not include /usr/include/{linux,asm}/ header"
#error "files directly for the compilation of kernel modules."
```

&nbsp;

A possible patch:
```
diff -ruN a/ebpf_prog/Makefile b/ebpf_prog/Makefile
--- a/ebpf_prog/Makefile
+++ b/ebpf_prog/Makefile
@@ -29,7 +29,7 @@
 
 BIN := opensnitch.o opensnitch-procs.o opensnitch-dns.o
 CLANG_FLAGS = -I. \
-       -I$(KERNEL_HEADERS)/arch/x86/include/generated/ \
+       -I$(KERNEL_HEADERS)/arch/$(ARCH)/include/generated/ \
        -I$(KERNEL_HEADERS)/include \
        -include $(KERNEL_DIR)/include/linux/kconfig.h \
        -I$(KERNEL_DIR)/include \
@@ -52,6 +52,6 @@
 
 %.o: %.c
        $(CLANG) $(CLANG_FLAGS) -c $< -o - | \
-               $(LLC) -march=bpf -mcpu=$(CPU) -filetype=obj -o $@
+               $(LLC) -march=bpf -mcpu=generic -filetype=obj -o $@
 clean:
        rm -f *.o
diff -ruN a/ebpf_prog/opensnitch.c b/ebpf_prog/opensnitch.c
--- a/ebpf_prog/opensnitch.c
+++ b/ebpf_prog/opensnitch.c
@@ -1,7 +1,6 @@
 #define KBUILD_MODNAME "dummy"
 
 #include "common_defs.h"
-#include <linux/version.h>
 #include <uapi/linux/tcp.h>
 #include <net/sock.h>
 #include <net/udp_tunnel.h>
diff -ruN a/ebpf_prog/opensnitch-dns.c b/ebpf_prog/opensnitch-dns.c
--- a/ebpf_prog/opensnitch-dns.c
+++ b/ebpf_prog/opensnitch-dns.c
@@ -4,7 +4,6 @@
 #include <linux/in6.h>
 #include <linux/ptrace.h>
 #include <linux/sched.h>
-#include <linux/version.h>
 #include <net/sock.h>
 #include <uapi/linux/bpf.h>
 #include <uapi/linux/tcp.h>
```

&nbsp;
I'm not sure if this is all quite right and possibly just a _problem_ in openSUSE, but maybe it helps in some way.
&nbsp;

One additional note:
The optional DNS monitor (`opensnitch-dns.o`) requires a running `systemd-resolved` service.
In openSUSE, the `systemd-resolved.service` is included in the `systemd-network` package, which is not installed by default.

Accordingly, the rpm-spec file should contain a `Suggests: systemd-network` or `Recommends: systemd-network`.

Or subsequently:
```
$ sudo zypper in systemd-network
$ sudo systemctl enable --now systemd-resolved.service
```

**Comment by gustavo-iniguez-goya** [comment]
added @munix9 :+1: 

> The optional DNS monitor (opensnitch-dns.o) requires a running systemd-resolved service.

As far as I know it doesn't require systemd-resolved. It only hooks libc functions. Could you explain why do you think it requires systemd-resolved?

**Comment by munix9** [comment]
> added @munix9 +1
> 
> > The optional DNS monitor (opensnitch-dns.o) requires a running systemd-resolved service.
> 
> As far as I know it doesn't require systemd-resolved. It only hooks libc functions. Could you explain why do you think it requires systemd-resolved?

Ah, then this message probably means something else - should perhaps be a bit clearer what it refers to and what it is used for.
```
/var/log/opensnitchd.log
[2023-05-28 13:41:47]  IMP  Start writing logs to /var/log/opensnitchd.log
[2023-05-28 13:41:48]  WAR  Unable to use systemd-resolved monitor: /run/systemd/resolve/io.systemd.Resolve.Monitor doesn't exist
```

**Comment by gustavo-iniguez-goya** [comment]
yeah, probably a tag like "[DNS] Unable to use ..." ?
https://github.com/evilsocket/opensnitch/commit/b560ad6967b6148c5a2f204bb3fd2239e4c8bdac
https://github.com/evilsocket/opensnitch/blob/master/daemon/dns/systemd/monitor.go

**Comment by munix9** [comment]
> yeah, probably a tag like "[DNS] Unable to use ..." ? [b560ad6](https://github.com/evilsocket/opensnitch/commit/b560ad6967b6148c5a2f204bb3fd2239e4c8bdac) https://github.com/evilsocket/opensnitch/blob/master/daemon/dns/systemd/monitor.go

Something like that, yes.

If a running `systemd-resolved` is missing and the basic functionality is not affected or disrupted, it should not be a warning either, but just an info, imho.

**Comment by gustavo-iniguez-goya** [comment]
Added :+1:

**Comment by munix9** [comment]
LGTM, thanks!
