### ISSUE TITLE
Fork the project so that it is clear how to donate to this project

### ISSUE THREAD

**Issue by elovin** [evilsocket/opensnitch#967]
Hi everyone,
I finally got around to donate some money to this project although it was a bit confusing 
since the project page has a donation link to @evilsocket patreon page although @gustavo-iniguez-goya 
has been by far the main maintainer / developer of this project since 2019. 

So I was wondering why you @gustavo-iniguez-goya are not maintaining the project in your own fork / project page ?

That would also make it clear that donating to the project actually means supporting the project, since right
now the only way to properly donate to this project is by donating directly to you.

**Comment by elovin** [comment]
Hi @gustavo-iniguez-goya thank you for that information.

Maybe we could once more discuss redirecting to your fork as opposed to continuing the development here ?

As far as I can tell the main reason why this was not done before is because
@evilsocket  [considered working on the project again in the future](https://github.com/gustavo-iniguez-goya/opensnitch/issues/40#issuecomment-741644995) (that was more than 2.5 years ago).

Is that still the case @evilsocket or do you think it makes more sense now to redirect to @gustavo-iniguez-goya project now ?

**Comment by evilsocket** [comment]
I think that in order to make it clearer how to donate to this project, all it would take is an edit to the README with the proper patreon/whatever link, which is something I suggested (using his own link) @gustavo-iniguez-goya doing in several instances.

**Comment by gustavo-iniguez-goya** [comment]
no problem @evilsocket :)

I've added myself to the the list of people to donate, and added a new section to the readme.

I think it's a little bit more clear now @elovin . Thank you!

**Comment by evilsocket** [comment]
@gustavo-iniguez-goya feel free to remove my patreon from the FUNDING file, i think it's appropriate to this project that you're the only receiver of funds.
