### ISSUE TITLE
I18N

### ISSUE THREAD

**Issue by sexybiggetje** [evilsocket/opensnitch#97]
Considering there are talks of rewrite, how about accepting a translatable application as a  feature? Improves foreign UX. Could use Transifex or plain PO files for translating.

**Comment by ei8fdb** [comment]
Yes, definitely agree, it would be very good to have localised versions of Opensnitch.

Transifex is free for open source projects, but they need to be contacted before hand.

This is what [TX's website says about FOSS projects](https://docs.transifex.com/faq/all#what-is-considered-an-open-source-project) on Transifex:

> Open Source projects are ones with publicly available source codes licensed under an OSI-approved license, such as GPL or BSD. In order to translate an Open Source project on Transifex, you'll be asked to provide the following:
> 
> A link to your project's code repository.
> The repository must contain a LICENSE file stating your project's license type.
> 

The repo already has [a GPL licence file](https://github.com/evilsocket/opensnitch/blob/master/LICENSE), and the repo is open.

Having access to a "proper" l18n tool is very handy especially for crowd sourced translating.

To gauge interest leave a few  👍 and I'll contact them to see if they'd give us free access.
