### ISSUE TITLE
type object 'Config' has no attribute 'DEFAULT_SERVER_MAX_MESSAGE_LENGTH'

### ISSUE THREAD

**Issue by molitona** [evilsocket/opensnitch#970]
opensnitch-ui on arch failed to launch after upgrade of:

```
upgraded opensnitch-git (1.6.0rc5.r43.474ad76-1 -> 1.6.0rc5.r110.01069d3-1)
upgraded opensnitch-ebpf-module-git (1.6.0rc4.r23.b7c6c8b-1 -> 1.6.0rc5.r110.01069d3-1)
```

```
╰─ opensnitch-ui                                                                                                                    ─╯
	 ~ OpenSnitch GUI - 1.6.0-rc5 ~
	protobuf: 4.21.12 - grpc: 1.53.0
-------------------------------------------------- 

Using server address: unix:///tmp/osui.sock
Traceback (most recent call last):
  File "/usr/bin/opensnitch-ui", line 115, in <module>
    maxmsglencfg = cfg.getSettings(Config.DEFAULT_SERVER_MAX_MESSAGE_LENGTH)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'Config' has no attribute 'DEFAULT_SERVER_MAX_MESSAGE_LENGTH'
```

the daemon status:

```
╰─ systemctl status opensnitchd.service                                                                                             ─╯
● opensnitchd.service - Application firewall OpenSnitch
     Loaded: loaded (/usr/lib/systemd/system/opensnitchd.service; enabled; preset: disabled)
     Active: active (running) since Sun 2023-06-18 12:43:47 CET; 1h 19min ago
       Docs: https://github.com/evilsocket/opensnitch/wiki
   Main PID: 628 (opensnitchd)
      Tasks: 15 (limit: 9393)
     Memory: 85.3M
        CPU: 6.950s
     CGroup: /system.slice/opensnitchd.service
             └─628 /usr/bin/opensnitchd -rules-path /etc/opensnitchd/rules

Jun 18 12:43:47 Unknown systemd[1]: Started Application firewall OpenSnitch.
Jun 18 12:43:52 Unknown opensnitchd[628]: [2023-06-18 11:43:52]  IMP  Starting opensnitch-daemon v1.6.0
Jun 18 12:43:52 Unknown opensnitchd[628]: [2023-06-18 11:43:52]  INF  Loading rules from /etc/opensnitchd/rules ...
Jun 18 12:43:57 Unknown opensnitchd[628]: found /usr/lib/libc.so.6
```

**Comment by gustavo-iniguez-goya** [comment]
hey @molitona !

I think your installation is out of date, the error is complaining about a non-existent attribute, but it's there:
https://github.com/evilsocket/opensnitch/blob/01069d363b8cd8fc9fa5eadd51ecce83334569a8/ui/opensnitch/config.py#L106

I just tested opensnitch-git 1.6.0rc5.r110.01069d3-1 and works fine for me.

**Comment by molitona** [comment]
Hi @gustavo-iniguez-goya my installation is up to date. is qt5-webkit aur package needed for opensnitch as i saw it got deleted after the update?

**Comment by gustavo-iniguez-goya** [comment]
nope, `qt-webkit` it's not needed. I think you already had a similar problem some time ago, but I don't remember how you solved it (python3.10 vs python3.11 maybe?).

I don't know how you are installing the AUR package, but with yay it builds fine. You can always clone the AUR repo, and verify that the missing attribute is in `opensnitch-git/src/opensnitch/ui/opensnitch/config.py` and then build it with `makepkg -si` (I don't use Arch so maybe there're better ways to do this). 

Anyway, your `config.py` should be the same than the latest from this repo https://github.com/evilsocket/opensnitch/blob/master/ui/opensnitch/config.py

**Comment by molitona** [comment]
replaced /usr/lib/python3.11/opensnitch/config.py content with https://github.com/evilsocket/opensnitch/blob/master/ui/opensnitch/config.py and it worked now!

here is the diff between old and new config.py

![Screenshot from 2023-06-20 09-41-49](https://github.com/evilsocket/opensnitch/assets/35532337/83a3f058-f7d3-45c4-9555-a6705c914861)
