### ISSUE TITLE
Would it be possible to update releases ?

### ISSUE THREAD

**Issue by linux-dummy** [evilsocket/opensnitch#971]
Hello and thank you so much for your work !

Sorry for my dummy request, but would it be possible to update the releases section more often ?

I see that you are working a lot on this project, fixing issues and adding features very often, but the last stable release is from July 2022 and the last release candidate from February ... would it be possible to have deb files for 1.6.0 or 1.6.0.1 release ?

Thank you in advance.

**Comment by jackffmm** [comment]
0.6 is a big update afaik, sine it support incoming connections.
I'd like to know how long will it take anyway.

**Comment by gustavo-iniguez-goya** [comment]
It's almost ready, I'll add a new tag probably today, and build the packages ASAP. At least for x86_64.

**Comment by gustavo-iniguez-goya** [comment]
v1.6.0 published.
