### ISSUE TITLE
Unable to set new process monitor (ebpf) for ZEN Kernel

### ISSUE THREAD

**Issue by devmalick** [evilsocket/opensnitch#973]
OpenSnitch Version: 1.6.0
OS: Garuda Linux based on ArchLinux rolling release Garuda (2.6.16-1)
Desktop: Xfce v: 4.18.1 tk: Gtk v: 3.24.36 info: xfce4-panel wm: xfwm v: 4.18.0 vt: 7
Kernel: Linux MX1 6.3.8-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Wed, 14 Jun 2023 20:10:15 +0000 x86_64 GNU/Linux

Getting warning message OpenSnitch that "Unable to set new process monitor (ebpf) method from disk: unable to load eBPF (opensitch.o). Your kernel version (6.3.8-Zen1-1-zen) might not be compatible . If this error persists, change process monitor method to 'proc' "

**Comment by gustavo-iniguez-goya** [comment]
Hi @devmalick ,

That kernel seems to have eBPF functionality disabled. As suggested by the warning message, change it to 'proc' to silence that message.

You can run the checks to see what features are missing: `opensnitchd -check-requirements`

See this issue for more information:
https://github.com/evilsocket/opensnitch/issues/774
