### ISSUE TITLE
"Once" actions are saved as temporary rule

### ISSUE THREAD

**Issue by akronym0** [evilsocket/opensnitch#977]
Is there a reason for this? It doesn't make sense to store those because there won't be a second time :-) So this looks like a bug to me

The same could be said about  "timed" rules, that is, expired rules should be removed after expiry, but that looks more like a feature request.

**Comment by gustavo-iniguez-goya** [comment]
"Once" sometimes is useful to force a pop-up whenever an app opens a connection and you want to keep an eye on it in an interactive manner. I use it mostly for debugging purposes, but I know that some users use it as a log, for later review and create more elaborated rules from there.

Anyway, there's an option under Preferences->Rules to delete/not save expired rules.

These temporary rules are only stored on the GUI. The daemon deletes them once they expire.

**Comment by akronym0** [comment]
> These temporary rules are only stored on the GUI. The daemon deletes them once they expire.

I guess that is the problem, the GUI does not delete them. I have set this option for "any temporary rules" but rules (with any expiration time) do not get deleted. I have to close and open Opensnitch to remove them.
